### ISSUE TITLE
redux-saga + webpack + uglifyjs: Saga must be a Generator function

### ISSUE THREAD

**Issue by satispunk** [yelouafi/redux-saga#10]
First I would like to say that I am exiting about redux-saga.

I faced problem with redux-saga + webpack + uglifyjs combination in production build. For some reason sagas are "too well" uglified and don't pass the check utils.is.generator(saga). In result it throws and an error "Saga must be a Generator function"

I found a workaround. Just simple use such options:
new webpack.optimize.UglifyJsPlugin({
        mangle: {except: ['GeneratorFunction'] }
})

Hope it helps someone. Is there any better way to avoid such errors?

**Comment by yelouafi** [comment]
@satispunk I've uploaded a fix to the generator test. This isn't yet released on npm, could you try with the latest source on this repo and confirm the issue has gone ?

**Comment by satispunk** [comment]
@yelouafi 
It is not very convenient to check it without npm release at the moment. But will do it as it released

**Comment by yelouafi** [comment]
I understand, I released a patch version '0.3.2'. I m pretty sure it would fix the problem, but wanted a confirmation. You can try with it and confirm me if it's Ok.

**Comment by satispunk** [comment]
Got it! Seems it works now.

**Comment by yelouafi** [comment]
Great! And thanks!

**Comment by yelouafi** [comment]
https://github.com/yelouafi/redux-saga/pull/12#commitcomment-15183083

**Comment by yelouafi** [comment]
Released a patch version on npm (0.3.3). Now it accepts any function returning an iterator (with a next method as @gaearon suggested). Hope this will fix it for good this time.
