### ISSUE TITLE
runSage doc is confusing

### ISSUE THREAD

**Issue by DjebbZ** [yelouafi/redux-saga#103]
Hi,

The example from the docs :

``` javascript
runSaga(
  serverSaga(store.getState),
  storeIO(store)
).done.then(...)
```

and the docs just below (both the signature `runSaga(iterator, {subscribe, dispatch}, [monitor])` and the **Arguments** paragraph) seem to mismatch.

1. The signature shows 3 parameters, the **Arguments** has 4 bullet points
2. I don't get what `storeIO(state)` is at all. The second param of `runSaga` ? If so, the function returns an object of `{subscribe, dispatch}` right ? Is is another saga ? If so, the signature doesn't show that it's possible to pass multiple sagas.
3. The task object returned by `runSaga` is hidden in the first part of the page. I was expecting it to clearly stated in the **Arguments** paragraph, as it's already describing the signature. Maybe adding a link the proper section of the *Non blocking calls* (the one with the table) would be better.

**Comment by yelouafi** [comment]
Yes. This needs to be updated since  0.7.0 deprecate connecting dynamic Sagas to the store using storeIO (https://github.com/yelouafi/redux-saga/releases).

[In the API](http://yelouafi.github.io/redux-saga/docs/api/index.html#runsagagenerator-subscribe-dispatch-monitor) I left the runSaga empty. Since its main purpose now is to connect Sagas to external IO (other than the Store). I need to also update usage examples.

**Comment by yelouafi** [comment]
Ok a partial fix; moved runSaga new docs to

http://yelouafi.github.io/redux-saga/docs/api/index.html#runsagagenerator-subscribe-dispatch-monitor

and for this linke

http://yelouafi.github.io/redux-saga/docs/advanced/UsingRunSaga.html

Put a temporary fix. Need to put some concrete example here like connecting a Saga directly to a React component, or websocket data source ...

**Comment by yelouafi** [comment]
Can't come up yet with a useful example for runSaga. will tarck this in #60. I added a simple (although dumb) explanation. any comment or suggestions for use cases are welcome

**Comment by slorber** [comment]
it's probably useful as a low-level api only. For example for those who wants to build a middleware to allow dispatching sagas, or whose who want a saga to exist only the time a component is mounted (like [redux-react-local](https://github.com/threepointone/redux-react-local)

For me it's more of an architectural low-level API to build on top than something you should use regularly in your app
