### ISSUE TITLE
Higher level API

### ISSUE THREAD

**Issue by yelouafi** [yelouafi/redux-saga#107]
Implementation of the Higher level API proposed here https://github.com/yelouafi/redux-saga/issues/70#issuecomment-182539075. 

[Implementation](https://github.com/yelouafi/redux-saga/blob/master/src/internal/sagaHelpers.js) (not released yet)

Tests: 
[takeEvery](https://github.com/yelouafi/redux-saga/blob/master/test/sagaHelpers/takeEvery.js)
[takeLatest](https://github.com/yelouafi/redux-saga/blob/master/test/sagaHelpers/takeLatest.js)

@gaearon @slorber I have one concern: If we're going to include Generator code in the library. Babel will automatically transpile that code using regenerator runtime. This will lock the library users into using regenerator runtime themselves which could be undesirable (e.g. user code targets a modern browser which supports generators)

**Comment by gaearon** [comment]
Interesting. I don't know what would be the best way to solve this. Are there precedents in other libraries?

**Comment by yelouafi** [comment]
One solution is to implement those functions without generators, i.e. implement the iterator manually. It could be done with the above functions but maybe more complicated if we are going to add other helpers with more complicated logic.

This concern was the reason I was thinking about puting the helpers on a separate repo.

**Comment by yelouafi** [comment]
Ok until someone has a better solution, I'll go with manual implementation 

https://github.com/yelouafi/redux-saga/blob/master/src/internal/sagaHelpers.js

Looking at the above, One can understand how Generators simplify things

I also added more tests (cancel watchers) in order to test the manual implementations

https://github.com/yelouafi/redux-saga/blob/master/test/sagaHelpers/takeEvery.js
https://github.com/yelouafi/redux-saga/blob/master/test/sagaHelpers/takeLatest.js

**Comment by slorber** [comment]
great will test that in next release :)

Don't know so much about the generator problem. 
For JS bundles you can make 2 different js files.
For Browserify/Webpack, can't the lib client handle lib transpiling? I think browserify support this by declaring a transform on the lib but don't know about Webpack

**Comment by gaearon** [comment]
No, Webpack does not do that.

**Comment by yelouafi** [comment]
FYI released 0.8.0

https://github.com/yelouafi/redux-saga/releases/tag/v0.8.0
