### ISSUE TITLE
Handling response codes

### ISSUE THREAD

**Issue by cherta** [yelouafi/redux-saga#110]
Hi everybody, this is a question not an actual issue but I don't know where to ask so here it goes.

I'm building an app that has a public and a private section and we are using sagas to manage side effects, most of the time we `call` a function that retrieves data from a backend.

Because sessions may be expired (we use jwt that provide a TTL for each token) or unauthorized we wrapped the `call` method to something with a little more semantic to us, here is an example:

```javascript
//sagas/utils.js
import { sessionExpired, resourceForbidden, resourceUnauthorized } from '../actionCreators'

export function* callCheckingAuthentication(fn, ...rest) {
  const response = yield call(fn, ...rest)
  const code = response.code

  if(code === 419) { //419: When the session has expired
    yield put(sessionExpired())
  }
  if(code === 403) { //403: When the resource is forbidden
    yield put(resourceForbidden())
  }
  if(code === 401) { //401: When the resource is unauthorized
    yield put(resourceUnauthorized())
  }

  return Promise.resolve(response)
}
```

I know `callCheckingAuthentication` is a terrible name but it is a WIP and I can't figure out a better name.

The main idea is to use this new function when making an authenticated request, like this:

```javascript
import { dataLoaded } from '../actionCreators'
export function* dataRequested() {
  let action = null
  while(action = yield take('DATA_REQUESTED')) {
    const result = yield callCheckingAuthentication(fetchData)
    yield put(dataLoaded(result.data))
  }
}
```

This allow us to `put` relevant actions (`SESSION_EXPIRED`, `RESOURCE_FORBIDDEN`, etc) so they can be `take`en by other sagas or reduced by any interested reducers. The key thing is to always return the original result so we don't break the regular flow of the generator waiting for this result.

I was wondering if this is a valid approach or if it has any drawbacks, so far we haven't experienced any issue with this approach but maybe somebody can came up with one.

**Comment by ngerritsen** [comment]
Seems valid. We use a requestSaga in our application which handles the request and it's status codes. We use that saga in multiple places and it works perfectly, plus it's testable.

**Comment by slorber** [comment]
Hi,

In my app I used to handle this with an XHR interceptor. This way I'm sure I'm not missing any case if someone starts to use some ad-hoc api request in componentDidMount.

I've built [ajax-interceptor](https://github.com/slorber/ajax-interceptor) for that.

**Comment by cherta** [comment]
Thanks for the answers, I think both are good options, I do like more explicit APIs instead of filters, having worked a lot with rails I tend to think filters lead a more obscure API design in favor of magically gaining the functionality. Anyway we are not more than 2 developers, I imagine if there were 5+ people filters can be an option.

Changing the subject, do you know if there are any plans to add gitter or slack to the project? I think these type of questions belongs there and not here. Maybe @yelouafi wants to say something about that.

**Comment by mjrussell** [comment]
:+1: for a chat location so we don't have to fill up the issue tracker with general questions about writing sagas/best practices. Maybe can request a chat channel in the Reactiflux discord? Seems like this project is getting big enough. 

@gaearon probably knows more about that process.

**Comment by yelouafi** [comment]
@cherta @mjrussell FYI https://gitter.im/yelouafi/redux-saga

**Comment by ngerritsen** [comment]
@mjrussel I also requested that

**Comment by yelouafi** [comment]
@cherta in your example. If the request completes for example with a `sessionExpired` error, what's the meaning of dispatching `dataLoaded(result.data)` ? (I mean if there is an error, there is no loaded data and if there is loaded data there is no error ?).

**Comment by cherta** [comment]
You are right @yelouafi I was missing that case, ex:

```javascript
import { dataLoaded, handleError } from '../actionCreators'
export function* dataRequested() {
  let action = null
  while(action = yield take('DATA_REQUESTED')) {
    const result = yield callCheckingAuthentication(fetchData)
    if(result.status === 200) {
      yield put(dataLoaded(result.data))
    } else {
      yield put(handleError(result))
    }
  }
}
```

I think I can also `try` `catch` for errors but I don't like to handle business logic in catch blocks but that's my personal taste.

**Comment by yelouafi** [comment]
What about making the error codes handling a normal function, a function which returns an action ?

```javascript
function responseAction(response) {
  const code = response.code

  if(code === 419) { //419: When the session has expired
    return sessionExpired() 
  }
  ...
  ...
  return dataLoaded(reponse.data)
}

export function* dataRequested() {
  let action = null
  while(action = yield take('DATA_REQUESTED')) {
    const result = yield call(fetchData)
    yield put(responseAction(result))
  }
}
```

**Comment by cherta** [comment]
yeap, that would definitely work, I like that approach

**Comment by kfrajtak** [comment]
@cherta, that's an interesting piece of code. I tried to implement something similar but failed with the `fetchData` promise. Can you share the code of that? 
Thanks, Karel
