### ISSUE TITLE
Strange behavior when testing sagas after `call()`.

### ISSUE THREAD

**Issue by larsbs** [yelouafi/redux-saga#114]
Hi,

I'm trying to test some simple sagas following the examples in this repository but the tests are giving me strange results. First of all, the code:

#### `sagas/index.js`
```javascript
export function* loadApp() {
  yield put(showLoading());
  const { users, expenses, categories } = yield call(fetchAll);
  yield put(receiveUsers(users));
  yield put(receiveExpenses(expenses));
  yield put(receiveCategories(categories));
  yield put(finishLoading());
}
```

#### `test/sagas/index.js`
```javascript
describe.skip('#loadApp()', function () {
  const loadAppGenerator = loadApp();
  const users = [{ id: 1 }, { id: 2 }, { id: 3 }];
  const expenses = [{ id: 1 }, { id: 2 }, { id: 3 }];
  const categories = [{ id: 1 }, { id: 2 }, { id: 3 }];

  it('should start yielding SHOW_LOADING action', function () {
    const expected = put(ApplicationActions.showLoading());
    const result = loadAppGenerator.next().value;
    expect(result).to.deep.equal(expected);
  });
  it('should yield a call to api.fetchAll()', function () {
    const expected = call(fetchAll);
    const result = loadAppGenerator.next().value;
    expect(result).to.deep.equal(expected);
  });
  it('should yield action RECEIVE_USERS', function () {
    const expected = put(UsersActions.receiveUsers(users));
    const result = loadAppGenerator.next(users).value;
    expect(result).to.deep.equal(expected);
  });
  it('should yield action RECEIVE_EXPENSES', function () {
    const expected = put(ExpensesActions.receiveExpenses(expenses));
    const result = loadAppGenerator.next(expenses).value;
    expect(result).to.deep.equal(expected);
  });
  it('should yield action RECEIVE_CATEGORIES', function () {
    const expected = put(CategoriesActions.receiveCategories(categories));
    const result = loadAppGenerator.next(categories).value;
    expect(result).to.deep.equal(expected);
  });
  it('should finish yielding FINISH_LOADING action', function () {
    const expected = put(ApplicationActions.finishLoading());
    const result = loadAppGenerator.next().value;
    expect(result).to.deep.equal(expected);
  });
});
```
In the above example, the first two calls to `next()` returns a valid state and the tests are passing ok. But, in the third test (when testing RECEIVE_USERS action), when I call `loadAppGenerator.next(users).value`, it doesn't pass the `users` to the action creator. Instead of returning the expected: 

```javascript
PUT: { 
  type: RECEIVE_USERS, 
  payload: { users: [{id:1}, {id:2}, {id:3}] }
}
```

I'm getting the users as undefined:

```javascript
PUT: {
  type: RECEIVE_USERS,
  payload: { users: undefined }
}
```

In other cases is like the `next()` call was a bit advanced. I have more examples in [expenses-api-frontend](https://github.com/larsbs/expenses-api-frontend/tree/master/test/unit/sagas/index.js)

**Comment by yelouafi** [comment]
When you expect a result from a `yield` like here

```javascript
const { users, expenses, categories } = yield call(fetchAll);
```

Then in your test you need to pass the whole response to the next call to `next`

```javascript
it('should yield action RECEIVE_USERS', function () {
    const expected = put(UsersActions.receiveUsers(users)); 
    /* here, you need to pass the expected result */
    const result = loadAppGenerator.next({users, expenses, categories}).value;
    expect(result).to.deep.equal(expected);
  });
```

In the following calls to `next` you don't need to pass any argument to `next` since in the Generator you're not assigning the results of `put`s to any value

**Comment by larsbs** [comment]
Yeah, that was it! Thanks for the quick response. So, in every `next()` call you have to pass the context/variable that the generator expects to exist, isn't it?

**Comment by yelouafi** [comment]
Yes. Anytime you use the 'return value' of yield (e.g via assignament `val = yield something`, in an expression like `if(yield soemthing)`), you have to pass the mocked result to the next `next` call

**Comment by kumar155** [comment]
Hi i have obstacle while testing my saga function which consists the different saga calls 
export function* fetchFromSource() {
  try {
    const site = yield select(selectedSourceSite);
    const siteId = site.Id;
    const plant = yield select(selectedSourcePlant);
    if (plant.Id !== undefined) {
      const plantId = plant.Id;
      const application = yield select(getRdsmApplicationSelected);
      }
   }
}
here im writing the jest tests for this 
describe('fetch From Source', () => {   
    let generator = saga.fetchFromSource();
    it('should return selectedSourceSite selector', () => {
      expect(generator.next().value).toEqual(select(selectedSourceSite));
    });
    it('should return selectedSourcePlant selector', () => {
      const genNext = generator.next();
      console.log(genNext.value);
      expect(genNext.value).toEqual(select(selectedSourcePlant));
    });    
}

First selecte test is passing here when i'm testing the second select test is failing here when i remove the
const siteId = site.Id; this line from saga  function second select test  is passed , how to test this with siteId i need SiteId in the function but i'm not pasted full function here

**Comment by Andarist** [comment]
@kumar155 Please share ur problem on something like codesandbox.io so we can help you better.
