### ISSUE TITLE
takeEvery / takeLatest arguments being passed differently from the example and docs

### ISSUE THREAD

**Issue by zalmoxisus** [yelouafi/redux-saga#118]
Any reasons of having other implementation than specified in docs?

[It should be implemented](http://yelouafi.github.io/redux-saga/docs/api/index.html#takeeverypattern-saga-args) as:
```js
function* takeEvery(pattern, saga, ...args) {
  while(true) {
    const action = yield take(pattern)
    yield fork(saga, ...args.concat(action))
  }
}
```
But [de facto](https://github.com/yelouafi/redux-saga/blob/master/src/internal/sagaHelpers.js#L39):
```js
function* takeEvery(pattern, saga, args = []) {
  while(true) {
    const action = yield take(pattern)
    yield fork(saga, ...args, action)
  }
}
```

So, [the example](https://github.com/yelouafi/redux-saga/blob/master/examples/shopping-cart/src/sagas/index.js#L28) will not work. It should be:
```js
yield* takeEvery(actions.GET_ALL_PRODUCTS, checkout, [getState])
```
which is confusing as we expect passing arguments as for `fork` and other methods.

**Comment by yelouafi** [comment]
No there are no reason, that was as an implementation mistake. The correct is what's in the API and examples.

Thanks for pointing on this. [already released a patch for this](https://github.com/yelouafi/redux-saga/releases/tag/0.8.2) (and of course added tests cases for args passing)

**Comment by zalmoxisus** [comment]
Thanks a lot for such a fast fix! Works as expected now.

**Comment by phaistonian** [comment]
This got me wondering too.

Thanks for resolving this.

**Comment by k88manish** [comment]
[takeLatest.js](https://github.com/redux-saga/redux-saga/blob/master/packages/core/src/internal/sagaHelpers/takeLatest.js#L6) still passing action as the last argument. 

```javascript
const yFork = ac => ({ done: false, value: fork(worker, ...args, ac) })
```

But [example](https://redux-saga.js.org/docs/api/index.html#takelatestpattern-saga-args) in docs mentions 

```javascript
const takeLatest = (patternOrChannel, saga, ...args) => fork(function*() {
  let lastTask
  while (true) {
    const action = yield take(patternOrChannel)
    if (lastTask) {
      yield cancel(lastTask) // cancel is no-op if the task has already terminated
    }
    lastTask = yield fork(saga, ...args.concat(action))
  }
})
```
