### ISSUE TITLE
saga.apply is not a function

### ISSUE THREAD

**Issue by danscan** [yelouafi/redux-saga#133]
![screen shot 2016-02-18 at 4 05 29 pm](https://cloud.githubusercontent.com/assets/1638987/13158113/7530e774-d659-11e5-82a6-074f78e9e4cf.png)

I'm encountering this w/ `react-native@0.20` and `redux-saga@0.8.2`.

**Comment by danscan** [comment]
Not sure if this is the result of a transformation from `babel-preset-react-native`... 
![screen shot 2016-02-18 at 4 12 55 pm](https://cloud.githubusercontent.com/assets/1638987/13158358/90b1eea2-d65a-11e5-95da-e2e586b93042.png)

**Comment by yelouafi** [comment]
It's likely because you passed the result of a generator function instead of the function itself

```javascript
function*saga() { ... }

// wrong
mid = sagaMiddleware(saga())

//correct
mid = sagaMiddleware(saga)
```

**Comment by danscan** [comment]
![screen shot 2016-02-18 at 4 23 40 pm](https://cloud.githubusercontent.com/assets/1638987/13158672/fec854f2-d65b-11e5-942e-ebebe2499f43.png)
This is what I'm passing to `sagaMiddleware`.

**Comment by yelouafi** [comment]
You cant pass the result of `takeEvery` to the middleware. You have to wrap it in a generator

```javascript
export default function* rootSaga() {
  yield [
     takeEvery(...),
     takeEvery(...)
  ]
}
```

**Comment by danscan** [comment]
That worked.  Thank you!
