### ISSUE TITLE
Getting `proc first argument must be an iterator` with react-native

### ISSUE THREAD

**Issue by mohebifar** [yelouafi/redux-saga#144]
This problem looks so weird. I am using redux-saga and react-native for developing an android app. I keep getting an error saying `proc first argument (Saga function result) must be an iterator` as long as I do not start *Debug in chrome*. When I try to understand the issue by starting *Debug in chrome* the error goes away and the app works as expected!

![screenshot_2016-02-23-01-54-10](https://cloud.githubusercontent.com/assets/6104558/13235000/dd8ea818-d9d0-11e5-827d-8c2da1ee2843.jpg)

The code is so simple:

```js
function* setUserByJwt(getState) {
  const user = jwtDecode(getState().user.jwt).user;
  yield put({type: SET_USER, user});
}

function* watchLogin(getState) {
  yield* takeEvery(SET_JWT, setUserByJwt, getState);
}

function* rootSaga(getState) {
  yield fork(watchLogin, getState);
}

export default function create() {
  const store = createStore(
    rootReducer,
    applyMiddleware(createSagaMiddleware(rootSaga)),
    autoRehydrate() // Comes from redux-persist (The problem still exists when I remove it. So the problem is not related to it.)
  );
}
```

**Comment by yelouafi** [comment]
The error is raised because the middleware runs `rootSaga(getState)` and checking that the result is an Iterator. 

The fact that it works in Chrome debugger makes me suspect something to do with Generator/Iterator support (present in the Chrome emulator but not on the dev. device). But this is just a speculation as I never developed react native apps.

Maybe someone with experience in react native apps could help.

**Comment by mohebifar** [comment]
I used es6-symbol and it solved the issue.

At first, the error was "Can't find variable Symbol". So I imported `babel-polyfill` by mistake while I should had rather used `es6-symbol` mentioned in #54. For some reason that I still do not understand, it was passing the "Symbol" error and was stopping on "not an iterator" error instead.

**Comment by yelouafi** [comment]
The iterator test checks for a Symbol.iterator method on the result. But this should also raise an error kind of Symbol is not defined.

Anyway closing this as it seems more an issue with the underlying platform. Feel free to comment, I can reopen it if necessary
