### ISSUE TITLE
How to use saga for ServerSide rendering?

### ISSUE THREAD

**Issue by budarin** [yelouafi/redux-saga#146]
Redux-saga is completely different from other middleware, so I can't see how to run & stop saga on server side for getting initial state of store for the route (keeping in mind dynamically loaded routes and component & authorization checks in router)

**Comment by yelouafi** [comment]
see https://github.com/yelouafi/redux-saga/issues/13#issuecomment-182883680

Closging this; I reopened #13 to track this

**Comment by budarin** [comment]
thanks
