### ISSUE TITLE
Sagas and reducers: order of execution

### ISSUE THREAD

**Issue by emirotin** [yelouafi/redux-saga#148]
I supposed that as sagas are middleware they're executed before the reducers
It appears that actually this is not true.

Here's my example:

1) reducer that stores the returnUrl erases it after the successful login:

```
[at.LOGIN.SUCCESS]: (state, payload) => {
    // (1)
    const token = payload.access_token
    return state.merge({
      token,
      returnUrl: undefined
    })
  }
```

2) I have a saga that is supposed to intercept the `LOGIN.SUCCESS` action and do the redirect:

```
function* handleLogin() {
  // (2)
  const returnUrl = yield select(state => state.auth.get('returnUrl') || '/')
  yield put(connectSocket())
}

const loginSuccess = sagaDaemon(LOGIN.SUCCESS, handleLogin)
```

where `sagaDaemon` is our helper method:

```
const sagaDaemon = (actionType, taskSaga) => {
  return function* daemon() {
    while (true) {
      const nextAction = yield take(actionType)
      // (3)
      yield fork(taskSaga, nextAction.payload, nextAction.meta)
    }
  }
}
```

By placing `debugger` statements in places (1), (2), and (3) I see, that first the reducer is called, then the master saga gets the control, and then the forks task saga.

So, questions:
- it this behaviour determined?
- is it possible / could it be possible to control it?

In many cases we actually want our sagas to happen _after_ the reducers (currently we ensure this with short delay effects), but certainty is needed.
In this particular case the order is not a big deal (I will refactor it slightly), but again I'd like to know that the observed behavior is guaranteed (or how to deal with it if it's not).

**Comment by yelouafi** [comment]
the middleware first hit the reducers then after dispatches to sagas. Since reducers are always synchronous the answer is yes sagas always take actions after the reducers.

The order of what happens after is entirely defined by how you implement your flow. In the example above the master of course takes the action first and then forked task

**Comment by yelouafi** [comment]
Should certainely be mentioned in the docs

**Comment by emirotin** [comment]
Thanks for the clarification.

**Comment by yelouafi** [comment]
FYI added a note on the API docs

http://yelouafi.github.io/redux-saga/docs/api/index.html#selectselector-args

**Comment by mcrawshaw** [comment]
Updated doc link

https://redux-saga.github.io/redux-saga/docs/api/index.html#selectselector-args

**Comment by L-Jovi** [comment]
Maybe the foolish question, if I indeed want to launch saga ahead of action, how should I implement it?

The reason what I insist because our project remain lots of old structure design, I cannot easily change every place which iterate new function, I want to use saga `take('*')` help me that insert some handler before dispatch to reducer.

Regards.

Thanks for your time.

**Comment by shinima** [comment]
@L-Jovi This solution should work for you. Have a try.

```js
// Add another redux middleware as follows:
const beforeEmitter = ({ dispatch }) => next => action => {
  const beforeAction = {
    ...action,
    type: `BEFORE_${action.type}`
  };
  next(beforeAction); // emit a 'before-action' for every action
  return next(action);
};

const sagaMiddleware = createSagaMiddleware();
const store = createStore(
  reducer,
  applyMiddleware(beforeEmitter, sagaMiddleware)
);

// In your saga, add handlers for these 'before-actions' 
function* rootSaga() {
  while (true) {
    const beforeAction = yield take(action => action.type.startsWith("BEFORE"));
    console.log(beforeAction);
  }
}
```

**Comment by L-Jovi** [comment]
@shinima Thanks for your sample code, it works :)

**Comment by rmoorman** [comment]
@mynameistechno this is also how I approach this. Having the main flow/logic within sagas and not being split between sagas and something else interacting with the store can make things easier to follow IMO.

**Comment by csorfab** [comment]
> Instead of depending on the fact that reducers execute before sagas, I'm wondering if it's less brittle and more explicit to have a saga trigger the reducer by putting another action. E.g.
> 
> ```js
> function* updateItemSaga(item) {
>   yield put(putItemAction(item)) // this updates the state in a reducer
>   const item = yield select(getItemSelector); // grab the updated state
>   yield call(request.put, {path, item})
> }
> ```
> 
> Thoughts? We now need two actions, but it's arguably more readable/obvious?

Well, now you depend on the assumption that put() returns _after_ updating the state in the store... Which might not be the case if you use an async action middleware.

**Comment by sebringj** [comment]
It's kind of wrong to call it middleware as its always executing AFTER the reducers which is not how middleware behaves on a server. Good design but confusing name. Maybe call them appendware?

**Comment by ThomasStubbe** [comment]
Has this changed recently?
Since we've updated to react-native 60.5, react-redux 7.1.1 and redux-saga 1.0.5, Our `yield TakeEvery` has precedence over our reducer.... =X

**Comment by Andarist** [comment]
No, sagas should normally run after reducers. You have to have to async stuff in between or something else is wrong with your setup. If you share a runnable repro case then I could take a look at it.
