### ISSUE TITLE
Sagas and socket.io examples?

### ISSUE THREAD

**Issue by will-harrison** [yelouafi/redux-saga#154]
I wonder if anyone has had examples of a saga calling a sever side soket and the round trip response. They act very similarly, both passing messages around, hoping to find a good working example. I'm trying to hook a rethinkdb on the server side.

**Comment by yelouafi** [comment]
maybe those links can help

http://stackoverflow.com/questions/34859932/can-i-use-redux-sagas-es6-generators-as-onmessage-listener-for-websockets-or-ev/34866840?noredirect=1#comment57501919_34866840

http://stackoverflow.com/questions/35277682/how-to-tie-emitted-events-events-into-redux-saga

**Comment by will-harrison** [comment]
I'll dig into those. See if I can wrap my head around them a little more. Thanks.

**Comment by wasd171** [comment]
This looks like a lot of boilerplate code, unfortunately. Perhaps it should be merged into lib as some kind of utility?

I personally feel that it might be achievable with `runSaga` and custom `subscribe`, which would probably look more natural. Unfortunately, it's still too complicated for me =(
