### ISSUE TITLE
Undefined action

### ISSUE THREAD

**Issue by paulxtiseo** [yelouafi/redux-saga#156]
Code below.  Seems like the `yield put(Routes.login())` creates an action with an undefined type. Am I not calling RNRF the right way? (Screenshot of console below code.)

```
import { fork, put, take } from 'redux-saga/effects'
import { Actions as Routes } from 'react-native-router-flux'

import * as services from '../services'
import * as creators from '../actions'
import * as actions  from '../constants/actions'

export function* initializeApp() {
  yield take(actions.INITIALIZE_APP)
  yield put(creators.showWaitingModal())
  // init stuff here
  yield put(creators.hideWaitingModal())
  yield put(Routes.login())
}

export default function* root(getState) {
  yield [
    fork(initializeApp)
  ];
}
```

<img width="815" alt="screen shot 2016-02-26 at 4 20 31 pm" src="https://cloud.githubusercontent.com/assets/2977050/13365804/343fc5d0-dca5-11e5-8e44-237edd69ba55.png">

**Comment by yelouafi** [comment]
Can you disable the Saga monitoring ? You can do this by running the application in production mode (set `process.env.NODE_ENV` to `production`)

**Comment by yelouafi** [comment]
Most of the react-native issues reported so far are related to absent `Symbol` support. 

see https://github.com/yelouafi/redux-saga/issues/144#issuecomment-187452310

**Comment by yelouafi** [comment]
FYI released v0.9.2 patch which addresses Symbol issue in react-native apps. May fix your issue

**Comment by paulxtiseo** [comment]
My issue was different, but thanks for the notification.

**Comment by jwhitley** [comment]
@paulxtiseo, I'm having trouble getting sagaMonitor to run in my RN app.  Did you have to do anything unusual to get the monitor to work with RN?

FWIW, I've verified it's being imported correctly, but I'm not seeing any saga logging in the Chrome debugger, nor is `$$LogSagas()` defined in the debugger console.  My store is being created using a fairly standard setup:

```javascript
export default function configureStore(initialState) {
  return createStore(
    reducer,
    initialState,
    applyMiddleware(
      sagaMonitor,
      createSagaMiddleware(...sagas)
    )
  );
}
```
