### ISSUE TITLE
Sagas aren't being triggered, EFFECT_TRIGGERED only at startup

### ISSUE THREAD

**Issue by tsemerad** [yelouafi/redux-saga#157]
I had sagas set up in my app, handling side effects. I hooked up the saga middleware to my store, passing in the `rootSaga`, and was successfully executing a side effect in response to an action. I committed this code, then proceeded to add another side effect to respond to a different action. This worked as well, and I committed it.

Now when I run my code, at startup I see `EFFECT_TRIGGERED` twice followed by `EFFECT_RESOLVED` twice, but other than that, the sagas are never triggered in response to the actions they're set up to watch. I thought that was bizarre, so I reverted to a previous commit where I know the sagas' side effects were working, and it too has this odd behavior. I then reverted to the first commit where I set up sagas, and it too isn't working.

Do you have an idea what could cause such behavior? I've compared my sagas and store to those in the examples, and they look fine. Since my saga and store code were working fine before, but stopped working (without me changing them, or any underlying libraries), I'm thinking the issue has to be caused by something related to my development environment. I tried setting up the development environment of the app on a different computer, reinstalling `node_modules` from scratch, and it's having the same issue. If you have any idea what could be causing this issue, I'd greatly appreciate it.

I'm using redux-saga 0.9.1

**Comment by yelouafi** [comment]
Can you show me your saga code and store setup

**Comment by tsemerad** [comment]
When I start the app, it will log "inside rootSaga!" and the console shows 2 `EFFECT_TRIGGERED` actions, followed by 2 `EFFECT_RESOLVED` actions. The `action.effect.FORK.fn` of the `EFFECT_TRIGGERED` actions is `routingSaga`, as is the `action.result.FORK.fn` of the `EFFECT_RESOLVED` actions. It never logs "inside routingSaga!", and none of the generator functions in `/sagas/routing.js` are triggered in response to actions anymore.

`/sagas/index.js`
```javascript
import { fork } from 'redux-saga/effects';
import routingSaga from './routing';

export default function* rootSaga() {
  console.log('inside rootSaga!');
  yield [
    fork(routingSaga),
  ]
}
```

`/sagas/routing.js`
```javascript
import { takeEvery } from 'redux-saga'
import { take, call, fork, put, select } from 'redux-saga/effects'
import * as types from '../constants/ActionTypes';
import * as toolNames from '../constants/ToolNames';
import * as routingActions from '../actions/RoutingActions';
import { requestPolylineRoute } from '../utils/routing';
import { getRoutingCoordinates } from '../selectors';

function* getPolylineRoute(action) {
   try {
      const responseJson = yield call(requestPolylineRoute, action.fromLatLng, action.toLatLng);
      const route = responseJson.routes[0];
      yield put(routingActions.getRouteSuccess(route))
   } catch (err) {
      yield put(routingActions.getRouteFailure(err));
   }
}

function* getRouteIfWeHaveOriginAndDestination(action) {
  // if we activate the Routing tool, request a route
  const state = yield select(); // passing in undefined gets current state
  const { currentLocation, targetLocation } = state;
  if (currentLocation && targetLocation) {
    yield put(routingActions.getRouteRequest(currentLocation, targetLocation));
  }
}

function* watchActivateRoutingTool() {
  const conditions = action => action.type === types.ACTIVATE_TOOL && action.id === toolNames.TOOL_ROUTING;
  yield* takeEvery(conditions, getRouteIfWeHaveOriginAndDestination)
}

function* handleSetTargetLocation(action) {
  const routingToolIsActive = yield select(state => state.tools.get(toolNames.TOOL_ROUTING).active);
  if (routingToolIsActive) {
    yield* getRouteIfWeHaveOriginAndDestination(action)
  }
}

function* watchSetTargetLocation() {
  yield* takeEvery(types.SET_TARGET_LOCATION, handleSetTargetLocation)
}

function* watchGetRouteRequest() {
  yield* takeEvery(types.GET_ROUTE_REQUEST, getPolylineRoute);
}

export default function* routingSaga() {
  console.log('inside routingSaga!')
  yield [
    fork(watchActivateRoutingTool),
    fork(watchGetRouteRequest),
    fork(watchSetTargetLocation),
  ]
}
```

`/store/configureStore.js`
```javascript
import { applyMiddleware, createStore, compose } from 'redux';
import thunkMiddleware from 'redux-thunk';
import createSagaMiddleware from 'redux-saga'
import createLogger from 'redux-logger';
import rootReducer from '../reducers';
import rootSaga from '../sagas';
import Immutable from 'immutable';


const loggerMiddleware = createLogger({
  // transform logged Immutable objects into regular JS, so it is human readable
  transformer: (state) => {
    const newState = {};
    for (const i of Object.keys(state)) {
      if (Immutable.Iterable.isIterable(state[i])) {
        newState[i] = state[i].toJS();
      } else {
        newState[i] = state[i];
      }
    }
    return newState;
  }
});

const sagaMiddleware = createSagaMiddleware(rootSaga);

// array of middleware we want in all environments
const middleware = [thunkMiddleware, sagaMiddleware];

let createStoreWithMiddleware;

// In production, we want to use just the middleware.
// In development, we want to use some store enhancers from redux-devtools.
// UglifyJS will eliminate the dead code depending on the build environment.

if (process.env.NODE_ENV === 'production') {
  createStoreWithMiddleware = applyMiddleware(...middleware)(createStore);
} else {
  const { devTools, persistState } = require('redux-devtools');
  createStoreWithMiddleware = compose(
    applyMiddleware(...middleware, loggerMiddleware), // only log when not in production
    devTools(),
    persistState(
      window.location.href.match(/[?&]debug_session=([^&]+)\b/)
    )
  )(createStore);
}

export default function configureStore(initialState) {
  const store = createStoreWithMiddleware(rootReducer, initialState);

  if (module.hot) {
    // Enable Webpack hot module replacement for reducers
    module.hot.accept('../reducers', () => {
      const nextRootReducer = require('../reducers');
      store.replaceReducer(nextRootReducer);
    });
  }

  return store;
}
```

**Comment by yelouafi** [comment]
I don't see any issue with your Saga code above. Since there is an `EFFECT_RESOLVED` for the `routingSaga` function, it means the function has been executed. You can verify here

https://github.com/yelouafi/redux-saga/blob/master/src/internal/proc.js#L288

The forked function (`routingSaga`) will be called before resolving the fork effect. But if the function above is called, it should print an `inside RoutingSaga` message which never happens (are you sure you're pointing to the right `routingSaga` function ?)

Otherwise you can trace what your Sagas actually is doing by using the sagaMonitor middleware. the source is here

https://github.com/yelouafi/redux-saga/blob/master/examples/sagaMonitor/index.js

Here is an example of how to use it

https://github.com/yelouafi/redux-saga/blob/master/examples/async/src/store/configureStore.js

After starting the application, type `$$LogSagas()` in the console. Then show me a snapshot of the console output

**Comment by tsemerad** [comment]
Here's the `$$LogSagas()` output.
![sagamonitorscreenshot](https://cloud.githubusercontent.com/assets/961776/13376599/e649f4f6-dd74-11e5-8e31-36e820692318.png)

I then decided to try using `routingSaga` as the root saga. It did log "inside routingSaga!" as expected, but it seems to "short-circuit" in the same way as the `index.js` root saga:
![sagamonitorscreenshot_routingsaga](https://cloud.githubusercontent.com/assets/961776/13376646/2bf80604-dd76-11e5-9174-59e54abaf3ae.png)

**Comment by yelouafi** [comment]
It seems the fork effect is not interpreted but returned as is. I think the middleware skips to this condition 

https://github.com/yelouafi/redux-saga/blob/master/src/internal/proc.js#L223

So my guess is that all `asEffect.xxxx(effect)` fails. 

Can you say more about your dev environement: are you using babel (which version 5 or 6) with webpack ? are you using react-native ?

**Comment by tsemerad** [comment]
I'm using babel-core@5.8.22 with webpack@1.12.13, webpack-core@0.6.8, webpack-dev-server@1.10.1, and webpack-dev-middleware@1.2.0. I am building an Electron app, using electron-prebuilt@0.30.5. I have the babel polyfill set up and have been using other functionality that requires the polyfill. 

The sagas were running fine in my dev environment, until I packaged a build of the Electron app, and launched the packaged build. I noticed that in the packaged app the generators weren't triggering, so I went back to my dev environment and launched that and it too had stopped triggering the sagas. I tried it on a separate Macbook with a newer OS and fresh node install, but it too wasn't triggering the sagas. So I'm pretty sure there's in issue with my combination of packages - it just strikes me as odd that the sagas had been working, and I hadn't changed a single package since then.

Thanks a lot for trying to help me with this. I greatly appreciate it.

**Comment by yelouafi** [comment]
Can you try with babel 6. I've seen a similar issue with babel 5+react-native due to some incomplete Symbol support. I suspect the same issue perhaps with the electron VM and the old babel polyfill

**Comment by tsemerad** [comment]
Yes, I will give that a try. Thanks for the advice.

**Comment by tsemerad** [comment]
I've updated my project to babel 6, and the latest electron. Specifically, babel-core 6.3.26 and babel-polyfill 6.3.14, and electron 0.36.8 (which uses Node 5.1.1). I first upgraded just babel, but it didn't fix the saga issue, so I upgraded electron as well. I've rebuilt all of my `node_modules` in Node 5.1.1 (previously was using 0.12). The app runs normally except the sagas still aren't working.

**Comment by tsemerad** [comment]
I'm going to try setting up sagas in the boilerplate project that my project is based on, [electron-react-boilerplate](https://github.com/chentsulin/electron-react-boilerplate), to see if I can reproduce the problem there.

**Comment by yelouafi** [comment]
I released a new version 0.9.2 which removes `Symbol` dependency from the lib. You may want to try, if your issue is due to buggy `Symbol` support as I suspect, this should fix the issue.

**Comment by tsemerad** [comment]
It's working! Thank you so much for your work on this awesome library. I was not looking forward to rewriting my sagas as thunks.

**Comment by manjeetwadi** [comment]
@tsemerad what solution had you adopted

**Comment by angemile09** [comment]
hi, what is your solution???

**Comment by manjeetwadi** [comment]
@angemile09 never able to find a solution, moved to redux-thunk

**Comment by lyminhtanh** [comment]
In my case, that's because of the dependencies conflict (defined Saga twice).
I used React-admin library for my admin page that's ALREADY used Saga inside.
However, I defined Saga library again in my package.json file that leads to the same issues as yours.
Just simply remove saga lib in package.json (then re-run 'yarn' or 'npm install' depends on your project)
Everything would be fine.
FYI, I used     "react-admin": "^2.8.6", you can check the saga version worked well in its dependencis.
Hope this helps.

**Comment by kylewstewart** [comment]
I had a similar issue where the my watcherSagas with yield takeAll where triggered once and then stopped working. My issue was solved as I had an error in my first watcherSaga which disable all subsequent watcher calls.

**Comment by samar768** [comment]
Hi There, I am facing the same issue when I am trying to implement the redux-saga in my existing react app and getting the same behaviour. somehow the sagaroot initialises on start-up and thereafter the actual action is not firing. 
in addition to that, dispatch can hit the action creator but the actual watcher method is failing to reroute the function
strange thing is that when i create a scratch react app, it does work perfectly fine but in an existing app with below-mentioned reference library is failling.
my app is using the below config 

The node version is 16.13.2.
babel code is     7.11.4
Webpack is        4.44.1

**Package.json file**
{
  "name": "portal",
  "version": "1.0.0",
  "description": "",
  "private": true,
  "scripts": {
    "dev": "webpack --watch --mode=development",
    "build": "webpack --mode production",
    "test": "echo \"Error: no test specified\" && exit 1",
    "lint": "eslint ./js/Risk/EBP/EBPMIR/**/*.js && ./js/Risk/Common/**/*.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@babel/core": "^7.11.4",
    "@babel/plugin-proposal-class-properties": "^7.2.1",
    "@babel/plugin-transform-runtime": "^7.2.0",
    "@babel/preset-env": "^7.2.0",
    "@babel/preset-react": "^7.0.0",
    "babel-eslint": "^10.0.1",
    "babel-loader": "^8.0.6",
    "babel-plugin-redux-saga": "^1.1.3",
    "css-loader": "^3.2.1",
    "eslint": "^8.6.0",
    "eslint-config-prettier": "^5.0.0",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-jsx-a11y": "^6.1.2",
    "eslint-plugin-prettier": "^3.1.0",
    "eslint-plugin-react": "^7.12.3",
    "eslint-plugin-react-redux": "^3.0.1",
    "html-loader": "^0.5.5",
    "html-webpack-plugin": "^3.2.0",
    "style-loader": "^1.0.1",
    "webpack": "^4.44.1",
    "webpack-bundle-analyzer": "^3.6.0",
    "webpack-cli": "^4.9.1"
  },
  "dependencies": {
    "@babel/runtime-corejs2": "^7.3.1",
    "axios": "^0.21.1",
    "cogo-toast": "^1.0.4",
    "core-js": "^2.5.7",
    "date-fns": "^2.1.0",
    "js-htmlencode": "^0.3.0",
    "jsonpath-plus": "^6.0.1",
    "lodash": "^4.17.11",
    "math.js": "^1.1.46",
    "mathjs": "^5.6.0",
    "micro-memoize": "^3.0.1",
    "numbro": "^2.1.2",
    "path": "^0.12.7",
    "pre-commit": "^1.2.2",
    "prop-types": "^15.7.2",
    "react": "^16.13.1",
    "react-bootstrap-typeahead": "^3.3.6",
    "react-countup": "^4.1.3",
    "react-datepicker": "^2.4.0",
    "react-dom": "^16.13.1",
    "react-loader-spinner": "^2.3.0",
    "react-number-format": "^4.0.6",
    "react-quill": "^1.3.3",
    "react-redux": "^7.2.1",
    "redux": "^4.0.1",
    "redux-logger": "^3.0.6",
    "redux-saga": "^1.2.1",
    "redux-thunk": "^2.3.0",
    "styled-components": "^4.1.3",
    "validator": "^13.5.2",
    "xlsx": "^0.17.4"
  }
}

my saga is as below:
**STARTUP FILE**

// import statements
import React from "react";
import ReactDOM from "react-dom";
import { Provider } from "react-redux";
import { createStore, applyMiddleware, compose } from "redux";
import ReduxThunk from "redux-thunk";
import logger from "redux-logger";
import rootReducer from "./ebpsasria/reducers";
import rootSagas from "../ebpra/ebpsasria/saga/sagas";
import App from "./ebpsasria";
import createSagaMiddleware from "redux-saga";

const saga = createSagaMiddleware();
const middleWares = [saga, ReduxThunk, logger];
// const middleWares = [saga];
// initialise redux store
const composeEnhancers =
	(window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ && window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__({ trace: true, traceLimit: 25 })) || compose;
const store = createStore(
	rootReducer,
	composeEnhancers(applyMiddleware(...middleWares)) // Note: logger must be the last middleware in chain, otherwise it will log thunk and promise, not actual actions
);

saga.run(rootSagas);

// render app
ReactDOM.render(
	<Provider store={store}>
		<App />
	</Provider>,
	document.getElementById("ebpsasriav2Risk")
);


ROOTSAGA.JS

import { put, takeLatest, all } from "redux-saga/effects";
import { GETUSER_STARTED, SETUSER_SUCCESS } from "./sagaActiontypes";

function getuser() {
	const json = setTimeout(() => {
		console.log("return user");
	}, 10000);
	// yield put({ type: SETUSER_SUCCESS, json: json.articles });
}
function* actionUserWatcher() {
	yield takeLatest(GETUSER_STARTED, getuser);
}
export default function* rootSaga() {
	yield all([actionUserWatcher()]);
}

any help would be appreciated as I need to implement redux-saga along with redux-thunk to handle the project's complexity.
