### ISSUE TITLE
using root saga or multiple sagas

### ISSUE THREAD

**Issue by zivni** [yelouafi/redux-saga#160]
Hi. I'm new to redux-saga and cannot figure this out:

The documentations says that an array of sagas can be passed to createSagaMiddleware.

But all the examples are using composition of saga into a root saga.

Is there a difference between the to ways, or is createSagaMiddleware with multiple sagas just a syntactic sugar over the root saga pattern?

**Comment by slorber** [comment]
I think there's not much difference.

The only difference I can see right now is probably related to error/cancellation propagation, but I think it has not been implemented properly yet. Probably that starting sagas as an array instead of forks isolates them better?

**Comment by yelouafi** [comment]
the middleware support for passing multiple sagas is a just a convenience. If you need to control top Sagas (like cancelling them) you should use a single root Saga. You can't do this with the createSagaMiddleware(..topSagas) because you can't get a reference to the forked tasks.

**Comment by johanneslumpe** [comment]
@yelouafi I know this is an old issue, just wanted to clarify: using `.run` actually mitigates this issue, as it allows us to get a reference to each run task. Is there any downside to this? We're using this in our codebase to dynamically register sagas across multiple code-split chunks and still be able to wait for them when rendering on the server-side and I haven't come across any issues yet.

**Comment by rwieruch** [comment]
Redux Saga uses the `all` function in the recent version (0.15.3) where you can combine multiple sagas to one root saga for the Redux store.

    import { takeEvery, all } from 'redux-saga/effects';

    ...

    function *watchAll() {
      yield all([
        takeEvery("FRIEND_FETCH_REQUESTED", fetchFriends),
        takeEvery("CREATE_USER_REQUESTED", createUser)
      ]);
    }

**Comment by andredp** [comment]
Is it ok to do this?

```
// foo.js
export function *fooSagas() {
  yield all([
    takeEvery("FOO_A", fooASaga),
    takeEvery("FOO_B", fooBSaga),
  ]);
}

// bar.js
export function *barSagas() {
  yield all([
    takeEvery("BAR_A", barASaga),
    takeEvery("BAR_B", barBSaga),
  ]);
}

// index.js
import { fooSagas } from './foo';
import { barSagas } from './bar';

export default function* rootSaga() {
  yield all([
    fooSagas,
    barSagas
  ])
}
```

Is there any downsides on doing that? I like to use `takeEvery` (I think it's more idiomatic than hand-writing the infinite loop, and it's faster to test the actual forked saga), but I don't konw if I should compose them that way.

**Comment by Andarist** [comment]
Its just fine, the only downside (but rly a minor) is slightly more memory used up. I'll explain this only for completeness ;)

Each saga - what u pass to the `sagaMiddleware.run`/`runSaga` and every generator passed into the `call`, `apply`, `fork`, `spawn`, `all`, `race` effects is internally becoming a Task. So if u add another layer of the generators in between they all get instances internally etc.

And as every effect is just an object you can actually export them instead of the generators.

So slightly more performant would be to:
```js
// foo.js
export const fooSagas = [
  takeEvery("FOO_A", fooASaga),
  takeEvery("FOO_B", fooBSaga),
]

// bar.js
export const barSagas() = [
  takeEvery("BAR_A", barASaga),
  takeEvery("BAR_B", barBSaga),
];

// index.js
import { fooSagas } from './foo';
import { barSagas } from './bar';

export default function* rootSaga() {
  yield all([
    ...fooSagas,
    ...barSagas
  ])
}
```

But you know how it is... dont optimize prematurely ! :)

**Comment by andredp** [comment]
@Andarist,
Thank you so much for the explanation, it all makes more sense now. 👍

**Comment by fend25** [comment]
@Andarist 
Thank you for the answer.
There is an `all` function in this code snippet.
But it seems there is no function called `all` in the redux-saga export:
```
import {all} from 'redux-saga'
```
throws the error:
```
"export 'all' was not found in 'redux-saga'
```

How to combine sagas correctly?

**Comment by Andarist** [comment]
`all` is an effect therefore it should be exported by `redux-saga/effects`

**Comment by fend25** [comment]
@Andarist 
Thank you!
I've found correct import path right after I posted a question here.
Sorry for worrying you.

**Comment by jfconde** [comment]
@Andarist thank you very much. We will follow this pattern in our projects :)

**Comment by Dictory** [comment]
@Andarist, i use like u say, but have warning:
`[...effects] has been deprecated in favor of all([...effects]), please update your code`

**Comment by Andarist** [comment]
@Dictory the warning is probably from some other part of your code, just setup a breakpoint on the console.log's line, stop there and see what has caused it in the stack trace

**Comment by SmirnovW** [comment]
@Andarist could u answer please, what a difference between a
`export default function* rootSaga() {
    yield [
        fork(fooSagas),
        fork(booSagas),
    ];
}`
and
`export default function* rootSaga() {
  yield all([
    fooSagas,
    booSagas,
  ])
}`
What should I prefer to use?

**Comment by Andarist** [comment]
@SmirnovW it depends what `fooSagas` and `booSagas` are, if they are the same thing in both examples then your second example probably is not working at all. First snippet should work, but yielding arrays directly is deprecated at the moment and the array should be wrapped in `all` effect.

**Comment by SmirnovW** [comment]
@Andarist yes, this is the same things, and of course, the second example should be with called functions :)

**Comment by Andarist** [comment]
In that case its just a matter of passing effects and non-effects (promises and iterators) to the redux-saga. While it is capable of handling those, the preferred way is to wrap them in effects (thus **delaying** their execution)

**Comment by nhiicts** [comment]
@Andarist . Hi, I have a question.
```
export default function* rootSaga() {
  yield all([
    fooSagas,
    booSagas,
  ])
}
```
As the document said.  booSagas will be abort if fooSagas throw an error and vice versa. it would be better if we use
```
export default function* rootSaga() {
  yield all([
   spaw(fooSagas),
   spaw(booSagas),
  ])
}
```
Right?

**Comment by Andarist** [comment]
@dfee as mentioned - it depends on what `fooSagas` are, `all` accept any effects (+ promises/awaitables and iterators), if `fooSagas` is a factory which returns an effect then yes - it has to be called

**Comment by Phoelpis** [comment]
@Andarist Hello, great feedback. I am working on a project with multiple:
```
export default function* rootSaga(): * {
    yield all(...
```
And i get copies of the same saga, resulting in the same saga being called multiple times. Any suggestions on how to avoid this? I believe they added a rootSaga per page (some sagas are common over multiple plages). But is it a good practice to have a rootSaga containing all sagas in the project, even if they never get used? 
Thank you.

**Comment by Andarist** [comment]
Ideally you wouldnt have to do that, i think its a viable approach to call sagaMiddleware.run multiple times in your app. This allows you to prepare a good code-splitting architecture, but how to do that in your app is up to you.

**Comment by Phoelpis** [comment]
@Andarist Thank you! But in the case of calling sagaMiddleware.run multiple times in the app, how do i avoid duplicates. Is there a way to check already registered sagas?

**Comment by Andarist** [comment]
You shouldnt call this with the same set of sagas - you should just be able to start new sagas by using this. How you organize the whole thing is up to you though.

**Comment by DevMobile2** [comment]
> Its just fine, the only downside (but rly a minor) is slightly more memory used up. I'll explain this only for completeness ;)
> 
> Each saga - what u pass to the `sagaMiddleware.run`/`runSaga` and every generator passed into the `call`, `apply`, `fork`, `spawn`, `all`, `race` effects is internally becoming a Task. So if u add another layer of the generators in between they all get instances internally etc.
> 
> And as every effect is just an object you can actually export them instead of the generators.
> 
> So slightly more performant would be to:
> 
> ```js
> // foo.js
> export const fooSagas = [
>   takeEvery("FOO_A", fooASaga),
>   takeEvery("FOO_B", fooBSaga),
> ]
> 
> // bar.js
> export const barSagas = [
>   takeEvery("BAR_A", barASaga),
>   takeEvery("BAR_B", barBSaga),
> ];
> 
> // index.js
> import { fooSagas } from './foo';
> import { barSagas } from './bar';
> 
> export default function* rootSaga() {
>   yield all([
>     ...fooSagas,
>     ...barSagas
>   ])
> }
> ```
> 
> But you know how it is... dont optimize prematurely ! :)

@Andarist With this approach if any saga fails will it kill the root saga or the other sagas as mentioned in this comment
[https://github.com/redux-saga/redux-saga/issues/760#issuecomment-273737022](https://github.com/redux-saga/redux-saga/issues/760#issuecomment-273737022).
