### ISSUE TITLE
Docs: NonBlockingCalls loginFlow final example waits for LOGOUT even when forked authorize failed

### ISSUE THREAD

**Issue by pke** [yelouafi/redux-saga#162]
In this doc example http://yelouafi.github.io/redux-saga/docs/advanced/NonBlockingCalls.html

```
function* loginFlow() {
  while(true) {
    const {user, password} = yield take('LOGIN_REQUEST')
    // fork return a Task object
    const task = yield fork(authorize, user, password)
    yield take('LOGOUT')
    yield cancel(task)
    yield call(Api.clearItem('token'))
  }
}
```

The saga waits for `LOGOUT` even when the `task` error'd out due to authorization failures.
Shouldn't it go back to the beginning of the loop and wait for the next `LOGIN_REQUEST` and also cancel the previous request before it forks another `authorize` request?

Also, could the sample also be written using `while(takeLatest('LOGIN_REQUEST'))`?

**Comment by yelouafi** [comment]
Yes you're right in the above case it should be something like

```javascript
function* loginFlow() {
  while(true) {
    const {user, password} = yield take('LOGIN_REQUEST')
    // fork return a Task object
    const task = yield fork(authorize, user, password)
    yield take(['LOGOUT', 'LOGIN_ERROR'])
    yield cancel(task)
    yield call(Api.clearItem('token'))
  }
}
```

>Also, could the sample also be written using while(takeLatest('LOGIN_REQUEST'))?

`takeLatest` will only take `LOGIN_REQUEST` and not `LOGOUT` events. You can yield a `race` between the authorize call and the LOGOUT action also. But anyway, the purpose of the example was to implement the feature using only `fork` and `cancel`

**Comment by yelouafi** [comment]
FYI updated the docs

http://yelouafi.github.io/redux-saga/docs/advanced/NonBlockingCalls.html

**Comment by pke** [comment]
Wow, that was quick! Was about to create a PR myself.
