### ISSUE TITLE
Throttling example in docs will miss the last update

### ISSUE THREAD

**Issue by axelson** [yelouafi/redux-saga#166]
The throttling example in the docs will miss the very last (trailing) update which can cause inconsistent problems:
https://github.com/yelouafi/redux-saga/blob/7ab806f511a80c2b966c7a00d80bc2fb187ec1b5/docs/recipes/README.md#throttling

I think the docs need to be updated with a warning about missing the last update. And ideally we could have a first-class throttle in redux-saga (which is issue #105)

**Comment by yelouafi** [comment]
You're right the implementation was simplistic

To capture trailing actions. We could use something like (Not tested)

```javascript
unction* watchThrotlled(actionType, worker, wait) {
  let lastAction
  let lastTime = Date.now()
  let countdwon = 0 // handle leading action

  while(true) {
    const winner = yield race({
      action: take(actionType),
      timeout: countdwon ? call(delay, countdwon) : null
    })
    const now = Date.now()
    countdwon -= (now - lastTime)
    lastTime = now

    if(winner.action) {
      lastAction = action
    }
    if(lastAction && countdwon <= 0) {
      yield fork(worker, lastAction)
      lastAction = null
      countdwon = wait
    }
  }
}
```

**Comment by yelouafi** [comment]
FYI added the warning and also the trailing version to the docs

http://yelouafi.github.io/redux-saga/docs/recipes/index.html
