### ISSUE TITLE
Execution order in sagas with multiple puts

### ISSUE THREAD

**Issue by jonaskello** [yelouafi/redux-saga#167]
I am trying to understand what causes the order of execution in sagas that do multiple puts. Not sure if this is the correct place to ask this, or maybe it is already clear from the docs. If so please direct me there :-). Anyway, I have put together the example below:

```
import React from 'react';
import ReactDOM from 'react-dom';
import {createStore, compose, applyMiddleware} from 'redux';
import {connect, Provider} from 'react-redux';
import createSagaMiddleware from 'redux-saga'
import {put, take} from 'redux-saga/effects'

const onClickAction1 = () => ({type: "ON_CLICK_ACTION1"});
const onClickAction2 = () => ({type: "ON_CLICK_ACTION2"});
const onClickAction3 = () => ({type: "ON_CLICK_ACTION3"});
const sagaAction1 = () => ({type: "SAGA_ACTION1"});
const sagaAction2 = () => ({type: "SAGA_ACTION2"});
const sagaAction3 = () => ({type: "SAGA_ACTION3"});

export function* watchAction1() {
	while (true) {
		const action = yield take('ON_CLICK_ACTION1');
		const action1 = sagaAction1();
		console.log("Saga: put >>", action1);
		yield put(action1);
		const action2 = sagaAction2();
		console.log("Saga: put >>", action2);
		yield put(action2);
	}
}

function rootReducer(state = '', action) {
	console.log("Reducer: receive <<", action);
	return state;
}

export const store = createStore(rootReducer, applyMiddleware(createSagaMiddleware(watchAction1)));

export function _MainComponent(props) {
	const {state, dispatch} = props;
	return <div>
		<button onClick={(e) => {
		const action1 = onClickAction1();
		console.log("onClick: dispatch >>", action1);
		dispatch(action1);
		const action2 = onClickAction2();
		console.log("onClick: dispatch >>", action2);
		dispatch(action2);
		}}>Start actions
		</button>
	</div>
}

const MainComponent = connect((state) => ({state: state}))(_MainComponent);

const mountNode = document.getElementById('app');
ReactDOM.render(<Provider store={store}><MainComponent /></Provider>, mountNode);
```

When I run it I get the log:

1. onClick: dispatch >> Object {type: "ON_CLICK_ACTION1"}
2. Reducer: receive << Object {type: "ON_CLICK_ACTION1"}
3. Saga: put >> Object {type: "SAGA_ACTION1"}
4. onClick: dispatch >> Object {type: "ON_CLICK_ACTION2"}
5. Reducer: receive << Object {type: "ON_CLICK_ACTION2"}
6. Reducer: receive << Object {type: "SAGA_ACTION1"}
7. Saga: put >> Object {type: "SAGA_ACTION2"}
8. Reducer: receive << Object {type: "SAGA_ACTION2"}

Here is my attempt to understand what is going on.

1. The onClick handler dispatches ON_CLICK_ACTION1.
2. The reducer is called with the ON_CLICK_ACTION1 action.
3. The saga middleware is called. It looks at ON_CLICK_ACTION1 and finds that the watchAction1 saga is waiting for this action so it executes the saga to the next yield (by calling next on it's iterator). The saga yields a put effect with SAGA_ACTION1 to the saga middleware. The saga middleware does nothing more, or maybe it puts the effect in a queue for later execution?. The reason that the yielded action is not dispatched here may be that it cannot be dispatched within the current dispatch?
4. The dispatch of ON_CLICK_ACTION1 is now complete, control is turned back to the onClick handler which dispatches ON_CLICK_ACTION2.
5. The reducer is called with ON_CLICK_ACTION2.
  1. The saga middleware is called with ON_CLICK_ACTION2 as sees no saga on hold for it so it does nothing.
  2. The dispatch of ON_CLICK_ACTION2 is now complete and control is turned back to the onClick handler which has no more work to do.
6. The saga middleware somehow dispatches the previously yielded SAGA_ACTION1. Not sure how this is triggered?
  1. The reducer is called with the ON_CLICK_ACTION1 action.
7. The saga middleware somehow determines that it should run the saga to the next yield. The saga yields put SAGA_ACTION2. The middleware somehow determines that this can be directly dispatched.
8. The reducer is called with SAGA_ACTION2.
  1. The saga middleware runs the saga to the next yield and finds that it is waiting for ON_CLICK_ACTION1.

I probably have a lot of this wrong and would like some help to understand what is really going on.

**Comment by yelouafi** [comment]
The `put` effect dispatches actions asynchronously on the next microtask (using Promise.then). In your example the 2 Component actions will be handled by the reducers before the 2 Saga actions. 

The Sagas dispatches its actions asynchronously because synchronous dispatches have some unpredictable side effects (among them nested dispatches, you can also consult [some test cases here](https://github.com/yelouafi/redux-saga/blob/master/test/recipes/takeSync.js))

**Comment by jonaskello** [comment]
Thanks! I like how redux-saga keeps the flow of a process in one place. The thing I have trouble with is just to reason about the order things happen in. I did some reading up onmicrotasks and I think I understand it better now :-). If I find some time I will try to make a rewrite of my above example and how it uses the microtask queue. I think an explainer like that might be useful for the docs.
