### ISSUE TITLE
combineSagas utility funciton

### ISSUE THREAD

**Issue by yjcxy12** [yelouafi/redux-saga#171]
At the moment we have to do something like 
```javascript
export default function* root() {
    yield [
        fork(saga1),
        fork(saga2),
        fork(saga3),
        fork(saga4)
    ];
}
```
Would be great to have combineSagas just like redux's combineReducers. 
Use it like
```javascript
export default rootSaga = combineSagas({
    saga1,
    saga2,
    ...
});
```

**Comment by yelouafi** [comment]
`combineReducers` has for purpose to combine multiple reducers into different state slices. Sagas do not store state into the Redux Store so I think the analogy do not make much sens.

From your example it seems the purpose of `combineSagas` is to take out some (not so much IMO) boilerplate of forking mulitple tasks at startup. You can just write a helper function for that

```javascript
function startSagas(...sagas) {
  return function* rootSaga() {
    yield sagas.map(saga => fork(saga))
  }
}

// usage
export default rootSaga = startSagas(saga1, saga2, ...)
```

**Comment by yjcxy12** [comment]
I was more aware of the project structural similarities. I'd have "reduces" folder, contains different reducers, and in index.js it would be something like:
```javascript
import { combineReducers } from 'redux';
import firstReducer from './firstReducer';
import secondReducer from './secondReducer';
import thirdReducer from './thirdReducer';

const rootReducer = combineReducers({
    firstReducer,
    secondReducer,
    thirdReducer
});

export default rootReducer;
```

I've tried to find a way to sort of "combine" all different sagas into a single rootSaga, so that it can be passed into createSagaMiddleware. Couldn't find it on docs, but in examples it had a pattern. And the "sagas" folder is very similar to "reducers" - having different sagas, and an index.js that exports rootSaga.
```javascript
import { fork } from 'redux-saga/effects';
import firstSaga from './firstSaga';
import secondSaga from './secondSaga';
import thirdSaga from './thirdSaga';

export default function* rootSaga() {
    yield [
        fork(firstSaga),
        fork(secondSaga),
        fork(thirdSaga),
    ];
}
```

Just with weird syntax for someone just starting up with redux-saga like me. 

Agreed that it's only very little boilerplate, but at least a mention of creating rootSaga in docs would be great.

**Comment by pke** [comment]
You can hand in many sagas into the middleware, not only one. So there is no need to combine them like you do, is there?

`createSagaMiddleware(firstSaga, secondSaga, thirdSaga)` should be the same as 

```
export default rootSagas = [
  firstSaga, secondSaga, thirdSaga
]
createSagaMiddleware(...rootSagas)
```

Whats the yield and fork doing in your code?

**Comment by yjcxy12** [comment]
Saw the pattern in the most of examples. Not clear the differences / pros and cons of two ways.

**Comment by yelouafi** [comment]
@yjcxy12 see #160

**Comment by Darmikon** [comment]
Hi, I was just searching how to combine redux sagas
and found this discussion useful.
I didn't understand why I should `fork` for these combinations.
I'd like to leave my helper functions here.
I've just written them and hasn't been tested enough. 
Correct me if I'm wrong. 
Thanks.

```
//notesSagas.js
import foldersSaga from './folders'
import notesSaga from './notes'
export default [
	foldersSaga,
	notesSaga,
]
//or export default foldersSaga

//rootSaga.js
import {sagas as notesSagas} from '~/notesSagas'

/**
 * @param {(generator|generator[])}
 */
function* combine(sagas){
	yield Array.isArray(sagas)
		? sagas.map(saga=>saga())
		: [sagas()]
}

/**
 * @param {...generators}
 */
function* apply(...sagas){
	yield Array.isArray(sagas)
		? sagas.map(saga=>combine(saga))
		: [combine(sagas)]
}

/**
 * @param {...generators}
 */
function combineSagas(...sagas){
	return function*(){
		yield apply(...sagas)
	}
}

export default combineSagas(
	notesSagas
)

/*
export default function* rootSaga() {
	// yield [
	// 	combine(notesSagas),
	// 	combine(otherSagas),
	// ]

	yield apply(
		notesSagas
		,otherSagas
	)
}
*/


//configureStore.js
import sagas from '../rootSaga'
...
sagaMiddleware.run(sagas)
...
```

**Comment by Andarist** [comment]
So basically what you trying to achieve is a deepFlatMap for arrays of arrays of generators and run each of them within saga?

**Comment by Darmikon** [comment]
I didn't think about deep nesting. But maybe it could be achieved using such functions.
In short, I have a big module per url route with own sagas not related with other pages. 
I want to see which sagas take part in the lifecircle of particular module. 
I can add and remove sagas inside separated module without touching rootSaga. I only mount module bundle to rootSaga once.
And entire bundle can be a simle saga as well. Not only arrays of sagas. But in general my bundles are arrays.

**Comment by Andarist** [comment]
So in general I would advise you to use smth like [flatMapDeep](https://lodash.com/docs/4.17.4#flatMapDeep):
`yield flatMapDeep(bundledSagas, fork)`

I think this is exactly what you need, if not please specify your requirements stricter and I'll try to adjust my advice accordingly :)

**Comment by alfonsodev** [comment]
I'm starting to use redux-saga, 
and decided to organize my sagas by topic in different files, 
I was looking also for a way to include all my sagas at once,
I came up with this code 
```
import * as groupOne from 'app/saga/groupOne'
import * as groupTwo from 'app/saga/groupTwo'
// grupOne and Two are exporting several watcher sagas 

import { map } from 'ramda'

const combinedSagas = {
  ...groupOne,
  ...groupTwo,
}
export default function* rootSaga() {
  yield map(key => combinedSagas[key](), Object.keys(combinedSagas))
}
```
Do you see any downside to this approach ? 
would I get any benefit from using `fork` ? 
Thanks.

**Comment by Andarist** [comment]
@alfonsodev the downside is that you create iterators here, they will have different identities with each run, so its harder to test. You are also yielding an array, which is deprecated now - you should wrap that array in `all` effect.

Idiomatic way of using redux-saga is to yield effects (description object) only, although yielding promises and iterators is allowed.
