### ISSUE TITLE
Design question: unavoidable callbacks

### ISSUE THREAD

**Issue by StevenLangbroek** [yelouafi/redux-saga#172]
I'm working on a project, where alot of complex stuff happens in a node-service (spawning and interacting with a python kernel). I'm refactoring their "thunks" to `redux-saga`, but I'm having trouble getting an `rxjs` subscription callback to `put` an action back into the store. Simplified code example:

```js
while (true) {
  const { id, source } = yield take(EXECUTE_CELL);

  const childMessages = new IOPubSubject(id).share();

  childMessages
    .ofMessageType(['execute_input'])
    .first()
    .subscribe(res => {
      // I need to put this `res` back into the store.
    })
}
```

How do I `put` / `dispatch` those results into the store in a clean way?

**Comment by yelouafi** [comment]
Here are some possible ways to handle *push* event sources

### pass dispatch parameter to your saga

The simplest way, see #108

The downside is that `dispatch` must be passed around to child sagas

### Use Channels

You can read more at this SO question

http://stackoverflow.com/questions/35277682/how-to-tie-emitted-events-events-into-redux-saga/35287785#35287785

Although it seems a lot of boilerplate. The channel abstraction can be used to connect to multiple sources (Observables, websockets ...). For example

```javascript
function createRxChannel(observable) {
  const channel = createChannel()
  observable.subscribe(
    channel.put,
    channel.put, // error
    () => channel.put(null) // ends the channel
  )
  return channel
}

function* saga() {
  while (true) {
    const { id, source } = yield take(EXECUTE_CELL);
    const childMessages = new IOPubSubject(id).share();

    const channel = createRxChannel(
      childMessages
        .ofMessageType(['execute_input'])
        .first()
    })

    let message
    while (message = (yield call(channel.take))) {
      // ...
    }
  }
}
```

I'm also investigating on adding channel support directly into the core see #155

**Comment by yelouafi** [comment]
You may also want to look at this solution https://github.com/yelouafi/redux-saga/issues/108#issuecomment-191687909
