### ISSUE TITLE
silently swallows typo errors in sagas

### ISSUE THREAD

**Issue by pke** [yelouafi/redux-saga#173]
I have this saga with a typo 

```
function *persistAccount() {
  while (true) {
    const result = yield take([actions.LOGIN_SUCCESS, actions.USER_UPDATED, actions.LOGOUT_SUCCESS])
    console.info("Got persist action")
    switch (result.type) {
      case actions.LOGIN_SUCCESS:
      case actions.USER_UPDATED:
        console.info("Updating credentials")
        if (result.access_token) {
          localStorage["access_token"] = result.access_token
        }
        if (result.user) {
          localStorage["user"] = JSON.stringify(result.user)
        }
        break
      case action.LOGOUT_SUCCESS:
        debugger
        console.info("Clearing credentials")
        localStorage.removeItem("access_token")
        localStorage.removeItem("user")
        break
    }
  }
  console.info("!!!!!!!!!!!!!!!!!!!EXIT")
}
```

The last switch statement has `action` instead of `actions`.
However no console output. No error. Debugger does not jump in.

Is that an es6 function generator issue or related to redux-saga?

**Comment by yelouafi** [comment]
The middleware should log all caught errors into the console (except for Cancel errors where a warning is printed only while in dev mode). In your case the middleware should print a message like this (**assuming a `LOGOUT_SUCCESS` action id dispatched**)

```
persistAccount: uncaught ReferenceError: action is not defined(…)
```

But I couldn't reproduce your issue: I tried a and I get the error printed on the console

**Comment by pke** [comment]
Hmmm. Maybe I had an outdated version. I try to reproduce and open this here again if the issue remains the same.
