### ISSUE TITLE
Mock delays during cucumberjs BDD tests

### ISSUE THREAD

**Issue by pke** [yelouafi/redux-saga#176]
I am using cucumberjs to test some of the aspects of my redux app.
In my app I have onboarding sagas that usually wait for some time before they trigger.

`yield wait(10, "minutes")`

Now in cucumber, or any test, I don't want to wait so long. In Cucumber the whole app is started just as it normally would atm. I guess I'd have to insert a custom middle-ware to intercept the "wait" effects and resolve them immediately when running under the cucumber env?

**Comment by yelouafi** [comment]
I don't know much about cucumber. But in redux-saga you don't have to execute the real wait function in the tests. You can use the `call` effect instead of calling the function directly

```javascript
function* saga() {
  yield call(wait, 10, 'minutes')
}

// test
const gen = saga()

assert.deepEqual( gen.next().value, call(wait, 10, 'minutes') )
```

see http://yelouafi.github.io/redux-saga/docs/basics/DeclarativeEffects.html

**Comment by pke** [comment]
Thanks, the question for me is who drives all the sagas. In a normal react app, this is done by the middleware. I guess I'd have to create a cucumber-sagas middleware to at least give me all the available sagas. Or not and I can have a cucumber step definition like this:

```
When("I start the app for the first time") {
  this.onboardingSaga = onboarding()
}

When("I use the app for 10 minutes") {
  if (!this.deepEqual(this.onboardingSaga.next().value, call(wait, 10, "minutes")) {
    throw new Error("On boarding did not wait for 10 minutes")
  }
}
```

**Comment by yelouafi** [comment]
As I said I don't know much about cuncomber so can't really help on this.

**Comment by slorber** [comment]
@pke instead of trying to wait less time when wait(10 minutes) is called, why not replace it by wait(1 second) in case your are in cucumber tests env
