### ISSUE TITLE
[Question/Documentation] How to deal with "many" sagas

### ISSUE THREAD

**Issue by eMerzh** [yelouafi/redux-saga#178]
Hi,

I'm planning to use saga, but i was wondering, 
as a SPA, i got somewhat "many" possible API calls
So when i discovered that you have to mention all your sagas in the store creation, 
i feared about performance or managements issues. 

What's the recomended way of dealing with 10+/100+ sagas, is it a good idea? 
should i try to group them as much a possible ?

**Comment by pke** [comment]
I have to chim in here and ask why I see so many saga examples that export 

```
export default sagas = [
  yield [
    fork *saga1,
    fork *saga2,
    ...
  ]
]
```

What's the benefit? Shouldn't a simple array of saga func generators be sufficient to hand into the saga middleware?

**Comment by eMerzh** [comment]
Yeah i use the same kind of things
in my sagas.js
```js
export default function* root() {
    yield [
        fork(watchLogin),
        fork(watchLogout)
    ];
}
```

**Comment by pke** [comment]
Why not just return the sagas without forking them? I would guess the saga middleware forks each saga in the array anyway

**Comment by yelouafi** [comment]
@pke it's mostly for convenience see #160

@eMerzh as @pke said `fork`ed and startup Sagas are started with the same mechanism function under the hood so I don't think there is a perf. difference between the 2 methods. As mentioned in #160 the only difference is that using `fork` you get a reference to a Task object so you can interact with is (cancel it, inspect if it's running etc ...)

**Comment by eMerzh** [comment]
Thanks for the reply :)
my initial question, was more about, is it normal to have "a lot of sagas" 
like ... 1 per api call / endpoint or smth ?
so if the application calls 20 distincts endpoints like (create / update / delete / list of object A, ....) i should have this much sagas?

or is it a code smell? then what's the recommended way ?

**Comment by yelouafi** [comment]
it depends on the use case; but if the requirements for all APIs are the same (e.g. dispatch success/error actions on each api response, handle logout errors ...)  I'd start with one parametrized saga. This way if the requirements are going to change (which is likely to happen at the beginning) I'll only have to change in one place.

If you have for example an api call that's called in many places then you may define a saga that just delegates the generic request saga

```javascript
function* apiSaga(fn, args, successAction, errorAction) {
  try {
    const { response } = yield call(fn, ...args)
    yield put(successAction(response)
  } catch({ error }) {
    yield put(errorAction(error)
  }
}

// this one is used on many places
function* fetchUser(userId) {
  yield* apiSaga(api.fetchUser, userId, actions.userFetchSuccess, actions.userFetchError)
}
```

But beware of premature factoring, do it if you're only confident that all your api calls (or most of them) are handled the same way.

**Comment by pke** [comment]
@yelouafi Speaking of such factoring, that what I am using atm in my app:

```
import { takeEvery } from "redux-saga"
import { put, call } from "redux-saga/effects"
import { requestAsync } from "./api"
import { REQUEST } from "./apiActions"

function *performRequest(request) {
  try {
    const { payload, response } = yield call(requestAsync, request.method, request.path, request.data, request.headers)
    const successAs = request.successAs ? request.successAs : "payload"
    yield put({ type: request.successAction, payload: {
      [successAs]: payload,
      response,
      timestamp: Date.now()
    }})
  } catch (error) {
    yield put({
      type: request.errorAction,
      error: true, payload: {
        error,
        request,
        timestamp: Date.now()
      }
    })
  }
}

export function *apiRequest() {
  yield *takeEvery(REQUEST, performRequest)
}
```

It is used by other modules like this:

```
function *fetchCities() {
  yield put(apiAction(getCities(), REFRESH_SUCCESS, REFRESH_ERROR, "cities"))
}

function *refreshCities() {
  yield log(fetchCities(), "Initial city refresh")
  yield *takeLatest(REFRESH, fetchCities)
}

export default [
  refreshCities
]
```

Its slightly different than your example, as the city saga does not import the apiSaga directly but creates an `REQUEST` action. I am not sure if your model or mine is "better". What are the pros & cons?

**Comment by eMerzh** [comment]
Thanks @yelouafi for your reponse.

so if i understand correctly, i still have to add a 3rd function that mostly
```js
function *watchUserSaga() {
  yield* takeEvery("USER_FETCH_REQUESTED", fetchUser);
}
```
right? 


and i have to add the watchUserSaga + fetchUser for each of my endpoints?

**Comment by yelouafi** [comment]
>and i have to add the watchUserSaga + fetchUser for each of my endpoints?

Yes but you can also setup multiple watchers on the same place

```javascript
function *watchMany() {
  yield [
    takeEvery("USER_FETCH_REQUESTED", fetchUser),
    takeEvery("ANOTHER_ACTION", anotherSaga),
    ...
  ]
}
```

**Comment by pke** [comment]
@yelouafi and what would be the best way to have them all being canceled on `LOGOUT` action?

**Comment by yelouafi** [comment]
@pke You'll have to use the low level API for that

```javascript
function *takeEvery(watchAction, cancelAction, worker) {
  const taskArray = []
  while(true) {
    const action = yield take([watchAction, cancelAction])
    if(action.type === cancelAction)
      yield tasks.map(t => cancel(t))

    else {
      const task = yield fork(worker, action)
      taskArray.push(task)
      task.done(() => remove(taskArray, task))
    }
  }
}

function *watchMany() {
  yield [
    takeEvery("USER_FETCH_REQUESTED", "LOGOUT", fetchUser),
    takeEvery("ANOTHER_ACTION", "LOGOUT", anotherSaga),
    ...
  ]
}
```

**Comment by pke** [comment]
hmmm forking all the worker actions and `race` them against the `cancelAction` would not work?

**Comment by yelouafi** [comment]
Sure It would and the code will also be more declarative, you won't even need to create a custom helper. OTOH you'll have to create a task-watcher for each forked worker (not a big deal on most cases)

```javascript
function* cancellableWorker(worker, cancelAction, workerAction) {
  yield race([
    call(worker, workerAction),
    take(cancelAction)
  ])
}

function *watchMany() {
  yield [
    takeEvery("ACTION", cancellableWorker, fetchUser, "LOGOUT")
    ...
  ]
}
```

**Comment by slorber** [comment]
@yelouafi by chance do you know why this does not work?

```javascript
yield stamples.map(stample => {
    call(watcherGenerator,stample);
});
```

while this works:

```javascript
yield call(watcherGenerator,stample);
```

I don't understand :D

**Comment by yelouafi** [comment]
```js
yield stamples.map(stample => {
    /* return */ call(watcherGenerator,stample);
});
```

**Comment by slorber** [comment]
:O obviously :)

by chance is there a way to add a warning for such cases when we are yielding an array those values are not effects/promises? it would probably be helpful to others

**Comment by yelouafi** [comment]
Maybe adding a warning when an undefined value. more general and can also cover the above case

**Comment by slorber** [comment]
hmmm actually one might want to map and not return effect for all the elements of the array (I almost did try that).

I certainly can use _.compact to remove undefined values from the array anyway

**Comment by TeodorKolev** [comment]
I want to use redux-saga for API calls. Since I have many different url calls how can I achieve that? Basicaly I use [this ](http://www.webpackbin.com/NkNhb8R3-)example, but I dnon't know how to multiply it. Is there any tutorials for that? Just to be sure: I have two different buttons in different components that make API calls.

**Comment by davidwparker** [comment]
@TeodorKolev - I've modified your example to show using two different API calls. You should be able to expand upon that to make it work: http://www.webpackbin.com/VkdjuU02Z

**Comment by TeodorKolev** [comment]
@davidwparker Great thanks man. Appreciated! If you want add that links as answer of [this](http://stackoverflow.com/questions/39666643/multiple-redux-sagas). I will accept it, because it really helps me.

**Comment by jamiesunderland** [comment]
I've experienced the same problem. My solution was to create a sagas.js file next to app.js that acts as the root saga and then maps over the imported sagas. so for example 

`sagas.js`

``` js
import { fork } from 'redux-saga/effects';
import MySaga from './path/to/MySaga';
import MyOtherSaga from './path/to/MyOtherSaga';

const sagas = [
  ...MySaga,
 ...MyOtherSaga
];

export default function* root() {
  yield sagas.map(saga => fork(saga)); 
}
```

`path/to/MySaga.js`

``` js
export default [myWatchSagaForSomething, myWatchSagaForSomethingElse];
```

`app.js`

``` js
import Sagas from './sagas';
/*
lot of other stuff ...
*/
sagaMiddleware.run(Sagas);
```

**Comment by granmoe** [comment]
We've ended up doing the same thing as @jamiesunderland. We do it within a modified ducks pattern, where the saga code is all contained within our ducks. Each duck exports a `sagas` array, then we `yield sagas.map(startSaga)` in our rootSaga (startSaga spawns each saga and has some top level custom logic).

**Comment by waclock** [comment]
@jamiesunderland your solution seems to be pretty clean, however when you fork the watchers in the root of sagas, you should do it like this:

`  yield sagas.map(saga => saga.map(watcher => fork(watcher)))`

Otherwise, you'd be forking a complete saga and not each watcher, which causes an error.

**Comment by mattzuba** [comment]
@waclock - it works exactly as @jamiesunderland posted if running the code under anything that supports [array spreading](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator) (unless your code has been transpiled in which case it's probably converted into array concats.

**Comment by ofirgeller** [comment]
Might help someone, this setup gives my flexibility of changing how I import and export.

```
const flatMap = (arr, func) => {

    return [].concat(arr.map((i) => {
        if (Array.isArray(i)) {
            return i.map(func);
        } else if (typeof i === 'object') {
            return Object.keys(i).map(k => func(i[k]));
        } else {
            return func(i);
        }
    }));
    
};


export default function* rootSaga() {
    yield flatMap([
        login,
        courses
    ], fork);
}
```

**Comment by viadrew** [comment]
Here's my approach to this:
`rootSaga.js`
```javascript
import saga1 from './path/to/1/sagas';
import saga2 from './path/to/2/sagas';

export default [
    saga1,
    saga2
];
```

`path/to/1/sagas.js`
```javascript

function* watcher1 (){...}
function* watcher2 (){...}

export default function* root {
    yield fork(watcher1);
    yield fork(watcher2);
}
```

`index.js`
```javascript
import createSagaMiddleware from 'redux-saga';
import createStore from './store';
import rootSaga from './rootSaga';
/*
...
*/
const sagaMiddleware = createSagaMiddleware();
rootSaga.map(saga => sagaMiddleware.run(saga))  // Register all sagas
```

**Comment by rwieruch** [comment]
Redux Saga has the `all` function in the recent version (0.15.3) to combine multiple sagas to one root saga for the Redux store.

    import { takeEvery, all } from 'redux-saga/effects';

    ...

    function *watchAll() {
      yield all([
        takeEvery("FRIEND_FETCH_REQUESTED", fetchFriends),
        takeEvery("CREATE_USER_REQUESTED", createUser)
      ]);
    }

**Comment by granmoe** [comment]
@rwieruch The only caveat of using `all` in the root saga to combine sagas is that (if I'm reading the docs correctly) if any of the sagas throws, all of the sagas in the `all` will be cancelled.

**Comment by andredp** [comment]
@granmoe is there any reason that can happen in a normal situation? 

I mean, if you test your sagas you expect your program to behave correctly... Thus, if a saga throws, there's something you're not testing (nor expecting) and the Application is left in an unstable state... So if one throws, not sure if you really want the other ones working.

**Comment by granmoe** [comment]
@andredp If you have any saga that makes any network request, and the network request throws for any reason, all of your other sagas would die. So if you want your app to keep working when the internet connection is intermittent or not have to handle every single type of error thrown explicitly and restart at each saga's level (which is not a bad option, either), then you will need some generic restart logic.

**Comment by granmoe** [comment]
That said, there are alternative approaches, and they have been discussed at length in other issues.

**Comment by granmoe** [comment]
https://github.com/redux-saga/redux-saga/pull/644

**Comment by Andarist** [comment]
@andredp 
This is only sometimes suggested as precaution measure. But I would rather advise to use a wrapper around ur 'unsafe' calls (i.e. network requests), like [here](https://github.com/redux-saga/redux-saga/issues/713#issuecomment-268502263) - with a generic solution of restarts its quite easy to lose control about how ur program behaves. More granular approach let u be more specific and handle each case differently - according to the circumstances of the failed call

**Comment by danielstern** [comment]
Using ES6, you can do something like:


```
import * as sagas from './sagas';
for (let saga of Object.values(sagas))
{

    sagaMiddleware.run(saga);

}

```

With `./sagas/index/js` being:

```
export { priceCalculationSaga } from './priceCalculation';
export { submitCheckoutSaga } from './submitCheckout';
```
