### ISSUE TITLE
Provide eslint rules for sagas

### ISSUE THREAD

**Issue by pke** [yelouafi/redux-saga#179]
I recently forgot to `call` an async function. It would be nice to have a `eslint saga-call` rule that enforce s the usage of `yield <effect> asyncFunc` instead of `yield asyncFunc`.

Since I recently wrote a simple eslint myself I might create a PR for that, if there is any interest.

**Comment by tgriesser** [comment]
Do you think it'd also be possible to detect missing `yield` for effect?

```js
var x = effect(asyncFunc)
```

Rather than

```js
var x = yield effect(asyncFunc)
```

**Comment by pke** [comment]
Sure, every effect could be covered.

**Comment by yelouafi** [comment]
@pke thanks, this would be useful. I'm not sure the place where to put the file: maybe an  `eslint-config-saga.js` file on the root directory

**Comment by yelouafi** [comment]
@pke is this still relevant ?

**Comment by pke** [comment]
Its on my agenda to do, yes. You can close for now if you want. I'll open a PR once I am ready.

**Comment by yelouafi** [comment]
I'll keep it open since it's still actionable. Thanks

**Comment by fhelwanger** [comment]
Maybe we could have an `eslint-plugin-redux-saga` for that, like [eslint-plugin-react](https://github.com/yannickcr/eslint-plugin-react).

Do you think it's worth?

**Comment by pke** [comment]
@fhelwanger Sure, that would make it cleaner for sure and easier to integrate with eslint.

**Comment by pke** [comment]
Wrote the first rule see #261 

@yelouafi I propose to create a new repo called `eslint-plugin-redux-saga` and collect all the rules we think would make sense there as issues first and create them step by step. Since you own the redux-saga repo I think it would be best hosted under your username? I could push my initial plugin to my account and you could fork it, or how would you like us to proceed?

**Comment by pke** [comment]
@tgriesser There you go:

```es6
ruleTester.run("yield-effects", rule, {
  valid: [
    {
      code: "function* test() { yield take('ACTION') }",
      parserOptions: { ecmaVersion: 6 }
    }, 
    {
      code: "function* test() { notAnEffectDoesNotNeedYield() }",
      parserOptions: { ecmaVersion: 6 } 
    }    
  ],
  invalid: [
    {
      code: "function* test() { take('ACTION') }",
      output: "function* test() { yield take('ACTION') }",
      parserOptions: { ecmaVersion: 6 },
      errors: [{ message: "take effect must be yielded" }]
    }
  ]
})
```

**Comment by pke** [comment]
I have setup a preliminary work-in-progress repo at https://github.com/pke/eslint-plugin-redux-saga

**Comment by yelouafi** [comment]
I'm closing this b/c it's too old. Sorry I didn't check the repo (I'm not really familiar with how to write eslint rules, was planning to learn on it but couldn't find the time). If you like you can submit a PR to add a link on the [addons section](http://yelouafi.github.io/redux-saga/docs/ExternalResources.html). I think it makes more sense to keep the repo under your username.

**Comment by pke** [comment]
@yelouafi The rules are now published on npm. I have created a PR #452  that updates the [addons section](http://yelouafi.github.io/redux-saga/docs/ExternalResources.html)
