### ISSUE TITLE
EFFECT_TRIGGERED cluttering the redux-logger output

### ISSUE THREAD

**Issue by pke** [yelouafi/redux-saga#180]
Is there a way to prevent the events from being logged?

**Comment by skellock** [comment]
You can turn it off in the predicate that powers your redux logger.

```
const predicate = (getState, { type }) => type !== 'EFFECT_TRIGGERED'
const logger = createLogger({ predicate })
```

In my own version, I have a blacklist of messages I dodge and use Ramda to filter them out.  Overkill?  Absolutely.  Works great. >:)

**Comment by pke** [comment]
I just wonder I never saw it before. Maybe my node ENV was not set correctly to `development` and saga did not try to log anything.
