### ISSUE TITLE
race effect without automatic cancellation ?

### ISSUE THREAD

**Issue by youknowriad** [yelouafi/redux-saga#183]
Hi, 

I have this use case where I want to hava a race but avoid automatic cancellation : 

```javascript
export function* mySaga() {
  const task = yield fork(myApiCallSaga)
  let { timeout, result } = yield race({
    timeout: delay(500),
    result: task.done
  })

  if (timeout) {
    yield put({ type: 'display-something' })
    result = yield join(task)
  }

  return result
}
```

Basically here, I trigger an Api call in a forked saga, and if the forked task lasts more than 500ms, I display something (trigger a put), and join the forked tasked to get the result.

The problem here is that the race effect cancels myApiCall if the timeout expires.

May be there's another way of doing this. 

Thanks a lot

**Comment by youknowriad** [comment]
I've found this workaround, make the promise uncancelable : 

```
export function* mySaga() {
  const task = yield fork(myApiCallSaga)
  const taskPromise = new Promise((resolve, reject) => {
    task.done.then(resolve, reject)
  })
  let { timeout, result } = yield race({
    timeout: delay(500),
    result: taskPromise
  })

  if (timeout) {
    yield put({ type: 'display-something' })
    result = yield taskPromise
  }

  return result
}
```

What do you think ?

**Comment by yelouafi** [comment]
I think the proposition makes sense. I've been thinking on adding a non destructive race effect. Maybe we need also the same thing for parallel effect (no automatic cancellation)

**Comment by yelouafi** [comment]
With v0.10.0 you can replace task.done with join(task). If timeout wins only the join (i.e. the waiting) will be cancelled not the task itself

**Comment by youknowriad** [comment]
great, that means we can close the issue 👍.  Thanks a lot for the hard work.

**Comment by lnunno** [comment]
@yelouafi You mentioned here and a couple other issues that you were thinking of adding a non destructive race effect, can I ask if you tried this or have plans to implement? I have a use case for that type of effect as well.
