### ISSUE TITLE
How to correctly write integration test with sagas?

### ISSUE THREAD

**Issue by jackgeek** [yelouafi/redux-saga#187]
I have a common pattern in my app that I don't know how to test properly.  I want to test a feature in it's entirety, it is composed of a react component that fires an action that a saga TAKEs and then PUTs an action that causes new state in the reducer.

Here is my saga:

```
const forever = true;

export default function* watchForSomeAction(getState) {
  while(forever) {
    const action = yield take(SOME_ACTION);
    yield fork(doSomethingMaybe, getState);
  }
}

export function* doSomethingMaybe(getState) {
  // ... some logic
  if (...) {
    yield* put(someActionCreator({ blah }));
  }
}

```

Here is my mocha test:

```
describe('feature integration', () => {
  let store;

  beforeEach(() => {
    const reducer = combineReducers({ feature: featureReducer });
    const createStoreWithMiddleware = compose(
      applyMiddleware(sagaMiddleware(featureSaga)),
    )(createStore);
      store = createStoreWithMiddleware(reducer, {});
  });

  it('when SomeComponent is mounted should purge store', () => {
      // Arrange
	  // ...
      // Act
	  // ... Component dispatches action that saga is listening for ...
      // Assert
	  // !!! NEED TO PAUSE HERE til after someAction has been dispatched to store
      // expect(store.getState().somePartOfStateThatIsAffectedBySomeAction).to.be.deep.equal(expectedState);
    });
  });
});

```

I could make my test asynchronous and do a setTimeout and wait an arbitrary length of time until the store is in the state I expect but this feels icky and unreliable.  Is there a hook I can use to ensure my test assertions run after the saga has completed the PUT?

**Comment by jackgeek** [comment]
I'm trying to put a JSBin together that illustrates this better.  In my debugging of the test I have found some odd things happening which make me think I'm missing something fundamental.

**Comment by yelouafi** [comment]
If you mock your API (ajax calls) to return some fake promises then doing setTimeout(..,0) will be sufficient; timer callback will always be scheduled after all promises resolution

**Comment by magestican** [comment]
You can do something like this to mock your API responses during integration testing : 

jest.mock('redux-saga/effects',  () => {
  function mockFunctions() {
  const original = require.requireActual('redux-saga/effects');
  let getStaffServicesAndMoreAPI_RESPONSE = require('./datasets').getStaffServicesAndMoreAPI_RESPONSE;
  let getStaffServicesAndMoreApi = require('../actions/sagas/appointmentStep').getStaffServicesAndMoreApi;
  return {
    ...original,
    call : (functionSignature) =>{
      if(JSON.stringify(functionSignature) == JSON.stringify(getStaffServicesAndMoreApi)){
        return getStaffServicesAndMoreAPI_RESPONSE;
      }
    }
  }
  }
  return mockFunctions();
});
