### ISSUE TITLE
How to wait for 2 actions and join their results in redux-saga

### ISSUE THREAD

**Issue by kfrajtak** [yelouafi/redux-saga#190]
Hi,
in my application I'd like to define a saga that will handle either `LEFT_CHANGED` or `RIGHT_CHANGED` actions and continue with new action `SOURCES_CHANGED` with payload consisting of payloads of the two aforementioned actions.

    export function* watchLeftRightChanged() {  
      const left = null;
      const right = null;
      while (true) {
        const result = yield take(['LEFT_CHANGED', 'RIGHT_CHANGED'])
        switch (result.type) {
          case 'LEFT_CHANGED':
            yield put({ type: 'SOURCES_CHANGED', result, right })
            continue;
          case 'RIGHT_CHANGED':
            yield put({ type: 'SOURCES_CHANGED', left, result })
            continue
        }
      }
    }
The problem is that `left` and `right` properties of the action are null when `SOURCES_CHANGED` action is emitted and their value is not kept (I believe dut to the nature of the iterator).

Thanks for help,
Karel

**Comment by slorber** [comment]
@kfrajtak you have to either compute state inside your saga (so you can't use const because you need to reassign variables overtime), OR reuse existing Redux store state if you have reducers that compute state


For example:

```javascript
export function* watchLeftRightChanged() {  
  let right;
  let left;
  while (true) {
    const result = yield take(['LEFT_CHANGED', 'RIGHT_CHANGED'])
    switch (result.type) {
      case 'LEFT_CHANGED': left = result.payload; break;
      case 'RIGHT_CHANGED': right = result.payload; break;
    }
    yield put({ type: 'SOURCES_CHANGED', left, right })
  }
}
```

OR 


```javascript
export function* watchLeftRightChanged() {  
  while (true) {
    const result = yield take(['LEFT_CHANGED', 'RIGHT_CHANGED'])
    const left = select(state => state.leftState)
    const right = select(state => state.rightState)
    yield put({ type: 'SOURCES_CHANGED', left, right })
  }
}
```

**Comment by kfrajtak** [comment]
Thanks, @slorber, that worked like a charm!

**Comment by jhewlett** [comment]
@kfrajtak I had the same need and wrote this lib: [redux-saga-combine-latest](https://github.com/jhewlett/redux-saga-combine-latest)

It takes @slorber 's first approach of aggregating actions in local state, and only fires the handler when all action types have come in. e.g.

```javascript
combineLatest(['type1', 'type2'], handleActions)
```

As soon as an action of type `type1` and `type2` have been received, it fires the `handleActions` saga, passing an array of actions. As new actions of each type come in, it fires again with the latest action of each type.

**Comment by kfrajtak** [comment]
Thanks, @jhewlett, I'll have a look at your lib!
