### ISSUE TITLE
Docs: NonBlockingCalls loginFlow final example does not work

### ISSUE THREAD

**Issue by amelon** [yelouafi/redux-saga#192]
Hi,

I've tryied docs non blocking call with following exemple:

```javascript
function* authorize(credentials) {
  try {
    const payload = yield call(Api.authorize, credentials)
    yield put({type: 'LOGIN.SUCCESS', token}))
    return payload.token
  } catch(error) {
    if (!isCancelError(error)) {
      yield put({type: 'LOGIN.ERROR', error })
    }
  }
}


export default function* watchAuth() {
  while(true) {
    var { username, password } = yield take('LOGIN.REQUEST')
    const authTask = yield fork(authorize, {username, password})
    yield take(['LOGOUT', 'LOGIN.ERROR'])
    yield cancel(authTask)
  }
}
```

where `Api.authorize` is a promise that reject on error.

On a 'LOGIN.ERROR', task `authTask` is cancelled and I receive following error :

````
Unhandled promise rejection 
...
SagaCancellationException
...
````

I think the problem is on 'LOGIN.ERROR' `watchAuth` cancel the still running task `authorize` which receives a `SagaCancellationException` but can no more catch it. (clear??)

**Comment by yelouafi** [comment]
>I think the problem is on 'LOGIN.ERROR' watchAuth cancel the still running task authorize which receives a SagaCancellationException but can no more catch it

`cancel` doesn't throw on an already terminated task. 

I tried to reproduce the error but I can't see the logged error ([see this bin](http://jsbin.com/botife/edit?js,console)).

**Comment by amelon** [comment]
Hi,
I think the problem is on unterminated task which is already in `catch` and it results in a `uncaught error` in promise.

That's the case in your JS Bin, if you have a bad authentification.
In you JS Bin, if you enter a bad username (adminx for exemple) you can see in console log the `uncaught error`.

Is it normal ?

**Comment by yelouafi** [comment]
>I think the problem is on unterminated task which is already in catch and it results in a uncaught error in promise.

Ok, I understand now. In this code 

```javascript
function* authorize(credentials) {
 ...
  catch(error) {
    if (!isCancelError(error)) {
      yield put({type: 'LOGIN_ERROR', error })
    }
  }
}
```

When the `yield put(...)` dispatches the `LOGIN_ERROR` action, `watchAuth` takes the action and throws a cancellation exception inside  `authorize` while authorize is still waiting for the `put` to return (because everything is done synchronously in this sequence). Since there is no surrounding try/catch this results in the promise rejection error.

The error wont affect `watchAuth` because forked tasks are isolated but the error can be confusing to the user.

In this case we can fix it by 

```javascript
function* watchAuth() {
  while(true) {
    var { name, password } = yield take('LOGIN_REQUEST')
    const authTask = yield fork(authorize, {name, password})
    const action = yield take(['LOGOUT', 'LOGIN_ERROR'])
    if(action.type === 'LOGOUT')
      yield cancel(authTask)
  }
}
```

**Comment by amelon** [comment]
Yes, so nice, your solution is perfect.

I can confirm it is very confusing and I spent many time to figure out what's wrong.

I didn't know that `take` return a full action. 
Good news.

thanks for your reply and saga project ;)

**Comment by yelouafi** [comment]
Fixed the docs.
