### ISSUE TITLE
Add `delay` effect

### ISSUE THREAD

**Issue by pke** [yelouafi/redux-saga#193]
I keep copying+pasting the `delay` effect between my projects. Don't you think it would be a good candidate to be included in `redux-saga`?

I have also enhanced the signature of the function to yield to true instead of undefined:

```es6
function delay(ms) {
  return new Promise(resolve => setTimeout(() => resolve(true), ms))
} 
```

Then you could easily check for timeouts in `race`

```es6
const { timeout, otherCall } = yield race({
  timeout: call(delay, 5000),
  otherCall: call(asyncFunc, ...)
})
```

**Comment by ooflorent** [comment]
That would be a great addition! Maybe you should submit a pull request.

**Comment by pke** [comment]
Would that be an effect like `take` and `put` or a simple function as described above?

```es6
function* wait(ms, result=true) {
  return call(new Promise(resolve => setTimeout(() => resolve(result), ms)))
}

const { timeout, otherCall } = yield race({
  timeout: wait(5000),
  otherCall: call(asyncFunc, ...)
})
```

**Comment by ooflorent** [comment]
I see something like this:

```js
export function* delay(ms, result = ms) {
  return new Promise(resolve => {
    setTimeout(() => resolve(result), ms)
  })
}

export function wait(ms) {
  return call(delay, ms)
}
```

* `delay` is a _task_
* `wait` is an _effect_ which under the hood calls the `delay` task

**Comment by yelouafi** [comment]
adding a `delay` util function could make sens. But adding a new effect here is irrelevant here since this is just an alias for a call effect. I prefer to keep the core small and focused

**Comment by slorber** [comment]
I too had to copy this method in my project. Initially I though it was built-in but figured out it was not later :)

**Comment by burakcan** [comment]
i'm using something like following. it's simple but it does the work for me:
```
function *sleep(time) {
  yield new Promise(resolve => setTimeout(resolve, time));
}
```

**Comment by axelson** [comment]
I'd vote for just adding a `delay()` util function to the docs or a `contrib` folder.

**Comment by yelouafi** [comment]
@axelson Fyi added a delay fn to redux-saga/utils in the current master branch

**Comment by pke** [comment]
Thanks , so I can close this one.

**Comment by Anahkiasen** [comment]
@yelouafi I don't see `delay` being [exported here](https://github.com/yelouafi/redux-saga/blob/master/src/utils.js#L1) and when I do `import {delay} from 'redux-saga/utils'` I get `undefined`. Should I import from somewhere else?

**Comment by yelouafi** [comment]
Sorry forgot to mention: its exported from the root redux-saga

**Comment by chenxsan** [comment]
@Anahkiasen I think it's `import {delay} from 'redux-saga'`.

**Comment by Anahkiasen** [comment]
That worked, thanks!

**Comment by Julio-Assis** [comment]
just a note on the docs because it's related to this. On the page `https://redux-saga.js.org/docs/advanced/ForkModel.html` the `delay` import is coming from `'redux-saga/effects'` when it should be as you mentioned here `'redux-saga'`

**Comment by Andarist** [comment]
@Julio-Assis starting from redux-saga@1 the delay is coming from `redux-saga/effects`

**Comment by alexander-elgin** [comment]
It seems that `delay` had a long journey. it was at every place where it ever could.

**Comment by thehaystacker** [comment]
In your saga file, create a delay function like:

`const delay = time => new Promise(resolve => setTimeout(resolve, time));`
Then create the watcher like:

```
const fnWatcher = function* () {  
  yield call(delay, 2000);
  yield put({type: 'ACTION_SUCCESS'});
};

takeEvery("ACTION_NAME", fnWatcher);
```

**Comment by burakcan** [comment]
wow it's been almost 4 years. time flies.

**Comment by justinlazaro-iselect** [comment]
is delay already working in saga?

**Comment by Andarist** [comment]
Yes
