### ISSUE TITLE
`yield* takeEvery` causing 'not a function' error

### ISSUE THREAD

**Issue by davej** [yelouafi/redux-saga#197]
Basically more or less the same as the examples from the README. Using the following code:

```js
import { CREATING_LIVE_SHARE } from '../actions/liveShare';

export function* createLiveShare({ server }) {
  // ...
}
export function* watchLiveShare() {
  yield* takeEvery(CREATING_LIVE_SHARE, createLiveShare);
}
```

```js
import watchLiveShare from '../sagas/liveShare';

const sagaMiddleware = createSagaMiddleware(watchLiveShare);
const store = createStore(
  // ...
  applyMiddleware(sagaMiddleware)
);
```

The error I get is:
```
watchLiveShare: uncaught TypeError: (0 , _reduxSaga.takeEvery)(...)[(intermediate value)] is not a function
```

It works fine when I remove the `*` character from the `yield` statement, i.e. `yield takeEvery(...);`. I am not quite clear what `yield*` does compared to `yield` and if it is required.

Just in case it's relevant, I am using [babel-preset-es2015-node5](https://github.com/alekseykulikov/babel-preset-es2015-node5) in node, so generators are not being polyfilled.

**Comment by yelouafi** [comment]
I suspect this has to do with incomplete `yield*` support on Node 5. see https://kangax.github.io/compat-table/es6/#test-generators

**Comment by MichalBures** [comment]
I'm having the same issue running the latest Electron (0.37.2), though I also get this error:
`(0 , _reduxSaga.takeEvery)(...)[Symbol.iterator] is not a function`

I'm guessing it's related to the removal of Symbol in `0.9.2` since using the same configuration but with `0.9.1` works fine.

**Comment by davej** [comment]
@MichalBures FYI: I'm also in Electron.

**Comment by yelouafi** [comment]
>I'm having the same issue running the latest Electron (0.37.2), though I also get this error:
(0 , _reduxSaga.takeEvery)(...)[Symbol.iterator] is not a function

yeah; it seems a valid point. `takeEvery` implements iterators manually and `yield*` would be expecting a `Symbol.iterator` method. the method was removed since 0.9.2.

I'm also curious electron is throwing this kind of error, since electron (besides react native) was one of the platforms having issues with Symbols prior to 0.9.2

**Comment by davej** [comment]
I can also confirm that downgrading to `0.9.1` fixes this issue. @yelouafi: What's do you suggest? Stick with `0.9.1` for the moment?

**Comment by MichalBures** [comment]
> I'm also curious electron is throwing this kind of error, since electron (besides react native) was one of the platforms having issues with Symbols prior to 0.9.2

Well, I've been using `redux-saga` since something like `0.4.0` with Electron `0.36.x` (I've updated to `0.37.x` today as part of an update day) and so far I've had no issues.

**Comment by yelouafi** [comment]
>I can also confirm that downgrading to 0.9.1 fixes this issue. @yelouafi: What's do you suggest? Stick with 0.9.1 for the moment?

You can also just use the `yield takeEvery` form.  The only difference is when using the saga Monitor (you'll get an additional `unkown` node under the watcher) which is not a big deal IMO (and will probably be improved on the next release)

I can't re-add the Symbol support for now, as it'll cause a lot more trouble. Probably I should add a conditional check in the saga helpers

```javascript
function makeIterable() {
  const iterable = { next: ..., throw: ... }
  if(typeof Symbol !== undefined and Symbol.iterator) {
    iterable[Symbol.iterator] = () => iterable
  }
}
```

@MichalBures I was referring to this issue #157

**Comment by MichalBures** [comment]
`0.9.5` fixes this issue for me. Thanks!

**Comment by yelouafi** [comment]
Oops! forgot to mention this in release notes. Thanks for the remainder
