### ISSUE TITLE
Performance issue: the dispatch() of saga actions takes several hundred milliseconds

### ISSUE THREAD

**Issue by slestang** [yelouafi/redux-saga#201]
I refactor a rather complex logic of fetching/refreshing/updating data from a hierarchy of components to a redux saga and now I encounter jank each times my data get refreshed.

My saga is composed of a loop that every 10s fork a task with 2 levels of nested *yield call()* that end-up making XHR request. I have around 40 *leaf* call() that makes XHR requests.

So I have a timer that get triggered every 10s. With the Chrome Timeline I can clearly see 2 parts inside the timer:
* redux-saga execute all my *call()* and send the XHR requests (takes around 100ms). 
* redux-saga execute a redux dispatch() with, if I understood correctly, its *internal* actions, only useful for itself. This part takes around 400ms.

So every 10s my page freeze completely for half a second :-(

I looked at the average time of other dispatch on other view it is more around 20ms when they aren't any re-render.

Do you think I end up using redux-saga the wrong way or it seems *normal* to you?
Do you have any idea on how to improve this time?
Or do you need more information?

**Comment by yelouafi** [comment]
it may be related to #159. The midleware fires multiple monitoring events in dev. mode which may cause perf. issue. try in production mode

**Comment by slestang** [comment]
Thanks @yelouafi , with production files me task is always below 200ms of execution time. Much better.

**Comment by slestang** [comment]
Thanks @yelouafi , with production files me task is always below 200ms of execution time. Much better.
