### ISSUE TITLE
Not compatible with your operating system or architecture: fsevents@1.0.8

### ISSUE THREAD

**Issue by mahmoudHosny** [yelouafi/redux-saga#202]
when I'm trying to install redux-saga I got this error
Not compatible with your operating system or architecture: fsevents@1.0.8
node:5.8.0
npm:3.7.3

**Comment by yelouafi** [comment]
redux-saga doesn't have any dependency on `fsevents@1.0.8` this may be related to another module depending on filesystem events likely webpack or browserify

**Comment by mahmoudHosny** [comment]
Thank you
I'm using browserify
So I installed the module with no-optional flag

**Comment by aams** [comment]
See https://github.com/npm/npm/issues/11632
