### ISSUE TITLE
Errors not propagating as expected

### ISSUE THREAD

**Issue by davej** [yelouafi/redux-saga#203]
```js
function* doThrow() {
  throw new Error('some error');
}

function* doSomething() {
  try {
    yield call(doThrow);
  }
  catch(err) {
    console.log('caught error', err);
  }
}

export function* watchDoSomething() {
  yield* takeEvery('DO_SOMETHING', doSomething);
}
```

When I dispatch the `DO_SOMETHING` action with the code above, it doesn't catch the error as I would have expected, instead the console says:
```
Uncaught (in promise) Error: some error
```

I get the same output if I call the method directly: `yield doThrow()`.

If I add a `*` to the yield call on line 7 then it errors with:
```js
yield* call(doThrow);
// -> Uncaught (in promise) TypeError: (0 , _effects.call)(...)[(intermediate value)] is not a function
```

The only way I can get it to work as expected is if I add a `*` *and* call the method directly:
```js
yield* doThrow();
// -> caught error Error: some error
```

Any idea what's going on here, or am I doing it all wrong? I'm using the latest Electron release with redux-saga@0.9.1.

Apologies if this is expected behaviour rather than an issue in the lib.

**Comment by davej** [comment]
Just tried this on `redux-saga@0.9.4` and it seems to work ok now. This must have been fixed in newer versions.

**Comment by yelouafi** [comment]
yes it have been fixed in https://github.com/yelouafi/redux-saga/releases/tag/v0.9.3

>yield* call(doThrow);

You can't delegate (`yield*`) to any value. Only to iteratros see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/yield*
