### ISSUE TITLE
Time for v0.9.5 ?

### ISSUE THREAD

**Issue by fasterthanlime** [yelouafi/redux-saga#205]
Since there's been a few contributions merged since v0.9.4, I'd really like if there was a new release containing them! (keeping a git clone of the repo in my `node_modules` is impractical).

On a related note, does anyone know why telling npm to install a specific version of redux-saga doesn't work? When I have this in my package.json:

```json
dependencies: {
  "redux-saga": "git://github.com/yelouafi/redux-saga.git#master"
}
```

...then the installed `node_modules/redux-saga` doesn't contain a `lib/` directory, it only has `dist/`

(that's with npm 3.6)

**Comment by yelouafi** [comment]
I think yes. I'll be making a release tonight

**Comment by fasterthanlime** [comment]
Thanks a lot! Sorry for opening an issue on a sunday :star2:

**Comment by yelouafi** [comment]
forgot to mention 0.9.5 is out https://github.com/yelouafi/redux-saga/releases/tag/v0.9.5

**Comment by fasterthanlime** [comment]
Awesome, thanks!
