### ISSUE TITLE
How to take on either type?

### ISSUE THREAD

**Issue by bgerm** [yelouafi/redux-saga#21]
How can I `yield` on the `take` of either `types.TYPE_ONE` or `types.TYPE_TWO`?

I'm trying 

```
const { one, two } = yield race({
  one: take(types.TYPE_ONE),
  two: take(types.TYPE_TWO)
})
```

But `two` never seems to `take` unless I place it before `one` as follows (in which case `one` no longer takes):

```
const { one, two } = yield race({
  two: take(types.TYPE_TWO),
  one: take(types.TYPE_ONE)
})
```

**Comment by bgerm** [comment]
Still confused as to why that doesn't work, but I read the source and discovered you can do this:

yield take([types.TYPE_ONE, types.TYPE_TWO])

**Comment by slorber** [comment]
that seems to me a valid issue and i think both should work
