### ISSUE TITLE
Confused about the difference between certain patterns

### ISSUE THREAD

**Issue by Anahkiasen** [yelouafi/redux-saga#216]
I read the docs, and looked in the issues, but I'm still confused about the difference between certain patterns. Imagine I have a cycle that runs every second, and I want to do certain things each cycle, I have 3 sagas:

```js
function *taskOne() {}
function *taskTwo() {}
function *taskThree() {}

function *onCycle() {
  // ???
}
```

What would be the correct way to execute those each cycle? What is the difference between these three approaches?

```js
// Independant yields
yield taskOne();
yield taskTwo();
yield taskThree();

// Array yield
yield [
    taskOne(),
    taskTwo(),
    taskThree(),
];

// Array yield + fork
yield [
    fork(taskOne),
    fork(taskTwo),
    fork(taskThree),
];

// Array yield + call
yield [
    call(taskOne),
    call(taskTwo),
    call(taskThree),
];
```

From what I understand the first approach is blocking. Now fork starts the saga in the background, but the docs also mention that yielding an array also does this. And what does `call` do differently in this case?

**Comment by yelouafi** [comment]
### 1- Sequential execution

```javascript
yield taskOne();
yield taskTwo();
yield taskThree();

// or using the declarative form
yield call(taskOne);
yield call(taskTwo);
yield call(taskThree);
```

Will run the 3 sagas sequentially: first run `taskOne` and **wait until it terminates** then only resume and run `taskTwo` and also wait for its completion, and same with taskThree. `yield taskOne()` and `yield call(taskOne)` behaves the same way, in both cases the saga will block until the called task terminates; but the `call` form is easier to test (see [Declarative Effects](http://yelouafi.github.io/redux-saga/docs/basics/DeclarativeEffects.html))

### 2- Parallel execution (blocking)

```javascript
results = yield [
    taskOne(),
    taskTwo(),
    taskThree(),
];

// or
results = yield [
    call(taskOne),
    call(taskTwo),
    call(taskThree),
];
```

Will run all tasks in parallel and **wait for all of them to complete** before resuming; After all tasks complete (successfully) `results` will contain the return values of all called tasks

### 3- Parallel execution (Non blocking)

```javascript
results = yield [
    fork(taskOne),
    fork(taskTwo),
    fork(taskThree),
];

// same as
const results = []
results.push( fork(taskOne) )
results.push( fork(taskTwo) )
results.push( fork(taskThree) )
```

Will run all tasks in parallel **But do not wait for them to complete**. Instead the Saga will resume immediately. `results` will contain now an array of [Task](http://yelouafi.github.io/redux-saga/docs/api/index.html#task) objects. You can then use [`join`](http://yelouafi.github.io/redux-saga/docs/api/index.html#jointask) or [`cancel`](http://yelouafi.github.io/redux-saga/docs/api/index.html#canceltask) on those tasks

**Comment by Anahkiasen** [comment]
I see, makes a lot more sense now! Thanks a lot

**Comment by Sinistralis** [comment]
@yelouafi In regards to option 2, by "parallel" do you mean that each of these will be called in sequence even if they have not completed yet? As this is not the behavior I am seeing.

**Comment by Sinistralis** [comment]
Nevermind, I think I see what's up. The issue is Redux reads actions one at a time.

**Comment by anton6** [comment]
@yelouafi can you please clarify what is the difference between?:

```
results = yield [
    call(taskOne),
    call(taskTwo),
    call(taskThree),
];
```
and

```
results = yield all([
    call(taskOne),
    call(taskTwo),
    call(taskThree),
]);
```
