### ISSUE TITLE
Can you pass "this" to the function parameter of yield call? 

### ISSUE THREAD

**Issue by nickzarate** [yelouafi/redux-saga#217]
I am currently using [parse.com](http://parse.com/) with my application, and trying to add redux-saga. I obviously plan to get rid of parse as they are shutting down, but until I migrate off of it I am stuck with their "jQuery compatible" Parse Promises. I am attempting to use redux-saga's `yield call(fn, args)` function with `query.first().then` as the function parameter that returns a jQuery compatible Promise:
```
let query = new Parse.Query('ClassName')
let object = {}
try {
  object = yield call(query.first().then)
} catch(err) {
  console.log(err) // TypeError: Cannot read property '_resolved' of null
}
```
However the function always throws an error, and I think it is because redux-saga is expecting an es6 promise. Is there any way to use jQuery compatible promises with `call`?

**Comment by yelouafi** [comment]
>However the function always throws an error, and I think it is because redux-saga is expecting an es6 promise. Is there any way to use jQuery compatible promises with call?

`call` should work with any object having a `then` method. In your code you should however pass just the Promise-like object not the `then` method itself

```javascript
object = yield call(query.first())
```

**Comment by nickzarate** [comment]
Oh ok, sorry I should have mentioned, I have actually tried that as well but when I use:
```
object = yield call(query.first())
```
The error is:
```
Error: call/cps/fork first argument must be a function, an array [context, function] or an object {context, fn}
```
Also, `console.log(query.first())` logs a ParsePromise Object. Actually what I first tried was:
```
yield call(query.first)
```
but then I got an error in the query.first function, because it tries to access `this`, which has the value of null. I realize this may be a Parse issue.

**Comment by yelouafi** [comment]
You can pass `this` by using  [`apply`](http://yelouafi.github.io/redux-saga/docs/api/index.html#applycontext-fn-args)

```javascript
yield apply(query, query.first)
```

If you want to yield a promise directly you must do

```javascript
yield query.first()
```

But the 2nd form is [harder to test](http://yelouafi.github.io/redux-saga/docs/basics/DeclarativeEffects.html)

**Comment by nickzarate** [comment]
Wow, that works great, thank you so much! I will change the title in case anyone else has the same issue as this has nothing to do with jQuery compatible promises.
