### ISSUE TITLE
Should we catch `SagaCancellationException`?

### ISSUE THREAD

**Issue by zalmoxisus** [yelouafi/redux-saga#218]
Probably, I'm missing something, but manual cancelations throw in production.

I have
```js
export default function* rootSaga() {
  yield [
    takeLatest(SOME_ACTION, doSomeStuff),
    // ...
  ];
}
```

Where `doSomeStuff` is listening for messages via websockets, so when `SOME_ACTION` is called again it results in a `SagaCancellationException`, which is just an useful informative warning in development environment, but an `Unhandled promise rejection` in production.

UPD: It seems we always should have `try-catch` in the watchers even if the errors are handled in sub-functions.

**Comment by yelouafi** [comment]
>UPD: It seems we always should have try-catch in the watchers

Can you explain ? The cancellation errors are not propagated to parent sagas;  so even if you don't wrap a saga in a try/catch the cancellation of the sub-saga wont propagate to the parent saga

I think the error is thrown because the middleware fails the `done` promise of `doSomeStuff` And the browser runtime detects the failed/unhandled promise

**Comment by zalmoxisus** [comment]
@yelouafi, yes. I didn't have `try-catch` in `doSomeStuff` as it just calls subtasks where I was catching the errors, but we need catching errors along all children tree, even if we can have nothing than `SagaCancellationException` there.

To clarify this, I have a lot of socket subscribers. When the category is changed, I cancel everything and subscribe again to new channels with new data. Since the watcher has a lot of subtasks children, there are a lot to cancel.

**Comment by metrue** [comment]
@zalmoxisus 
@yelouafi 

So what is the best solution to handle <code> the SagaCancellationException </code>, 
if I have watcher and worker like this:

```
import types from './types';
import { takeLatest } from 'redux-saga';
import { put } from 'redux-saga/effects';
import api from '../../../api';

const {
  FETCH,
  FETCH_SUCCESS,
  FETCH_FAILED,
} = types.GAMES;

function* fetcher(action) {
  const { query } = action;
  const resp = yield api.listGames(query);
  if (resp.status === 200) {
    const { games } = yield resp.json();
    yield put({ type: FETCH_SUCCESS, list: games });
  } else {
    yield put({ type: FETCH_FAILED });
  }
}

function* fetchSaga() {
  yield* takeLatest(FETCH, fetcher);
}

export default [fetchSaga];
```

<code> SagaCancellationException </code> will happen when a FETCH happened, but  api.listGames not done yet.  do I need to take care this exception, and where I should to do the try-catch if I want to catch it.
