### ISSUE TITLE
actions dispatched by redux-saga are not detected by redux-localstorage middleware.

### ISSUE THREAD

**Issue by jhogendorn** [yelouafi/redux-saga#234]
This is an interaction with the [redux-localstorage@rc1](https://github.com/elgerlambert/redux-localstorage/tree/1.0-breaking-changes) package.

I'm not sure if this is a redux-saga issue, a redux-localstorage issue, or if I'm just doing something dumb, so apologies for the [cross-issue](https://github.com/elgerlambert/redux-localstorage/issues/39).

```
const rootMiddleware = compose(
  applyMiddleware(
    syncHistory(browserHistory),
    sagaMiddleware(...[sagas]),
    ...[otherMiddleware],
  )
)

  const finalReducer = compose(
    mergePersistedState()
  )(reducer)

  const storage = compose(
    filter(persistPaths)
  )(adapter(window.localStorage));

  const createPersistentStore = compose(
    persistState(storage, persistKey)
  )(createStore)

  return createPersistentStore(
    finalReducer,
    rootMiddleware,
  )

```

I'm finding that the localstorage middleware does not fire when actions are dispatched from a saga via `put`, however actions dispatched outside saga's hit the middleware just fine.

**Comment by yelouafi** [comment]
I suspect this has to do with Redux middleware/enhance issue. When there are multiple store enhancers, each enhancer gets its own dispatch pipeline, so an enhancer may not see actions from another enhancer (see for example #48 and https://github.com/yelouafi/redux-saga/issues/13#issuecomment-169179962)
