### ISSUE TITLE
Generators compiles to while loops

### ISSUE THREAD

**Issue by vojtatranta** [yelouafi/redux-saga#236]
Is it not a bad idea to use generators?
This is what you get in JS if you compile your example with Babel https://babeljs.io/repl/#?evaluate=true&presets=es2015%2Creact%2Cstage-2&experimental=true&loose=false&spec=false&code=import%20%7B%20takeEvery%2C%20takeLatest%20%7D%20from%20'redux-saga'%0Aimport%20%7B%20call%2C%20put%20%7D%20from%20'redux-saga%2Feffects'%0Aimport%20Api%20from%20'...'%0A%0A%2F%2F%20worker%20Saga%20%3A%20will%20be%20fired%20on%20USER_FETCH_REQUESTED%20actions%0Afunction*%20fetchUser(action)%20%7B%0A%20%20%20try%20%7B%0A%20%20%20%20%20%20const%20user%20%3D%20yield%20call(Api.fetchUser%2C%20action.payload.userId)%3B%0A%20%20%20%20%20%20yield%20put(%7Btype%3A%20%22USER_FETCH_SUCCEEDED%22%2C%20user%3A%20user%7D)%3B%0A%20%20%20%7D%20catch%20(e)%20%7B%0A%20%20%20%20%20%20yield%20put(%7Btype%3A%20%22USER_FETCH_FAILED%22%2C%20message%3A%20e.message%7D)%3B%0A%20%20%20%7D%0A%7D%0A%0A%2F*%0A%20%20starts%20fetchUser%20on%20each%20dispatched%20%60USER_FETCH_REQUESTED%60%20action%0A%20%20Allow%20concurrent%20fetches%20of%20user%0A*%2F%0Afunction*%20mySaga()%20%7B%0A%20%20yield*%20takeEvery(%22USER_FETCH_REQUESTED%22%2C%20fetchUser)%3B%0A%7D%0A%0A%2F*%0A%20%20Alternatively%20you%20may%20use%20takeLatest%0A%0A%20%20Do%20not%20allow%20concurrent%20fetches%20of%20user%2C%20If%20%22USER_FETCH_REQUESTED%22%20gets%0A%20%20dispatched%20while%20a%20fetch%20is%20already%20pending%2C%20that%20pending%20fetch%20is%20cancelled%0A%20%20and%20only%20the%20latest%20one%20will%20be%20run%0A*%2F%0Afunction*%20mySaga()%20%7B%0A%20%20yield*%20takeLatest(%22USER_FETCH_REQUESTED%22%2C%20fetchUser)%3B%0A%7D

And last thing you want is never ending loop in your code that blocks everything. Should you not rather use standard promises?

**Comment by billyjanitsch** [comment]
There's no infinite/blocking loop here (see the switch cases with `return` statements). For more info about how this works, look into Facebook's [`regenerator`](http://facebook.github.io/regenerator/), used by Babel. Generators (both natively and as simulated by `regenerator`) are non-blocking. Promises don't quite accomplish the same goal.

**Comment by yelouafi** [comment]
@vojtatranta the while loop is just used to orchestrate the generator flow (the return statements inside the switch break the while loop). It doesn't mean the generator will run forever and consume your entire CPU time. otherwise everybody would have noticed , don't you think? :)
