### ISSUE TITLE
Non blocking calls

### ISSUE THREAD

**Issue by Mistereo** [yelouafi/redux-saga#238]
What is `Api.storeItem` and `Api.clearItem` in [Non blocking calls](http://yelouafi.github.io/redux-saga/docs/advanced/NonBlockingCalls.html) section of docs?

It seems to me that it should be:
```javascript
yield call(Api.storeItem, {token})
// and
yield call(Api.clearItem, 'token')
```
Instead of:
```javascript
yield call(Api.storeItem({token}))
// and
yield call(Api.clearItem('token'))
```
Am I missing something here?

**Comment by yelouafi** [comment]
>Am I missing something here?

No, It's me who missed here :)
