### ISSUE TITLE
Middleware should be passing EFFECT actions?

### ISSUE THREAD

**Issue by joonhyublee** [yelouafi/redux-saga#241]
Hi,
I'm currently building a performance-critical app:
- that fires many actions per second (~x60 per second)
- that has many react-redux connect()ed components
- that has many sagas running in parallel to take care of effects (~x5 effects per action)

Since I'm also relying heavily on multiple sagas to take care of effects, I get many saga-related actions running through my redux reducers (`EFFECT_TRIGGERED`, `EFFECT_RESOLVED`, `EFFECT_REJECTED`), but I don't think it is necessary for them to go normal redux reducers, because they are dealt only by sagas anyway.

So I implemented something like:

```javascript
const no_saga_actions = () => next => action => {
    if (action.type != 'EFFECT_TRIGGERED' &&
        action.type != 'EFFECT_RESOLVED' &&
        action.type != 'EFFECT_REJECTED') return next(action);
};
```

where my redux configuration store looks like:
```javascript
const store  = createStore(
    combined_reducer,
    applyMiddleware(
        createSagaMiddleware(...combined_saga),
        no_saga_actions,
    )
);
```

I know I have to minimize the number of effects and connect()ed components to increase speed eventually, but this has resulted in much greater performance already, simply because my redux store is receiving less actions and that results in less connect()ed wrapper renders.

I wonder if passing saga-related actions is by design, or if there should be an option somewhere to prevent it from flowing to redux reducers (or if you would like me to submit a PR for that)..?

Thanks!

**Comment by yelouafi** [comment]
Those are monitoring actions. They are only fired in development mode. You wont see them if you start your app in production mode

**Comment by joonhyublee** [comment]
Thanks for the clarification. I've been using a build from npmcdn. Using the minified build also solves the problem, for anyone else interested!

**Comment by ronanwize** [comment]
@joonhyublee curious, what kind of performance are you seeing? We're in development of something similar and I'm curious what the throughput of the sagas is.

**Comment by joonhyublee** [comment]
@ronanwize for reference, I have a page of about x10 custom-built graphs. Because each graph selectively fetches data from the server and automatically zooms to fit data on the fly when a user drags it, I have each of the mouse events handled as action to the redux store and various effects handled by redux saga. (without all these effects, I would just handle them as local component state updates)

So optimally, with proper throttling and all, I have **~x60** actions per second. Each scroll action may trigger 3~5 effects within the respective saga. So that is **~x300** actions per second. With x10 graphs on the page, each react-redux `connect()`ed to redux store, this leads to **~x3,000** `connect()` wrapper re-renders per second and more, leading to heavy jank (**~5fps**), even with all the `shouldComponentUpdate` optimizations. Granted, `connect()` wrappers are very efficient, **but no user interaction should be firing x1,000's of function calls in the first place.**

As you can see, things can get out of hand really easily when you handle mouse events through redux store / redux saga, but it was _absolutely necessary_ in my case. To optimize, it is crucial to:
- minimize actions passed to the store (all `connect()`ed wrappers will update for each action) &
- minimize the number of `connect()`ed components at a given instance
- make `mapStateToProps` functions as computation-free as possible

There is no trick here, but with aggressive effects batching, component restructuring, selective showing (rendering only the visible graphs using infinite-list-esque technique), I got the number of actions, number of `connect()`ed components and subsequent re-renders down to manageable level.

One useful technique is to implement a custom middleware similar to one shown above to **filter out actions specific to redux-saga**. These actions had the sole purpose of triggering a saga, and had no direct consequence on the store. **Remember, even inconsequential actions will invalidate the store and trigger an update on all `connect()`ed components**. This alone significantly cut down the number of actions. There are libraries that allow you to do this, like [**redux-ignore**](https://github.com/omnidan/redux-ignore), but my use case was so simple that I just wrote my own.

**Comment by joonhyublee** [comment]
Just to add, it can be difficult to use existing redux monitoring tools to see all the actions that are being passed to the store, simply because there are too many actions being fired per second and devtools designed to scrutinize individual actions can't keep up. So I wrote a simple aggregate analytics middleware to use in conjunction with react perf addon:
![image of aggregate analytics](https://i.imgur.com/KSKCtRu.png)
```javascript
const make_analytics = () => {
    const perf = React.addons.Perf;
    let stats = {};
    let is_counting = false;
    
    const count_action = action => {
        if (is_counting) {
            if (!stats[action.type]) stats[action.type] = 1;
            else stats[action.type] = stats[action.type] + 1;
        }
    };
    
    const start = () => {
        is_counting = true;
        perf.start();
    };
    
    const stop = () => {
        is_counting = false;
        perf.stop();
        console.log(stats);
        perf.printWasted();
        stats = {};
    };
    
    const get_stats = () => {
        console.log(stats);
    };
    
    return {
        count_action,
        start,
        stop,
        get_stats
    };
};

window.analytics = make_analytics();

const analytics_middleware = store => next => action => {
    window.analytics.count_action(action);
    return next(action);
};
```
and using it looks like:
```javascript
store  = createStore(
    combined_reducer,
    applyMiddleware(
        analytics_middleware,
        createSagaMiddleware(...combined_saga),
        ignore_middleware
    )
);
```
in case you are wondering what my ignore_middlware looks like:
```javascript
const ignore_middleware = store => next => action => {
    if (action.type != 'REQUEST_NAVIGATION') return next(action);
};
```
@yelouafi sorry, this is not really redux-saga specific, but thought I'd share since somebody asked.. :)

**Comment by slorber** [comment]
@joonhyublee this might interest you: http://stackoverflow.com/questions/34782249/can-a-react-redux-app-really-scale-as-well-as-say-backbone-even-with-reselect/34788570

**Comment by joonhyublee** [comment]
@slorber food for thought. thanks!
