### ISSUE TITLE
Translate docs to chinese (started)

### ISSUE THREAD

**Issue by superRaytin** [yelouafi/redux-saga#242]
`redux-saga` is very helpful for me, so I decided to translate all docs to chinese, this may help other chinese developers too :)

The repo located at [https://github.com/superRaytin/redux-saga-in-chinese](https://github.com/superRaytin/redux-saga-in-chinese)

**Comment by yelouafi** [comment]
Thanks! I'll add a link to this in the docs

**Comment by yelouafi** [comment]
Sorry for being (too much) late. I added a link ti the README

https://github.com/yelouafi/redux-saga#documentation
