### ISSUE TITLE
Run real saga actions within unit tests?

### ISSUE THREAD

**Issue by aksonov** [yelouafi/redux-saga#243]
I want to run saga actions within unit tests (nodejs environment) and cannot find how. I've tried to run store.dispatch(ACTION) and then wait using setTimeout(5000, done) but it doesn't work.

Note, i don't want to test actions itself (i saw docs how to test actions easily without any mock), but want to run related 'watch' generators and all real saga chains.

**Comment by darrhiggs** [comment]
You have your `setTimeout` [arguments backwards](https://developer.mozilla.org/en-US/docs/Web/API/WindowTimers/setTimeout) in your comment.

Is it the same in your code?

**Comment by aksonov** [comment]
I'm just doing 'sleep' using setTimeout and done but probably it is not enough:
```
        store.dispatch({type: actions.LOGIN_REQUEST, username: users[3], password: passwords[3]});
        setTimeout(done, 5000);
```
store is created as written in docs. The same store used by Provider within react native and LOGIN_REQUEST is processed correctly.

**Comment by aksonov** [comment]
Yes, i didn't write correctly arguments in first comment, but code arguments should be ok and it still doesn't work...

**Comment by darrhiggs** [comment]
I'm not sure exactly what you are asking. In your first comment you state:

> I want to run saga actions within unit tests (nodejs environment) and cannot find how

If this is what you want then the [docs](http://yelouafi.github.io/redux-saga/docs/advanced/Testing.html) give you some examples of how to test sagas.

**Comment by aksonov** [comment]
But I don't want to test sagas, i want to run them...

**Comment by fhelwanger** [comment]
Take a look at http://yelouafi.github.io/redux-saga/docs/api/index.html#runsagaiterator-subscribe-dispatch-getstate-monitor

**Comment by aksonov** [comment]
@fhelwanger Thanks, but i want to run it _inside_ redux environment (but nodejs not react native).

**Comment by darrhiggs** [comment]
Could you link to a gist of your unit test (maybe with some explanatory comments) of what you are trying to achieve.

**Comment by aksonov** [comment]
I've just used this for thunk: http://redux.js.org/docs/recipes/WritingTests.html
Looks like it is the same for saga, i've just thought that maybe there is some easier way to run saga actions.

**Comment by yelouafi** [comment]
@aksonov Without seeing a gist or a simplified example, we can't really say why it doesn't work
