### ISSUE TITLE
Rendering before completion

### ISSUE THREAD

**Issue by foobahh** [yelouafi/redux-saga#244]
Question here (likely not an issue with redux-sagas, and more just how redux handles promises)... I can't seem to figure out why the redux/saga app is not waiting until post-success to re-render itself.  I have noticed similar behavior with the redux-promises package.  Below is example output with redux-logger (which is provided as the last middleware option to the store, per the logger docs), which was generated with a bare-minimum replica of the real-world example simply fetching a single user from a local DB
```
action @ 22:34:39.603 TRIGGER_FETCH 
index.js:150  action @ 22:34:39.609 USER_REQUEST 
App.js:17 RENDERING  Object {user: Object}
index.js:150  action @ 22:34:39.640 USER_SUCCESS 
```
is this expected behavior? Or is this symptomatic of having configured a generator incorrectly...

Thanks!

**Comment by yelouafi** [comment]
> I can't seem to figure out why the redux/saga app is not waiting until post-success to re-render itself

It's hard to answer without providing more details. The time the app will re-render itself depends on how you wire the store to your component and isn't related to Sagas. If you're using react-redux then a component will re-render every time the connected state slice changes

**Comment by foobahh** [comment]
Going to close & follow up with either the redux repo itself or redux-logger, this behavior seems to be prevalent with all async implementations (if you were to console.log in App.js within the redux async example, same thing occurs).  Just weird.  Thanks though! This is a great repo, nice work

**Comment by adamyonk** [comment]
@foobahh do you have any follow-up issues elsewhere on GH? I'm interested in this as well.
