### ISSUE TITLE
Exception getting lost when calling iterator.throw on a generator that doesn't define a correponding try/catch

### ISSUE THREAD

**Issue by danwad** [yelouafi/redux-saga#245]
Uncaught exceptions are logged to console in the `next` method in `proc.js`, but are a bit difficult to track down as the logged exception isn't the original exception but the one thrown by regenerator when it tries to call `throw` which doesn't exist.

[proc.js#L135-L154](https://github.com/yelouafi/redux-saga/blob/master/src/internal/proc.js#L135-L154)

    try {
      // calling iterator.throw on a generator that doesn't define a correponding try/Catch
      // will throw an exception and jump to the catch block below
      const result = error ? iterator.throw(error) : iterator.next(arg)
      if(!result.done) {
         runEffect(result.value, parentEffectId, '', next)
      } else {
        end(result.value)
      }
    } catch(error) {
      if(error instanceof SagaCancellationException) {
        end(error, false, true)
        if(isDev) {
          log('warn', `${name}: uncaught`, error)
        }
      } else {
        end(error, true)
        log('error', `${name}: uncaught`, error)
      }
    }

Console displays:

`proc.js:123 sagaName: uncaught TypeError: Cannot read property 'call' of undefined(…)`

If I stick a breakpoint in `proc.js` I can see the correct exception in the error variable in the try block but `iterator.throw(error)` hides the exception.

I am using babel-polyfill and I believe the logged exception originates [here](https://github.com/facebook/regenerator/blob/master/runtime.js#L62).

**Comment by yelouafi** [comment]
Can you give a little example? In my local tests I can see the same error thrown inside the Saga logged into the console.

**Comment by danwad** [comment]
Sorry for the delay. I've figured out the cause but I'm not sure if this is supported usage.

```
function* error() {
  throw new Error('this error is not logged correctly')
}

function* saga() {
  yield* [
    error()
  ]
}
```

**Comment by slorber** [comment]
@danwad if you call error() like that the generator is not called it's just a regular function call then. You should rather use:

```javascript
function* saga() {
  yield* [
    call(error)
  ]
}
```

**Comment by danwad** [comment]
@slorber Oops - thanks. This also hides the exception.

```JavaScript
function* error() {
  throw new Error('this error is not logged correctly')
}

function* saga() {
  yield* [
    call(error)
  ]
}
```

**Comment by slorber** [comment]
have you imported call?

Also I'm not sure but is `yield* []` with an array something that actually works? (I mean with the asterisk)

**Comment by danwad** [comment]
`yield*` is used to [yield to an iterable object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/yield*). An array is iterable and so `yield* []` is valid.

Yes, redux-saga's `call` is imported.

**Comment by danwad** [comment]
This issue is fixed in master.
