### ISSUE TITLE
Max sagas in a real-world app

### ISSUE THREAD

**Issue by ronanwize** [yelouafi/redux-saga#248]
Hi @yelouafi a quick question:

What is the reasonable maximum number of sagas one could have in a real-world app?

The examples are of course quite simple; a production application will have alot more. Have you profiled this? What is a realistic number we can use and have good performance? 100? 1000?

Thanks!

**Comment by burakcan** [comment]
In my current project; there's around 80-90 sagas(some of them are really complex full flows like login flow) and i didn't experience any performance issue; but didn't do an in depth analysis.

**Comment by yelouafi** [comment]
@ronanwize I don't have an exact answer to this. a Saga 'running in the background' is just an object instance with a few method and its local/closure state. IMO what affects the performance is not how many Sagas do you have in an application but how many Sagas fires concurrently in response to a single action.

And If you have a large number of Sagas you could  try to refactor the common code into common sagas (for example request/response with the same logic)

**Comment by ronanwize** [comment]
Thanks for the response @yelouafi - I was suspecting the answer was along those lines. 

We actually have alot of sagas that are more or less boilerplate to execute all of our API activities so we're working on refactoring them into a saga "generator". We're planning on open-sourcing most of this once it's in a more or less stable, working state because we've done a few things we haven't seen before. Should be interesting.

Thanks for the advice about keeping concurrent sagas to a minimum - I'll make sure this gets into our architectural recommendations too.
