### ISSUE TITLE
yield from callback function/event listener?

### ISSUE THREAD

**Issue by evgenyt1** [yelouafi/redux-saga#249]
Is there a way to yield from callback function. e.g.

```
function* mySaga() {
    hashHistory.listenBefore(location => {
        yield put({ type: 'LOCATION_CHANGE', payload: location });
        var state = yield select();
        return true; // or false depending on state
        // or do some more yield stuff        
    });
}
```

How do you handle this kind of side effects?

**Comment by fhelwanger** [comment]
Your `listenBefore` callback is in a different context than your saga, it's a normal function, not a generator. Thus, you can't use `yield` and redux-saga insn't aware of it.

I'd call `listenBefore` outside my saga (maybe where you setup react-router?) and use `store.dispatch` to dispatch `LOCATION_CHANGE`. Then, inside the saga, you can `yield take('LOCATION_CHANGE')` to handle additional side effects.

**Comment by evgenyt1** [comment]
@fhelwanger Thanks for reply.
yield take('LOCATION_CHANGE') won't allow me to return value from callback (to prevent or allow browser navigation).

Does it mean that this kind of "side effect" couldn't be handled in sagas at all?

**Comment by zalmoxisus** [comment]
Hey @evgenyt1.

You can do it as follows:
```js
const watchHistory = () => new Promise((resolve, reject) => {
  hashHistory.listenBefore(location => { resolve(location); }
});

function* mySaga() {
    let location;
    while (true) {
        location = yield watchHistory();
        yield put({ type: 'LOCATION_CHANGE', payload: location });
        var state = yield select();
        return true; // or false depending on state
        // or do some more yield stuff   
    }
}
```

A second solution would be to use channels as [described on SO](http://stackoverflow.com/questions/35277682/how-to-tie-emitted-events-events-into-redux-saga). It is also planned to [be supported out of the box](https://github.com/yelouafi/redux-saga/issues/155).

A third solution would be just to use `dispatch` (and `getState` in your case) parameters passed into rootSaga. Though it seems uglier than above ones, I usually use this solution for binding events. A bit harder to test, but cleaner and guaranteed that you'll not miss any event.

**Comment by evgenyt1** [comment]
@zalmoxisus "return true" will just return from mySaga, and won't be handled by listenBefore

Thanks for channels reference.

**Comment by zalmoxisus** [comment]
@evgenyt1, you could pass state to `watchHistory` and return true or false inside `hashHistory.listenBefore` listener, but it will recreate additional listener every time, so I removed that solution.

**Comment by yelouafi** [comment]
@evgenyt1 did you find some warkaround?

**Comment by evgenyt1** [comment]
@yelouafi I spent few days trying and debugging a bunch of ways, including generating and handling promises, using callbacks, etc. However all of this complicated my code much and was unreliable (as I want different sagas handle different routes and depend on each other result). 

My workaround is not to use sagas in this case. Just a special list or routing handlers, that are called synchronously in predictable order by some general entry point (events of router), get state/dispatch and routing stuff as parameters, with final "fallback" handler that just approves user navigation (it wasn't handled by routing handlers).

In my case I have a routing directory in src with handleAuth.js, handlePage1.js, handlePage2.js etc.
So the order is also important, and event handlers can depend on other handler result. As auth goes first, than page handlers that can fetch some data from store, redirect (using dispatch), etc etc

**Comment by yelouafi** [comment]
@evgenyt1 Thanks for you feedback. I think this kind of interaction is better handled by a more conventional listener approach. At least I can't think of a simple method using Sagas

**Comment by jk2K** [comment]
refer to http://stackoverflow.com/a/35288877/2227031

so far the best way is create a generic channel with put and take methods?

**Comment by jk2K** [comment]
After many many google and carefully read the redux-saga docs
I found that we can use [`eventChannel`](http://yelouafi.github.io/redux-saga/docs/advanced/Channels.html) of redux-saga

See my [SO](http://stackoverflow.com/a/38762340/2227031) answer

**Comment by mohamed-ismat** [comment]
Hi everyone, just a question related to this. If I pass down the store instance from where I configure the store to the root saga, and down to my saga where I need to dispatch an action inside an event callback, is there anything wrong with doing this?

```
function* saga(store) {
  const notification = new Notification("title")

  notification.onclick = e => {
    store.dispatch(someAction())
  }

}
````

**Comment by Andarist** [comment]
@mohamed-ismat its breaking the standard control flow and bypass the saga execution, you can wrap your `Notification` in a channel

```js
const chan = eventChannel(emit => {
  const notif = new Notification("title")
  notif.onclick = e => emit(someAction())
  return () => {}
})
const ac = yield take(chan)
chan.close()
yield put(ac)
```
