### ISSUE TITLE
Regenerator runtime in lib/dist

### ISSUE THREAD

**Issue by npbee** [yelouafi/redux-saga#252]
Hello and thanks for your work on this library!

I noticed that there are some generator functions in the `src` that are being compiled to use the regenerator runtime within `lib` and `dist`:

https://github.com/yelouafi/redux-saga/blob/master/src/internal/proc.js#L377-L382

```javascript
else {
  _iterator = (error ?
      function*() { throw error }
    : function*() { return (yield result) }
  )()
}
```

https://github.com/yelouafi/redux-saga/blob/master/dist/redux-saga.js#L857-L886
```javascript
else {
    _iterator = (error ? regeneratorRuntime.mark(function _callee() {
        return regeneratorRuntime.wrap(function _callee$(_context) {
            while (1) {
                switch (_context.prev = _context.next) {
                    case 0:
                        throw error;

                    case 1:
                        case 'end':
                        return _context.stop();
                }
            }
        }, _callee, this);
    }) : regeneratorRuntime.mark(function _callee2() {
        return regeneratorRuntime.wrap(function _callee2$(_context2) {
            while (1) {
                switch (_context2.prev = _context2.next) {
                    case 0:
                        _context2.next = 2;
                    return result;

                    case 2:
                        return _context2.abrupt('return', _context2.sent);

                    case 3:
                        case 'end':
                        return _context2.stop();
                }
            }
        }, _callee2, this);
    }))();
}
```

I don't think this was intentional because it basically requires the end user to have the regenerator runtime library in place.  I think some form of this issue has been in place for a while in the library and I've been using it without issue, so it seems like an edge case.  But just for reference, here's a quick fiddle that shows the failure case:  https://jsfiddle.net/npbee/bbz17aak/1/

There are a couple of different ways to solve this and I'm not sure which you think would be the best way.  I'm happy to help in any way I can!

**Comment by yelouafi** [comment]
@npbee Thanks for pointing to this. it was an inattention from my part
