### ISSUE TITLE
[API Proposal]: Support for channels/event sources

### ISSUE THREAD

**Issue by yelouafi** [yelouafi/redux-saga#254]
this has been a long standing issue in redux-saga: how to hookup to external event sources like websockets, observables ...

## Problem

actually redux-saga provides only a way to connect to dispatched store actions using `take(pattern)`. If you want to introduce other events, say for example a websocket connection, you'll need to subscribe manually to the source and then dispatch actions to the store. But then you you'll have to carry the `store.dispatch` method along the saga call/fork chain which is awkward.

In some SO answers I was recommending solutions based on channels ([see here](http://stackoverflow.com/questions/35277682/how-to-tie-emitted-events-events-into-redux-saga)). In the following I propose a possible integration of this solution into redux-saga

## Proposal

This involves 2 additions: new `take(channel, [pattern])` and introducing a special `END` action. In this post I'll present only the 1st. I present `END` in  its own issue (#255) since it deserves a separate discussion

A channel is basically an object with 2 method `take` and `put`. In this proposal I introduce only one type of channels: event channels. which can be connected to source events. Fundamentally, this generalize the actual take, since store actions maybe considered as the default input channel for sagas

There is a [usage example ](https://github.com/yelouafi/redux-saga/blob/master/examples/cancellable-counter/src/sagas/index.js) in the cancellable-counter example. Below is an excerpt

```javascript
import { eventChannel, END } from 'redux-saga'


const countdown = (secs) => {
  /**
     eventChannel takes a subscribe function, under the hood it creates
     a channel and put all emitted events from the event source into the channel
  **/
  return eventChannel(listener => {
      const iv = setInterval(() => {
        secs -= 1
        if(secs > 0)
          listener(secs)
        else {
          //console.log('countdown terminated')
          listener(END)
          clearInterval(iv)
          
        }
      }, 1000);
      /**
         the subscribe function of the event source must return an unsubscribe
      **/
      return () => {
        //console.log('countdown cancelled')
        clearInterval(iv)        
      }
    }
  )
}

export function* incrementAsync({value}) {
  const chan = yield call(countdown, value)
  try {
    let ev = yield take(chan)
    while(ev !== END) {
      yield put({type: INCREMENT_ASYNC, value: ev})
      ev = yield take(chan)
    }
    yield put(action(INCREMENT))
  } finally {
    /**
       closing the channel causes the event channel to unsubscribe
       this is no-op if the channel has already terminated
    **/
    chan.close()
  }
}
```

Questions

- What do you think of this solutions? pros/cons, are there other possible solutions?

- actions are not queued in the actual implementation, so the model works like with the actual `take(action)`. I preferred to keep things simple. Should we introduce buffering (Is it indispensable with now non blocking is possible) ? and how do buffering compose with the actual race/parallel effects?

- actually `eventChannel` has a signature of `subscribe -> channel` where `subscribe: listener -> unsubscribe`. i.e. The `subscribe` argument is a function which takes a listener and returns an unsubscribe function. I'm not sure if we should have a signature similar to Rx of the upcoming [ES6 observable](https://github.com/zenparsing/es-observable). Actually you can signal completion by emitting an `END` event, and errors by putting an `Error` object. Since observables may be standarized on Javascript, should we adopt the ES6 signature for subscription?

- should we provide a direct `take(observable)` which creates automatically the event channel internally and connect it to the source? it'd make things easier but also pose some conceptual issues, esp. managing subscription disposal.

- Actually the full `channel` interface is not exposed but only the eventChannel part. Exposing the full channel w'll be able to also put on the channel: (`yield put(channel, action)`) which may provide a way for Sagas to communicate directly without passing via store actions. Do you think this is necessary?

**Comment by timeu** [comment]
Support for channels/events would be great. 
I have been using the channel approach of your StackOverflow answer (the one you linked) for reacting to websocket events and so far it works really good. As far as I understand the proposal, it tries to generalize the solution of the stackoverflow answer ?

For Websockets I think some kind of buffering would be really handy. Would it be possible to implement a  buffered channel manually/by the user with your `eventChannel` proposal ?

**Comment by imranismail** [comment]
I've been using the above as well, in fact I've went ahead and written a library for it

https://github.com/127labs/fawkes.js

Please proceed with this.

**Comment by yelouafi** [comment]
> As far as I understand the proposal, it tries to generalize the solution of the stackoverflow answer ?

It's more about formalizing the concept. Generalization applies to `take` since now `take(action)` can be simply seen as taking from a (very special) channel: the redux store channel.

>For Websockets I think some kind of buffering would be really handy. Would it be possible to implement a buffered channel manually/by the user with your eventChannel proposal ?

Is it necessary to have buffering? If you have a saga which take events then forks tasks in a non-blocking way, then you won't miss any event. 

Are there any use cases which can't be solved with the take-and-fork pattern?

**Comment by timeu** [comment]
@yelouafi: Ah I think I understand now. Yeah I think this is an elegant solution . 

Regarding buffering: 
Currently I fork a saga to watch websockets events and based on the contents I dispatch actions to update the store : 

```javascript
function* monitorWebSocketEvents(channel) {
  while (true) {
    const message = yield call(channel.take);
    var body = JSON.parse(message.body);
    switch (body.state) {
      case 'FINISHED':
        yield put(analysisFinished(body,body.id));
        break;
      case 'ERROR':
        yield put(analysisFailed(body,body.id));
      default:
        yield put(messageReceived(body,body.id));
    }
  }
}
````

So I guess without buffering I would fork another saga task that actually dispatches the action ? 

```javascript
function* monitorWebSocketEvents(channel) {
  while (true) {
    const message = yield call(channel.take);
     fork(handleWebSocketEvent,message);
  }
}

function* handleWebSocketEvent(message) {
   var body = JSON.parse(message.body);
   switch (body.state) {
      .... # see above
  }
}
````
I guess I won't miss any events with the take-and-fork pattern but is the order of handling the events guaranteed with that approach ?

**Comment by yelouafi** [comment]
@timeu good remark. 

The order is not the same in the 2 approach. In the queued channel version actions are dispatched in sequence while in the 2nd actions from forked tasks are interleaved.

I guess it makes sense to add the  queueing variant (including for store action)
