### ISSUE TITLE
Can I inject/mock the store when unit testing redux-sagas?

### ISSUE THREAD

**Issue by garpur** [yelouafi/redux-saga#256]
I have a saga that uses "yield select()" to get the store state and uses that state to decide if it should perform an async data-fetch.

I can easily test the "data needed" scenario but am having problems testing "data already in store"

is there a recommended way to test this?

cheers garpur

**Comment by yelouafi** [comment]
You can pass the mock result to the next call of `generator.next`

```javascript
function* saga() {
  const state = yield select(mySelector)
  if(!state.dataLoaded)
    yield call(fetchData)
}

const gen = saga()
assert.deepEqual(gen.next().value, select(mySelector))
assert.deepEqual(gen.next({dataLoaded: false}).value, call(fetchData))
```

**Comment by garpur** [comment]
Thank you that did the trick :)

**Comment by kwnccc** [comment]
@yelouafi @garpur Trying the same test case with Jest doesn't work the same for the `select` effect. 

```
const gen = saga()
expect(gen.next().value).toEqual(select(mySelector));
```
Jest returns the following explanation:
```
Expected value to equal:
  {"@@redux-saga/IO": true, "SELECT": {"args": Array [], "selector": [Function stateSelector]}}
Received:
  {"@@redux-saga/IO": true, "SELECT": {"args": Array [], "selector": [Function stateSelector]}}
Difference:
Compared values have no visual difference.
```

**Comment by Andarist** [comment]
Probably ur `mySelector` has other references in both cases. Could u check it?

**Comment by kwnccc** [comment]
@Andarist `mySelector` is nothing more that an anonymous function that returns the current state, so it's something like `const state = yield select(state => state)`. Is this not a proper way?

**Comment by kwnccc** [comment]
Yeap so the above approach made it work! So as you described @Andarist the reference is the same in that way.

**Comment by Andarist** [comment]
Yeah, i think most people store their selectors in the reducer file or in a dedicated file but close to the reducer
