### ISSUE TITLE
Is it possible to watch for @@INIT?

### ISSUE THREAD

**Issue by jshthornton** [yelouafi/redux-saga#259]
Currently I have an app which needs to wait for the `@@INIT` action to start a saga. But all of my current attempts result in `@@INIT` being called before the sagas have start up.

Is there a better way to do this?

**Comment by yelouafi** [comment]
I'm not sure if `@@INIT` is a public API in Redux (cc @gaearon). for example inside reducers you rely only on the state param to be undefined. 

Is it necessary to wait for the specific `@@INIT`. You can for example start the saga after the store creation

```javascript
import createSagaMiddleware from 'redux-saga'
// other imports

const sagaMiddleware =  createSagaMiddleware()
const store = createStore(reducer, applyMiddleware(sagaMiddleware ))
sagaMiddleware.run(mySaga)
```
