### ISSUE TITLE
Reset sages when redux-devtools reset/revert the state

### ISSUE THREAD

**Issue by pke** [yelouafi/redux-saga#260]
I have a saga that pulls data in intervals from a server when the user is logged in.
Using the `redux-devtools` its possible to revert such a logged in state, but the saga continues to run cause it cached the authentication token from the previous state when it started.

Whats the best pattern to make sagas react to `redux-devtool` changes?

**Comment by slorber** [comment]
@pke this is a hard problem to solve.

Sagas come from backend world, and during event-sourcing replay, we generally disable the sagas (or at least make them not reprocess already processed events). The thing is we generally replay the full event-log (with different projection, ie reducers, code) and we don't reset to a past point and start going new actions from here (like Redux permits). 

These problems have already been discussed a bit in existing issues, like https://github.com/yelouafi/redux-saga/issues/22

**Comment by yelouafi** [comment]
Also see #5
