### ISSUE TITLE
Cancel all tasks in login flow

### ISSUE THREAD

**Issue by pke** [yelouafi/redux-saga#261]
I have this saga:

```
function* authorizedFlow() {
  let payload
  while (({payload} = yield take(actions.LOGIN_SUCCESS))) {
    const { access_token } = payload
    yield race({
      watchers: yield [
        call(refreshUser, access_token),
        call(refreshActivities, access_token),
        call(refreshPendingTransactions, access_token)
      ],
      logout: yield take(actions.LOGOUT_SUCCESS)
    })
    console.info("authorizedFlow: Logged out")
  }
}
```

I would like to cancel all the watchers when the `LOGOUT_SUCCESS` action was sent. The `cancel` method does not seem to accept an array of tasks. Whats the most elegant way to cancel those watchers. Is that flow a good pattern anyway? Of course each watcher could race against the `LOGOUT_SUCCESS` itself but I'd like to keep them clean.

**Comment by slorber** [comment]
@pke 

Take a look at: https://github.com/yelouafi/redux-saga/issues/78


The generator loosing the race should normally already be cancelled automatically as far as I know. 

Also this [comment](https://github.com/yelouafi/redux-saga/issues/78#issuecomment-181530866):

> Parallel effect cancellation means cancellation of all sub-effects

So, for me it looks like your watchers should already be cancelled on logout. Are you sure they are still running? Unless you fork them they should already be automatically cancelled no?

**Comment by pke** [comment]
They definitely keep on running.

Thats how they look: 

```
function* refreshUser(access_token) {
  while (true) {
    try {
      const user = yield call(api.getUserAsync, access_token)
      yield put(actions.userRefreshed(user))
    } catch (error) {
      // No user refresh error show. We should have a global strategy to count refresh errors
      // And display a message
      console.error(error)
    }
    yield take(actions.REFRESH_USER)
  }
}

function* refreshActivities(access_token) {
  while (true) {
    try {
      const activities = yield call(api.getActivitiesAsync, access_token)
      console.info(`${activities.length} activities fetched`)
      yield put(actions.activitiesUpdated(addInvoices(sortActivities(activities))))
    } catch (error) {
      console.error(error)
    }
    /*yield race({
      timeout: call(delay, 5 * 1000),
      refresh: take(actions.REFRESH_ACTIVITIES)
    })*/
    yield take(actions.REFRESH_ACTIVITIES)
  }
}

function* refreshPendingTransactions(access_token) {
  while (true) {
    try {
      let pending = yield call(api.getPendingParkingTransactionsAsync, access_token)
      yield put(actions.pendingTransactionsUpdated(pending))
    } catch (error) {
      console.error(error)
    }
    yield call(delay, 5 * 1000)
  }
}
```

**Comment by yelouafi** [comment]
@pke the catch-all `try/catch` blocks traps all errors including Cancellation errors

Try adding a test in the catch blocks

```javascript
catch(e) {
  if(isCancel(e)) return
  console.log(e)
}
```

**Comment by pke** [comment]
@yelouafi  I have put in `debugger` statements in the `catch` block, they are not triggered. Also all catch blocks have `console.error()` logging so I should see something in the console

**Comment by yelouafi** [comment]
@pke Ok I missed your first example. Inside race, you shouldn't yield effects just specify them

```javascript
yield race({
      watchers: /*yield*/ [
        call(refreshUser, access_token),
        call(refreshActivities, access_token),
        call(refreshPendingTransactions, access_token)
      ],
      logout: /*yield*/ take(actions.LOGOUT_SUCCESS)
    })
```

**Comment by slorber** [comment]
great catch :)

**Comment by pke** [comment]
:+1: great! Another setting for the hopefully soon coming `eslint-redux-saga` :)

**Comment by pke** [comment]
Created an `eslint` rule for that:

```es6
ruleTester.run("no-yield-in-race", rule, {
  valid: [
    {
      code: "function* test() { yield race({ posts: call(fetchApis) }) }",
      parserOptions: { ecmaVersion: 6 }
    }, 
    {
      code: "function* test() { yield race({ watchers: [call(watcher1), call(watcher2)] }) }",
      parserOptions: { ecmaVersion: 6 } 
    }    
  ],
  invalid: [
    {
      code: "function* test() { yield race({ posts: yield call(fetchApis) }) }",
      output: "function* test() { yield race({ posts: call(fetchApis) }) }",
      parserOptions: { ecmaVersion: 6 },
      errors: [{ message: "yield not allowed inside race: posts" }]
    },
    {
      code: "function* test() { yield race({ watchers: yield [call(watcher1), call(watcher2)] }) }",
      errors: [{ message: "yield not allowed inside race: watchers" }],
      output: "function* test() { yield race({ watchers: [call(watcher1), call(watcher2)] }) }",
      parserOptions: { ecmaVersion: 6 } 
    }
  ]
})
```

Does this look correct to you guys?

**Comment by yelouafi** [comment]
@pke You're getting the exception because the saga catch errors only around the `call` effect. But if the cancellation happens while the saga is blocked in `take` then the thrown Error is uncaught.

Anyway the 0.10.0 version no longer throw on Cancellation so you shouldn't get this warnings; Also cancellations are now logged used console.info on dev mode

**Comment by yelouafi** [comment]
@pke as for the eslint rule, TBH I havent created ESlint rules before. I'll try this and report back. Thanks for this

**Comment by yelouafi** [comment]
BTW the last comment IMO should be posted on #179

**Comment by yelouafi** [comment]
closing this. ESlint rules is tracked in #179
