### ISSUE TITLE
Pattern: Waiting for Stores?

### ISSUE THREAD

**Issue by 3LOK** [yelouafi/redux-saga#269]
Hi,

Couldn't find any documentation about this one, so I might be thinking of it completely wrong, but here's my situation, would love to hear some thoughts about it:

My app has a login mechanism which eventually can send different actions (FB_LOGIN_SUCCESS, GOOGLE_LOGIN_SUCCESS, ...) that are received by a reducer which stores a computed access-token.

I have a saga that needs to send a request with the access-token, so what I want to do in pseudo code in many of my different sagas is:

```
access-token = [select access token from store]
if [there isn't an access-token] then [wait for the store to have one]
[call api with access-token]
```

How can I do the [wait for store to have one]? What is the correct pattern here?

Thanks!

**Comment by chenxsan** [comment]
I would do the access-token fetching in another generator like:

```
function * fetchToken () {
  let token = [call api to fetch access-token]
  if (token) {
    // dispatch action to store the access-token
    dispatch(...)
    // then return it to whoever called it
    return token
  }
}
```
Then the pseudo code would be written:

```
access-token = [select access token from store]
if [there isn't an access-token] then yield * fetchToken
[call api with access-token]
```
Although the access-token is not `select`ed from store, i'm ok with this. But any api called would need the access-token check, so there will be a lot boilerplate. 

We could improve it with a custom selector generator function:

```
function * giveMeToken () {
  access-token = [select access token from store]
  if [there isn't an access-token] then access-token = yield * fetchToken
  return access-token
}
```
And the function to call api:

```
access-token = yield * giveMeToken
[call api with access-token]
```
Again, we will still have a lot boilerplate code since we need to select the access-token every time we call api, and of course we can make it better.

**Comment by 3LOK** [comment]
Thanks, I might have been unclear:

There's no API to fetch the access token - it is calculated by the reducer based on results from FB's SDK's callback or Google's SDK's callback (an 'onLogin' callback). Basically you can't 'pull' the access-token if it doesn't exist, the access-token is pushed to the reducer, so I still need somehow to 'wait for the reducer'.

So the situation is:

** LoginSaga
- [ Call FB's login method to show the login box. ]
- [ Wait for user to approve login ]
- [ Put FB_LOGIN_SUCCESS with access-token ]

** LoginReducer
 - [ Listen to FB_LOGIN_SUCCESS, GOOGLE_LOGIN_SUCCESS, TWITTER_LOGIN_SUCCESS, etc.. ]
 - [ When one of them arrives take the specific server access-token, convert to generic access-token ]
 - [ Store in state. ]

** My Very Cool Saga:
 - [ Get the generic access-token from the store. ]
 - [ No access-token? Wait for store to have one (***** How to do this? ****) ]
 - [ Call my-very-cool-api-that-requires-accesstoken-to-do-cool-things with the generic access token, ]

I hope that was clear enough, let me know if not.

**Comment by yelouafi** [comment]
@3LOK can't your saga just wait for the *_LOGIN_SUCCESS actions. Since sagas execute after reducers your saga should see the calculated token

**Comment by 3LOK** [comment]
@yelouafi Thanks! It could, but I was hoping there might be a cleaner solution: 

The thing about waiting for the different *_LOGIN_SUCCESS is that every time I now add another *_LOGIN_SUCCESS (lets say tomorrow I'll add Twitter login), I'll need to remember to update this file as well. I think it somewhat 'harms' the encapsulation (doesn't seem right that some of my sagas will know what are the different login types...). 

The other option would be to 'put' a generic LOGIN_SUCCESS after each specific *_LOGIN_SUCCESS, and wait for it, but perhaps the concept of waiting for a state change is a valid design pattern to consider in redux-sagas.

Thanks!

**Comment by yelouafi** [comment]
You can use `take` with a function predicate instead of a constant

```javascript
function isLoginAction(action) {
  return action.type.endsWith('LOGIN_SUCCESS')
  /**
   or to avoid relying on strings, you can set an `isLoginSuccess` 
   field on the action then return
   return action.isLoginSuccess
  **/
}

function* saga() {
  yield take(isLoginAction)
}
```

**Comment by 3LOK** [comment]
Thanks!

I don't 100% love this idea (of going by action string, as it means my other sagas need to know about the actions of the login saga). 

For the meanwhile, i simply have:

```javascript
let accessToken = yield select(state => state.login.access);
while (accessToken === null) {
    yield take();
    let accessToken = yield select(state => state.login.access);
}
```

Not pretty at all, but works.

**Comment by yelouafi** [comment]
Another way is to hold a reference to the task doing the login; and share it with the other Sagas needing to wait for a login for ex. by making it a param

```javascript
function* saga(loginTask) {
  /*
      if loginTask has already completed this will resolve immediately
      otherwise it'll wait for the loginTask to start or complete (if it's already in progress)
  */
  yield join(loginTask)
  let accessToken = yield select(state => state.login.access);
}
```

**Comment by yelouafi** [comment]
Hmm... This remind me of Wait conditions in Java: Wait until a condition on the store is met (regardless of the different possible action pathes causing the state change)

**Comment by yelouafi** [comment]
A more Saga-conventional approach is to create a Saga acting as a decoupling point: it will listen to all *_LOGIN_ACCESS actions and dispatch a `TOKEN_DISPONIBLE`
