### ISSUE TITLE
Adding support for calling function with `this` context (object/class methods)

### ISSUE THREAD

**Issue by inyono** [yelouafi/redux-saga#27]
Consider the class
```.js
export default class API {
  fetch() {
    console.log(this);
  }
}
```
With `backend = new API()`, the call `yield  call(backend.fetch)` logs `undefined`, whereas `yield backend.fetch()` logs the correct `this`.

Edit: `yield call(backend.fetch.bind(backend))` works fine, too. So feel free to close this if you don't consider this an bug.

**Comment by yelouafi** [comment]
Seems a valid issue to me. `yield call( backend.fetch.bind(backend) )` can not be tested easily, because the call `backend.fetch.bind(backend)` will return a different result each time it's called.

Adding context (this) support to the `call` effect is a bit awkward because the `call(fn, ...args)` is variadic (I dont feel also the form `call(null, fn, ...args)` for non-class functions)

I think we should provide another effect creator to handle this case like `method(API, fetch, ...args)`

**Comment by tappleby** [comment]
Would it make sense to keep it similar to `Function.prototype.call` and `Function.prototype.apply`?

`call` works as is, if you need binding use apply?

```js
call(method, arg1, arg2, argN) // Could be an alias for apply(method, null, [arg1, arg2, argN])
apply(method, context, [arg1, arg2, argN])
```

**Comment by yelouafi** [comment]
@tappleby I agree. Your solution looks better

**Comment by yelouafi** [comment]
FYI. the new v0.4.0 supports the `apply` effect.

**Comment by inyono** [comment]
Nice, thanks :+1:

**Comment by pke** [comment]
Signatur of `apply` effect seems to have changed to `apply(context, method...)`

**Comment by voodoods** [comment]
In addition: Binding the class Object itself with `yield call(MyClass.myFunction.bind(MyClass)` seems to preserve the `this` context as well, even though `apply` should be the solution of choice.

**Comment by jgehrcke** [comment]
On the topic, from https://github.com/microsoft/TypeScript/wiki/'this'-in-TypeScript:

> The biggest red flag you can keep in mind is the use of a class method without immediately invoking it. Any time you see a class method being referenced without being invoked as part of that same expression, this might be incorrect.

The same document lists the solution that @murtraja also mentioned: using an instance arrow function: https://github.com/microsoft/TypeScript/wiki/'this'-in-TypeScript#use-instance-functions

**Comment by jgehrcke** [comment]
I like what's documented today, this signature of the `call()` effect: `call([context, fnName], ...args)`

> Same as call([context, fn], ...args) but supports passing a fn as string. Useful for invoking object's methods, i.e. yield call([localStorage, 'getItem'], 'redux-saga')
