### ISSUE TITLE
Is there an upgrade path to 0.10.0 from 0.9.x?

### ISSUE THREAD

**Issue by pke** [yelouafi/redux-saga#275]
It seems the running of sagas has changed dramatically.

Where I before had:

```es6
// accountSagas.js
export default [
  authorizedFlow,
  loginFlow,
  logoutFlow,
  newSignupFlow,
  ...voucherSagas
]
```

```es6
// sagas.js
export default sagas = createSagaMiddleware( [
    ...account.sagas,
    /*...*/
 }
```

and 

```es6
import sagas from "./sagas"
const composedStore = compose(
  applyMiddleware(thunk, sagas, logger)
)(createStore)
```

Now I have to hand in a generator function but I have no clue how. Event the sample `real-world` does not help much. I managed to re-arrange my `applyMiddleware` call and add a call to `sagaMiddleware.run` after the store creation, but what should the root saga function return?
I've tried to let it return this:

```es6
function* root() {
  return yield [
    yield fork(function()* { return account.sagas })
  ]
}
```

But the `account.sagas` are not started.

Any migration guide available?

**Comment by chenxsan** [comment]
Check the release note here https://github.com/yelouafi/redux-saga/releases/tag/v0.10.0

**Comment by slorber** [comment]
`account.sagas.map(saga => sagaMiddleware.run(saga))` should do the job


Or maybe

```javascript
function* root() {
  yield account.sagas.map(saga => call(saga));
}
```

**Comment by yelouafi** [comment]
@pke i wouldn't recommend importing the middleware in the same sagas module. It's better to export a root Saga (cf @slorber answer above) from the module then run it from elsewhere (eg. main file as in the examples).

>I managed to re-arrange my applyMiddleware call and add a call to sagaMiddleware.run after the store creation, but what should the root saga function return?

`sagaMiddleware.run` returns a Task object. see API docs http://yelouafi.github.io/redux-saga/docs/api/index.html#middlewarerunsaga-args
