### ISSUE TITLE
Root saga pattern - fork vs. run?

### ISSUE THREAD

**Issue by anyong** [yelouafi/redux-saga#276]
I'm a bit confused here, what is the "correct" way to set up a root saga and a bunch of "router" sagas inside?

```js
// Using `fork`?
function* rootSaga () {
    yield [
        fork(saga1), // saga1 can also yield [ fork(actionOne), fork(actionTwo) ]
        fork(saga2),
    ];
}

// Using `middleware.run`?
function* rootSaga () {
    sagaMiddleware.run(saga1); // saga1 can also do middleware.run(actionOne), etc.
    sagaMiddleware.run(saga2);
}

function startRootSaga () {
    sagaMiddleware.run(rootSaga);
}
```

Also, is there any better way to get `store.getState` in all of those sagas other than passing it around as a parameter everywhere?

Just for clarity, I'm thinking of this as analogous to an `express` router where my action types are the routes - is this a good way to think about it?

```js
const app = express();

const router1 = express.Router();
router1.get('/get', get1Fn);

const router2 = express.Router();
router2.get('/get', get2Fn);

const rootRouter = express.Router();
rootRouter.use('/one', router1);
rootRouter.use('two', router2);

app.use(rootRouter);
```

This express router seems to be analogous to the above "saga router".

I would like to have just one call in my top level `app.js` to start the root saga, and then the rest of my sagas are broken up by area of the app, similar to the way I split the router code on the server side.

**Comment by yelouafi** [comment]
Example of config

./saga.js
```javascript
// Using `fork`?
function* rootSaga () {
    yield [
        fork(saga1), // saga1 can also yield [ fork(actionOne), fork(actionTwo) ]
        fork(saga2),
    ];
}
```

./main.js
```javascript
import { createStore, applyMiddleware } from 'redux'
import createSagaMiddleware from 'redux-saga'

import rootReducer from './reducers'
import rootSaga from './sagas'


const sagaMiddleware = createSagaMiddleware()
const store = createStore(
  reducer,
  applyMiddleware(sagaMiddleware)
)
sagaMiddleware.run(rootSaga)
```

**Comment by anyong** [comment]
Yeah that's pretty much what I'm doing, I just dont understand when I should use `fork` or `run`

**Comment by yelouafi** [comment]
`run` is normal javascipt method that can be use to create and start a task from outside the Sagas. And should be typically used in the same place where you create the store. `fork` is an *Effect* that can be only used with `yield` from inside Sagas. 

You shouldn't use `run` from inside Sagas just `yield fork`. And you can't use `fork` outside of Sagas.

**Comment by anyong** [comment]
Ok that's clear. Thanks!

**Comment by silvenon** [comment]
@anyong this issue is resolved then?

**Comment by purezen** [comment]
Hey, I was initialising sagas in my app first using 
```
const sagaMiddleware = createSagaMiddleware(rootSaga)
const store = createStore(
  reducer,
  applyMiddleware(sagaMiddleware)
)
```
and was encountering error saying `Error:
  createSagaMiddleware can only be called on Generator functions
  Argument undefined at position 0 is not function!`
while setting up tests. This was working fine in the app though. On looking further, when I did an explicit import of `store` in the test file, the test worked.
Then, I initialised the store with sagas as is mentioned here, using `sagaMiddleware.run(rootSaga)` and the test worked without explicitly importing the `store` in the test which is already being used in the sagas.

Can you tell me why this happened? Thx!
