### ISSUE TITLE
Testing error handling?

### ISSUE THREAD

**Issue by rayd** [yelouafi/redux-saga#28]
This just a question, not a real issue, but in your section on Error Handling you have the following example:
```javascript
function* checkout(getState) {

  while( yield take(types.CHECKOUT_REQUEST) ) {
    try {
      const cart = getState().cart
      yield call(api.buyProducts, cart)
      yield put(actions.checkoutSuccess(cart))
    } catch(error) {
      yield put(actions.checkoutFailure(error))
    }
  }
}
```
How would I go about testing the error case? I'd like to test what happens when the function passed in the `call` statement rejects its Promise or throws an Error.

The best thing I can think of is trying to mock the `call` function to just throw an error, but that seems messier than I'd like. Any ideas? Thanks!

**Comment by yelouafi** [comment]
>The best thing I can think of is trying to mock the call function to just throw an error

You don't have to mock, `yield call(...)` doesn't execute anything, to test the generator you provide it with dummy responses. To simulate a promise rejection, call `throw` on the iterator
 
```javascript
const cart = {}
const getState = () => cart
const iterator = checkout(getState)

assert.deepEqual(iterator.next().value, take(types.CHECKOUT_REQUEST))
assert.deepEqual(iterator.next(actions.checkoutRequest()).value, call(api.buyProducts, cart) )
// simulate a promise rejection
assert.deepEqual(iterator.throw('error').value, put(actions.checkoutFailure('error')))

**Comment by yelouafi** [comment]
sorry, didnt mean to close it

**Comment by rayd** [comment]
Ah, awesome! Thanks so much for the quick response. That makes a lot of sense.

**Comment by KamuelaFranco** [comment]
Can this go in the docs? Please?

**Comment by worc** [comment]
things have changed. `iterator.throw('error')` itself causes the error `Error: the string "error" was thrown, throw an Error :)`

**Comment by eelfonik** [comment]
@worc 
Just use `iterator.throw(new Error('error'))`

**Comment by worc** [comment]
with that `e` is still undefined in the catch block.
