### ISSUE TITLE
regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by dfcarpenter** [yelouafi/redux-saga#280]
So my application starts up fine (using Webpack dev server with hot reload) but on reload I keep getting this error. I have the import polyfill at the top of my index.js but i'm not sure from the examples, specifically the 'real-world' one, what I am supposed to include in my webpack configuration for this to work. 
Thanks

**Comment by yelouafi** [comment]
If you're using ES6 on the server you may want to import the polyfill on the server as well. also running on the server requires `node --require babel-register server.js` in packae.json https://github.com/yelouafi/redux-saga/blob/master/examples/real-world/package.json#L6

**Comment by dfcarpenter** [comment]
I found out that I had to include it in my webpack config like so 

```
entry: {
    js: ['babel-polyfill', './index.js'],
    vendor: ['react']
  },
```

**Comment by vinogradov** [comment]
For those who don't want to use babel-polyfill. Just
```javascript
import "regenerator-runtime/runtime";
```
and that's it! Because `babel-runtime` [depends](https://github.com/babel/babel/blob/7.0/packages/babel-runtime/package.json) on [regenerator-runtime](https://github.com/facebook/regenerator) already.

**Comment by protoEvangelion** [comment]
@vinogradov I stuck that in my saga file and it worked great! Thanks 🥇

**Comment by jasontenbrink** [comment]
@vinogradov thanks!  Quick note to those who come after.  It didn't work until I put it at the top of the file.

this worked:
`import 'regenerator-runtime/runtime'
import { applyMiddleware, createStore, compose, combineReducers } from "redux"
import {createLogger} from "redux-logger"
import createSagaMiddleware from 'redux-saga'
import { helloSaga } from './sagas'
import tenants from './tenantsReducer'`

this didn't:
`import { applyMiddleware, createStore, compose, combineReducers } from "redux"
import {createLogger} from "redux-logger"
import createSagaMiddleware from 'redux-saga'
import { helloSaga } from './sagas'
import tenants from './tenantsReducer'
import 'regenerator-runtime/runtime'`

**Comment by vinogradov** [comment]
thanks @jasontenbrink! It is very important point. I edited my original post according to your comment.

**Comment by pupudu** [comment]
I had the same problem and none of the solutions above worked. So then I moved the async function from the saga to a separate module and now everything works fine

**Comment by borrascador** [comment]
The following does not work for me:
`import 'regenerator-runtime/runtime'`

However, the following solution works:
`import regeneratorRuntime from 'regenerator-runtime/runtime'`

Any idea why I am getting different results from the rest of the thread?

**Comment by Andarist** [comment]
It depends on your babel config, so hard to tell without looking at it.

**Comment by yes1am** [comment]
if you use babel, try this:  
`npm install --save-dev @babel/plugin-transform-runtime`

add add in your .babelrc file
```js
"plugins": [
    "@babel/plugin-transform-runtime"
]
```

it works for me

**Comment by frankgo81** [comment]
> For those who don't want to use babel-polyfill. Put this **BEFORE ALL IMPORTS** (at the top of the file):
> 
> ```js
> import "regenerator-runtime/runtime";
> ```
> 
> and that's it! No need to add any dependencies because `babel-runtime` [depends](https://github.com/babel/babel/blob/7.0/packages/babel-runtime/package.json) on [regenerator-runtime](https://github.com/facebook/regenerator) already.

Alternatively, just import import "babel-polyfill";  at top of your entry file, such as index.js or index.jsx
