### ISSUE TITLE
Support for Observable in call

### ISSUE THREAD

**Issue by babeal** [yelouafi/redux-saga#281]
Can the effect call support observables as well.  right now i'm having to do:

  let dataFunction = () => { return businessesService.getAllWells().take(1).toPromise(); }
  const wells = yield call(dataFunction);

**Comment by yelouafi** [comment]
I'm not sure if this needs to be added to the core. you can create a little helper saga for this

**Comment by babeal** [comment]
Could you point me to an explanation on how to do that?  It looks like I would need to create my own effect?  Is this correct or is there an easier way.  I figured it would be nice to have the call abstraction understand whether I am using a promise or an observable whether its an Rx version or an ES7 version.  It seems weird that call wouldn't support an ES7 proposed interface.

**Comment by yelouafi** [comment]
```javascript
function* callObs(obs) {
   return ( yield obs.take(1).toPromise() )
}

function* saga() {
   ...
   const wells = yield call(businessesService.getAllWells());
}

**Comment by slorber** [comment]
@babeal I don't understand what you would expect redux-saga to do. What does it mean to call an observable? How can we know the behavior you want? You may want the first item of the stream, or you may want all the items of the stream once the stream ends

**Comment by babeal** [comment]
@slorber - of course the behavior of an observable can be different than a promise.  In this case for this operator I would expect that the semantics would remain the same and only the first value of the observable would be used.  This may or may not be acceptable.
