### ISSUE TITLE
Where is `getState` passed into a saga?

### ISSUE THREAD

**Issue by bricejlin** [yelouafi/redux-saga#286]
I'm having issues accessing `getState`. Here's my code

```js
function* foo(getState) {
  console.log(getState())
}

export default function* rootSaga(getState) {
  yield [
    bar(),
    foo(getState),
  ];
}
```

entry point file:
```js
const sagaMiddleware = createSagaMiddleware();

const middleware = process.env.NODE_ENV === 'production' ?
  [ thunk ] :
  [ sagaMiddleware, thunk, logger() ];

const store = createStore(rootReducer, applyMiddleware(...middleware));

sagaMiddleware.run(rootSaga);
```
When I run this in the browser, I get this is the error:
```
utils.js?1f12:176 uncaught at rootSaga 
 at rootSaga 
 getState is not a function
```

Any ideas what I'm doing wrong?

**Comment by fhelwanger** [comment]
It was changed on 0.10. Check: https://github.com/yelouafi/redux-saga/releases/tag/v0.10.0

> Removed deprecated `getState` argument passed to Sagas. You can use the `select` Effect to get the store state

To see how to use `select`: http://yelouafi.github.io/redux-saga/docs/api/index.html#selectselector-args

**Comment by bricejlin** [comment]
@fhelwanger ah I see. I was following the docs, which I guess is outdated. Thanks for the pointer!
