### ISSUE TITLE
createSagaMiddleware is not a function

### ISSUE THREAD

**Issue by mahmoudHosny** [yelouafi/redux-saga#288]
var createSagaMiddleware = require("redux-saga").createSagaMiddleware;
return undefined
So when I can't call  
var sagaMiddleware = createSagaMiddleware();

**Comment by yelouafi** [comment]
I think it's var createSagaMiddleware = require("redux-saga").default

**Comment by mahmoudHosny** [comment]
Thank it's Works
But it's not mentioned at docs
