### ISSUE TITLE
Usage of sagaMiddleware.run with redial.

### ISSUE THREAD

**Issue by cusxio** [yelouafi/redux-saga#293]
PS: I am trying to use [redial](https://github.com/markdalgleish/redial) to trigger `redux-saga` on the server side for initial state. Is it possible?

I have some questions regarding the following usage of sagaMiddleware.run, is it correct? 

I realised that redux-saga did run all the actions via `put` and hit the `fakeData`, but my promises are somehow resolved incorrectly. (i.e. I am getting 404 on my server, my server is not waiting for the promises, I think). 

I am not sure if this problem is related to redux-saga so I thought I try my luck here.

**Saga.js**
```js
import { call, put } from 'redux-saga/effects';
import axios from 'axios';
import { sagaMiddleware } from '../redux/store';

function fakeData() {
    return axios.get('http://localhost:9000/api/posts');
}

function *fetch() {
    try {
        yield put({ type: actionTypes.FETCH_START });
        const response = yield call(fakeData);
        yield put({ type: actionTypes.FETCH_SUCCESS, data: response.data });
        yield put({ type: actionTypes.FETCH_PENDING });
    } catch (e) {
        yield put({ type: actionTypes.FETCH_FAIL });
    }
}

export default function saga() {
    return new Promise((resolve, reject) => {
        const sagaTask = sagaMiddleware.run(fetch); // What is actually happening on this line?
        sagaTask.done.then(() => {
            resolve('Saga Done');
        }).catch(() => {
            reject();
        });
    });
}
```

**Component.js**
```js
import { provideHooks } from 'redial';
import { connect } from 'react-redux';
import saga from './Saga';

const redial = {
    fetch: function () {
        return saga().then(data => console.log(data)); // logs 'Saga Done'
    },
};

class PostList extends Component {
    render() {
        const { posts } = this.props;
        return (
            <div>
                {posts.map(post => <ListItem key={post.id} post={post} />)}
            </div>
        );
    }
}

export default provideHooks(redial)(connect(mapStateToProps)(PostList));

```

**Comment by yelouafi** [comment]
Sorry I dont know much about redial but the saga code seems corect. Although it can be simplified to

```javascript
sagaMiddleware.run(fetch).done.then(
  () => console.log(...),
  ...
)
```

**Comment by cusxio** [comment]
@yelouafi Yup ! I got it working now. It has nothing to do with redux-saga, but my server. 

I have a question, is this a valid usage of redux-saga? 

To dispatch actions on the fly, rather than waiting for a dispatch action using `take` or `takeEvery` that the examples seems to promote.

**Comment by hoanguyen311** [comment]
@yelouafi

**Comment by Andarist** [comment]
U probably need to dispatch special END action (exported by redux-saga) if u want to make SSR
