### ISSUE TITLE
Middleware Issue

### ISSUE THREAD

**Issue by aaesis** [yelouafi/redux-saga#294]
Hi I just want to ask about middleware I got an error:

Error: utils.js:42 Uncaught Error: sagaMiddleware.run(saga, ...args): saga argument must be a Generator function!

I only followed the documentation middleware which really give me error.

inside store.js

`export default function configureStore(initialState) {
  const sagaMiddleware = createSagaMiddleware()

  const store = createStore(
    rootReducer,
    initialState,
    compose(
      applyMiddleware(
        sagaMiddleware,
        createLogger()
      ),
    )
  )

  store.runSaga = sagaMiddleware.run
  store.close = () => store.dispatch(END)
  return store
}`

and in my main.js

I already imported the file store.js

`const store = configureStore()
store.runSaga(rootSaga)`

**Comment by yelouafi** [comment]
the error is raised because `rootSaga` is not (apparently) a Generator function.

**Comment by aaesis** [comment]
thanks problem is solve.
