### ISSUE TITLE
How to use redux-saga with event emmiters?

### ISSUE THREAD

**Issue by sanfilippopablo** [yelouafi/redux-saga#295]
I had an API call made with a promise, called with `call`, and it was great. But I wanted to show a progress bar of the download (the API response is very large), and fetch doesn't support progress update, so I rewrote it using an `XMLHttpRequest`, but I don't know how to connect it to a saga. This would be the code:
````es6
function * download () {
  const xhr = new XMLHttpRequest()
  xhr.open('GET', `/verylargedownload`, true)

  xhr.onload = (e) => {
    yield put({type: DOWNLOAD_SUCEEDED, data: xhr.response})
  }

  xhr.onprogress = (e) =>  {
    yield put({type: UPDATE_DOWNLOAD_PROGRESS, progressEvent: e})
  }

  xhr.onerror = (e) => {
    yield put({type: DOWNLOAD_FAILED, error: e)
  }

  xhr.send()
}
````

Of course this code is wrong, but it roughly explains why I'm trying to do.

I also know that it would be trivial to implement with redux-thunk, but that's not the point.

**Comment by fhelwanger** [comment]
Take a look at http://yelouafi.github.io/redux-saga/docs/advanced/Channels.html, specially `eventChannel`.

**Comment by sanfilippopablo** [comment]
Oh, exactly what I was looking for. Thanks.
