### ISSUE TITLE
takeEvery not taking every action?

### ISSUE THREAD

**Issue by solcik** [yelouafi/redux-saga#296]
Hello,

I ran into a problem with takeEvery helper. I am trying to catch all API actions with a "watchApiCalls" saga and then process them in a "apiCall" saga. I only wanted to try, how it will go with "WillMount" lifecycle method as stated below. When I refresh the page, where this component is, I got first log of actions - only 1 is "taken" and processed. The funny thing is, when I go to the page via transition / link, as can be seen in second screenshot, everything goes ok.

Do you have any clue why is that or how to fix this?

Thank you in advance.

```
export function* apiCall(action) {
  const { api, payload, types } = action;
  const token = yield select(getToken);

  return yield call(fetchApi, api, types, payload, token);
}


export default function* watchApiCalls() {
  yield* takeEvery((action) => action.api, apiCall);
}
```

```
componentWillMount() {
    if (!this.props.machines.isLoading && !this.props.machines.isLoaded) {
      this.props.fetchAllMachines();
    }
    if (!this.props.cartons.isLoading && !this.props.cartons.isLoaded) {
      this.props.fetchAllCartons();
    }
    if (!this.props.papers.isLoading && !this.props.papers.isLoaded) {
      this.props.fetchAllPapers();
    }
  }
```

<img width="505" alt="screenshot 2016-05-03 03 01 58" src="https://cloud.githubusercontent.com/assets/1543737/14972373/81f3280c-10db-11e6-9297-2ab258874be5.png">
<img width="502" alt="screenshot 2016-05-03 03 02 26" src="https://cloud.githubusercontent.com/assets/1543737/14972374/81f5b356-10db-11e6-8c8a-406a629cc472.png">

**Comment by yelouafi** [comment]
Are you logging the actions from reducers or some middleware like redux-loggger?

**Comment by solcik** [comment]
Redux-devtools + Redux-devtools-inspector

**Comment by yelouafi** [comment]
if it doesn't reach the devtools it's likely because it isn't dispatched at all. Unless some middleware intercept it.

**Comment by solcik** [comment]
Sorry, I forgot to mention, that actions with suffix "#BASE" have "api" property, so as You can see, these are dispatched from the component correctly in botch cases, but in the first one "watchApiCalls" saga will not start "apiCall" saga for last 2 - will start only for the first one, which results into #START and #SUCCESS actions.

**Comment by yelouafi** [comment]
sorry for the delay. Can you post a runnable Gist or a test case? it's hard to tell from the snippet above

**Comment by solcik** [comment]
No problem,

the thing is, that I made this for showcase: http://www.webpackbin.com/VyiajQE--

And it is running smoothly, when I tried to reproduce it in my codebase again (after clean npm install) it is running also ok. So I do not have a clue, where was a problem and I am closing this, since now it is ok. If I come across it again, I will report it here .)
