### ISSUE TITLE
multiple takes for the same action

### ISSUE THREAD

**Issue by xanderlu** [yelouafi/redux-saga#297]
The following code works properly. But I'm wondering if it is a valid pattern, or if there is a better way to go about doing this.

Basically, I have a saga that will always take `'FIRST_ACTION'` when it is dispatched. I have another saga that checks to see if either `'FIRST_ACTION'` or `'SECOND_ACTION'` is dispatched and then only do something once. If `'FIRST_ACTION'` is dispatched before `'SECOND_ACTION`' both of the sagas end up taking the action.

Does it make sense to have multiple sagas that `take` the same action? Or should I make sure each saga's `take` calls are unique? It seems like all the documentation and examples I've come across so far have each saga only `take` unique actions.

``` javascript
// saga1.js
function* onlyOne() {
  while (true) {
    yield take('FIRST_ACTION');
    // stuff...
}
```
```javascript
// saga2.js
function* twoActions() {
  yield take(['FIRST_ACTION', 'SECOND_ACTION']);
  // do something else...
}
```

**Comment by yelouafi** [comment]
I don't see a particular issue with it. It depends on the *work* to be done after taking the action. It could be even good to have multiple watcher for the same actions if they need to perform different tasks

**Comment by xanderlu** [comment]
Great! Thanks for clarifying!
