### ISSUE TITLE
Components exporting sagas

### ISSUE THREAD

**Issue by ashaffer** [yelouafi/redux-saga#30]
I think it'd be neat if you could use sagas for things like animation, or other things that might be unique to particular components. Is there a suggested pattern for this? E.g. exporting a `sagas` array or something.

**Comment by yelouafi** [comment]
the latest version includes a [`runSaga`](https://github.com/yelouafi/redux-saga#dynamically-starting-sagas-with-runsaga) function to start a saga outside of Redux. You can also connects the Saga to a custom input/output.

One idea is to use this function to connect a Saga to a React component, I mean for things that uses uniquely the local component state. For example provide a ReactComponentIO which routes component events as input to Sagas (to resolve `take` effects) and connects the output of the Saga to component's setState (to resolve `put` effects) 

```javascript
function* myComponentSaga(comp) {
  while(true) {
     yield take('CLICK')
     // yield some stuff
     yield put({clicked: true}) // same as setState({clicked: true})
  }
}

class MyComponent extends React.Component {

  componentDidMount() {
     this.sagaIO = ReactComponentIO(this)
     runSaga(mySaga(this), this.sagaIO) )
  }

  render() {
     return (
         ...
         <button onClick={this.sagaIO.fire({type: 'CLICK'})}
     )
  }
}
```

This is all quick and dirty, but can be refined further

**Comment by yelouafi** [comment]
I'll close this for the moment. Please feel free to add any comment. I can reopen it if necessary.
