### ISSUE TITLE
Missing code in docs

### ISSUE THREAD

**Issue by nick13jaremek** [yelouafi/redux-saga#300]
Hi there,

Amazing stuff in here, and also the docs are wonderful!

I was reading the *Advanced - Non blocking calls* docs section, and noticed that when it is said that *we need to move the token storage operation into the authorize task*, the `authorize` function code is missing a line for the actual token storage operation.

```js
function* authorize(user, password) {
  try {
    const token = yield call(Api.authorize, user, password)
    yield put({type: 'LOGIN_SUCCESS', token})
    yield call(Api.storeItem, {token}) // This is the missing line
  } catch(error) {
    yield put({type: 'LOGIN_ERROR', error})
  }
}
```

Just wondering if the line is actually missing or whether I am missing something here.

Thanks in advance!

**Comment by yelouafi** [comment]
You're right. It's missed
