### ISSUE TITLE
Argument is not a valid channel

### ISSUE THREAD

**Issue by Sinistralis** [yelouafi/redux-saga#301]
So I recently got the chance to upgrade our application to the 0.10.x version and finished making the changes listed in the release notes. I will attach my store/rootSaga code at the bottom for reference.

I am running into an issue now where all my sagas except the first one are throwing the error "Argument [object Object] is not a valid channel" when performing a put effect. I know you implemented channels in 0.10.x but no documentation of a default channel seems to exist, so I'm not quite sure what to do about this error.

Could you advise? No one else has seemed to encounter this so I assume I am just misunderstanding something.

Make sure to read the file names
https://gist.github.com/Sinistralis/9a02af9a9cd6614e43edb1c788ba10fe

I know that's a lot of code vomit but I'm not quite sure how else to describe this issue, and you might know how to fix it without needing to see code. If you need more information or a better description, let me know and I will try to accommodate.

**Comment by yelouafi** [comment]
I noticed a put with 2 args `put(setSessionOptions(responses[1].body), false)`. The signature of put is either `put(action)` or `put(channel, msg)`. When you call it with 2 args it expects the 1st to be a channel

**Comment by Sinistralis** [comment]
Well this is embarrassing. Looks like when I converted over I misplaced a paren. Good catch, I was completely blind to that.

Thanks for the help, apologies for wasting time with something unrelated to your work.

**Comment by eric-burel** [comment]
It can happen when you confuse API from `call` and `put` => `put(myAction, arg1, arg2)` should instead be `put(myAction(arg1,arg2))` (put the action and not the action creator).
