### ISSUE TITLE
Ability to put directly to the store (putRedux / putStore)

### ISSUE THREAD

**Issue by tgriesser** [yelouafi/redux-saga#302]
Would it make sense to add an effect similar to `put`, but which skips the redux-saga middleware and goes straight to the reducer? I currently have a `putRedux` effect which handles this, but the code to implement it is a bit ugly and far reaching - I wanted to see if there were any tips on how this could be easily implemented (with channels or otherwise), or if not if this would be a good addition to the core.

An example use case would be if you're receiving an action sent via a socket channel, and you'd want to put this external action to the redux store, but might not want to run the normal saga effect as would be called if the action were generated locally. 

Another would be if you had an xhr request to create a new resource, and the response provides a bit more info about this object and you want to re-use the same action name, sending the value/action directly to the reducer.

**Comment by yelouafi** [comment]
Actually the puts are executed simply calling dispatch. The action gets back to the saga middleware via the normal middleware pipeline which  then emits the action to all sagas

So if I understand you want the putted action to be ignored by the saga middleware and not emitted to sagas?

**Comment by tgriesser** [comment]
Yep, that's exactly what I'm looking for.

**Comment by yelouafi** [comment]
Yeah that would be possible by setting some special property (e.g. SKIP_SAGAS) on the action which the middleware can check. But not sure if the Api should be to expose a new Effect or simply expose the special property. Mainly because the first solution require mutating the dispatched action by the middleware

**Comment by tgriesser** [comment]
I'm going to close this, since the solution I'm after makes more sense if it's more generalized (skipping all middleware and not limited to just the sagas).
