### ISSUE TITLE
How to yield inside a forEach

### ISSUE THREAD

**Issue by jshthornton** [yelouafi/redux-saga#306]
Say for example we have a forEach loop which needs to yield.

```
function* mySaga() {
  [1,2,3].forEach(function* (x) {
   yield call(foo, bar); 
  });
}
```

What syntax would you use in mySaga to denote it to the middleware?

**Comment by yelouafi** [comment]
Use `map` to yield a parallel effect. If you want to yield effect in sequence (wait for 1st effect to terminate before yielding the 2nd) use a normal for loop

```javascript
function* mySaga() {
  yield [1,2,3].map(x => call(foo, bar));
}
```

**Comment by MoeSattler** [comment]
@yelouafi is it possible to handle errors of each call individually when doing it this way?

**Comment by Undistraction** [comment]
@yelouafi Was wondering the same thing myself. I need to repeat the same set of actions multiple times with error handling for each action. The equivalent of the following (which won't work because of the yield within the forEach loop:

```
function* example {
  x.forEach((y) => {
    const task = yield fork(a, y);
    const action = take([SUCCESS, FAILURE]);
    if(action === FAILURE) {
      cancel(task)
    }
  });
}
```

**Comment by Andarist** [comment]
just do the simplest thing
```javascript
function* safeSomeSaga(item) {
	const task = yield fork(someSaga, item);
	
	const { error } = yield race({
		success: take(SUCCESS),
		error: take(FAILURE),
	})
	
	if(error) {
		yield cancel(task)
	}	
}

function* example {
	yield items.map(item => call(safeSomeSaga, item))
}
```

ive corrected your example a little bit
1. you need to use `fork` instead of `call` to achieve a non-blocking effect which will return a task descriptor
2. and ive used a race instead of a take with array pattern, it feels more natural for me and gives more meaning for that part of the code

**Comment by Undistraction** [comment]
@Andarist Thanks for replying. I oversimplified my example. I'm actually looking for a way to loop over items, but treat each one as part of a sequence rather than have all running concurrently as in your answer above. A dynamic way to do the equivalent of the following (all that changes between the duplicated elements is the item):

```
function* exampleSaga(items) {
       const task = yield fork(someSaga, items[0]);
	
	const { error } = yield race({
		success: take(SUCCESS),
		error: take(FAILURE),
	})
	
	if(error) {
		yield cancel(task)
	}

        const task = yield fork(someSaga, items[1]);
	
	const { error } = yield race({
		success: take(SUCCESS),
		error: take(FAILURE),
	});
	
	if(error) {
		yield cancel(task)
	}

       const task = yield fork(someSaga, items[2]);
	
	const { error } = yield race({
		success: take(SUCCESS),
		error: take(FAILURE),
	})
	
	if(error) {
		yield cancel(task)
	}
}
```

**Comment by Andarist** [comment]
or better without such duplication
```javascript
function* example {
	for (let item of items) {
		const task = yield fork(someSaga, item);
	
		const { error } = yield race({
			success: take(SUCCESS),
			error: take(FAILURE),
		})
		
		if(error) {
			yield cancel(task)
			break
		}			
	}
}
```
ive assumed here that 1 error breaks the loop - so all remaining, not started yet tasks are discarded, if this is not your requirement, just delete the line

**Comment by Undistraction** [comment]
Of course! The trusty for-of loop. Thanks again. This was really helpful.

**Comment by idangozlan** [comment]
Improving @yelouafi answer:

```
function* mySaga() {
  yield all([...[1,2,3].map(x => call(foo, bar))]);
}
```

all is the new way while yielding an array is deprecated.

**Comment by realtebo** [comment]
@Andarist : your follwing snippet saved my night of work

```
function* example {
	yield items.map(item => call(safeSomeSaga, item))
}
```

**Comment by abelta** [comment]
How am I the only one getting an error with this?
```
uncaught at check call: argument [object Object] is not a function
```
This is what my code looks like.
```javascript
function * removeCreated() {
  const points = yield select(state => state.pointsCreated);
  try {
    yield all(points.map(point => call(rsf.firestore.deleteDocument, `points/${point}`)));
    yield call(removeCreatedSucceeded());
  } catch (error) {
    yield put(removeCreatedFailed(error.message));
  }
}
```

**Comment by GaelS** [comment]
I guess your issue is here : `yield call(removeCreatedSucceeded());`
`call` expects a function as first argument followed by the arguments used to execute the function with (just like it's done here: `call(rsf.firestore.deleteDocument, `points/${point}`)))`)

I guess `yield call(removeCreatedSucceeded);` should fix your issue.

**Comment by abelta** [comment]
@GaelS My mistake. That a call to an action generator so correct command would be ```yield put(removeCreateSucceeded())```. Thank you very much.

**Comment by oTranXuanDiep** [comment]
@yelouafi  I tried to use map to yield a parallel effect, but I received the following error. can u help me
// my saga
function* uploadMultipleFile(){
yield all(
      mediaFiles.map((file, index) =>
        call(CommonService.uploadFile, '/url', file),
      ),
    );
}

// Error from effect saga
```(property) uploadFile: (s3Url?: string | undefined, file?: File | undefined) => Promise<AxiosResponse<any>> | undefined
No overload matches this call.
  The last overload gave the following error.
    Argument of type '(s3Url?: string | undefined, file?: File | undefined) => Promise<AxiosResponse<any>> | undefined' is not assignable to parameter of type '{ context: unknown; fn: (this: unknown, ...args: any[]) => any; }'.```
      Type '(s3Url?: string | undefined, file?: File | undefined) => Promise<AxiosResponse<any>> | undefined' is missing the following properties from type '{ context: unknown; fn: (this: unknown, ...args: any[]) => any; }': context, fnts(2769)
effects.d.ts(499, 17): The last overload is declared here.
