### ISSUE TITLE
uncaught at root at root take(patternOrChannel): undefined argument on React Native

### ISSUE THREAD

**Issue by sibeliusseraphini** [yelouafi/redux-saga#311]
I'm receiving this error using redux-saga 0.10.2 on React Native

```js
uncaught at root 
 at root 
 take(patternOrChannel): undefined argument

reactConsoleError	@	ExceptionsManager.js:76
console.error	@	YellowBox.js:48
log	@	utils.js:176
end	@	proc.js:272
task.cont	@	proc.js:102
next	@	proc.js:259
currCb	@	proc.js:308
runForkEffect	@	proc.js:497
runEffect	@	proc.js:352
next	@	proc.js:248
currCb	@	proc.js:308
runForkEffect	@	proc.js:499
runEffect	@	proc.js:352
next	@	proc.js:248
proc	@	proc.js:209
runSaga	@	middleware.js:39
sagaMiddleware.run	@	middleware.js:58
configureStore	@	configureStore.js:49
```

**Comment by yelouafi** [comment]
It means that a `take(...)` call inside `root` saga was provided with an undefined argument (e.g. because a misspelled constant)

**Comment by sibeliusseraphini** [comment]
@yelouafi thanks, you are right, there was a typo in my code,

**Comment by liesislukas** [comment]
Just for other googlers, I've just had the same error on React, not native. And it was actually because of undefined.

Would love to see such explanation in error message itself for the next release. Thanks for your great job 👍

**Comment by Andarist** [comment]
@liesislukas
Isnt that info included in the error msg? It states that argument is undefined

**Comment by ChadEubanks** [comment]
We are getting this issue as well.  Anyone know anything else than the above?

**Comment by Andarist** [comment]
@ChadEubanks its probably issue with ur code, maybe u import some action type which doesnt exist (thus being undefined)? It should be easy to debug, just setup a breakpoint in `take` function

**Comment by rpedroni** [comment]
Such a simple bug but took me about an hour to find out the cause.
Since I create constants for all actions, I was passing in an `undefined` without knowing it.
Be wary 👍

**Comment by drewandrew** [comment]
@Andarist would it be possible to include the function/saga that this error is being thrown from within the error message? My bundler (webpack) is setup in such a way that makes these errors particularly difficult to track down because the errors

**Comment by Andarist** [comment]
@drewandrew new release of redux-saga@1-beta is coming and it will have much nicer error messages (and even nicer ones with a babel plugin)
