### ISSUE TITLE
actionChannel taking an array with a race call - not working

### ISSUE THREAD

**Issue by bradennapier** [yelouafi/redux-saga#312]
Hey Guys,
  Ok so just updated to 0.10.2 from 0.6 so new to all these amazing new commands you've provided.  I have setup a class system for my Sagas and one of the problems I have had was with parallel effects (sometimes actions that were taken second were finishing first).  Well I came here and sure enough you've built actionChannels to help with this issue - thanks!

  I am sure I am just doing something completely incorrect here... but I essentially am just trying to adapt what I already had using yield race to work with the actionChannels.  Now I haven't looked at source deeply yet but I am not sure why this wouldn't work.  Documentation states actionChannel will work synonymously as the take command.  So I basically just changed it so actionChannel takes "monitorTypes" and then takes the monitorChannel (instead of directly taking monitorTypes which works flawlessly minus the race conditions due to no buffering)

```
     const monitorChannel = yield actionChannel(monitorTypes)
      while(true) {
            const { cancelData, monitorData } = yield race({
              cancelData:   take(cancelTypes),
              monitorData:  take(monitorChannel)
            })
            ... continued logic here
       }
```

In the above example it will never resolve the race call.  If I use it as I had it previous, it does work as expected:

```
       while(!true) {
            const { cancelData, monitorData } = yield race({
              cancelData:   take(cancelTypes),
              monitorData:  take(monitorTypes)
            })
       }
```

cancelTypes and monitorTypes are arrays of actions.

**Comment by yelouafi** [comment]
I don't recommend using actionChannel inside race calls as it buffers all incoming actions so it may not work consistently with other effects: If you start a race and there is already an action in the channel's internal buffer the race will be resolved with it
