### ISSUE TITLE
can I use redux-saga in Internet Explorer 8 ?

### ISSUE THREAD

**Issue by codering** [yelouafi/redux-saga#313]
I mean 

```js
export { take, takem, put, race, call, apply, cps, fork, spawn, join, cancel, select, actionChannel, cancelled } from './internal/io'
```

convert  by babel , but  ``` Object.defineProperty ```  not work in IE8

```js
'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _io = require('./internal/io');

Object.defineProperty(exports, 'take', {
  enumerable: true,
  get: function get() {
    return _io.take;
  }
});
Object.defineProperty(exports, 'takem', {
  enumerable: true,
  get: function get() {
    return _io.takem;
  }
});

...

```

**Comment by sompylasar** [comment]
This is not specific to `redux-saga`, it's a Babel question actually. Any codebase with ES6 `export` statements that is transpiled with Babel will contain the `Object.defineProperty(...)` call.

https://phabricator.babeljs.io/T2322
https://phabricator.babeljs.io/T7322

**Comment by codering** [comment]
I see.  but redux-saga use the ```  getter ```  that may break in IE8 ? 

![image](https://cloud.githubusercontent.com/assets/2271825/15105274/e945674c-15f2-11e6-8fde-ab7a71e9f259.png)

<hr>
![image](https://cloud.githubusercontent.com/assets/2271825/15105291/089a48d8-15f3-11e6-844d-7fc39ad5cd21.png)

**Comment by yelouafi** [comment]
@codering didn't have in mind to support IE8. This would lead to unnecessary complications in the code

**Comment by codering** [comment]
OK, understand.
