### ISSUE TITLE
Inconsistent line-endings in the source code (at least in the npm-installed files)

### ISSUE THREAD

**Issue by sompylasar** [yelouafi/redux-saga#315]
Here's the example, note the `<CR>` on some lines:
<img width="763" src="https://cloud.githubusercontent.com/assets/498274/15101102/1eec464e-1590-11e6-8728-06ebc2070a6b.png">

**Comment by yelouafi** [comment]
This is not in the source files but the babel compiled files (inside lib folder). all `CR+LF` endings (yeap! I work in Windows locally) are converted to `LF`. Except in multiline comments where you still find `CR+LF`. I don't think this is an issue as long as it's in the compiled files and only inside comments. In the source You'll still find all lines ends with just `LF` (CR+LF are automtically converted to LF in git commits)

**Comment by sompylasar** [comment]
You can use `.editorconfig` and LF line-endings on Windows, too. This became a de-facto standard these days... I know this won't influence the functionality, so you may close as won't fix if you like.

**Comment by yelouafi** [comment]
TBH didn't work before with .editorconfig. I'll take a look, thanks.
