### ISSUE TITLE
Question: reducers vs sagas

### ISSUE THREAD

**Issue by 3LOK** [yelouafi/redux-saga#332]
Hi,

Lets say I have a concept in my system called Blah. Blah has a state with {thingyThing}. I have an action called refresh-thingy-thing which calculates something based on the current time and changes the state of thingyThing. (an example I right now invented. my question is more general than this specific example).

Question is where to place the refresh-thingy-thing code, in the reducer or the saga? Commonly the rule is "If it's async [side-effect], you should put it in a saga, and if it's sync you should put it in the reducer". I find this rule very weird because:

(1) This means that if someone wants to find where the implementation of refresh-thingy-thing handler, they need to know if the implementation is based on async code or sync code (which seems absurd in some sense).

(2) This means that if tomorrow I decide that refresh-thingy-thing should actually be calculated by a remote service (for performance blah blah), I need to move my code to a saga, changed surrounding code, and change my tests.

So what I'm asking: Why not always put all logic in sagas (sync or async), and have the reducer just handle a 'update-thingy-thing-state' which takes the output of the calculation and puts it in the state.

Why yes?

(1) It means all my logic are always in the same place - the sagas. XXXX related logics are always in the XXXX saga, and not split between XXXX saga and XXXX reducer.

(2) If I change my implementation to be asyc (for whatever reason), I don't need to change my tests (which will always be (1) send action to saga, (2) wait for update-thingy-thing-state (3) change update-thingy-thing-state has the correct value, irregardless to the sync or async implementation.

Why no? "Because sync actions should be in reducers, and async actions in sagas"... but why?

What do you think?

**Comment by flipjs** [comment]
Have a look at this blog/article:

[Using React (-Native) with Redux and Redux-Saga. A new proposal?](https://medium.com/@marcelschulze/using-react-native-with-redux-and-redux-saga-a-new-proposal-ba71f151546f#.je8blz8y2)

I really like the idea. I just started a new project and will be implementing this. Just like you said, sync or async, it will be handled by Saga. I'll split my actions into two and probably call it **signals** and **messages**. All signals, which are invoked from UI or lifecycle methods, will be captured by Saga and processed there. Saga will produce the messages, which then go to the reducers.

**Comment by jbrodriguez** [comment]
I'm currently doing this right now.

My actionCreators and reducers have shrunk to "mostly" one-liners.

I think the most important take away is that business logic (and orchestration) live in only one place in my code: the sagas.

**Comment by silvenon** [comment]
I'm doing something similar, but in that approach I don't like that I'm using synonyms to differentiate user actions from reducer actions. E. g. the UI triggers the `NEW_ITEM`, which triggers the `CREATE_ITEM` in the sagas (`REQUEST` and `SUCCESS`/`FAILURE`). I wish there was a pattern to avoid this awkwardness.

**Comment by flipjs** [comment]
What I do is, I add suffixes, like for example:

For (async) API request, my ui action is FETCH_USER
Then in reducer, I have:
FETCH_USER_REQUESTED
FETCH_USER_RESOLVED
FETCH_USER_REJECTED

For UI state, like for example showing notification, my action would be: SHOW_NOTIFICATION.
In reducer, it would be SHOW_NOTIFICATION_CALLED

I reserved _REQUESTED, _RESOLVED, and _REJECTED for api requests.

**Comment by silvenon** [comment]
Do you have action creators for that? How do you call them? The problem I had is that I can't have both `fetchUser()` and `fetchUser.request()`. And using `{ type: actions.FETCH_USER_REQUESTED }` is more redundant and less flexible if I decide to change underlying action style.

**Comment by flipjs** [comment]
You only need `fetchUser()` as your action which is called somewhere in your component. That will be captured and processed by Saga. Saga will emit FETCH_USER_REQUESTED (this could be optional like for example if you want to load spinner). Once you received the data or failed, you either emit RESOLVED or REJECTED.

Here have a look at this working example I created for you.

https://gist.github.com/flipjs/b8bf9ba0197e0ea65518d0dcfddd5f51

You dont even need to use suffixes. You can just add the status in your payload. Have a look at redux docs where it shows 2 examples on how you might create your async action creators.

http://redux.js.org/docs/advanced/AsyncActions.html

**Comment by jshthornton** [comment]
I really like the signals and messages approach. It is something that I am already doing in my applications, but everything is still labelled under actions. The clear separation makes it more obvious to the developers which actions should be listened to, and which ones should alter the state.

I think this could play well nicely in with other modules like `redux-ui`, so that you would have a signal which says 'hey, the user clicked the close button' which then produces a couple of messages such as 'well close the window, oh and whilst you are at it, send an analytics update message'.

**Comment by tugorez** [comment]
Hi guys, it is a really nice discussion here. 
Do you have any project which implements this pattern ? 
Have you seen any cons (ex performance issues, duplicated code etc... ) ?
Thank you very much for your time.

**Comment by phdog** [comment]
I've also came close to this signals-messagaes separation, though still labeling both as actions,  but keeping in separate files

**Comment by NickFranceschina** [comment]
pure happiness is when I'm struggling with a question, have a gut instinct as to what should be done but have no one to confirm my feelings, and then stumble upon the _exact_ question being answered in the way my instincts were telling me 😄  thank you so much!
