### ISSUE TITLE
call Apis in a for loop ?

### ISSUE THREAD

**Issue by dixitc** [yelouafi/redux-saga#333]
How do you chain Api calls in say a for loop ? eg: I have a files[] array , I want to sequentially do one file upload at a time . So the second file begins to upload after file 1 has finished uploading .
I tried this but it's not synchronous .
yield files.map(file => call(uploadImageApi , file))

**Comment by darrhiggs** [comment]
`files.map(file => yield call(uploadImageApi , file))` should work if `uploadImageApi` is either a generator function or returns a promise.

**Comment by dixitc** [comment]
Yup , should've seen that one . Thank you .

**Comment by davej** [comment]
I'm confused by this:
```js
files.map(file => yield call(uploadImageApi , file))
```

AFAIK you can't yield from inside a callback?

**Comment by dixitc** [comment]
Yea I ended up using yield files.map(file => call uploadImageApi)

**Comment by davej** [comment]
@dixitc That doesn't even look like valid JS.

I ended up needing to use a for loop instead:

```js
for (const i in files) {
  if (files.hasOwnProperty(i)) {
    yield call(uploadImageApi, files[i]);
  }
}
```

**Comment by slorber** [comment]
@davej 


# Parallel upload:

```javascript
yield files.map(file => call(uploadImageApi , file));
```

# Sequential upload:

```javascript
for (const i in files) {
  if (files.hasOwnProperty(i)) {
    yield call(uploadImageApi, files[i]);
  }
}
```

# Conclusion: both options work fine, but it depends on if you want the files to get uploaded in paralllel or in sequence, according to your own usecase.

**Comment by davej** [comment]
@slorber Yup, thanks for that, that's the conclusion I came to also. Might be best to use `fork` in the parallel upload example because `call` confuses the semantics.

**Comment by davej** [comment]
Actually I'm probably wrong, I'm guessing that the parallel upload example waits for all the uploads to complete before moving to the next operation.

**Comment by slorber** [comment]
@davej it depends on if you intend to use the result returned by the upload API.

If you use sequential upload you need to put the forked tasks in an array and join them afterwards to be able to get all the results. If you use sequential version above the yield directly returns an array of all the collected upload results (note that if any of the upload fails, it will throw)
