### ISSUE TITLE
Race condition in 0.10.x

### ISSUE THREAD

**Issue by davidjbradshaw** [yelouafi/redux-saga#336]
I've just upgraded to 0.10.4 and also tried this in 0.10.0. 

I'm now finding that `take` has become a little deaf during page load.

I have the following Saga that work fine in 0.9.5, that I've added some logging to.

```js
export function* loadSearchResultsSaga(action) {
  console.log('Put SEARCH_RESULTS_REQUESTED');

  yield put(searchResultsActions.loadSearchResults(action));

  console.log('Take SEARCH_RESULTS_SUCCESS');

  yield take([
    searchResultsTypes.SEARCH_RESULTS_SUCCESS,
    searchResultsTypes.SEARCH_RESULTS_FAILURE,
  ]);

  console.log('Put LOADING FINNISH');

  yield put(appStateActions.loadingFinish());
}
```

However in 0.10.x it gets stuck at the `take`.

To dig into this a bit further I've added the following Saga to log out all the redux actions.

```js
function* log() {
    yield* takeEvery('*', function* (action) {
      console.log('Action:', action.type);
    });
  }
```

This leads to the following output in the console.

```
searchResultsSagas.js:118 Action: SET_SEARCH_RESULTS_TRACKING_FLAG
searchResultsSagas.js:28  Put SEARCH_RESULTS_REQUESTED
searchResultsSagas.js:118 Action: SEARCH_RESULTS_REQUEST
searchResultsSagas.js:118 Action: LOCATION_UPDATED
searchResultsSagas.js:118 Action: HASH_UPDATED
client.js:55              [HMR] connected
searchResultsSagas.js:118 Action: SEARCH_RESULTS_SUCCESS
searchResultsSagas.js:35  Take SEARCH_RESULTS_SUCCESS
```

So it would seem that the Redux action is firing before the `take` has an opportunity to run. I'm guessing this is caused by a delay in the response to `yield put` on the previous line.

**Comment by yelouafi** [comment]
>I'm guessing this is caused by a delay in the response to yield put on the previous line.

In this line `put(searchResultsActions.loadSearchResults(action))` are you issuing an action to a middleware who'll execute the API call? (because now `put` will wait for the response from the dispatch call)

**Comment by davidjbradshaw** [comment]
Yep, it's passed to http://github.com/agraboso/redux-api-middleware

Should I be using something other than `put` now?

**Comment by davidjbradshaw** [comment]
This is the action.

```js
import { CALL_API, Schemas } from '../middleware/api';
import * as types from 'actionTypes/searchResultsTypes';
import { serialize } from 'utils/utils';
import config from 'config/global';

export const fetchSearchResults = (endpoint) => ({
  [CALL_API]: {
    types: [types.SEARCH_RESULTS_REQUEST, types.SEARCH_RESULTS_SUCCESS, types.SEARCH_RESULTS_FAILURE],
    rootUrl: '/bridge',
    schema: Schemas.SEARCH_RESULTS,
    endpoint,
  },
});

export const loadSearchResults = (params) => {
  const defaultParams = {
    page: 1,
    state: '',
    url: '/holidays/',
    pageStart: 0,
    results: 10,
    noNav: 1,
  };

  return fetchSearchResults(`/?${serialize(Object.assign(defaultParams, params))}`);
};
```

**Comment by yelouafi** [comment]
I think we should provide both options: sync (wait for the promise response) and async (do not wait). The question is which should be the default option?

>Should I be using something other than put now?

You can try this workaround (until the async option gets supported)

```js
yield fork(() => put(searchResultsActions.loadSearchResults(action)))
```

**Comment by davidjbradshaw** [comment]
From my point of view it would be nice to have `put` and `putSync` options as I think having 'put' wait is not a behavior I would expect.

I will give the `fork` idea a go this afternoon, when I have a bit more free time. If it works I have to change it in a lot of places.

Thanks.

**Comment by yelouafi** [comment]
>From my point of view it would be nice to have put and putSync options as I think having 'put' waiting is not a behavior I would expect.

I agree. Most of the time we do not expect responses from put effects.

**Comment by adjohu** [comment]
Agreed, this is making my logic much harder to debug.

**Comment by davidjbradshaw** [comment]
Just wondering when your going to released this patch.

Thanks

**Comment by yelouafi** [comment]
https://github.com/yelouafi/redux-saga/releases/tag/v0.10.5

**Comment by davidjbradshaw** [comment]
Thank you

**Comment by SpainTrain** [comment]
nit: this would have perhaps been better behind a minor version bump given that this breaks code that relies on the 0.10.0-0.10.4 behavior
