### ISSUE TITLE
Watching non-blockingly for actions

### ISSUE THREAD

**Issue by inyono** [yelouafi/redux-saga#34]
Consider in some Component:
```.js
handleLocalFileUpload(files) {
  files.forEach(file => {
    console.log(file);
    this.props.createAssetFromLocal(file);
  })
}
```
with an action creator
```.js
export const createAssetFromLocal = file => ({
  type: CREATE_ASSET_FROM_LOCAL_REQUEST,
  file
});
```
and the corresponding watcher
```.js
export const watchCreateAssetFromLocal = function *(getState) {
  while (true) {
    const { file } = yield take(actions.CREATE_ASSET_FROM_LOCAL_REQUEST);
    yield fork(createAssetFromLocal, file, getState);

    console.log('done');
  }
};
```
When calling `handleLocalFileUpload(['file 1', 'file 2'])`, we have the problem that two actions of type `CREATE_ASSET_FROM_LOCAL_REQUEST` will be dispatched shortly after, and the watcher misses the second one. The corresponding log:
```
file 1
file 2
done
```
Is there something we are doing wrong? I.e. is there a way to write a watcher that isn't blocked for a short moment?

**Comment by yelouafi** [comment]
Can't you dispatch a single action for the whole file list

```javascript
handleLocalFileUpload(files) {
    this.props.createAssetFromLocal(files);
}

export const watchCreateAssetFromLocal = function *(getState) {
  while (true) {
    const { files } = yield take(actions.CREATE_ASSET_FROM_LOCAL_REQUEST);
    yield files.map(file => fork(createAssetFromLocal, file, getState) );

    console.log('done');
  }
};
```

**Comment by inyono** [comment]
Yeah, that was also the workaround we did in this case. But there could be problems somewhere else, when there is no implicit delay introduced by the user. So do `redux-saga`'s watchers implicitly require a very short delay between actions? Just so that we don't run into an issue later.

**Comment by yelouafi** [comment]
>Yeah, that was also the workaround we did in this case

IMO; it's more than a workaround; whenever I dispatch multiple actions *synchronously*; then it feels (still IMO) like a code smell. If I have all the user/server/... input at a given moment, I should dispatch the whole input as one batch to the store.

>But there could be problems somewhere else, when there is no implicit delay introduced by the user

If I'm not mistaken, there will be always a delay between 2 user actions. Each user command (click, input, event ajax responses) are scheduled on the next tick of the event loop. i.e. the current event loop tick will always terminate all the pending tasks before handling the next user input.

>So do redux-saga's watchers implicitly require a very short delay between actions? Just so that we don't run into an issue later.

redux-saga uses promise chaining with `promise.then` to drive its progression. Promises chained callbacks are executed asynchronously; but they are always executed in the same event loop queue. It means event if a user event happens in-between, it wont be missed

So the rules are (should probably figure in the docs)

- do not dispatch multiple actions synchronously, dispatch one action with all the input

- use fork to avoid blocking.

**Comment by inyono** [comment]
Thanks for the clarification.

> IMO; it's more than a workaround; whenever I dispatch multiple actions synchronously; then it feels (still IMO) like a code smell. If I have all the user/server/... input at a given moment, I should dispatch the whole input as one batch to the store.

In this case, you are definitely right. But what about when the action is not dispatched because of a user input but, for example, by a saga. So maybe (I have no use case for this, yet, so everything a little theoretical) my saga dispatches `CREATE_ASSET_REQUEST_SUCCESS` and I have a watcher that listens for this action (for whatever reason ;) ). Then I couldn't be sure that there is a delay between two actions. Not sure, if this could even be a valid use case and if it isn't covered by your last paragraph anyway...

**Comment by yelouafi** [comment]
>my saga dispatches CREATE_ASSET_REQUEST_SUCCESS and I have a watcher that listens for this action (for whatever reason ;) ). Then I couldn't be sure that there is a delay between two actions. 

What you're describing here is 2 sagas communicating via the store. So the 2nd saga must be waiting for the action at the moment the 1st dispatches it. 

>Then I couldn't be sure that there is a delay between two actions.  Not sure, if this could even be a valid use case and if it isn't covered by your last paragraph anyway

Of course you could :). (I mean if you're the author of the 1st saga). But anyway, `CREATE_ASSET_REQUEST_SUCCESS` is normally dispatched after some external event (ajax respoonse, websocket message), so yes it's also covered by my above comment.

The only case I suspect is when the saga fire consecutively 2 actions; and another Saga is waiting also consecutively for those 2 actions. But in this case, I dont see why simply not send one action with all the required payload

**Comment by inyono** [comment]
Okay, thanks!

**Comment by arekkas** [comment]
Doesn't this imply that synchronously incoming event's (e.g. two callbacks resolve at the same time, aka sequential in the cpu commands) have the same issue. I know that this is a highly unusual case but if you're serving millions of requests it's definitely something worth considering

**Comment by yelouafi** [comment]
>two callbacks resolve at the same time

The 2 callbacks will always be scheduled in different task queues.

**Comment by arekkas** [comment]
thanks for clarification :+1:

**Comment by yelouafi** [comment]
FYI. Release 0.6.0 supports synchronous actions. there were more use cases (actions fired simultaneously from different components or middlewares)

**Comment by inyono** [comment]
Cool :+1:
