### ISSUE TITLE
yield cancelled() effect not returning true when a forked task is cancelled.

### ISSUE THREAD

**Issue by pavanpodila** [yelouafi/redux-saga#340]
I have a root saga that forks a subtask as below:

```js 

// Forked task //
function* slowAction() {
    yield call(delay, 30 * 1000);

    try {
        if (Math.random() > 0.45) {
            yield put({type: actions.SLOW_ACTION_COMPLETED});
        } else {
            yield put({type: actions.SLOW_ACTION_FAILED});
        }
    } finally {
        if (yield cancelled()) {
            debugger;
            yield put({type: actions.SLOW_ACTION_CANCELED});
        }
    }
}

// Root saga //
function* watchActions() {
    while (true) {
        yield put({type: actions.NO_ACTION});
        yield take(actions.SLOW_ACTION);

        let task = yield fork(slowAction);
        let action = yield take([
            actions.CANCEL_SLOW_ACTION,
            actions.SLOW_ACTION_FAILED,
            actions.SLOW_ACTION_COMPLETED
        ]);

        if (action.type === actions.CANCEL_SLOW_ACTION) {
            yield cancel(task);
        }

    }
}

```

When I cancel the task, the `yield cancelled()` effect never returns true. Because of that the `SLOW_ACTION_CANCELED` action is never `put` out.

Please advise what I missing here. Awesome working with this library!

**Comment by yelouafi** [comment]
can you make sure the `actions.CANCEL_SLOW_ACTION` fires before the others? Or more perferably could you make some runnable gist to reproduce the issue?

BTW the example can be simply rewritten

```js
function* watchActions() {
    while (true) {
        yield put({type: actions.NO_ACTION});
        yield take(actions.SLOW_ACTION);

        yield race({
          task: call(slowAction),
          cancel: take(actions.CANCEL_SLOW_ACTION)
        })
    }
}
```

**Comment by pavanpodila** [comment]
Thanks @yelouafi for giving a simpler form of the saga. I've created a runnable gist here: https://gist.github.com/anonymous/4a0ec7bde66323effd9224fecc0e5305 

You can see that the `yield cancelled()` is __still not called__. However I do see a `slow action cancelled` message on the console. I would ideally like my code in finally getting executed.

**Comment by yelouafi** [comment]
That was a subtle one! you need to put the `call(delay, 3 * 1000)` inside the `try` block

```js
function* slowAction() {
  try {
    yield call(delay, 3 * 1000);
    if (Math.random() > 0.45) {
      yield put({type: 'SLOW_ACTION_COMPLETED'});
    } else {
      yield put({type: 'SLOW_ACTION_FAILED'});
    }
  } finally {
    if (yield cancelled()) {
      console.log('cancelled!')
      yield put({type: 'SLOW_ACTION_CANCELED'});
    }
  }
}
```

**Comment by pavanpodila** [comment]
Awesome! Really is subtle. So lesson for me is to **run all effects inside the try/catch/finally block**

**Comment by pavanpodila** [comment]
Just to finish off, I do see the console logs correctly and the `yield cancelled()` is getting called:

```
"@@redux/INIT"
"NO_ACTION"
"SLOW_ACTION"
"CANCEL_SLOW_ACTION"
"SLOW_ACTION_CANCELED"
"slowAction has been cancelled"
""
"NO_ACTION"
```
