### ISSUE TITLE
Is it possible to use redux-saga with lets say Alt.js

### ISSUE THREAD

**Issue by DEllement** [yelouafi/redux-saga#347]
i see in all example related to redux-saga that it require a redux store in order to work.

is it possible to make it work without it, or do i have to adapt my AltStore to Redux Store.

Thanks

**Comment by slorber** [comment]
@DEllement yes it is

I've just twitted about it because probably others could be interested.

https://twitter.com/sebastienlorber/status/735037978377105408
https://gist.github.com/slorber/c095671a14b2eccf8ad665a97a7b8ad1

**Comment by DEllement** [comment]
Thanks @slorber for sharing your code, very apreciated :+1:

**Comment by DEllement** [comment]
So here was the solution for AltJs

`import { runSaga }  from 'redux-saga';
import rootSaga from './app/sagas';

const reduxSagaIO = {
    dispatch: events => alt.dispatcher.dispatch(events),
    subscribe: listener => {
        const callback = (events) => {
            console.log(events.type, events);
            listener(events);
        }

        alt.dispatcher.register(callback);
        return () => alt.dispatcher.unregister(callback)
    },
    getState: () => AppStore.getState //AppStore is my main AltJs Store instance
}

runSaga(rootSaga(), reduxSagaIO);`

**Comment by slorber** [comment]
NP.

I've backlinked the link in my gist for users interest to use Alt :)
