### ISSUE TITLE
Retrying network request for set amount of time

### ISSUE THREAD

**Issue by StevenLangbroek** [yelouafi/redux-saga#349]
Hey, I understand this is a "how to" question, and this might not be the place for it. If so, feel free to close ticket, and I'll open elsewhere.

I'm implementing payments against a very retro (I'm being nice here ;) ) API, and can't rely on the redirect after payment to contain the correct status. After payment, the payment provider makes a callback to a URL specified by us, which updates the order, which I have to check against. What I'd like to achieve in a semi-sensible way is this:

- User lands on page, start saga
- For 10 seconds (a `race` I imagine), `call` the order endpoint every 2 seconds to see if the order has the correct status
- If the request "fails" (promise rejects), keep retrying
- If the request "succeeds" (promise resolves), end race
- After 10 seconds, if the request hasn't succeeded, assume "fails".

I understand the race concept and have implemented it elsewhere, I'm just not sure how to do the "retry every 2 seconds" and fit it in there. Any thoughts?

If you feel this warrants an extra page under "Advanced Concepts" I'd be happy to write it and contribute it back.

**Comment by yelouafi** [comment]
Could this solve your issue?
```js
function* saga() {
  for(var i = 1; i <= 5; i++) {
    try {
      yield call(orderApi)
      return Success
    } catch(err) {
      // do not call delay if the last attempt fails
      if(i < 5) {
        yield call(delay, 2000) // retry after 2s
      }
    }
  }
  // attempts failed after 5x2secs
  return Error
}
```

>If you feel this warrants an extra page under "Advanced Concepts" I'd be happy to write it and contribute it back.

I think it's a good case to add to the Recipes section

http://yelouafi.github.io/redux-saga/docs/recipes/index.html

**Comment by StevenLangbroek** [comment]
Thanks for the quick reply. Would this be correct then?


function* saga() {
  for(let i = 1; i <= 5; i++) {
    try {
      const order = yield call(orderApi);
      return order;
    } catch(err) {
      if(i < 5) {
        yield call(delay, 2000);
      }
    }
  }
  // attempts failed after 5x2secs
  return new Error('Order not fulfilled. Giving up.');
}

**Comment by yelouafi** [comment]
You'll have to throw the error instead of returing it
```js
function* checkOrderSaga() {
  for(let i = 1; i <= 5; i++) {
    try {
      const order = yield call(orderApi);
      return order;
    } catch(err) {
      if(i < 5) {
        yield call(delay, 2000);
      }
    }
  }
  // attempts failed after 5x2secs
  throw new Error('Order not fulfilled. Giving up.');
}
```

**Comment by StevenLangbroek** [comment]
And I `call` this "subsaga" with `call` effect?

**Comment by yelouafi** [comment]
yes; throwing instead of returning is because you catch in the containing saga, so you're expecting the subsaga to throw errors instead of returning them
