### ISSUE TITLE
Catching misspelled patterns for take

### ISSUE THREAD

**Issue by tgriesser** [yelouafi/redux-saga#35]
From the docs, `take()` or `take('*')` may be used for matching all actions, however if an undefined value is passed explicitly, it's typically an indicator of a misspelled constant. What do you think about either only using `take('*')` for matching all actions, adding a check that would error in cases which are likely user error:

```js
export function take(pattern){
  if (arguments.length > 0 && is.undef(pattern)) {
    throw new Error(INVALID_PATTERN)
  }
  return effect(TAKE, is.undef(pattern) ? '*' : pattern)
}


take(constant.MISSPELLED_PATTERN) // would throw
```

**Comment by yelouafi** [comment]
Yeah. It'd be safer.

**Comment by tgriesser** [comment]
:+1:
