### ISSUE TITLE
Monitoring the state of a saga in Redux Form's onSubmit callback

### ISSUE THREAD

**Issue by oreqizer** [yelouafi/redux-saga#353]
Hi, I have the following [sagas](https://github.com/oreqizer/reactizer/blob/develop/src/universal/redux/modules/user/userSagas.js), and the following Redux Form [submitter](https://github.com/oreqizer/reactizer/blob/develop/src/web/modules/Signup/index.jsx#L48).

which basically just dispatches an action, that `takeLatest` watches for in saga watchers, running the `loginUser` saga.

is there any simple way I can get a state of a saga, for example in a Promise (or a way I can turn into a Promise), so i can return the Promise in the `onSubmit` callback? This enables stuff like `submitting` prop.

**EDIT:**
for reference, the watchers are [here](https://github.com/oreqizer/reactizer/blob/develop/src/universal/redux/modules/user/userWatchers.js#L16) and the action creator is [here](https://github.com/oreqizer/reactizer/blob/develop/src/universal/redux/modules/user/userDuck.js#L69)

**Comment by oreqizer** [comment]
OK I found a [solution](http://redux-form.com/6.0.0-alpha.13/docs/api/ActionCreators.md/) - see `startSubmit` and `stopSubmit`. I'll use that in the Sagas themselves to replicate the behavior.

Funny that I was figuring this out for two days - combining so many different APIs is not as obvious at times. 😭

**Comment by yelouafi** [comment]
sorry I couldn't help. Didnt work with Redux form.
