### ISSUE TITLE
Fractal sagas as in redux-elm

### ISSUE THREAD

**Issue by caesarsol** [yelouafi/redux-saga#357]
Hello,
I'm looking for a way to apply a saga to a single reducer, and not to the entire store through the enhancer.
This is only conceptual, as every reducer is then connected to the store.
I am organizing my application in a fractal way, where every reducer is property of the component and inside a component directory structure.

This is already working in [redux-elm](https://github.com/salsita/redux-elm), where an `Updater` (which is the Elm concept of a reducer) "refers" to a component-wise saga.
I'm looking for a way to do this without depending on the the redux-elm package, like a function to call in every reducer:

```js
function * componentSaga() {
  // saga for the component actions
}

function reducer(state = initialState, action) {
  callSaga(state, action, componentSaga)
  // normal reducer logic here
}
```

Is there already an equivalent of the `callSaga` fictional function?

**Comment by yelouafi** [comment]
see http://yelouafi.github.io/redux-saga/docs/advanced/UsingRunSaga.html for manually starting Sagas

It's not recommended to do such calls inside a Reducer. If your component architecture supports some lifecycle events  you can hook the runSaga call inside some  'component loaded' lifecycle method

**Comment by caesarsol** [comment]
Hello, thanks for the response and for the documentation link (have to admit I missed that one).
Could you elaborate on the reason why it's not recommended to do such calls inside a Reducer?

Seems that it's the approach used in in redux-elm by @salsita, am I wrong?
If you are not familiar, it binds every reducer with its relative saga, but actually it makes sure that there are no double-triggers with its way of propagating actions. Is that the main concern?

thanks!
