### ISSUE TITLE
Disable default saga error logging by config

### ISSUE THREAD

**Issue by hoschi** [yelouafi/redux-saga#360]
When saga errors get handled by the using code, e.g. such as described in #343, it would be great to disable default logger.

Side note: Is the logger active in production environment? I took a sneak peak into the code https://github.com/yelouafi/redux-saga/blob/ae39cf06dee57ddd3db935a0023db5f584eb1748/src/internal/utils.js#L104 and there is no `isDev` check like in other places of the code.

**Comment by yelouafi** [comment]
Thnking of making a config option passed to the middleware factory function to customize this

**Comment by hoschi** [comment]
This would help :)

**Comment by musbaig** [comment]
In my specific use case I'm continuously starting a race every 5 secs, as a result, the log warnings are flooding the console, drowning out other logs. Being able to turn them off in _dev mode_ would be a godsend?
Fantastic work btw, redux-sagas are by far the best usage of generators this side of the galaxy!

**Comment by thebartekbanach** [comment]
Any update at this issue?

It would be great to be able to turn off redux-saga console logging.

Use case that could be implemented by redux-saga-test-plan:
https://github.com/jfairbank/redux-saga-test-plan/issues/147#issuecomment-519114278

**Comment by Andarist** [comment]
You can customize `onError` to override the default `logError` function.
