### ISSUE TITLE
Pattern to handle reactive data changes in Meteor using sagas, perhaps using runSaga()

### ISSUE THREAD

**Issue by jcheroske** [yelouafi/redux-saga#364]
I'm trying to come up with a pattern for handling changes to reactive data. Without using sagas, I might be tempted to write something like:

```
Meteor.autorun(() => {
  const user = Meteor.user();
  dispatch({
    type: "USER_CHANGED", 
    payload: user
  });
});
```
This will fire the action anytime the user changes. I can't help but think that there is a much better way to do this, possibly using `runSaga()` but I really need some help seeing the way forward. The problem is essentially: How do I integrate reactive changes into the redux universe? Ideally, the pattern would support starting and stopping the monitoring of the reactive data. Being able to discern what exactly changed in the data (USER_LOGOUT, USER_DELETED, etc) would be grand, but mostly what I'm wanting is to have all the code that does this kind of thing built around the same infrastructure as the rest of the side-effect generating code. In other words, built on sagas and generators. Thanks for any help.

**Comment by jschlieber** [comment]
Take a look here: [Channels](http://yelouafi.github.io/redux-saga/docs/advanced/Channels.html).
You can use `eventChannel` to subscribe to `Tracker.autorun(() => { ... })`.

**Comment by jschlieber** [comment]
Here is my personal approach to sync Meteor Collections with the Redux store. The `meteorDataSaga` generator `function*` takes an `Array` of `Mongo.Collection` as its first parameter:

```javascript
import {Tracker} from 'meteor/tracker';
import {eventChannel} from 'redux-saga';
import {
  take,
  call,
  put,
} from 'redux-saga/effects';

export const METEOR_FETCH_DATA = 'METEOR_FETCH_DATA';

function fetchData(Collection) {
  const entityName = Collection._name;
  return eventChannel(dispatch => {
    const computation = Tracker.autorun(() => {
      const data = Collection.find().fetch();
      setTimeout(() => dispatch({data, entityName}), 0);
    });
    return () => {
      computation.stop();
    }
  });
}

function* observe(channel) {
  while (true) {
    const event = yield take(channel);
    yield put({type: METEOR_FETCH_DATA, ...event});
  }
}

export default function* meteorDataSaga(Collections) {
  const channels = [];
  for (let Collection of Collections) {
    channels.push(yield call(fetchData, Collection));
  }
  const observers = channels.map(channel => observe(channel));
  yield observers;
}
```

The `meteorDataSaga` dispatches an action of type `METEOR_FETCH_DATA` with `data` and `entityType` properties whenever the reactive computation for a Collection reruns. It's then up to the  `reducer` to handle these actions.
I normalize the data into an Immutable data structure with an `entities` reducer:

```javascript
import Immutable from 'immutable';
import {
  normalize,
  Schema,
  arrayOf,
} from 'normalizr';
import {METEOR_FETCH_DATA} from '../sagas/meteor_data';

const Schemas = {
  'orders': new Schema('orders', {idAttribute: '_id'}),
};

function normalizeEntities(data, entityName) {
  return Immutable.fromJS(normalize(data, arrayOf(Schemas[entityName])).entities[entityName]);
}

export default function entities(state = Immutable.Map(), action) {
  if (action.type === METEOR_FETCH_DATA) {
    return state.set(action.entityName, normalizeEntities(action.data, action.entityName));
  }
  return state;
}
```
Hope this helps and please let me know if there is a better and more elegant way to do this...

**Comment by jcheroske** [comment]
@jschlieber, thank you for the detailed reply. Your solution seems similar to what I'm doing for small bites of Meteor data, like the current user or the server connection state. I was planning on using minimongo to hold the domain objects, but I'm starting to think that going pure redux would be better. A couple of thoughts and questions:

* Have you looked at the observer api for Meteor client cursors? Here's a snippet of pre-saga code:

```
export const syncCollection = (collection, dispatch) => {
  const actions = getActions(collection);
  collection.find().observe({
    added(doc) {
      dispatch(actions.added(doc));
    },

    changed(doc) {
      dispatch(actions.changed(doc));
    },

    removed(doc) {
      dispatch(actions.removed(doc));
    }
  });
};
```
Maybe using it vs. just grabbing the whole collection every time might be more efficient? Idk.

* Can you say a little bit about your experiences with normalize vs. minimongo? What do you feel you lost and gained?

* I was looking at immutable and backed away because lodash doesn't play totally nice with it. But now I'm thinking of making the switch. Do you have any pearls you'd like to share to an immutable newbie?

**Comment by jschlieber** [comment]
I'm also reflecting about a similar approach at the moment. In my opinion, when using the redux store as the single source of truth, we should probably completely bypass MiniMongo and directly use DDP to avoid data duplication and possible performance bottlenecks. I found some projects utilizing this approach ([here](https://github.com/rclai/redux-ddp) and [here](https://github.com/looshi/redux-ddp)) but they don't use redux-saga to manage side effects. I'm going to try to do a similar thing with redux-saga tomorrow and share my results here...

Excuse me for not being to address all your questions at the moment.

**Comment by jcheroske** [comment]
@jschlieber Not a problem at all! I think you're correct in wanting to go straight from ddp into redux. Although all of this will be superseded by Apollo, I can't help but think there are others out there who would find such a bridge useful in the meantime.

Since the whole thing is driven by subscriptions, I'm curious what pattern you're using to handle them with redux. Do you link subs to routes or component mounts? I was thinking about an HOC that would fire subscribe/unsubscribe actions when the component was mounted/unmounted/updated and maybe also when a route was entered/exited. Then a saga could do the actual subscription work, and a record of the subscriptions could be put in the store so that the app could be brought back to its previous state.

**Comment by jschlieber** [comment]
@jcheroske You're absolutely right. To be honest, I didn't realize how mature the Apollo project and similar efforts already are (or at least they seem to be at first glance). That happens when you're immersed in your own work for months. Thanks for helping me to take a step back and looking at the big picture again. I need to do some research before spending to much time into building a ddp-redux bridge. If Apollo with GraphQL solves all these problems and will be production ready soon, then it's probably not worth all the effort.

> Since the whole thing is driven by subscriptions, I'm curious what pattern you're using to handle them with redux. Do you link subs to routes or component mounts? I was thinking about an HOC that would fire subscribe/unsubscribe actions when the component was mounted/unmounted/updated and maybe also when a route was entered/exited. Then a saga could do the actual subscription work, and a record of the subscriptions could be put in the store so that the app could be brought back to its previous state.

For that purpose I created a special React component called `SideEffect`. It takes a side effect `function` or a thunk as prop. That function then gets called in every life cycle method of the `SideEffect` component provided with a life cycle hook constant as parameter.

```javascript
const sideEffectThunk = (dispatch) => {
  let subId;
  return (hook) => {
    switch (hook) {
      case WILL_MOUNT:
        dispatch(meteorSubscribe('orders', [], id => subId = id));
        return;
      case WILL_UNMOUNT:
        return dispatch(meteorUnsubscribe(subId));
      default:
        return;
    }
  }
};

let Container = ({dispatch, ...passDownProps}) => (
  <SideEffect
    thunk={sideEffectThunk.bind(this, dispatch)}
  >
    <Component {...passDownProps}/>
  </SideEffect>
);
```
The subscription work is then done by a saga.

**Comment by adamgins** [comment]
@jschlieber @jcheroske wondering where you go to on this? I am looking to leverage react-native to enable an Offline First mobile client to an existing meteor project... 

I have been at the persisting the collections that the user subscribes to with `redux`, `redux-persist` and using https://github.com/lhz516/react-redux-meteor to pub/sub and was about to go down the `observe` route and came across this thread... so interested to see where you've ended up, pls?

thanks
