### ISSUE TITLE
Will forking too many watchers cause performance issues?

### ISSUE THREAD

**Issue by t-benze** [yelouafi/redux-saga#366]
Hi, in the site we're building, when the app is launched, we will fork all the action watcher at the same time, as follows:

```js
function* watchBlabla1() {
  yield* takeLatest(action1, blaBla1);
}
function* watchBlabla2() {
  yield* takeLatest(action2, blaBla2);
}
function* watchAll() {
  yield [
    fork(watchBlabla1),
    fork(watchBlabla2),
    ...
  ]
}
```

Currently we already have a few dozens of these kind of watcher running at the same time, and we expect it to grow more and more. My question is that is it ok to do things this way, will it cause any performance issues?

**Comment by yelouafi** [comment]
It depends on the use case, I dont think having many watchers will impact the perf. on most cases (unless it's a perf. critical app ).But you need to profile the app and measure the impact

**Comment by shaoner** [comment]
That's the most abstract answer I've ever read. Just say that you don't know..
