### ISSUE TITLE
Calling generator functions from normal functions

### ISSUE THREAD

**Issue by luandro** [yelouafi/redux-saga#368]
The payment gateway I'm using forces me to use a function that doesn't return the callback value. This is what my code looks like:

```
function RequestPayment({code}, {
  success: (transactionCode) => {
    alert("success - " + transactionCode);
    sendSuccessPayment().next(transactionCode);
  },
  abort: () => {
    alert("aborted!");
    sendFailPayment().next();
  }
});

function* sendFailPayment() {
    yield put(failPayment({ok: false}));
};

function* sendSuccessPayment(code) {
    yield put(successPayment({ok: true, code }));
};

export function* createPayment() {
  while (true) {
    const action = yield take(START_PAYMENT);
    const payment = yield call(paymentApi, action.payload)
    if (payment.ok) {
      const gateway = yield call(RequestPayment, payment.code);
    } else {
      yield put(failPayment(payment));
    }
  }
}
```

The problem is I can't get to call the yields in the `sendFailPayment` and `sendSuccessPayment` generator functions. Am I missing something?

**Comment by jschlieber** [comment]
1. Your "function" `RequestPayment` doesn't look like a function (there is no function body).
2. The Redux Saga middleware is in control of running your Sagas, i.e. generator functions. Thus, you never call `next` yourself. Doing so is a clear indication your doing something wrong. In your case, by calling `sendSuccessPayment().next(transactionCode)` your just creating an iterator the middleware is not aware of and running your generator function until it reaches the first `yield`. That's it. By the way: the argument `transactionCode` will be thrown away, because it is the first `next` call on that iterator.
3. You can only `yield call` your `RequestPayment` function if it returns a Promise or is a generator function itself.
4. For Node style functions use `yield cps`.
5. For everything else you'd have to either wrap it to return a promise or work with [`eventChannel`](https://yelouafi.github.io/redux-saga/docs/advanced/Channels.html)

Hope I could help somehow...

**Comment by luandro** [comment]
Thanks for the awesome response. I've tried creating a promise from the function, and also calling it with `cps`, but it doesn't work since the first thing it returns is a `true`. But I think `cps` might be what I'm looking for, since it logged `this.callback.abort is not a function` as a callback, which is a good sign already. This is how I tried calling it:
```
yield cps(RequestPayment(payment.code, (err, res) => {
        console.log(err);
        console.log(res);
}));
```

This is what the `RequestPayment` function looks like: 

```
function (token,callback) {
      try {
        initLightbox(token,callback);
        return true;
      }
      catch(e) {
        _logErrors(e,"initLightbox");
        throw e;
      }
    }
```

Thanks for the help, cheers!

**Comment by jschlieber** [comment]
If you take a look at the [API Reference](https://yelouafi.github.io/redux-saga/docs/api/index.html#cpsfn-args) your function call should look like this: 
```javascript
yield cps(RequestPayment, payment.code);
```
The API Reference about the `cps` effect creator function states clearly: 

> Creates an Effect description that instructs the middleware to invoke fn as a Node style function

As you see, you must not call the function yourself. Instead, the Redux Middleware is instructed to do it for you by yielding the effect description. It has nothing to do with the function returning `true` (I don't really see the point of doing so anyway). The middleware doesn't care about what your Node style function returns...
The error message `this.callback.abort is not a function` is a clear indication that your "callback" is in fact not a Node style callback and thus your function is not a Node style function...
It seems your "callback" is not even a callback but an object with callback properties. One of them being `abort`. If I guess correctly from your first post, the second one is `success`. So you could wrap the `initLightbox` function into a function returning a promise like this:

```javascript
function requestPayment(token) {
  return new Promise((resolve, reject) => {
    initLightbox(token, {
      abort() {
        reject();
      },
      success(transactionCode) {
        resolve(transactionCode);
      }
    }
  }
}
```
Then your `createPayment` Saga would look something like this:
```javascript
export function* createPayment() {
  while (true) {
    const action = yield take(START_PAYMENT);
    const payment = yield call(paymentApi, action.payload)
    if (payment.ok) {
      yield put(successPayment(payment));
      const gateway = yield call(requestPayment, payment.code);
      ...
    } else {
      yield put(failPayment(payment));
    }
  }
}
```
Really try wrapping your head around [promises](http://www.html5rocks.com/en/tutorials/es6/promises/) and [generator functions](https://davidwalsh.name/es6-generators) first... Cheers!

**Comment by luandro** [comment]
I'll have a look, thanks for the patience. For now I'm giving up because of time (and knowledge) constraints, and just call the gateway function from the React component where it can access the actions from these weird `try` and `catch` functions it creates. But I'll have a closer look at promises and generators for sure.

Cheers!
