### ISSUE TITLE
HMR in Real World example

### ISSUE THREAD

**Issue by Hyra** [yelouafi/redux-saga#370]
I'm trying to figure out why HMR isn't working correctly for me in the real world example.

Changing a component or container leads to the following warning:

```
process-update.js?e13e:81 [HMR] The following modules couldn't be hot updated: (Full reload needed)
This is usually because the modules which have changed (and their parents) do not know how to hot reload themselves. See http://webpack.github.io/docs/hot-module-replacement-with-webpack.html for more details.
```

I've gone over the code, but it looks like all parts are in place. 

Anyone else experiencing this issue?

**Comment by yelouafi** [comment]
fixed by #422
