### ISSUE TITLE
Confusion with channels

### ISSUE THREAD

**Issue by AidanNichol** [yelouafi/redux-saga#371]
I've been trying out the new channels option and it works great. But I got confused for a while by an argument name in the sample code.
I refactored the sample code to work with my pouchdb changes event stream and ended up with (omitting some of the db options parameter details) 
```
function createChangeChannel (...) {
  // every change event will call put on the channel
  let subscriber = (listener)=>{
    let monitor = db.changes({ ... })
      .on('change', (data)=>listener(data))
      .on('complete', listener(END))
      .on('error', error => console.error('changes_error', error));
      // The subscriber must return an unsubscribe function
      return () => monitor.cancel();
    };
  return eventChannel(subscriber, buffers.fixed());
}

export default function * monitorChanges () {
  const channel = yield call(createChangeChannel, ...);
  while (true) {
    const change = yield take(channel); // Blocks until the promise resolves
    // handle the change somehow
  }
}
```
I had made a dumb mistake and got the following error
```
utils.js?1f12:186 uncaught at monitorChanges 
 TypeError: listener must be a function
```
which confused me considerably because in my code ```listener``` is clearly a function.

I eventually figured out that it wasn't refering to the anything in my code named ```listener``` but to what was attached to one of the event sources. I need to change the second one to
```
  .on('complete', ()=>listener(END))
```
That got me thinking. It seems to me, that the function that gets passed to the subscriber and is named and described in the documentation as ```listener``` isn't really a listener function but is something that is used by one. Isn't it's more like ```putEventOnChannel``` and would it be clear if a name along those lines was used in the documenation?

**Comment by kuy** [comment]
Agreed. So I use `emit` instead of `listener` in my project and examples.

https://github.com/kuy/redux-saga-examples/blob/master/startstop/sagas.js#L50
https://github.com/kuy/redux-saga-examples/blob/master/microblog/firebase.js#L8
https://github.com/kuy/redux-saga-chat-example/blob/master/src/client/sagas.js#L18

```es6
function subscribe(socket) {
  return eventChannel(emit => {
    socket.on('users.login', ({ username }) => {
      emit(addUser({ username }));
    });
    socket.on('disconnect', e => {
      // TODO: handle
    });
    // ...
  });
}
```

**Comment by yelouafi** [comment]
Agree. `emitter` or `channelEmitter` seems more appropriate

**Comment by AidanNichol** [comment]
I was going to make a PR for a couple of other minor things in the documentation so I'll make this change at the same time if that is OK with you.

**Comment by yelouafi** [comment]
It's ok. Thanks
