### ISSUE TITLE
Right pattern for reporting error to user

### ISSUE THREAD

**Issue by tonyxiao** [yelouafi/redux-saga#372]
With Redux Saga, what's the recommended pattern to report error while executing an operation to user? With `redux-thunk` we can return a promise while dispatching an operation and allow user to essentially observe that promise. Since all the actions are plain objects in saga world, this isn't possible. And it's not always convenient to report error via state change (think react native alerts)

**Comment by kuy** [comment]
I think that there is no difference between redux-saga and redux-thunk on the ability for reporting the progress to user. Because of Redux is single state, we need to put the operation progress to the store. And the state is changed only by Actions. So you can dispatch Actions based on the progress of operations.

*Note: `callAPI(...)` returns Promise object*

```es6
// redux-thunk (action creator)
function fetchRequest(id) {
  return dispatch => {
    dispatch({ type: FETCH_OBJECTS_REQUEST });
    callAPI(id).then(data => {
      dispatch({ type: FETCH_OBJECTS_SUCCESS, data });
    }).catch(error => {
      dispatch({ type: FETCH_OBJECTS_FAIL, error });
    });
  };
}
```

```es6
// redux-saga
function* runRequest({ payload }) {
  const { id } = payload;
  const { data, error } = yield call(callAPI, id);
  if (data && !error) {
    yield put({ type: FETCH_OBJECTS_SUCCESS, data });
  } else {
    yield put({ type: FETCH_OBJECTS_FAIL, error });
  }
}

function* handleRequest() {
  yield* takeLatest(FETCH_OBJECTS_REQUEST, runRequest);
}
```

**Comment by tonyxiao** [comment]
In `redux-thunk` you can do

```javascript
function fetchRequest(id) {
  return dispatch => {
    dispatch({ type: FETCH_OBJECTS_REQUEST });
    return callAPI(id).then(data => {
      dispatch({ type: FETCH_OBJECTS_SUCCESS, data });
      return data;
    }).catch(error => {
      dispatch({ type: FETCH_OBJECTS_FAIL, error });
      throw error;
    });
  };
}
```

And in the calling function
```
this.props.dispach(fetchRequest()).then((data) => {
  // Do something upon success
}, (err) => {
  // Do something upon failure
})
```
Strictly speaking this isn't going through the store, but sometimes it's really convenient to be able to do stuff like this when interacting with other APIs that are imperative rather than declarative.

**Comment by kuy** [comment]
Umm... I understand what you want to say. I have no idea to do directly like that with redux-saga.
If you do so, React component (which calls `this.props.dispach`) is no longer pure. This causes decreasing of testability.

> when interacting with other APIs that are imperative rather than declarative

Does this mean an use-case like **chained API calling**?

For example, please consider two API endpoints; `/users` and `/users/<id>/posts`.
You want to load a list of users from `/users` endpoint first, and then load a list of latest posts for each user. But if you get an error on calling `/users`, you don't want to call `/users/<id>/posts`.

```es6
this.props.dispach(fetchRequest()).then((data) => {
  this.props.dispatch(fetchOtherRequest()).then((data) => {
    // Do something upon success both
  }, (err) => {
    // Error handling
  });
}, (err) => {
  // Do something upon failure
})
```

If chained API call is your hidden needs, it's a common pattern in redux-saga.

```es6
function* handleRequestSearchByLocation() {
  while (true) {
    const action = yield take(SUCCESS_USER);
    const { payload, error } = yield call(API.searchByLocation, action.payload.location);
    if (payload && !error) {
      yield put(successSearchByLocation(payload));
    } else {
      yield put(failureSearchByLocation(error));
    }
  }
}

function* handleRequestUser() {
  while (true) {
    const action = yield take(REQUEST_USER);
    const { payload, error } = yield call(API.user, action.payload);
    if (payload && !error) {
      yield put(successUser(payload));
    } else {
      yield put(failureUser(error));
    }
  }
}

export default function* rootSaga() {
  yield fork(handleRequestUser);
  yield fork(handleRequestSearchByLocation);
}
```

**Comment by yelouafi** [comment]
As @kuy mentioned it depends on the sepecific use case. If you want to achieve a general purpose communication mechanism you make take a look at [the Channel API](http://yelouafi.github.io/redux-saga/docs/api/index.html#channel).

**Comment by messense** [comment]
I think this didn't resolve the problem ` it's not always convenient to report error via state change (think react native alerts)`?

How can I do that?

**Comment by itinance** [comment]
https://github.com/itinance/redux-saga-rn-alert

**Comment by oshalygin** [comment]
Just looking at this and I like the solution provided by @kuy .  That said, you can still use thunks alongside sagas when you need to.
