### ISSUE TITLE
Question: handling uncaught exceptions - spawn vs fork

### ISSUE THREAD

**Issue by rayd** [yelouafi/redux-saga#374]
I know a similar question to this was posted in #250, but the solution presented there doesn't seem to work for `fork`-ed sagas that synchronously throw an Error. With the `wrapFork` function suggested in #250, the `reportTheError` function doesn't seem to be called in this case:
```javascript
// Example from a mocha test
const testSaga = function*(arg) {
    throw new Error(arg);
};
const task = sagaMiddleware.run(function*() {
    yield utils.wrapFork(testSaga, 'test error');
});
return task.done.catch(() => {
    expect(reporterSpy).to.have.been.calledOnce;
    expect(reporterSpy).to.have.been.calledWith(
        sinon.match.instanceOf(Error).and(sinon.match.has('message', 'test error'))
    );
});
```
Here's the `wrapFork` function for reference:
```javascript
// Mostly stolen from https://github.com/yelouafi/redux-saga/issues/250.
function* wrap(saga, ...args) {
    const reportError = yield select(getReporter);
    // const task = yield spawn(saga, ...args);
    const task = yield fork(saga, ...args);
    task.done.catch(reportError);
    return task;
}

// wrap the fork effect
export function wrapFork(saga, ...args) {
    return call(wrap, saga, ...args);
}
```
It seems like this happens because the `wrap` generator never makes it past the `yield fork(saga, ...args);` line when the error is propagated up the saga-chain for `fork`-ed sagas. If I change the `wrapFork` function to a "wrapSpawn" function that `spawn`s the saga I want to wrap, then the `Task` is detached and the error isn't propagated up the chain. Then I'm able to catch the error coming from the `spawn`-ed task. I guess my questions are:
* Is this behavior expected (when the wrapped saga immediately throws an error)?
* Should I just be using `spawn` instead of `fork`? It seems like I should default to using `spawn` unless I need the "child saga" to take down the parent in the case of an error. Does that sound right?

I know there's a lot of text here - thanks for reading through it all!

**Comment by yelouafi** [comment]
>Is this behavior expected (when the wrapped saga immediately throws an error)?

Yes.And with the new fork model of 0.10 uncaught errors bubbling from `fork`ed saga will abort the parent chain. So a forked task should always handle its errors.

>Should I just be using spawn instead of fork? It seems like I should default to using spawn unless I need the "child saga" to take down the parent in the case of an error. Does that sound right?

`spawn` is used for detached children, a spawned task lives as a separate process, meaning cancelling a parent task wont automatically cancel the spawned task.

Using spawn just for this use case seems a little overkill; if what you need is to send crash reports you may look at #343

**Comment by rayd** [comment]
Ah ok, thank you very much for the quick answer. This clears things up a lot.

I think using a "wrapped spawn" and "wrapped takeEvery"

```javascript
function* wrap(saga, ...args) {
    const reportError = yield select(getReporter);
    const task = yield spawn(saga, ...args);
    task.done.catch(reportError);
    return task;
}

export function spawnWrapped(saga, ...args) {
    return call(wrap, saga, ...args);
}

export function* takeEveryWrapped(pattern, saga, ...args) {
    /*eslint-disable no-constant-condition*/
    while (true) {
        const action = yield take(pattern);
        yield spawnWrapped(saga, ...args.concat(action));
    }
}
``` 
will work best for me. I'm using the "while true, take and fork" pattern quite a bit in my code and any uncaught error (perhaps due to an unexpected null value in state for example) in the fork part will kill that whole saga, which is not what I want. So I think using the wrapped spawn insulates me from these uncaught errors without entirely swallowing them (i.e. they're reported and I can address them now).
