### ISSUE TITLE
select() doesn't seem to work properly with reselect

### ISSUE THREAD

**Issue by adjohu** [yelouafi/redux-saga#377]
```
const dogSelector = createSelector(
  dogsSelector,
  dogIdSelector,
  (dogs, dogId) => {
    // this only gets fired once, not twice.
    console.log('dogs', dogId);
    return dogs.get(dogId);
  }  
)

// In the saga...
const dogs = [1,2,3];
for (let dogId of dogs) {
    let dog = yield select(dogSelector, {params: {dogId}});
}
```

**Comment by slorber** [comment]
@adjohu not sure by try the following: 

`yield select(state => dogSelector(state), {params: {dogId}});`

**Comment by adjohu** [comment]
No luck.

My hack for now is:

```
const dogSelector = (state, props) => {
  return dogsSelector(state).get(props.params.dogId)
} 
```

**Comment by adjohu** [comment]
So it seems to be an issue specifically with `createSelector` in reselect.

**Comment by slorber** [comment]
I don't know.

> select() doesn't seem to work properly with reselect

This does not really describle the problem. Please show error or returned object

**Comment by andykenward** [comment]
@adjohu [Reselect doesn't support arguments](https://github.com/reactjs/reselect#q-how-do-i-create-a-selector-that-takes-an-argument) being passed to them by default.

**Comment by adjohu** [comment]
Selectors have the signature `(state, props) => stateSlice` where props is
a plain object (usually an @connected component's props).

I thought that calling `yield select(selector, {...props})` would pass
props into the selector.

-- 
Adam Hutchinson
Sent with Airmail

On 8 June 2016 at 14:55:26, Andy Kenward (notifications@github.com) wrote:

@adjohu <https://github.com/adjohu> Reselect doesn't support arguments
<https://github.com/reactjs/reselect#q-how-do-i-create-a-selector-that-takes-an-argument>
being passed to them by default.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/yelouafi/redux-saga/issues/377#issuecomment-224596250>,
or mute the thread
<https://github.com/notifications/unsubscribe/AAoB8bbbhrSPNa_WmPdpHytrFQ3FflDlks5qJsnGgaJpZM4Iv70L>
.

**Comment by adjohu** [comment]
Based on that link, maybe I need to rethink my implementation.

-- 
Adam Hutchinson
Sent with Airmail

On 8 June 2016 at 14:55:26, Andy Kenward (notifications@github.com) wrote:

@adjohu <https://github.com/adjohu> Reselect doesn't support arguments
<https://github.com/reactjs/reselect#q-how-do-i-create-a-selector-that-takes-an-argument>
being passed to them by default.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/yelouafi/redux-saga/issues/377#issuecomment-224596250>,
or mute the thread
<https://github.com/notifications/unsubscribe/AAoB8bbbhrSPNa_WmPdpHytrFQ3FflDlks5qJsnGgaJpZM4Iv70L>
.

**Comment by npbee** [comment]
@adjohu, I use reselect and redux-saga together in this way and it seems to work ok, so perhaps there's an error elsewhere?  Here's a quick fiddle:  https://jsfiddle.net/npbee/bsvh7mgw/
