### ISSUE TITLE
Move questions to StackOverflow?

### ISSUE THREAD

**Issue by slorber** [yelouafi/redux-saga#378]
Hi,

Maybe it would be better to move all questions to StackOverflow?

There's already a [tag](http://stackoverflow.com/questions/tagged/redux-saga) and some questions

I think people like gamification / obtain some reputation there and are more likely to help each others if there is a reward, while few people look at each others questions on github, leaving more work for project maintainers.

Also there's a lot of watchers of this repository that may receive a lot of notifications related to questions. I'd like to follow the progress of this repository so I'd like to keep watching, but I don't have much time to answer questions (and if I have I can go on SO) so it would help if questions and bugs/releases/enhancements are separated

**Comment by yelouafi** [comment]
Yeah I agree. The issue is that sometimes people report issues and it's not clear immediately if it's a bug or a mistake in the reported example.

Perhaps we should require some template for issue reporting
