### ISSUE TITLE
Dispatch saga return promise?

### ISSUE THREAD

**Issue by aight8** [yelouafi/redux-saga#379]
Is it possible to add saga helpers to reject/resolve/progress a promise which is returned when execute a saga action to redux? I currently add callbacks to the meta field of an saga action.

Is this technically possible by redux?

My use case is in redux-form but there is so much other use cases. Currently you lose any direct callback after dispatching an saga action (only workaround is to add callback methods to the action).

**Comment by musbaig** [comment]
Checkout issue #161, solution is near the bottom, cheers.

**Comment by bakatrouble** [comment]
Is [`store.runSaga().done`](https://github.com/yelouafi/redux-saga/tree/master/docs/api#runsagaiterator-options) correct solution for this problem?

**Comment by Andarist** [comment]
Could you elaborate on your problem, hopefully with example code? Its not
obvious from this issue

**Comment by bakatrouble** [comment]
I could provide example later, but I'll try to explain it now shortly
I was trying to wire redux-saga together with redux-connect in order to delay router redraw until asynchronous data is fetched, so I needed to get an action promise. I ended up using `Task.done` promise, getting the `Task` via `store.runSaga()`. Is it appropriate way to do it or there are better ones?

**Comment by Andarist** [comment]
I would say that more natural way of doing this is to store a flag in your
state and update it on promise's success, then connect would do its thing -
select this state from the store and render appropriately.

runSaga is not the best for this use case, at least not with the snippet
you have proposed, cause it would never resolve I think as you use there an
infinite helper - takeEvery. Which stays alive until cancellation or error

**Comment by morgs32** [comment]
@bakatrouble I'm with you. Having a ton of flags all over my code for ever POST or PUT seems ridiculous. @Andarist, every form that you want to monitor (isDirty? isPristine?) you want to update the "initialValues" (to use a redux-form term) when the POST or PUT is complete. I have to have a flag, flip it with the saga, then what, flip it back after the component sees the flag and resets the form?

**Comment by morgs32** [comment]
Ahhh @musbaig thanks for that issue ref. Thank god for redux-form.

**Comment by TomMahle** [comment]
For people coming here significantly after @musbaig's comment I believe this is the one he is referring to: https://github.com/redux-saga/redux-saga/issues/161#issuecomment-229350795 (please correct me if I'm wrong, @musbaig )

**Comment by musbaig** [comment]
@TomMahle yup, that's the correct one, I still use both the original approach and improvements thereof
