### ISSUE TITLE
How to run sagas in loop

### ISSUE THREAD

**Issue by fusionstrings** [yelouafi/redux-saga#38]
First of all thanks a lot for providing community with this nifty tool. I am able to reduce lot of corners around my app.

One thing I was wondering how to achieve is how to run sagas in loop. i.e.
    
```js
forEach(result, (item) => {
  yield fork(api.endpoint, item);
});
```

I am getting following error while trying so 

```
Uncaught (in promise) Error: https://localhost:3000/fuses/fuse-react-redux/sagas/index.js: Unexpected token (30:12)
  28 |     yield put(actions.requestNewItems());
  29 |     forEach(result, (item) => {
> 30 |       yield fork(api.endpoint, item)
     |             ^
  31 |     });
```

saga works if put outside of loop with single item. e.g.

```js
yield fork(api.endpoint, item)
```

I am not sure if by convention it's not supposed to work this way.

**Comment by yelouafi** [comment]
You can't yield from a  callback. Only from generators. A possible solution is

```javascript
yield result.map(item => fork(api.endpoint, item))
```

**Comment by fusionstrings** [comment]
That worked like charm. Thanks a lot. Everyday I am learning new and awesome stuff about sagas. Best complement to Redux.
