### ISSUE TITLE
Can I expect reducer to do its thing BEFORE the saga watching for the same action?

### ISSUE THREAD

**Issue by richierob62** [yelouafi/redux-saga#383]
I have a reducer... two of the actions it responds to are:
RESORT_CUSTOMER
CUSTOMER_RESORT_REQUIRED

```
// RESORT_CUSTOMER just updates state for the selected sort
case actions.RESORT_CUSTOMER: {
    return state.set('sort', action.payload.sort);

```
```
// CUSTOMER_RESORT_REQUIRED actually sorts the data
case actions.CUSTOMER_RESORT_REQUIRED: {
    const list = state.get('list');
    const sort = state.get('sort');
    const fieldToSortOn = sort.column;
    const valueMapper = (item) => item[fieldToSortOn];
    const compareFunctionFactory = (dir) => {
        return (itemA, itemB) => {
            const resultValue = dir == 'asc' ? -1 : 1;
            if (itemA < itemB) return resultValue;
            if (itemA > itemB) return -1 * resultValue;
            return 0;
        };
    };
    const compareFunction = compareFunctionFactory(sort.dir);
    const sortedList = list.sortBy(valueMapper, compareFunction);
    return state.merge({
        list: sortedList
    });
}

```
Note: resorting can be required as a result of a selection by the user or as a subsequent step following an API call, so RESORT_CUSTOMER (UI action) and CUSTOMER_RESORT_REQUIRED (following UI action or API call) have to be handled differently.

Now, since I can't fire actions from inside reducers, and don't want to duplicate the code under 
'case actions.CUSTOMER_RESORT_REQUIRED' as a part of 'case actions.RESORT_CUSTOMER', I am handling this in my sagas.

In my sagas, I use these in 2 places:

a) If a RESORT_CUSTOMER is dispatched, I dispatch a CUSTOMER_RESORT_REQUIRED after.

```
function* watchCustomerResort() {
  while(true) {
    yield take(actions.RESORT_CUSTOMER);
    yield put( actions.resortRequired('customer') );
  }
}
```

b) After data is loaded from the API..

```
if(response) {
  yield put( actions.dataLoaded('customer', response) );
  yield put( actions.resortRequired('customer') );
}

```
Btw, actions.resortRequired is just a little helper action creator that returns the specific action:
export const resortRequired = (type) => ({type: _.trim(_.toUpper(type)) + '_RESORT_REQUIRED' });

Now this all works fine IF I can guarantee that the reducer will respond to RESORT_CUSTOMER before the saga dispatches actions.resortRequired('customer').  In other words, that the reducer will set the state for the required sort before the saga dispatches the action to do the actual sort.

My manual "clicks" suggest I'm safe, but I don't know if this is guaranteed by how middleware like saga works.
Any insights?

**Comment by yachaka** [comment]
It is guaranteed, the reducers are called before the `yield take(actions.RESORT_CUSTOMER)` is resumed.

See [https://github.com/yelouafi/redux-saga/blob/master/src/internal/middleware.js#L46](https://github.com/yelouafi/redux-saga/blob/master/src/internal/middleware.js#L46).

**Comment by richierob62** [comment]
Thanks, much.
