### ISSUE TITLE
Support for clearing/flushing buffered events in a channel

### ISSUE THREAD

**Issue by sam-jay** [yelouafi/redux-saga#384]
Let's say that I have a channel taking in events but at some point I need to suspend processing these events in response to some action and later start processing again. I want to ignore all the events accumulated in the buffer during the suspended period.

I could teardown the channel after receiving the first action and then recreate it later when I want to start processing again. But it might not be efficient if creating the channel is expensive (maybe I need to establish a network connection to receive events or something like that).

Is there any way to cleanly handle this using the current API? If not, what do you think about adding support for clearing buffered events in a channel?

**Comment by yelouafi** [comment]
>Is there any way to cleanly handle this using the current API

you can create your own [buffer](http://yelouafi.github.io/redux-saga/docs/api/index.html#buffer) and pass it to eventChannel

**Comment by sam-jay** [comment]
> you can create your own buffer and pass it to eventChannel

that's not a bad way to go.

are you interested in a pull request for ```buffer.clear()```, ```channel.clearBuffer()```, or ```channel.clear()```?

**Comment by yelouafi** [comment]
Hmm... Not sure about this. Seems more like an implementation concern for a special kind of buffers (buffers which clear on some action/event)

**Comment by Andarist** [comment]
@sam-jay 
I aint sure if you have noticed but the API for it is available for some time already (I know it wasnt when you have posted your issue). There is an effect now called `flush` and you can use it like this - `yield flush(channel)`
