### ISSUE TITLE
Dispatch action or action creator?

### ISSUE THREAD

**Issue by DarrylD** [yelouafi/redux-saga#387]
A little confused so please excuse my ignorance.

In the readme I see an example ***dispatching the action***:
```
class UserComponent extends React.Component {
  ...
  onSomeButtonClicked() {
    const { userId, dispatch } = this.props
    dispatch({type: 'USER_FETCH_REQUESTED', payload: {userId}})
  }
  ...
}
```

In an [example](https://github.com/yelouafi/redux-saga/blob/6c6ad42c7b53fa8ce419bfdccab78d508e862e99/examples/async/src/containers/App.js) I see ***dispatching of the action creator***?
```
import { selectReddit, invalidateReddit } from '../actions'

class App extends Component {
  ...
  handleChange(nextReddit) {
    this.props.dispatch(selectReddit(nextReddit))
  }
  ...
}
```

Any reason for the variation? Don't both approaches do the same thing?

I thought one of the benefits of sagas was the fact you no longer needed to do as much importing (hence the first example).

Trying to standardize an approach before I convert over to sagas.

**Comment by janhartmann** [comment]
They do the same thing, but with an action creator you can define your action one place and use it several places. So e.g if the `type` signature change, you only have to fix it one place. In the example the `selectReddit(reddit)` simple does this:

```
export function selectReddit(reddit) {
  return {
    type: SELECT_REDDIT, // actually a constant
    reddit
  }
}
```

Which would be the equivalent of doing:
 
`this.props.dispatch({type: "SELECT_REDDIT", reddit: {reddit} });`

**Comment by slorber** [comment]
@DarrylD I yhink my answer here might help you 

http://stackoverflow.com/questions/34570758/why-do-we-need-middleware-for-async-flow-in-redux/34623840#34623840

**Comment by DarrylD** [comment]
@slorber funny, that answer is what led me to considering sagas thus asking this question. Very good answer by the way.

But my question still stands since the example in this repo conflict with the answer.

**Comment by slorber** [comment]
@DarrylD thanks :)

I think we allow to dispatch an action creator because people might want to keep using thunks with redux-saga. I think thunks are not needed anymore with redux-saga, but one might want to migrate progressively to sagas and keep both during the migration.

In this example as the selectReddit is not a thunk I don't see much interest, except the ability to have an action builder, on which you can easily add assertions, and eventually a typesystem like typescript or flow. I'd recommend to keep the usage of actionCreators just for that as it can help maintainability.

**Comment by DarrylD** [comment]
Interesting. I'm not using thunks at the moment but, I think I'll play around some some options. I have to say, at this moment, AC's seems pretty redundant for my use case. Maybe maintainability would be a factor but, it seems like the additional boilerplate/overhead offsets a bit.

Also gonna implement [ducks](https://github.com/erikras/ducks-modular-redux), that should also help a bit.
