### ISSUE TITLE
console.error: "uncaught", "at rootSaga at loginFlow ...

### ISSUE THREAD

**Issue by Baisang** [yelouafi/redux-saga#389]
I'm trying to implement a really basic login skeleton similar to what is detailed in the [docs](http://yelouafi.github.io/redux-saga/docs/advanced/NonBlockingCalls.html). Mine is a little simpler since in my UI there will be no way for the user to send a login action before the login actually occurs. But, I am working in react-native if that makes any difference.

So I have a button right now that dispatches an action with a mock payload. This action is recognized by the reducer, so it is firing. But when it hits the saga for some reason I get the following error:

![screen shot 2016-06-14 at 5 20 40 pm](https://cloud.githubusercontent.com/assets/6789626/16064263/68a9f26e-3254-11e6-8250-d358ae3abe07.png)

Here is my saga code:

``` js
function* authorize(email, password) {
  // just returns a fake token for now
  const session = 'fake'
  yield console.log('in authorize');
  yield put({type: types.LOGIN_SUCCESS, session});
  return session;
}

function* loginFlow() {
  while (true) {
    const submit_action = yield take(types.LOGIN_SUBMITTED);
    const email = submit_action.payload.email;
    const password = submit_action.payload.password;
    yield console.log(email);
    const session = yield call(authorize, email, password);
    // After we're logged in, only thing we can do is log out
    // TODO: figure out what to actually do here?
    if (session) {
      yield take('LOGOUT')
    }

  }
}

export default function* rootSaga() {
  yield fork(loginFlow);
}
```

Also, here is my saga initialization code:

``` js
// saga initialization
const sagaMiddleware = createSagaMiddleware();
const store = applyMiddleware(sagaMiddleware)(createStore)(reducer);
sagaMiddleware.run(rootSaga).done.catch((error) => console.warn(error));
```

The exception seems to occur before the console.log(email) in loginFlow. I'm not really sure how this is happening. Any help on the issue would be appreciated.

**Comment by kuy** [comment]
Fix `yield console.log(email);` to `console.log(email);`. You can yield only redux-saga's effect objects.

**Comment by Baisang** [comment]
thanks - that gets me a little further along, but I still get the same "uncaught" error, but this time in authorize it seems. I'll try to keep looking into it.

**Comment by kuy** [comment]
Umm... I can't tell your clear hint but please try following (pseudo) code. In this code, I use Promise as a return value for dummy purpose. In real-world, you may use Fetch API and it return Promise object.

```es6
function authorize(email, password) {
  return new Promise((resolve, reject) => {
    const session = 'fake';
    console.log('in authorize');
    resolve(session);
  });
}

function* loginFlow() {
  while (true) {
    const submit_action = yield take(types.LOGIN_SUBMITTED);
    const email = submit_action.payload.email;
    const password = submit_action.payload.password;
    console.log(email);
    // Wait for auth
    const session = yield call(authorize, email, password);
    // Todo: Error handling to make sure success and failure of auth
    // Dispatch action (move from authorize function)
    yield put({type: types.LOGIN_SUCCESS, session});
    // After we're logged in, only thing we can do is log out
    // TODO: figure out what to actually do here?
    if (session) {
      yield take('LOGOUT')
    }
  }
}
```

**Comment by Baisang** [comment]
thanks for your help! the issue ended up being unrelated to the saga middleware. It was just a more generic exception that managed to bubble up all the way.

**Comment by rclai** [comment]
Is there any way to make these exception errors more helpful? There is no way to see where the error originates from.

**Comment by denizs** [comment]
@Baisang : 
Do you remember what caused the issue?
I'm facing the same problem
Best,
D

**Comment by Baisang** [comment]
@denizs , unfortunately I don't remember the specific issue, but I do remember that it was specific to my implementation.

I think one of the current issues with redux-saga is that, as rclai stated, no matter what kind of exception is raised each error will look exactly like that. Sometimes if you look carefully at the console output (i.e. on your xcode or whatever) you can find the actual Javascript exception that caused the red screen of death. Hope this can help in some way.

**Comment by denizs** [comment]
@Baisang thanks for your quick answer! After fiddling around I also found that the exception raised was specific to my implementation. I was trying to add an authorization header to my xhr calls by `api.headers["authorization] = token` in my apiAuth saga. 

However, I instantiated `api` as a `const` :-D
Basically a banal mistake caused by fatigue, I spent like 20 minutes before I noticed what was wrong.

**Comment by NajibRajak** [comment]
Hi, how are you?
I am facing similar to error. 
![simulator screen shot 22 dec 2016 21 12 14](https://cloud.githubusercontent.com/assets/23481840/21447574/56361e50-c88b-11e6-94a7-b0c169d62c7b.png)
my code is:
mport { take, call, put } from 'redux-saga/effects'
import Types from '../actions/ActionTypes'
import { loginSuccess, loginFailure } from '../actions/Creators'


export default (api) => {
  function * worker (authData) {
    const response = yield call(api.login, authData)
    if (response.ok) {
      if (response.data && response.data.status !== 'error') {
        yield put(loginSuccess(response.data))
      } else {
        yield put(loginFailure(response.data))
      }
    } else {
      yield put(loginFailure(response.data))
    }
  }

  function * watcher () {
    while (true) {
      const authData = yield take(Types.LOGIN_ATTEMPT)
      yield call(worker, authData.user)
    }
  }

  return {
    watcher,
    worker
  }
}

**Comment by Andarist** [comment]
Probably one of your dispatched actions `throw`, one of `loginSuccess`, `loginFailure`.

It may be in you reducer, I see there is a `replaceAtIndex` function in your call stack. Maybe it doesnt receive correct arguments? Try to wrap your actions in:
```javascript
try {
  // ... regular action code
} catch (e) {
  debugger
}
```
and your should find the mistake within minutes.

Hope you catch it!

**Comment by NajibRajak** [comment]
I found that. 
Thanks for your help.
Best wished and regards.

**Comment by simlmx** [comment]
For lack of a better solution, I simply wrap all my sagas in a `try`/`catch` block and `console.log` the error before re-throwing it in the `catch` clause.

**Comment by Andarist** [comment]
@simlmx 
Could you describe your exact problem more thouroghly? I would like to get rid of the pain points of our API, but do so I need to understand all concerns. Your feedback will be really much appreciated.

**Comment by simlmx** [comment]
Sure! So basically anytime there is a mistake in my code (for example using an undeclared variable), my (React Native) app will fail with the `'uncaught', 'at rootSaga \n at mySaga...` message others have posted a screenshot of.  As far as I can tell, that error message doesn't say much about what the actual problem is, but if I put a big `try`/`catch` around everything inside my failing saga (here "mySaga"), then I can print some helpful error message like `ReferenceError: Can't find variable: x`.

**Comment by granmoe** [comment]
Is there anything that can be done to address @rclai 's concern? Many of my co-workers have asked about this as well.

**Comment by Andarist** [comment]
Sure, there is always room for improvement. I'll start another issue, so people can point out the pain points in the lib regarding this.

**Comment by simlmx** [comment]
I found a better way than my `try/catch` everywhere. I forked redux-saga and changed this:
`https://github.com/redux-saga/redux-saga/blob/v0.14.3/src/internal/proc.js#L437`
by basically logging `error.message` on its own one line before. This way I get the stack AND the error message on an uncaught exception. I'd be happy to make a PR but I pretty much know nothing about `npm` and compiling the library with those simple changes modifies a lot the files under the `dist` folder, which doesn't sound right.

**Comment by saademou** [comment]
My dispatched actions are loginSuccess and loginFailure.

I put them in a separate file : loginActions.js

`import * as types from './actionTypes';

export function loginRequest(email, password) {
  return {
    type: types.LOGIN.REQUEST,
    email,
    password,
  }
}

export function loginSuccess({token, user}) {
  return {
    type: types.LOGIN.SUCCESS,
    token,
    user,
  }
}

export function loginFailure(err) {
  return {
    type: types.LOGIN.FAILURE,
    err,
  }
}

export function logout() {
  return {
    type: types.LOGOUT,
  }
}`

**Comment by AlastairTaft** [comment]
Is there any reason why errors are being caught internally instead of just failing and throwing?

**Comment by AlastairTaft** [comment]
Based off @simlmx's comment, I basically did the same thing but rather than forking I wrote a little script to monkey patch the code automatically every time you run `yarn install` or `npm install`.

If anyone wants to do the same thing, you need to add a `postinstall` script to your `package.json` like so
```js
"scripts": {
  "postinstall": "node monkeyPatchReduxSaga.js"
}
```

And then add the following code to a new file named`monkeyPatchReduxSaga.js` to your project root folder.

```js

var fs = require('fs')

var filepath = 'node_modules/redux-saga/lib/internal/proc.js',
  contents = fs.readFileSync(filepath, {encoding: 'utf8'})

var newCodeStr = addMonkeyPatchCode(contents)
fs.writeFileSync(filepath, newCodeStr)


function addMonkeyPatchCode(codeStr){

  var monkeyPatchCode = `/**
   * Redux Saga has been monkey patched here, see issue
   * https://github.com/redux-saga/redux-saga/issues/389
   */

  throw err

  `

  if (codeStr.indexOf(monkeyPatchCode) !== -1){
    // Code is already monkey patched, don't do anything
    return codeStr
  }

  var index = codeStr.indexOf(`log('error', 'uncaught at ' + name, message || err.message || err);`)
  if (index == -1)
    throw new Error(`Unable to monkey patch redux saga code, perhaps a new version of
      the package has been used. At the time of writing this monkey patch redux
      saga was at version 0.16.0.`.replace(/\s+/gi, ' '))

  return codeStr.slice(0, index) + monkeyPatchCode + codeStr.slice(index)
}

```

Now I can see the actual errors.

I'm not sure why the package is trying to handle errors itself, that's always an over-engineering red flag to me and makes me lose confidence using the package.

**Comment by Andarist** [comment]
@AlastairTaft 
> Is there any reason why errors are being caught internally instead of just failing and throwing?

This should no longer be the case with latest beta release.

**Comment by ahmad2smile** [comment]
For me it was not putting `https://` before my host url.
