### ISSUE TITLE
Handling saga IO from within callbacks

### ISSUE THREAD

**Issue by romseguy** [yelouafi/redux-saga#39]
Yielding a call to a function that is using a callback to run its post execution behavior: `yield apply(someObject, someFunction)`

Seems I can't yield `put` from `someFunction` since the callback isn't a generator. How can I dispatch an action from that callback?

**Comment by yelouafi** [comment]
There is a `cps` effect that works with node style callbacks (err, res). But for now only works with non method functions (or strongly bound functions) [I'll have to fix that]

```javascript
const result = yield cps(func)
yield put(myAction(result))
```

Another solution is to *promisify* your method and use it with `call` instead of `cps`

```javascript
function promisifiedFn(...args) {
  return new Promise( (resolve, reject) => {
    obj.method(...args,  (err, res) => err ? reject(err) : resolve(res)
  }
}

**Comment by romseguy** [comment]
Thank you! Looking forward to the `apply` version of `cps`.

Is it okay to listen for DOM events like this?

```javascript
const waitForEvent = (el, type) => new Promise(resolve => el.addEventListener(type, event => resolve(event)))

function* listenToClick() {
  while (true) {
    const el = document.querySelector('.some-class')
    
    const event = yield call(waitForEvent, 'click')
    yield put(someActionCreator(event))
  }
}
```

**Comment by romseguy** [comment]
Just noticed 0.5.0 is out with improved `cps` and it works fine for this issue's original use case, but I haven't managed to use it to wait for a DOM event, I get `listenToClick: uncaught MouseEvent`:

```javascript
function* listenToClick() {
  while (true) {
    const el = document.querySelector('.some-class')

    const event = yield cps([el, el.addEventListener], 'click')
    yield put(someActionCreator(event))
  }
}
```

**Comment by yelouafi** [comment]
addEventListener calls its callback with the event as a first parameter. cps's callback is called with the event as a first argument by addEventListener, since cps expects an error first argument. it treats the event as an error.

I'd opt for your first solution but would remove the event listener after the promise is resolved

```javascript
const waitForEvent = (elm, eventType) => {
  return new Promise(resolve => {
    const cb = e => {
      resolve(e)
      elm.removeEventListener(eventType, cb)
    }
    elm.addEventListener(eventType, cb)
  })
}
```

**Comment by romseguy** [comment]
Alright, thanks for the tips :+1:

**Comment by floydwch** [comment]
Hi @yelouafi !

Thanks for your awesome work, but I have a question here: how to remove listeners in the automatically canceled race effects?
