### ISSUE TITLE
Usage with global exception handler

### ISSUE THREAD

**Issue by jonaskello** [yelouafi/redux-saga#391]
I'm using [zonejs](https://github.com/angular/zone.js/) to install a global exception handler that I want to catch all uncaught exceptions in my application (including async exceptions). It works fine for all but exceptions that happens in my sagas. I've been trying to troubleshoot this and It seems that redux-saga catches exceptions, logs them and then does nothing more. If my understanding of what happens in redux-saga is correct it means the exceptions are swallowed by redux-saga and never reaches the global exception handler. 

If the above is actually what happens, I am wondering if there is a rationale behind swallowing the exceptions in the sagas or if it can be changes to they are re-thrown so we can catch them at a higher level?

**Comment by yelouafi** [comment]
You can catch uncaught exceptions from your root Saga

```js
const rootTask = sagaMiddleware.run(rootSaga)
rootTask.done.catch(...)
```

**Comment by yelouafi** [comment]
But note that the method above works more as a crash reporting mechanism. i.e. when the error reaches that level, all sagas in the way are already cancelled.

**Comment by jonaskello** [comment]
Ok, I'll try using that hook. Will it catch all errors including async errors?

**Comment by yelouafi** [comment]
yes. all errors that are raised inside sagas are trapped

**Comment by jonaskello** [comment]
Ok, thanks!

**Comment by tadas-subonis** [comment]
@yelouafi this should be in the docs :-) :
```
const rootTask = sagaMiddleware.run(rootSaga);
rootTask.done.catch(function (err) {
    console.log("Error in Sagas", err);
});
```

**Comment by slorber** [comment]
@yelouafi also we often see people using a single root saga starting other sagas with fork, call array or something similar

I'm not sure it's a good idea to let people use redux-saga this way because a single uncatched error anywhere will make all the sagas cancelled, leading sometimes to the app becoming unusable. We all know it's quite annoying when this happens (see error boundaries in React) so it may be worth advocating for a clever isolation of sagas inside of a single top-level saga

**Comment by madebyherzblut** [comment]
@slorber is there already a gist/example where I can see this isolation in action?

**Comment by slorber** [comment]
@madebyherzblut use spawn instead of fork/call, or run multiple times `runSaga` method

**Comment by madebyherzblut** [comment]
Ah, thank you! I didn't know that I can run `runSaga` more than once.
