### ISSUE TITLE
RegEx in Sagas

### ISSUE THREAD

**Issue by lukaszszymanski** [yelouafi/redux-saga#392]
Hi,
is it possible to use RegEx patterns in sagas, example
instead of 
```
while(true) {
    const action = take(['FETCH_USERS', 'FETCH_OTHER_DATA'])
    yield put(startLoadingIndicator(action))
}
```
use regex pattern

```
while(true) {
     const action = take(/^FETCH_/ig)
     yield put(startLoadingIndicator(action))
}
```

**Comment by kuy** [comment]
`take` effect doesn't support RegExp as `pattern` argument, but you can write a custom effect.

Demo: http://kuy.github.io/redux-saga-examples/takex.html
GitHub: https://github.com/kuy/redux-saga-examples/tree/master/takex

```es6
function* takexSaga(pattern) {
  let action;
  while (true) {
    action = yield take('*');
    console.log('takex', action.type);
    if (pattern.test(action.type)) {
      console.log('takex:match', action.type);
      break;
    }
    console.log('takex:ignore', action.type);
  }
  return action;
}

function takex(pattern) {
  return call(takexSaga, pattern);
}

function* handleActions() {
  while (true) {
    const action = yield takex(/^FETCH_/);
    console.log('handle', action.type);
  }
}
```

**Comment by lukaszszymanski** [comment]
That will do it, thanks!

**Comment by lukehedger** [comment]
For anyone that lands here, this can actually be achieved simply using [`take(pattern)`](https://yelouafi.github.io/redux-saga/docs/api/index.html#takepattern) (also works with `takeLatest`, `takeEvery`):

```
yield takeLatest( action => /^FETCH_/.test(action.type), anotherSaga)
```

**Comment by pwharff** [comment]
The link above reports a 404. Here is a link to the official Redux Saga docs for [https://redux-saga.js.org/docs/api/#takepattern](take(pattern))
