### ISSUE TITLE
[question] How can I create a component using saga and export it as a package

### ISSUE THREAD

**Issue by sibelius** [yelouafi/redux-saga#394]
How can I create a component (like a react-redux-saga-messenger) using redux and redux-saga and create a npm package that can be installed by other apps?

in the main app I want something like this

`npm install react-redux-saga-messenger --save`

```jsx
import Messenger from 'react-redux-saga-messenger';

class App extends Component {
   render() {
       <Provider store={store}>
             <Messenger />
       </Provider>
   }
}
```

**Comment by kuy** [comment]
In your 'react-redux-saga-messenger', use default export to `<Messenger />` component and named export to saga. In the host application, you also need `fork` messenger's saga in the root saga like this.

```es6
import { messenger } from 'react-redux-saga-messenger';

export default function rootSaga() {
  yield fork(yourSaga);
  yield fork(messenger);
}
```

**Comment by kuy** [comment]
@sibelius [We recommend](https://github.com/yelouafi/redux-saga/issues/378) you to ask a question on [StackOverflow](http://stackoverflow.com/questions/tagged/redux-saga) with **redux-saga** tag.

**Comment by sibelius** [comment]
@kuy what happens if I want to add two of these messengers components ? Their actions will conflict with each other right?

**Comment by kuy** [comment]
@sibelius Even if you have one or more Messenger components, messenger's saga is always needed one. So you don't need to worry about the conflict. Why? It's similar to Redux's reducers. When you have 10 tooltip components, do you need 10 reducers? The answer is No. All actions from tooltips are processed in one reducer because all tooltip components have the same business logic.

**Comment by yelouafi** [comment]
@sibelius please note that questions should be posted on SO. this is to keep the issues repo. focused on bugs & proposals.

**Comment by sibelius** [comment]
ok, I will post on SO

**Comment by sibelius** [comment]
I've found this package that solves this problem: https://github.com/threepointone/react-redux-saga
