### ISSUE TITLE
[question/clarification] Starting root sagas

### ISSUE THREAD

**Issue by peter-perot** [yelouafi/redux-saga#395]
I'm just trying to figure out how to start a root saga the correct way.

In your beginner tutorial (http://yelouafi.github.io/redux-saga/docs/introduction/BeginnerTutorial.html) you start the root saga this way:

````javascript
// single entry point to start all Sagas at once
export default function* rootSaga() {
  yield [
    helloSaga(),
    watchIncrementAsync()
  ]
}
````

But in the most examples (like https://github.com/yelouafi/redux-saga/blob/master/examples/shopping-cart/src/sagas/index.js) you start it this way:

````javascript
export default function* root() {
  yield [
    fork(getAllProducts),
    fork(watchGetProducts),
    fork(watchCheckout)
  ]
}
````

See also https://github.com/yelouafi/redux-saga/issues/276 and https://github.com/yelouafi/redux-saga/issues/171.

My first idea was that variant 1 starts the second saga in the array when the first is completed, but you explicitly say that this is not the case:

> We're yielding an array with the results of the calls to the 2 sagas. This means the 2 resulting Generators will be started in parallel.

So what's the difference? I did not find any hint in the docs, but maybe I overlooked something.

**Comment by peter-perot** [comment]
I have been digging deeper into the discussion, and **I found my question answered here:** https://github.com/yelouafi/redux-saga/issues/160#issuecomment-190307098

Anyway it would be nice to put this clarification into the tutorial/docs since it's confusing for a beginner if the code in the tutorial uses another technique as the code in the sample projects.

**Comment by ms88privat** [comment]
What about this? Sometimes my App runs into issues, which is leading into a complete App crash because all my sagas will be canceled when I start them with fork.

```js
export default function* root() {
  yield [
    spawn(getAllProducts),
    spawn(watchGetProducts),
    spawn(watchCheckout)
  ]
}
```

@yelouafi which affect performance more? spawn or fork? Which ist better for the performance / memory of the App?

**Comment by slorber** [comment]
@ms88privat I think it's the same and the only difference is spawn is detached

**Comment by yelouafi** [comment]
see http://yelouafi.github.io/redux-saga/docs/basics/UsingSagaHelpers.html. At the bottom there is an example on how to start mulitple watchers

**Comment by smashercosmo** [comment]
Starting rootSaga is still a big source of confusion to me. I asked a question about it on stackoverflow. http://stackoverflow.com/questions/39438005/what-is-the-idiomatic-way-of-starting-rootsaga. Would really appreciate, if someone gives a thorough answer.
