### ISSUE TITLE
Error when emitting null in eventChannel

### ISSUE THREAD

**Issue by Moeriki** [yelouafi/redux-saga#396]
**Note:** `onFirebaseAuthStateChange` is an event emitter from Firebase. Emits a user object when a user signed on. Emits `null` when user signed out.

This logs an error.
```javascript
const firebaseAuthStateChangeChannel = () =>
  eventChannel((emit) => {
    onFirebaseAuthStateChange((user) => {
      emit(user)
    })
  })

export function* authWatch() {
  const userChannel = yield call(firebaseAuthStateChangeChannel)
  while (true) {
    const user = yield take(userChannel)
    if (user == null) {
      yield put(userLost(user))
    } else {
      yield put(userFound(user))
    }
  }
}
```

```
utils.js:188 uncaught at check Saga was provided with an undefined action
Hints:
    - check that your Action Creator returns a non-undefined value
    - if the Saga was started using runSaga, check that your subscribe source provides the action to its listeners
```

This works fine.
```javascript
const firebaseAuthStateChangeChannel = () =>
  eventChannel((emit) => {
    onFirebaseAuthStateChange((user) => {
      emit(user || 'null')
    })
  })

export function* authWatch() {
  const userChannel = yield call(firebaseAuthStateChangeChannel)
  while (true) {
    const user = yield take(userChannel)
    if (user === 'null') {
      yield put(userLost(user))
    } else {
      yield put(userFound(user))
    }
  }
}
```

I see how the error could be related. But I'm just wondering if this is intended design, and is there another way around this?

Thanks.

**Comment by Moeriki** [comment]
On second thought. The channels should feed back a result much like an action creator does.

Turning the code into `emit({ user })` makes perfect sense then.

**Comment by kuy** [comment]
@Moeriki Yes, it's a good workaround. I also use the same approach in [my exmaple](https://github.com/kuy/redux-saga-examples/blob/master/microblog/firebase.js#L10).

**Comment by yelouafi** [comment]
@Moeriki yes. As you said it's by design to keep things consistent with Redux actions.
