### ISSUE TITLE
Suspend execution of Effects

### ISSUE THREAD

**Issue by rybon** [yelouafi/redux-saga#399]
According to the documentation, the `yield` statements return descriptor objects, that are then processed by the middleware to perform the actual invocation of the side effects. Is there a way to suspend this processing? For example, when doing time-travel debugging?
Ideally, I'd want to store a boolean in the store indicating whether side effects should be performed or not. Then, I'd use that value to guard the processing of the descriptor objects. How can this be accomplished? Will there be a hook in `proc` for that?

**Comment by yelouafi** [comment]
Not sure what exactly the kind of behavior you are looking for : does resuming the execution execute all suspended effects or just should ignore them? Also to do hot relaod with time-travel you need to replay all the Sagas from the beginning. I don't see how just suspending the Effects would permit us to do time travel.

**Comment by rybon** [comment]
It would just ignore them. Basically I want to keep the sagas running, but just no-op the processing. I'm fine with just replaying the store dispatches. The replayed dispatches would still flow through the sagas, but the effects would never actually be executed.

My goal is to introduce an `if` guard in just one place (middleware) to no-op all side effects in the entire app. This would complicate hot reloading and time travelling the sagas themselves, but I'm fine with that for now until #5 and #22 resolve to a better way forward.

**Comment by yelouafi** [comment]
A possible way is to 'embed' the saga middleware itself in another middleware that will manage the pause/resume mechanism. This would also be a generic solution as you can apply it to any other middleware


A snippet (untested)

```js
function pauseResumeMiddleware(middlewre) {
  let paused = false
  return store => next => 
    let delegate = middleware(store)(next)

    return action => {
      if(action.type === 'PAUSE')
         paused = true
      else if(action.type === 'RESUME')
         paused = false

      if(paused)
        return next(action) // skip if paused
      else
        return delegate(action)
    }
  };
}

**Comment by rybon** [comment]
Sure, that could work.

I was actually looking into using the `monitor` option and adding a method to act as a hook in `runEffect`. In there, the very first thing we could do is call this `monitor` method to verify whether we should proceed with running the effect. Basically similar to `monitor && monitor.effectTriggered`, but wrapped in an `if` with a `return;` to act as a guard. Thoughts?

**Comment by yelouafi** [comment]
This will be more complicated b/c there maybe sagas in the middle of a blocking effect (API call, channel's take, a put waiting in a promise, a join); and also effects can be nested inside composite race/parallel effects.

**Comment by rybon** [comment]
True, if the application is in an 'unstable' state (in the middle of doing something) then this will not work properly. I haven't yet seen a solution that mitigates this problem though. I'd rather start with something less ideal and work towards a better solution.

**Comment by yelouafi** [comment]
see in #410
