### ISSUE TITLE
Unhandled promise rejection TypeError: Cannot read property 'response' of undefined

### ISSUE THREAD

**Issue by iam-peekay** [yelouafi/redux-saga#40]
Hi. I'm having a lot of trouble trying to incorporate facebook login and using sagas to do it. In my sagas, I have:
```
function* loginUser(username) {
  yield put(actions.loginUser.request(username));
  const { response, error } = yield call(api.loginUser, username);
  if (!error) {
    yield put(actions.loginUser.success(username, response));
  } else {
    yield put(actions.loginUser.failure(username, response));
  }
}
```

and then my async call looks like: 
```
function loginUser(username) {
  fetch('/auth/facebook')
    .then(function (response) {
      if (response.status >= 400) {
        throw new Error('Bad response from server');
      }
      return response;
    })
    .then(
      response => ({ response }),
      error => ({ error: error.message || 'Something shitty happened' })
    );
}
```

However, I keep getting a promise rejection error. The line ```const { response, error } = yield call(api.loginUser, username);``` is where it throws. I know that the response is coming back because i console.log it and it's there. But for some reason, the yield call is not able to read the response. 

Would you happen to know if I'm doing anything wrong?

**Comment by yelouafi** [comment]
Isn't a `return` statement missed in your `loginUser` function ?

**Comment by iam-peekay** [comment]
@yelouafi yes, it is. thank you for getting back so quickly.

**Comment by d7laungani** [comment]
Where is the return statement missing and what should it be? I am having this exact same issue. Thanks!

**Comment by Andarist** [comment]
just before the `fetch`, function `loginUser` creates a `Promise` (by using `fetch`) but it doesnt return it to the caller
