### ISSUE TITLE
runSaga doesn't signal Error when subscribe param return a non-function to unsubscribe

### ISSUE THREAD

**Issue by sergej-s** [yelouafi/redux-saga#401]
Hello! 
I try to run the next code on node 6.2.1. It logs 1, 2, and then stuck. I cannot undestand why it doesn't continue execution to the line take('TEST')... Can anyone help me please?

```
const {runSaga, delay} = require('redux-saga');
const {take, put, call} = require('redux-saga/effects');

function* anotherSaga() {
  yield delay(1000);
  console.log(2);
}

function* rootSaga() {
  while(true) {
    console.log(1);
    yield call(anotherSaga);
    console.log(3);
    const action = yield take('TEST');
    console.log(4);
    yield put(action);
  }
}

runSaga(
  rootSaga(),
  {
    subscribe(callback) {
      return setInterval(() => (callback({type: 'TEST'})), 1000);
    },
    dispatch(action) {
      console.log(action);
    },
    getState() {}
  }
);
```

**Comment by kuy** [comment]
@sergej-s  [We recommend](https://github.com/yelouafi/redux-saga/issues/378) you to ask on [StackOverflow](http://stackoverflow.com/questions/tagged/redux-saga) with **redux-saga** tag.

Unfortunately, `delay` is not a redux-saga's effect, just [a function that returns Promise object](http://yelouafi.github.io/redux-saga/docs/api/index.html#delayms-val). So you need to use `call` effect in `anotherSaga` generator function.

```
function* anotherSaga() {
  yield call(delay, 1000);
  console.log(2);
}
```

**Comment by sergej-s** [comment]
@kuy Thank you for reply. I've recreated question on StackOverflow 
[](http://stackoverflow.com/questions/37961873/redux-saga-is-stuck-on-yield-call)

I tried to replaced delay to call(delay, 1000), but it doesn't help. Still stuck after console.log(2). It seems that control isn't returned to rootSaga.

**Comment by yelouafi** [comment]
@sergej-s The problem is in the `subscribe` function

```js
subscribe(callback) {
  return setInterval(() => (callback({type: 'TEST'})), 1000);
}
```

the function should return an unsubscribe function, in your case you're just returning the interval `id`. The middleware was trying to call unsubscribe (a non function) which results in an error. The error of course was not signaled. This is an issue of redux-saga which must be fixed.

Note that simply returning a `clearInterval` in your example wont work either because the subscribe function must be multicast: it's shared between multiple Sagas, each Saga subscribes when started and unsubscribe when finished. So if you just return clearInterval, the first terminated Saga will call unsubscribe causing the interval to be stopped for all other Sagas

Here is a simplified example that works

```js
function createEmitter() {
  const listeners = []

  return {
    subscribe(l) {
      listeners.push(l)
      return () => {
        const idx = listeners.indexOf(l)
        if(idx >= 0)
          listeners.splice(idx, 1)
      }
    },

    emit(action) {
      listeners.forEach(l => l(action))
    }
  }
}

//... inchanged

const {subscribe, emit} = createEmitter ()
setInterval(() => emit({type: 'TEST'}), 1000);
rs.runSaga(
  rootSaga(),
  {
    subscribe,
    dispatch(action) {
      console.log(action);
    },
    getState() {}
  }
);
```

**Comment by sergej-s** [comment]
@yelouafi Thanks a lot for explanation!
Is it possible to run saga engine without setup a subscribe function? I'd like to use serveral sagas with eventChannels and channel communication between them. So there is no need to subscribe some main event source.

**Comment by yelouafi** [comment]
yes. you just pass noop functions for unused params

```js
const noop = () => {}
function runSagaEx(generator) {
  return runSaga(generator, {
    subscribe: () => noop,
    dispatch: noop,
    getState: noop,
  })
}

runSagaEx(rootSaga())
```

I should perhaps add support for this into the lib
