### ISSUE TITLE
Best Practice For Waiting On Async Actions In Sagas

### ISSUE THREAD

**Issue by git-blame** [yelouafi/redux-saga#403]
If I have an action as follows:
```javascript
export function someAsyncStuff() {
  return {
    types: [
      STUFF_PENDING,
      STUFF_FULFILLED,
      STUFF_REJECTED,
    ],
    payload: {
      promise: /* Some REST API call */,
    },
  };
}
```
Using ```yield put(someAsyncStuff)``` works OK. The action gets dispatched, etc. Most of the time I just continue and do other things. But sometimes there is an action that I need to wait to finish. Looking at the saga doc, I noticed that ```call()``` will block until a promise resolves and in the above case, ```put()``` returns a *Promise*. So I implement something like this so that the promise is given to ```call```:
```javascript
function *waitOnAction(action) {
  yield call((promise)=>promise, yield put(action()));
}

function* backgroundTask() {
  while (true) {
    try {
      /* do stuff */
      yield waitOnAction(someAsyncStuff);
      /* do other stuff */
    } catch (error) {
      // wait on error?
     yield call(delay, 5000);
    }
  }
}
```
This "doing async in a declarative/synchronous" looks nicely familiar to me from similarities in other areas. For example, yielding on a Future in python's Tornado framework. But I couldn't find any recommendations or examples in the Saga tutorials and docs on best practice for this kind of problem.

The closest I can think of is to use ```select()``` on a state attribute or ```take()``` on a known event/action after calling the ```put```. But I have some concerns:
* To be honest, I'm new to React and saga and I can't seem to get ```select``` to wait on an attribute.
* In theory, if the action completes quickly, ```select``` or ```take``` could miss the relevant event?
* Similarly, if the reducer doesn't update the associated attribute on *Promise.reject*, ```select``` could block forever?
* I have to know something about the action (i.e., what are its actions, what its reducer will update)

As I said, the combination of ```put``` and ```call``` for waiting on async actions seems pretty straightforward. But I wanted to ask if there are recommended or better ways to solve this?

**Comment by git-blame** [comment]
Looking through the saga code, it looks like you can force ```put``` to wait on a *Promise* if you call ```put.sync``` instead. But I don't know how official this is:

https://github.com/yelouafi/redux-saga/blob/master/src/internal/io.js
```javascript
put.sync = (...args) => {
  const eff = put(...args)
  eff[PUT].sync = true
  return eff
}
```

**Comment by yelouafi** [comment]
Although docs are not update yet, `put.sync` is a public API https://github.com/yelouafi/redux-saga/releases/tag/v0.10.5.

**Comment by git-blame** [comment]
Great.

**Comment by git-blame** [comment]
For completeness, if you are waiting on a *Promise* returned by an action that has been *dispatch* (like my *someAsyncStuff* example) and the Promise fails, you will get back a redux-action like what a reducer sees with its *error* property set. So if you are waiting to *catch* a rejected Promise, it won't happen. You need something like:

```javascript
function* waitOnAction(action, ...args) {
  const result = yield put.sync(action(...args));
  // if it is from a redux-action, we get an object with error set not a thrown error
  if (result !== undefined) {
    const { error } = result;
    if (error) {
      throw result;
    }
  }
  return result;
}
```

**Comment by gustavms** [comment]
https://redux-saga.github.io/redux-saga/docs/advanced/RacingEffects.html Read it carefully and in 10 hours you will have clear concepts. In your example you are missing Take and fork to handle it elegantly

**Comment by git-blame** [comment]
Thanks for the link. I'm well-aware of these options. I use `race` and `take` in other places. They do not apply here. For one thing, `take` cannot be used with a Promise. Forking a saga means you still need some mechanism within that saga to wait until that Promise is done.

The simplest way is to use `put.sync` as mentioned (and possibly the `await` operator).
