### ISSUE TITLE
Using Meteor.js methods with saga

### ISSUE THREAD

**Issue by kefirchik** [yelouafi/redux-saga#404]
Can anybody suggest how can I use server side methods with saga in Meteor.js?

With redux thunk I have something like this in action:
```
import {saveTicket} from '/lib/methods/methods';

export const USER_SAVED_TICKET = 'USER_SAVED_TICKET';
export function userSavedTicket(content) {
  return (dispatch, getState) => {
    saveTicket.call(content, (error, result) => {
      if (error) {
        dispatch(ticketSaveFailed(error.reason));
      } else {
        dispatch(ticketSaveSucceeded());
      }
    });
  }
}

export const TICKET_SAVE_SUCCEEDED = 'TICKET_SAVE_SUCCEEDED';
export function ticketSaveSucceeded() {
  return {
    type: TICKET_SAVE_SUCCEEDED,
  }
}

export const TICKET_SAVE_FAILED = 'TICKET_SAVE_FAILED';
export function ticketSaveFailed(errorReason) {
  return {
    type: TICKET_SAVE_FAILED,
    errorReason,
  }
}
```

my saga is:
```
import { take, put, call, fork, select } from 'redux-saga/effects';
import {saveTicket} from '/lib/methods/methods';

export default function *ticketSaved() {
  const { ticket } = yield take({ type: 'USER_SAVED_TICKET_SAGA' });
  const { err, res } = yield call(saveTicket.call, ticket);

  if (err) {
    yield put({ type: 'TICKET_SAVE_SUCCEEDED' }, err)
  } else {
    yield put({ type: 'TICKET_SAVE_FAILED' }, res)
  }
}
```
but it doesn't work... I can't figure out how to call this method :worried: 

and action:
```
export const USER_SAVED_TICKET_SAGA = 'USER_SAVED_TICKET_SAGA';
export function userSavedTicketSaga(content) {
  console.log("#userSavedTicketSaga action runned");
  return {
    type: USER_SAVED_TICKET_SAGA,
    content,
  }
}
```

**Comment by kuy** [comment]
@kefirchik [We recommend](https://github.com/yelouafi/redux-saga/issues/378) you to ask on [StackOverflow](http://stackoverflow.com/questions/tagged/redux-saga) with **redux-saga** tag.

In this line, `call` effect won't wait for a callback of `saveTicket` function.

```es6
const { err, res } = yield call(saveTicket.call, ticket);
```

Please consider using [`eventChannel`](http://yelouafi.github.io/redux-saga/docs/api/index.html#channelbuffer) to handle a callback of `saveTicket` function properly.
`eventChannel` is often used integrating saga with external services that have a callback/event-based API.
For example, the following code is an example of using Page Visibility API of web browsers with redux-saga.
https://github.com/kuy/redux-saga-examples/blob/master/startstop/sagas.js#L49

Demo: http://kuy.github.io/redux-saga-examples/startstop.html
GitHub: https://github.com/kuy/redux-saga-examples/tree/master/startstop
