### ISSUE TITLE
Is It Possible To Wait on a Canceled Task?

### ISSUE THREAD

**Issue by git-blame** [yelouafi/redux-saga#408]
I would like to cancel a subtask from the parent. The subtask does some clean-up and then exits. I would like to always wait for a subtask finish. However, the only option I can find, the *join* effect would also cancel the parent as well. Are there other ways for the parent to wait. Do I have to coordinate *put/take* some custom event?

```javascript
function* subTask() {
  try {
    run something for a while;
  } finally {
    if (yield cancelled()) { ... }
  }
}

function* mainTask() {
  while (true) {
    s = yield fork(subTask);
    run something;
    if (somethingWrong) {
      yield cancel(s); // <== early stop
    }
    yield join(s); // <==== work normally but will not work if subtask cancelled
  }
}
```

**Comment by yelouafi** [comment]
>Do I have to coordinate put/take some custom event?

Yes, once a task has been cancelled. The only way to communicate with it is through take/put. In your case I'd recommend to setup  an action channel to avoid race conditions

```js
function* subTask() {
  try {
    run something for a while;
  } finally {
    if (yield cancelled()) { 
      ... 
      yield put({type: 'CANCEL_DONE',...})
    }
  }
}

function* mainTask() {
  const cancelDoneChan = yield actionChannel('CANCEL_DONE')
  while (true) {
    s = yield fork(subTask);
    run something;
    if (somethingWrong) {
      yield cancel(s); // <== early stop
    }
    yield take(cancelDoneChan);
  }
}
```

**Comment by git-blame** [comment]
actionChannel dispatches action through the store. If I want to limit it just within sagas, I assume the same functionality can be done with "directly created" channels?

**Comment by yelouafi** [comment]
yes. can pass a channel to forked tasks as a param
