### ISSUE TITLE
eventChannel Emitter Does Not Return Until Receiver Blocks?

### ISSUE THREAD

**Issue by git-blame** [yelouafi/redux-saga#409]
I'm using an *eventChannel*, when I put *console.log* around the emitter, I noticed that the second one is not reached until the channel receiver calls something that blocks. Is this by design?

```javascript
...
eventChannel(... {
console.log('Emitting');
emitter({ type: SOME_EVENT});
console.log('Done emitting');
...
}
...
function* someTask() {
  event = yield take(channel);
  yield put(event);
  yield lots_of_other_stuff;
  yield take(channel) // or yield call(delay, ...)  <== log 'Done emitting' doesn't happen until here
```

**Comment by yelouafi** [comment]
yes; because event channels are implemented using continuation callbacks, the receiver's code is executed inside the stack frame of `emitter`. This means any non-blocking effects in the receiver will be executed before returning

**Comment by git-blame** [comment]
Is there a blocking effect that does nothing and is only meant to yield execution to other generators, or in this case let emitter finish? For example, in python's Tornado framework, it would be *yield gen.moment*.

I suppose I can simply issue a very short delay such as *yield call(delay, 10)*?

**Comment by yelouafi** [comment]
You can simply yield to a Promise.resolve() which is more performant 

```js
function nextTick() {
  return Promise.resolve()
}

function* saga() {
  yield call(nexTick)
}
```
