### ISSUE TITLE
Custom effects

### ISSUE THREAD

**Issue by christian-schulze** [yelouafi/redux-saga#414]
Is it possible/recommended to create custom effects?

My team was throwing around the idea, and on looking at the existing effects in `src/internal/io.js` it looks like this wasn't really intended.

What do you think?

**Comment by MattKunze** [comment]
I had similar thoughts a while back, but I haven't been able to come up with any concrete use cases for it yet. It seems like it might be useful as a dependency injection mechanism to isolate sagas from runtime instances that aren't necessarily available through the store.

But I have [yet] come up with a scenario that isn't handled through `call`, it would be interesting to hear what other's have come across.

**Comment by yelouafi** [comment]
I considered this idea when starting the lib. But as @MattKunze didn't think of use cases for it.

IMO it may be also more confusing. The semantics of a few effects (call, put, ...) if well understood make the code immediately understandable; With custom effects however, this may create another level of inderiction b/c the reader has to also understand the semantics of the custom operator (which may denote a call to a function)

**Comment by christian-schulze** [comment]
Thank you for your responses @MattKunze and @yelouafi.

For our specific use case, we have a function called `followLink`, which given a url, will expect a well defined JSON document in return. The JSON document has an embedded status, which `followLink` will use to retry (with exponential back-off and max retries) until either `error` or `ready` is returned.

We use `followLink` extensively in most of our Saga's hence why we were enquiring about custom effects. I guess in this scenario, `followLink` is a more specialised form of `call`.

**Comment by yelouafi** [comment]
>I guess in this scenario, followLink is a more specialised form of call.

Exact. You can create an effect creator which builds the specialized call effect.

For example

```js

// Saga to handle the effect logic
function* followLinkSaga(url) {
   yield call(fetch, url)
   //... retry logic
}

// Effect creator
function followLink(url) {
  return call(followLinkSaga, url)
}

// Use it like other effects
function* saga() {
   const {url} = yield take(ACTION)
   yield followLink(url)
}
```

**Comment by christian-schulze** [comment]
This is excellent advice, and a very simple refactor to existing code. Will take this idea for a spin tomorrow, but please consider this issue solved 👍
