### ISSUE TITLE
Ducks + sagas

### ISSUE THREAD

**Issue by LopatkinEvgeniy** [yelouafi/redux-saga#420]
I use ducks [modules](https://github.com/erikras/ducks-modular-redux) i my projects. I think that sagas must be a part of ducks module. But there is a problem with watchers-sagas that we must run. I write lite saga-manager class, which help me to create root saga. Its usage looks like this:

```
/* 
* auth module
*/

// reducer, actions....

// sagas
function *fetchAuthSaga () { ... }
function *loginSaga () { ... }
function *logoutSaga () { ... }

sagasManager.addSagaToRoot(function *watcher() {
  yield [
    takeEvery(FETCH, fetchAuthSaga),
    takeEvery(LOGOUT, logoutSaga),
    takeEvery(LOGIN, loginSaga),
  ];
});
```
I do the same things in all modules with sagas. Then i just run root saga:

```
// index.js
const store = configureStore();

store.runSaga(sagasManager.getRootSaga());
```

I think that sagasManager is missing part of redux-saga library even if you dont use ducks modules. In a large project there are a lot of sagas in separate files.

Here my implementation of sagasManager:

```
import { fork } from 'redux-saga/effects';

class SagasManager {
  constructor() {
    this.sagasWithArguments = [];
  }

  addSagaToRoot(...sagaWithArguments) {
    this.sagasWithArguments.push([...sagaWithArguments]);
  }

  getRootSaga() {
    const self = this;

    return function *rootSaga() {
      yield self.sagasWithArguments.map((sagaWithArguments) => fork(...sagaWithArguments));
    };
  }
}

export default new SagasManager;
```

PS: Sorry my poor English

**Comment by yelouafi** [comment]
It maybe suitable as part of a framework or a boilerplate based on the ducks pattern. But I dont think this should be part of the core lib.

**Comment by kamleshchandnani** [comment]
When doing code splitting how would you handle this? I am already facing issue. before code splitting everything was running smooth the code 
`sagasManager.addSagaToRoot(function *watcher() {
  yield [
    takeEvery(FETCH, fetchAuthSaga),
    takeEvery(LOGOUT, logoutSaga),
    takeEvery(LOGIN, loginSaga),
  ];
});
`
runs fine but as soon I created split bundles this doesn't registers watcher. Any clue?

**Comment by Andarist** [comment]
@kamleshchandnani 
just use this in ur split bundle
```js
sagaMiddleware.run(function *watcher() {
  yield [
    takeEvery(FETCH, fetchAuthSaga),
    takeEvery(LOGOUT, logoutSaga),
    takeEvery(LOGIN, loginSaga),
  ];
})
```

or depending on how much involved in this `sagasManager` you are you may need to tweak it a little bit. i.e. like this:
```js
import { all, flush, fork, take } from 'redux-saga/effects';
import { channel } from 'redux-saga';

class SagasManager {
  constructor() {
    this.sagasWithArguments = channel();
  }

  addSagaToRoot(...sagaWithArguments) {
    this.sagasWithArguments.put([...sagaWithArguments]);
  }

  getRootSaga() {
    const sagasChannel = this.sagasWithArguments;

    return function *rootSaga() {
      const initialSagas = yield flush(sagasChannel);
      yield all(initialSagas.map((initialSagaWithArguments) => fork(...initialSagaWithArguments)));
      
      while (true) {
        const dynamicSaga = yield take(sagasChannel)
        yield fork(...dynamicSaga)
      }
    };
  }
}

export default new SagasManager;
```

**Comment by kamleshchandnani** [comment]
But if I do
```
sagaMiddleware.run(function *watcher() {
  yield all([
    takeEvery(FETCH, fetchAuthSaga),
    takeEvery(LOGOUT, logoutSaga),
    takeEvery(LOGIN, loginSaga),
  ]);
})
```
Then I have to export each and everything from all the bundles and import it where I am initializing this isn't it? So the ducks pattern goes for a toss?

**Comment by Andarist** [comment]
Then the second option is (tweaked manager) is what you need

**Comment by kamleshchandnani** [comment]
![anc](https://user-images.githubusercontent.com/11384858/27253626-d33a8234-5395-11e7-859b-423f673b9375.png)

I just tweaked sagas manager as you mentioned. Rest everything remains same as per @LopatkinEvgeniy  pattern

**Comment by Andarist** [comment]
Inspect with a debugger this line `const initialSagas = yield flush(sagasChannel);` - somehow `sagasChannel` is referencing `loginSaga` (or some similar one), when it should be a channel's instance. Should be easily fixable - I've written this tweaked code in a rush and ofc didnt test it properly.

**Comment by kamleshchandnani** [comment]
@Andarist
But why we have to write this tweaked code? And what is this channel all about? twitter DM?

**Comment by Andarist** [comment]
I've DMed u on twitter :)
