### ISSUE TITLE
put effect causes re-render error

### ISSUE THREAD

**Issue by pke** [yelouafi/redux-saga#427]
I have this Protected HOC. Its purpose is to only render its WrappedComponent when the user is authenticated. Otherwise the AuthenticateComponent should be rendered (usually a login component).

```es6
import React from "react"

const PROPTYPES = {
  authenticated: React.PropTypes.bool.isRequired,
}
export default (WrappedComponent, AuthenticateComponent) => {
  let Protected = (props) => (
    props.authenticated
    ? <WrappedComponent {...props}/>
    : <AuthenticateComponent {...props}/>
  )
  Protected.propTypes = PROPTYPES
  return Protected
}
```

The props for the component come from a connected redux Container component

```es6
const AccountContainer = ({ children }) => (
  <div>{children}</div>
)
const select = state => state.account
export default connect(select, { refreshUser, logout })(Protected(AccountContainer, LoginContainer))
```

My `account` reducer looks like this

```es6
function authenticated(state = false, action) {
  switch (action.type) {
    case actions.START_SIGNUP_SUCCESS:
    case actions.LOGIN_SUCCESS:
      return true
    case actions.LOGIN_ERROR:
    case actions.START_SIGNUP_ERROR:
    case actions.LOGOUT_SUCCESS:
      return false
    default:
      return state
  }
}

...

export default combineReducers({
  authenticated,
  access_token,
  loggingIn,
  user,
  error,
})
```

My logout saga that causes the error looks like this:

```es6
function* logoutFlow(access_token) {
  while (yield take(actions.LOGOUT)) {
    try {
      yield call(api.logoutAsync, access_token)
      yield put(actions.logoutSuccess())
    } catch (error) {
      yield put(actions.logoutError(error))
    }
  }
}
```

It happens now that when `yield put(actions.logoutSuccess())` is called the `state.account.authenticated` property is set to false, and yet, the `WrappedComponent` is still rendered. It accesses various other properties of `account` and they all have been cleared also already, which the component does not check and expect them to be set. The component access `account.user.code` without proper null checking and this throws. It does not null check because the `WrappedComponent` assumes that when it gets rendered the `account` state is still `authenticated` and therefor everything in it still valid.

It is as if the render of the component is scheduled before the `logoutSuccess` action is dispatched to the store but the rendering is delayed for some reason. So when the actual render takes place, the precondition of the `Protected` component has already been me (during the previous schedule) and now when the component is actually rendered, the state has finally changed and the `WrappedComponent` cannot deal with that.

Any hint how `put` and react render schedules work togehter? Or is it maybe a redux `connect` problem?

**Comment by yelouafi** [comment]
`put` Effect simply executes `store.dispatch` behind the scene so I suspect the issue is elsewhere.

**Comment by yelouafi** [comment]
have you been able to locate the issue?

**Comment by pke** [comment]
Yes I also guess the error was somewhere else.
