### ISSUE TITLE
How to delay load provisioned data using webpack codesplit in sagas

### ISSUE THREAD

**Issue by pke** [yelouafi/redux-saga#430]
I want my app to start as fast as possible. At the moment I am `require("provisioned.json")` when a certain reducer JS file is loaded to provide part of the initial state for that reducer. This not only bloats the `bundle.js` file and slows down the initial `bundle.js` load time, but it also needs a lot of JSON parsing before I also normalize the data before the reducer saves it in the state.

My questions are the following:

1. How to have a saga wait for the app launch to be done. I guess I'd have to `put` an `APP_READY` action when the app component reaches its `componentDidMount` life-cycle event.
2. Have the saga then to load the provisioned data using webpacks codesplit feature with `require("provisioned.json", data => {})`. My question is how would I wrap `AMD require` or `ensure.require` in the proper saga effect like `call` or `fork`?
3. normalize the loaded data (in a webworker) and `put` an action in the store that the reducer for the data picks up

Especially question 2 seems difficult for me to solve.

**Comment by yelouafi** [comment]
>My question is how would I wrap AMD require or ensure.require in the proper saga effect like call or fork?

You can promisify the 'require' function then use it with call or fork

```js
function requireP(url) {
  return new Promise(resolve => {
    require("provisioned.json", resolve)
  })
}

function* saga() {
  ...
  const data = requireP("provisioned.json")
}
```

**Comment by pke** [comment]
Thanks, I will try that. I guess it could also be combined with webpack codesplitting to create a splitpoint inside `requireP`?

**Comment by pke** [comment]
@yelouafi should that be `const data = yield requireP()`?
