### ISSUE TITLE
Question of real-world's dispatch

### ISSUE THREAD

**Issue by monochrome-yeh** [yelouafi/redux-saga#431]
Hello,

I've a question about examples of "real world",

I don't understand why doesn't need to use `dispatch`,
but it's able to work (trigger actions)
https://github.com/yelouafi/redux-saga/blob/master/examples/real-world/containers/App.js#L15

however, others was work:
https://github.com/yelouafi/redux-saga/blob/master/examples/async/src/containers/App.js#L15

I don't get what cause is.

I would appreciate your reply, if you could have a look and let me know.

Thanks.

**Comment by HansDP** [comment]
Hello

In the *real-world* example, the action creator `updateRouterState` is bound to the dispatch method.when connecting the component to redux (https://github.com/yelouafi/redux-saga/blob/master/examples/real-world/containers/App.js#L88). 
In the *async* example, there is no `mapDispatchToProps` set, which indicates that only the `dispatch` method will be passed as property to your connected component.

This is related to how react-redux works
If you pass in an object in `mapDispatchToProps`, all methods will get bound to the dispatch method

From the documentation:

> `[mapDispatchToProps(dispatch, [ownProps]): dispatchProps]` (Object or Function): If an object is passed, each function inside it will be assumed to be a Redux action creator. An object with the same function names, but with every action creator wrapped into a dispatch call so they may be invoked directly, will be merged into the component’s props. If a function is passed, it will be given dispatch. It’s up to you to return an object that somehow uses dispatch to bind action creators in your own way. (Tip: you may use the bindActionCreators() helper from Redux.) If you omit it, the default implementation just injects dispatch into your component’s props. If ownProps is specified as a second argument, its value will be the props passed to your component, and mapDispatchToProps will be re-invoked whenever the component receives new props.

See [connect(...) documentation](https://github.com/reactjs/react-redux/blob/master/docs/api.md#connectmapstatetoprops-mapdispatchtoprops-mergeprops-options)

**Comment by monochrome-yeh** [comment]
maybe I have got the problem,

in my case:
```javascript
const mapStateToProps = ( store ) => {
    // console.log( store.router.pathname.substring( 1 ) )
    // const { language } = store.router.params
    const { language } = store

    return {
        language,
    }
}

const mapDispatchToProps = ( dispatch ) => {
    return {
        navigate,
        updateRouterState,
        resetErrorMessage,
        setUiLanguage
    }
}
```

in real-world:
```javascript
function mapStateToProps(state) {
  return {
    errorMessage: state.errorMessage,
    inputValue: state.router.pathname.substring(1)
  }
}

export default connect(mapStateToProps, {
  navigate,
  updateRouterState,
  resetErrorMessage
})(App)
```
I should't have use function to do `mapDispatchToProps`
Hahahaha, I'm so stupid, this problem confuse me whole the week...

however I'm so happy, cause of you reminded me about that... lol

thanks bro

**Comment by monochrome-yeh** [comment]
[Got an answer](https://github.com/yelouafi/redux-saga/issues/431#issuecomment-231762869)
related react-redux connect method.
