### ISSUE TITLE
Saga calls action after cancel

### ISSUE THREAD

**Issue by theWaR13** [yelouafi/redux-saga#439]
Hello. I've taken a code from [here](https://yelouafi.github.io/redux-saga/docs/advanced/TaskCancellation.html) and modified it a little bit. My task is to make a request to the server and then redirect to another page. Problem is that request to the server goes twice, the second time it appears after (!) redirecting. More than that, i found that if i redirect to '/' it's ok, request appears one time only, but if i redirect to '/another-page' it's being made twice. What is the problem? Here is a part of my code:

saga.js

```js
function* fetchData() {
  ...
  yield put(redirectTo('/another-page'));
}

function* main() {
  while (yield take(FETCH_DATA)) {
    const fetcher = yield fork(fetchData);

    yield take(LOCATION_CHANGE);  // this one goes from react-router-redux
    yield cancel(fetcher);
    console.log('Cancelled');
  }
}
```

index.js

```js
export class MyClass extends React.Component {

  componentWillReceiveProps = (props) => {
    if (props.redirectState !== '') {  // props.redirectState goes from component's state, it contains '/another-page'
      console.log('Redirecting');
      this.props.dispatch(push(props.redirectUrl));
    }
  }

  ...
}
```

After this code my output is:
Successfully fetched
Redirecting
Cancelled
Successfully fetched

In server's console i can see 2 requests as well.

Thanks in advance.

UPD. Also i found that fetchAction (which actually returns FETCH_DATA constant) is called one time only.

**Comment by Andarist** [comment]
You would have to need to post more code, so I can help you. There is not much to get out of the snippets you have posted.
