### ISSUE TITLE
Put in loop

### ISSUE THREAD

**Issue by 38Slava** [yelouafi/redux-saga#443]
How to call put effect in loop correctly?

So i wanna do something like this:

```javascript
function* dispatchAll (data) {
  yield put({
    type: 'TYPE',
    payload: data
  })
}
```

```javascript
function* foo ({ payload }) {
  try {
    const data = yield R.map(api, payload) // R = ramda.js
    yield R.map(dispatchAllPosts, data)
  } catch (err) {
    //
  }
}
```

But while i call put in loop app is freezing. Any advices?

**Comment by JesterXL** [comment]
What does your main saga.run look like, and what does your `.dispatch` action that starts the whole thing look like?

**Comment by sergej-s** [comment]
@38Slava Maybe I am wrong but here ```const data = yield R.map(api, payload)``` you should yield array of effects but you yield array of API invocation results. Also it seems here ```yield R.map(dispatchAllPosts, data)``` array of undefined are being yielded (if as dispatchAllPosts you mean dispachAll) instead of array of effects. 
Simple loop should look somthing like this:
```
for (let item of payload) {
  const data = yield call(api, item);
  yield call(dispatchAll, data);
}
```
or
```
const data = yield R.map(item => (call(api, item)), payload);
yield R.map(item => (call(dispatchAllPosts, item)), data);

```

**Comment by yelouafi** [comment]
if you want to yield multiple calls in parallel, use the snippet of @sergej-s; to put the results in parallel you can yield an array of put effects

```js
yield R.map(item => put({type: '...', payalod: item}), data)
```

**Comment by bmueller-sykes** [comment]
I'm late to the party here, but I'm having trouble getting this to work. If I have an array of actions, like: 
```
const actions = [
{action: 'ACTION1', payload: {x: 1}},
{action: 'ACTION2', payload: {y: 2}}
]
```
...how can I iterate over that array to `put` each of those actions? I've tried this:

```
        yield actions.map ( (current) => {
          put(current)
          return true;
        })
```
...but the `put` doesn't trigger. If I put `yield put([some action])` in the exact same place in my code, that triggers just fine.

If I try this:
```
        actions.map ( (current) => {
          yield put(current)
          return true;
        })
```
...then I get a JS error saying `yield is a reserved word`.

I've experimented a bit with `all`, but I haven't seen any examples where there is a `put` inside of an `all` (only `call` functions, which makes some sense, I think).

So, is it possible to do what I'm after here? Am I just not understanding something fundamental about how Redux Saga works?

**Comment by bmueller-sykes** [comment]
answering my own question. It appears this does the trick:
```
        yield actions.map ( (current) => {
          return put(current)
        })
```
You have to explicitly return the `put`. I don't think I saw that in any examples or docs, though perhaps I just missed it.

**Comment by ArtBIT** [comment]
Or simply: `yield actions.map(put)`

**Comment by Andarist** [comment]
@ArtBIT `yield actions.map(put)` might not work, because put will be called with both action and index arguments. `put`s signature is `function put(channel, action) { ... }` so it would create wrong effect (or just throw when validating.

Also you should wrap this with `all` effect which is preferred way of starting parallel effects. 

So the final code should look like this:
```js
yield all(actions.map(ac => put(ac)))
```

**Comment by ArtBIT** [comment]
@Andarist I stand corrected.
