### ISSUE TITLE
Using takeEvery executes multiple times for a single action

### ISSUE THREAD

**Issue by eliperelman** [yelouafi/redux-saga#445]
Trying to pinpoint the issue, but it seems that every time I try to use `takeEvery` with a simple `call`, the action is executed multiple times, in my case, it seems that the `console.log` is run 4 times. My reduced case:

```js
function* rootSaga() {
  yield* takeEvery(SIGN_IN, function*() {
    yield call(() => console.log('do something...'));
  });
}
```

Running this in a loop instead seems to have the same issue:

```js
function* signIn() {
  while (true) {
    yield take(SIGN_IN);
    yield call(() => console.log('do something'));
  }
}

function* rootSaga() {
  yield fork(signIn);
}
```

**Comment by sergej-s** [comment]
I have tested both of your code with action dispatched once like this
``` setTimeout(() => (store.dispatch({type: 'SIGN_IN'})), 1000);```
and everything is fine. Can you give more info?

**Comment by eliperelman** [comment]
In my view I have a button that is bound to a `signIn` function via:

```js
const signIn = () => dispatch({ type: 'SIGN_IN' });
```

Adding a `console.log` to this method only logs a single time, so the event/dispatch isn't happening multiple times:

```js
const signIn = () => {
  console.log('Signing in...'); // this only logs once
  dispatch({ type: 'SIGN_IN' });
};
```

For what it's worth I am also using `redux-elm` but I don't see anything specific there that would be causing this issue since this seems more on the level of `redux-saga`. My reducer syntax is obviously specific to `redux-elm` but should still execute sagas the same way. If this seems like an issue in `redux-elm`, I'll move my bug there.

Reducer, for clarity:

```js
import { Updater } from 'redux-elm';
import { takeEvery, delay } from 'redux-saga';
import { take, fork, call, put } from 'redux-saga/effects';

function* signIn() {
  while (true) {
    yield take(SIGN_IN);
    yield call(() => console.log('take some action...'));
  }
}

function* listen() {
  yield [
    fork(signIn)
  ];
}

export default new Updater({}, listen).toReducer();
```

Any other information I could provide that would be helpful?

cc: @tomkis1

**Comment by smashercosmo** [comment]
Couldn't this somehow be related to https://github.com/yelouafi/redux-saga/issues/429 ? Are you using node 6 without babel-plugin-transform-regenerator?

**Comment by eliperelman** [comment]
I am using Node.js v6.3.0 with Webpack, Babel, and the following in my babel config:

```js
module.exports = {
  plugins: [
    require.resolve('babel-plugin-transform-runtime')
  ],
  presets: [
    require.resolve('babel-preset-es2015'),
    require.resolve('babel-preset-stage-0'),
    require.resolve('babel-preset-react')
  ]
};
```

**Comment by tomkis1** [comment]
My suspicion is that this issue is definitly bug in `redux-elm` please @eliperelman feel free to file the issue there and let me investigate closer in `redux-elm` context. We would file the issue here after deeper investigation in `redux-elm`.

This can be closed.

**Comment by eliperelman** [comment]
Moved to [redux-elm/37](https://github.com/salsita/redux-elm/issues/37).

**Comment by originalkamaal** [comment]
i f you are calling it from render() method, this will execute multiple times as much as render() renders all component inside, separate the call from render method
