### ISSUE TITLE
Double call when LOCATION_CHANGE

### ISSUE THREAD

**Issue by chaintan17** [yelouafi/redux-saga#451]
I wonder if it normal behaviour to work like this.
if i use one of saga effect, let say `takeLatest`,
and i change location (may be, back and forward the page)

and saga now will take double dispatched action on `takeLatest`

if i do it again, change location
saga will take triple of that action.

Example code
```js
function* fetchHotel(action) {
   // BUSINESS LOGIC
}

export function* hotelSaga() {
  yield* takeLatest(SUBMIT_FILTER, fetchHotel);
}

export default [
  hotelSaga,
];
```

Currently, i have to cancel manually
like below code
```js
function* fetchHotel(action) {
   // BUSINESS LOGIC
}

function* fetchHotelWatcher() {
  yield* takeLatest(SUBMIT_FILTER, fetchHotel)
}

export function* hotelSaga() {
  const hotelWatcher = yield fork(fetchHotelWatcher);
  yield take(LOCATION_CHANGE);
  yield cancel(hotelWatcher);
}

export default [
  hotelSaga,
];
```

So do you think it is normal? i feel like it is not intuitive.
Or should it be in document at least? If yes, i will add them in to docs.

**Comment by somghosh** [comment]
+1

**Comment by Andarist** [comment]
I think that you might be forking some task which initialize `takeLatest` each time you fork it, but you would have to post more code concerning your issue I think as it is unclear from those lines you have posted how big picture looks like

**Comment by chaintan17** [comment]
@Andarist Hi, thanks for your help.
I just update the code, please review it.
thank you!

**Comment by Andarist** [comment]
```
function* fetchHotel(action) { 
    // business logic stuff
}
export function* homeSaga() {
  yield* takeLatest(SUBMIT_HOTEL_ID_FOR_SEARCH, fetchHotel);
}

export default [
  homeSaga,
];
```

is that whole saga code? you are not even using in this one `LOCATION_CHANGE ` which is connected to your problem as you said, I dont need buisness logic posted to help you, but I need to know exact saga code, what is root saga? how `hotelSaga` and `homeSaga` are tied with each other?

**Comment by chaintan17** [comment]
@Andarist  sorry for my poor example. I just fix the inconsistency.

I add `LOCATION_CHANGE` in the later code snippet because it's my fix to this issue.
I mean, i thought the first snippet should work properly enough, but after i revisit the page from back/forward navigation, the sagas get duplicated request.

I wonder shouldn't it cancel the saga normally without my `LOCATION_CHANGE` watcher?

**Comment by Andarist** [comment]
is `hotelSaga` your rootSaga or is it triggered from some of your other sagas?

**Comment by chaintan17** [comment]
@Andarist it's my root saga.
I inject it in my `routes.js`

```js
      path: '/hotel/:hotelId',
      name: 'hotel',
      getComponent(nextState, cb) {
        const importModules = Promise.all([
          System.import('containers/Hotel/reducer'),
          System.import('containers/Hotel/sagas'),
          System.import('containers/Hotel'),
        ]);

        const renderRoute = loadModule(cb);

        importModules.then(([reducer, sagas, component]) => {
          injectReducer('hotel', reducer.default);
          injectSagas(sagas.default);
          renderRoute(component);
        });

        importModules.catch(errorLoading);
      },
```

**Comment by chaintan17** [comment]
Thanks! i think i understand better. will take a look to what you lead more and find the better solution.

Thanks again!

**Comment by Gyvastis** [comment]
@chaintng did you solve this eventually?

**Comment by justinhp** [comment]
@chaintng Did you ever figure this out?

**Comment by Andarist** [comment]
@justinhp could u specify ur issue? It seems all is explained in this issue

**Comment by justinhp** [comment]
@Andarist Ah, ok.  I have the same setup in my `routes.js` file as @chaintng.  However, rather I'm doing `yield takeLatest(LOCATION_CHANGE, fetchSearchResults);`, so I want to dispatch an action whenever LOCATION_CHANGE is dispatched.  Running my code there causes additional calls every time the location changes.

**Comment by kai23** [comment]
@justinhp here what worked for me : 

```js
export function* getSessionOnLocationChange() {
  const watcher = yield fork(requestSession);
  yield take(LOCATION_CHANGE);
  yield cancel(watcher);
}
```

**Comment by justinhp** [comment]
@kai23 Merci!  That worked.
