### ISSUE TITLE
How to dispatch more actions in 1 yield via PUT

### ISSUE THREAD

**Issue by zatziky** [yelouafi/redux-saga#459]
Why is `redux-saga` not dispatching action when used in this form:

    function* updatePorts(action) {
        const {response} = yield SagaEffects.call(apiUpdatePorts, action.ports);
        if (response) {
            yield (() => {
                console.log("Dispatching - ", action.actionAfter);
                SagaEffects.put(action.actionAfter);
            })();

But it works in this manner:

    function* updatePorts(action) {
        const {response} = yield SagaEffects.call(apiUpdatePorts, action.ports);
        if (response) {
            yield SagaEffects.put(action.actionAfter);

I would like to dispatch 2 actions in 1 `yield` thats why I am trying to use the arrow function `(() => {})`.

**Comment by smashercosmo** [comment]
If you want to dispatch 2 actions in 1 yield, you can just use redux-batched-actions package.

**Comment by slorber** [comment]
you can yield an array of effects

**Comment by zatziky** [comment]
Can you show me how? An example please?

**Comment by zatziky** [comment]
@slorber It worked. I used it this way:


```
yield [
            SagaEffects.put(actions.saveItemsOk()),
            SagaEffects.put(actionsButton.savingEnded())
        ]
```

**Comment by kyle-ssg** [comment]
This post ranks high in google for this question, so thought I'd mention the above is deprecated and that you now want to do: 

```
yield SagaEffects.all([
            SagaEffects.put(actions.saveItemsOk()),
            SagaEffects.put(actionsButton.savingEnded())
        ])
```

**Comment by preciselywilliam** [comment]
@kyle-ssg is there any technical difference between 2x `yield put` and `all([put, put])`?

**Comment by ronayumik** [comment]
^asking the same question @kyle-ssg

**Comment by koobeeyak** [comment]
@preciselywilliam @ronayumik if you haven't seen it yet, [in the docs for SagaEffects.all()](https://redux-saga.js.org/docs/api/#alleffects) they compare it to a close representation of Promise's [all()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all), which returns a single promise once all the promises passed to it are resolved.
So if same idea applies to redux, you'll get one promise from `yield all([put, put])`, something you couldn't do with two separate `yield put`s.

**Comment by Absvep** [comment]
> This post ranks high in google for this question, so thought I'd mention the above is deprecated and that you now want to do:
> 
> ```
> yield SagaEffects.all([
>             SagaEffects.put(actions.saveItemsOk()),
>             SagaEffects.put(actionsButton.savingEnded())
>         ])
> ```

Great answer! But does this properly batch the two actions into a single subscription event? Making redux-batch redundant in this scenario.

**Comment by Andarist** [comment]
> @kyle-ssg Great answer! But does this properly batch the two actions into a single subscription event? Making redux-batch redundant in this scenario.

No. Even `batch` from Redux doesn't do that. It merely batches **renders**, not subscribers

**Comment by Absvep** [comment]
Ok, but https://github.com/manaflair/redux-batch/blob/master/README.md says that ” Note: Since this package got written, redux-saga improved and using all([ put(...), put(...) ]) seems to properly batch the two actions into a single subscription event, making redux-batch redundant in this scenario.” but should one use redux-batch with yield all([put(...),put(...)]) or it will not do batching?

Skickat från min iPhone

**Comment by icharge** [comment]
> Ok, but https://github.com/manaflair/redux-batch/blob/master/README.md says that ” Note: Since this package got written, redux-saga improved and using all([ put(...), put(...) ]) seems to properly batch the two actions into a single subscription event, making redux-batch redundant in this scenario.” So should one use redux-batch with yield all([put(...),put(...)]) or it will not do batching? Or do I misunderstand something? I.e do I need to use redux-batch in configeStore.js or is simply using yield.all(put,put) enough?
> […](#)
> ﻿ @kyle-ssg Great answer! But does this properly batch the two actions into a single subscription event? Making redux-batch redundant in this scenario. No. Even batch from Redux doesn't do that. It merely batches renders, not subscribers — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

I just try and it work perfectly fine
