### ISSUE TITLE
question: testing 

### ISSUE THREAD

**Issue by aft-luke** [yelouafi/redux-saga#46]
This issn't really an issue, I'm just trying to wrap my head around certain aspects of testing.

How do I use a yielded value inside a generator to continue on with tests? Consider:

```javascript

    function* watchDoSomething() {
        while (true) {
            const { thing } = yield io.take(actions.DO_SOMETHING)
            const fetch = yield io.fork(fetchSomething(thing.id))
        }
    }


...
        it('should wait for the next DO_SOMETHING', function() {
            sut.next().value.should.eql(io.take(actions.DO_SOMETHING))
        })
        it('should dispatch a fetch request', function() {
            sut.next().value
            sut.next().value.should.eql(io.fork(creators.fetchSomething)) 
            // errors with 'cannot read property thing of undefined' : attempting to destructure the undefined
            // result from yield io.take
        })
        it('should invoke fetch with the id', function() {
            sut.next().value
            sut.next().value
           // how do I test this last piece?
            sut.next().value.should.eql( ... )
        })
```

How do you simultaneously test that DO_SOMETHING is called *and* return a value on that `thing`? As far as the application is concerned, `thing` already has an id embedded on the action... but again, I'm not sure how to simulate this in the world of generators.

**Comment by mjrussell** [comment]
@aft-luke I just created a PR (more like a discussion) about possibly similar issues with testing #45

**Comment by yelouafi** [comment]
>How do I use a yielded value inside a generator to continue on with tests?

by calling `next(mockResult)`.

```javascript
 it('should wait for the next DO_SOMETHING', function() {
   sut.next().value.should.eql(io.take(actions.DO_SOMETHING))
 })
 
it('should dispatch a fetch request', function() {
  // inject mock result into next
  const mockThing = { thing: { id: 1 } }
  sut.next(mockThing).value.should.eql(io.fork(creators.fetchSomething)) 
  ....
}
```

If you want to simulate an error, call `throw(mockResult)` instead

Although you don't use it in the above example. We should provide a way to mock the result of forked tasks (e.g. `fetch = ` in your example )

**Comment by josebalius** [comment]
@yelouafi I was going to open another issue for a question very similar to this one, so I hope this is okay. Here is another case for testing

```
function* watchDoSomething() {
        while (true) {
            const response = yield io.take(actions.DO_SOMETHING)
            if(response.success) {
                 yield io.fork(fetchSomething())
            } else {
                // do something else
            }
        }
    }
```

How can I test that flow?

**Comment by yelouafi** [comment]
@josebalius This is related to #47. We need to provide an utility function to mock fork results

**Comment by yelouafi** [comment]
v0.6.0 includes a `createMockTask ` function, see [releases notes](https://github.com/yelouafi/redux-saga/releases) for usage example.
