### ISSUE TITLE
Redux-saga silently eats errors on .run()?

### ISSUE THREAD

**Issue by DelvarWorld** [yelouafi/redux-saga#462]
I'm fairly new to saga and generators in general. It's possible I'm misunderstanding how sagas are supposed to work / be used.

I have a runtime error in one of my sagas, and the error gets silently eaten. I only found it by turning on "pause on uncaught exceptions" in chrome. These lines appear to be the culprit: https://github.com/yelouafi/redux-saga/blob/9752adb5480d6449ae578644820a5cb9d9e7f2cb/src/internal/proc.js#L436-L439

I create middleware in a fairly straightforward way:

```javascript
const sagaMiddleware = createSagaMiddleware();
...
sagaMiddleware.run( userSaga );
```

`userSaga` looks something like:

```javascript
export default function* userSaga() {
    yield [
        takeEvery(
            SOME_ACTION, actionSideEffect
        )
    ];
}
```

And my side effect function:

```javascript
function actionSideEffect( action:Object ) {
    ... some code that errors on runtime
}
```

I don't know if the side effect being synchronous is related, or something that's encouraged in redux-saga, or even something that's allowed in redux-saga?

The [docs say](http://yelouafi.github.io/redux-saga/docs/api/index.html#createsagamiddlewareoptions) that the middleware should automatically log errors:

> By default, the middleware logs all errors and warnings to the console.

Not sure why they aren't getting logged for me. And [ErrorHandling.md](https://github.com/yelouafi/redux-saga/blob/master/docs/basics/ErrorHandling.md) doesn't mention anything about `saga.run`.

**Comment by yelouafi** [comment]
>I don't know if the side effect being synchronous is related

I think this is related to #441.

**Comment by yelouafi** [comment]
FYI [new 0.11.1 release](https://github.com/yelouafi/redux-saga/releases/tag/v0.11.1) fixes the errors issue. 

Can you try with the new release ? I'm mostly sure this is a similar issue
