### ISSUE TITLE
expose asEffect or add alternative way to distinguish effect type

### ISSUE THREAD

**Issue by R1ZZU** [yelouafi/redux-saga#465]
There is no legit way to distinguish different effect types. I've found `asEffect` in `lib/internal/io`, but I guess it's not really a good idea to use this outside redux-saga source code. Or is it? 😏  If so, then exposing this API for external usage will be really great

**Comment by Andarist** [comment]
But is `asEffect` a good solution here? Its purpose is unwrapping metadata from effect so it can be run by a proper handler. The fact it will return smth other than undefined only if effect is certain type would be rather sort of indirect logic.

**Comment by yelouafi** [comment]
In fact `asEffect` is already exported from the `redux-saga/utils`. 

> but I guess it's not really a good idea to use this outside redux-saga source code. Or is it?

There is a good case for it: implementing a Saga monitor (provided as option to the sagaMiddleware.run function). You can see how it's used in the [sagaMonitor example](https://github.com/yelouafi/redux-saga/blob/master/examples/sagaMonitor/index.js#L175-L245)

**Comment by anjunatl** [comment]
@yelouafi This is unrelated to this bug, but you mentioned redux-saga/utils and I'm having trouble finding that for another bug I'm working on. Is that some exported package that was removed at some point? https://github.com/clarketm/saga-monitor/issues/3

**Comment by anjunatl** [comment]
Found the answer - https://github.com/redux-saga/redux-saga/pull/1655
