### ISSUE TITLE
call([context, fn], args) does not allow access to context from args.

### ISSUE THREAD

**Issue by RobertSheaO** [yelouafi/redux-saga#467]
I just integrated AWS Cognito into my React/Redux project and when using `call([context, fn], args)` to call their authenticateUser function, the first argument doesn't have access to context. I'll detail a bit about how their code flows.

You setup an `authenticationDetails` and `cognitoUser` variable using object constructors, `cognitoUser.authenticateUser` needs access to `cognitoUser` to access some getters, so using `call([context, fn, args)` works here; however, `authenticationDetails` (the first of two params passed as args) needs access to the getters and setters inside `authenticationDetails`. The solution was to use `apply(context, fn, args)` which claims to be an alias, but since it works and the other one doesn't it can be a true alias.

Here's some implementation code:

```
const authenticationData = {
  Username: username,
  Password: password,
};
const authenticationDetails = new AWSCognito.CognitoIdentityServiceProvider.AuthenticationDetails(authenticationData);
const userData = {
  Username: username,
  Pool: userPool,
};
const cognitoUser = new AWSCognito.CognitoIdentityServiceProvider.CognitoUser(userData);
const token = yield apply(
  cognitoUser,
  cognitoUser.authenticateUser,
  [
    authenticationDetails,
    { onSuccess(){}, onFailure(){} }
  ]
);
```

**Comment by yelouafi** [comment]
Not sure to understand the exact issue, but the actual signature of the `call` effect above is not `call([context, fn], args)` but `call([context, fn], ...args)` (see [API](http://yelouafi.github.io/redux-saga/docs/api/index.html#callcontext-fn-args)). Maybe this is the cause of the issue you have

so in the code above you can replace apply with

```js
const token = yield call(
  cognitoUser,
  cognitoUser.authenticateUser,
  /*[ no brackets */
    authenticationDetails,
    { onSuccess(){}, onFailure(){} }
  /*] no brackets*/
);
```
