### ISSUE TITLE
Any idea to test this generator function?

### ISSUE THREAD

**Issue by n9ti** [yelouafi/redux-saga#47]
```javascript
export function * getData () {
  let task
  while (true) {
    let { data } = yield take(types.GET_DATA)
    task && task.isRunning() ? yield cancel(task) : null
    task = yield fork(callApi, data)
  }
}
```

**Comment by yelouafi** [comment]
This is related to #45 and #46. We need to provide a way to mock fork results (i.e. create mock tasks), since the developer can't create them himself.

I'm thinking of something like a `createMockTask` method; then your test should be something like this

```javascript
import { createMockTask } from 'redux-saga/lib/testUtils'

const it = getData()

assert.deepEqual( it.next().value, take(types.GET_DATA) )

const mockData = { ... }
const mockAction = {type: types.GET_DATA, data: mockData }

// resume the generator with mockAction
// since task is null, we expect yield null
assert.deepEqual( it.next(mockAction).value, null )

assert.deepEqual( it.next().value, fork(callApi, mockData ) )

// mock fork result
const mockTask = createMockTask()

// resume the generator with mock task
assert.deepEqual( it.next(mockTask).value, take(types.GET_DATA) )

// simulate a task ending
mockTask.setRunning(false)

// now expect a cancel
assert.deepEqual( it.next(mockAction).value, cancel(task) )
```

**Comment by aft-luke** [comment]
On a related note, this pattern is becoming quite common across a lot of my sagas. Fetch something, but do it in a non-blocking manner so if the user has quick fingers or the interface offers a cancel button, we can abort the outstanding xhr, capture the errors, and fire off another forked fetch. I don't really like the idea of a scoped "global" variable and doing things like `task && task.isRunning()`... it reminds me too much of recursion and doesn't seem to nicely line up with a structured programming paradigm. I wonder if there's a better way?

**Comment by josebalius** [comment]
@yelouafi @aft-luke I may not know enough about the codebase, but I am making the assumption that `call` etc know when it is called from an iterator or not and that's how it decides to run the effect or return the description?

What if somehow we could detect or a set a "testing" environment as true, or something similar, that would allow you to not only receive back the description of the effect, but also make that specific `call()` return a mock value that you could pass when running that effect? 

Like here run this effect, and return this mock value + plus the description of the effect. Some sort of test utils.

I need to put some code together.

**Comment by yelouafi** [comment]
@josebalius `call` is just a pure function that receives some params and return a plain object. It doesnt have to detect anything. What happens is that when the redux-saga middleware run the generator, it asks it to get the next effect. The generator returns for example a call object. The middleware then run the call (e.g. by making an xhr request ) and resume the generator when the result of the execution arrives.

In tests, you do the same thing, you ask the generator for the next effect. except that you dont run the call. you just resume the generator by some mock result

```javascript
function* saga() {
  const res = yield call(myFunc)
  yield put(action(res))
}

const it = saga()

assert.deepEqual( it.next().value, call(myFunc) )

const mockResultOfMyFuncCall = {}
assert.deepEqual( 
  // here you provide a dummy result to the generator into the next method
  it.next(mockResultOfMyFuncCall ).value,
  // and expect it putting an action with that result
  put( action(mockResultOfMyFuncCall) ) 
)
```

The issue with `fork` is that you can't give the generator an arbitrary mock value. Because fork results are expected to have some special properties. So there is no way actually for a library user to mock them. Thus we need to provide a function to create mock fork results

**Comment by yelouafi** [comment]
@n9ti  v0.6.0 introduces `createMockTask`. see [releases notes](https://github.com/yelouafi/redux-saga/releases/tag/v0.6.0) for usage example

**Comment by juliusosokinas** [comment]
Hey! I wonder how come setting `mockTask.setRunning(false)` in the test doesn't effect the previous task? I mean, if it is set to `true`, then obviously a cancellation should be called. But if it's `false`, shouldn't the generator just fork and skip the cancellation?
