### ISSUE TITLE
How should one test errors thrown in a function?

### ISSUE THREAD

**Issue by jessepollak** [yelouafi/redux-saga#470]
Hi! I'm trying to test a saga that throws an error inside of the saga body. The code looks like this:

```javascript
// code
export function *createLogin (API) {
  yield put(actions.login.request())
  try {
    const ID = yield select(getID)

    if (!ID) {
      throw new Error('Please provide an ID')
    }

    const response = yield call(
      [API, API.post],
      '/login/',
      {
        id: ID
      }
    )
    yield put(actions.login.success(response))
  } catch (error) {
    yield put(actions.login.failure(error))
  }
}

// test
it('should raise an error if there is no application ID', function () {
  const generator = module.createLogin(API)

  assert.deepEqual(
    generator.next().value,
    put(actions.login.request())
  )

  assert.deepEqual(
    generator.next().value,
    select(getID)
  )

  let next = generator.next()
  assert.deepEqual(next.value, put(actions.loginEntrypoint.failure(new Error('Please provide an ID'))))
}
```

Unfortunately, this test fails because the `assert.deepEqual` tries to compare the two `Error` objects, and while they have the same message, they have different properties so the test fails. I looked at [this issue](https://github.com/yelouafi/redux-saga/issues/28) where the error is passed into the iterator (i.e. it comes from an external source), but in this instance, the error is being thrown inside of the function and then caught. 

Has anyone dealt with testing a scenario like this before?

Thanks!

**Comment by yelouafi** [comment]
Why do you need to put the entire Error object in the action?  Could be just

```js
yield put(actions.login.failure(error.message))
```

Also I think the native `Error` object is not easily serializable and you need to put serializable thing into actions

**Comment by jessepollak** [comment]
Hm, I guess one could do that, but our actions conform to [flux-standard-action](https://github.com/acdlite/flux-standard-action) which specifies that `Error` objects should be passed in the `payload`.

Currently, we've created a `assertErrorActionEqual` function, but it feels pretty fragile.

```
function assertErrorActionEqual (action1, action2) {
  let asserted = false
  for (const k in action1) {
    if (action1[k].action) {
      assert.equal(action1[k].action.error, action2[k].action.error)
      assert.equal(action1[k].action.payload.message, action2[k].action.payload.message)
      assert.equal(action1[k].action.payload.name, action2[k].action.payload.name)
      asserted = true
    }
  }
  assert(asserted)
}
```

**Comment by yelouafi** [comment]
you can try having a function which create the error then use `call` in the saga to create the error

```js
function error(msg) {
  return new Error(msg)
}

export function *createLogin (API) {
    // ...
    if (!ID) {
      throw (yield call(error, 'Please provide an ID'))
    }
    // ...
}

// test
it('should raise an error if there is no application ID', function () {
  const generator = module.createLogin(API)

  // ...
  assert.deepEqual(
    generator.next().value,
    select(getID)
  )
  
  assert.deepEqual(
    generator.next().value,
    call(error, 'Please provide an ID')
  )

  // create a real Error and get the reference to it
  const idError = error('Please provide an ID')
  // pass it to the generator
  let next = generator.next(idError)
  assert.deepEqual(
    next.value, 
    put(actions.loginEntrypoint.failure(idError ))
  )
}
```

**Comment by yelouafi** [comment]
>I guess one could do that, but our actions conform to flux-standard-action which specifies that Error objects should be passed in the payload.

I think this conflicts with the requirement that actions should be plain and serializable objects. For an app user to send the action log to reply on the developer machine (eg to reproduce a bug) the actions have to be serializables. Unless I'm mistaken the native Error object can't be serialized (at least not automatically).
