### ISSUE TITLE
Saga being called multiple times

### ISSUE THREAD

**Issue by luandro** [yelouafi/redux-saga#471]
This is how I structure most of my sagas, and they're all working fine. But for some reason the add saga started behaving strangely. The first time I call the action that triggers `ADD` the saga runs only once. But if I call it again it calls it twice, than three times, etc. The action is only logged once, so it's definitely something in the Saga.

```
export function* add() {
  while (true) {
    const action = yield take(ADD);
    const fetch = yield call(push, action.payload);
    if (fetch.success) {
      yield put(changeRoute('/'));
    }
  }
}
```

Could anyone shed a light on what could create such odd behavior?

**Comment by luandro** [comment]
So I guess I was just missing a `return` statement in the end. I don't fully understand why, but it solved.

**Comment by brandondurham** [comment]
I’d be curious to know why this is happening. I’m experiencing the same thing.

**Comment by Andarist** [comment]
Do u use injectSagas in some router?

**Comment by brandondurham** [comment]
Sure do, the same way React Boilerplate uses it.

```
function createRoutes(store) {
	// create reusable async injectors using getAsyncInjectors factory
	const { injectReducer, injectSagas } = getAsyncInjectors(store);

	return [{
		label: 'Fonts',
		path: '/fonts',
		name: 'fonts',
		breadcrumbBar: true,
		pageHeader: { visible: false },
		licenseBarIsVisible: false,
		getComponent(nextState, cb) {
			const importModules = Promise.all([
				System.import('containers/Fonts/reducer'),
				System.import('containers/Fonts/sagas'),
				System.import('containers/Fonts')
			]);

			const renderRoute = loadModule(cb);

			importModules.then(([reducer, sagas, component]) => {
				injectReducer('fonts', reducer.default);
				injectSagas(sagas.default);
				renderRoute(component);
			});

			importModules.catch(errorLoading);
		},

		…

	}]
}```

**Comment by Andarist** [comment]
U probably need to cancel this saga on LOCATION_CHANGE cause it probably starts it again and again on each onEnter hook or something similar

**Comment by brandondurham** [comment]
I’ll give this a shot. Thanks for the tip!

**Comment by Andarist** [comment]
This issue pops up lately really often. Ill try to colaborate with
boilerplate maintainers so we can explain this better

**Comment by brandondurham** [comment]
Great idea. Thank so much!
