### ISSUE TITLE
How to forward errors using eventChannel?

### ISSUE THREAD

**Issue by romeovs** [yelouafi/redux-saga#472]
Using generator functions I know how to create a way to use exceptions by throwing errors:

```
function * foo () {
  yield 1
  yield 2
  throw new Error('oops!')
  yield 3
}

try {
  for (const n of foo()) {
    console.log(n)
  }
} catch (err) {
  console.log(`caught '${err.message}'`)
}
console.log('done!')
```

outputs:
```
1
2
caught 'oops!'
```
as expected.

However if I have an `eventChannel`, I do not see how I can easily throw errors from it:
```
const myChannel = function () {
  return eventChannel(function (emitter) {
     const s = someSource()
        .on('thing', emitter)
        .on('error', () => console.log('I do not know what to do here')
        .on('done', () => emitter(END))
     return () => s.cancel()
  }
}
```

Is there a way I can easily propagate errors from the `eventChannel` into my sagas?

**Comment by yelouafi** [comment]
Actually there is a [kind of] support for errors in `take` effects: if a take is resolved with an `Error` it will throw in the generator. For example

```js
const myChannel = function () {
  return eventChannel(function (emitter) {
     const s = someSource()
        .on('thing', emitter)
        .on('error', () => emitter(new Error(...) ) /* put an Error instance */ 
        .on('done', () => emitter(END))
     return () => s.cancel()
  }
}

function* saga() {
  const chan = yield call(myChannel)
  while(true) {
    try {
      const thing = yield take(chan)
    } catch(err) {
      // emitting an Error will throw here
    }
  }
}
```

Note that emitting an error will not abort the channel by default, if you want to end the channel after an error you'll have to close it explicitly (for example in the catch block of the Saga)

**Comment by romeovs** [comment]
Oh cool! It's even easier that I thought :+1:

Is this documented somewhere?

**Comment by yelouafi** [comment]
>Is this documented somewhere?

Not but it should be of course

**Comment by yelouafi** [comment]
done http://yelouafi.github.io/redux-saga/docs/api/index.html#takepattern

**Comment by adipascu** [comment]
This feature is working in `redux-saga 0.16.0`, I can't seem to find anything about it in the documentation.
