### ISSUE TITLE
How to "yield put" from within transaction()-callback of sqlite3-storage-plugin?

### ISSUE THREAD

**Issue by itinance** [yelouafi/redux-saga#475]
Using this awesome plugin [react-native-sqlite-storage](https://github.com/andpor/react-native-sqlite-storage) for dealing with sqlite3-databases, there is a callback necessary to create a transaction around the SQL-statements:

How can one use redux-saga effects like "put" within such a callback?

```
db.transaction( (tx) => {
   //  .... do something with the database
  // .... then put a state
   yield put({type: ACTIONS.R_SYNCHRONIZE_STATE_CAPTION, payload: "...some string..."});
})

```
PS: i know that there are some questions here for callback-usage. But the root cause of them was mostly a different one and i couldn't apply it onto my case.

Any ideas?

Thanks in advance!

**Comment by Andarist** [comment]
My solution might not be the best, but I dont know how to do it better for now. If anyone knows, please share! :)

So far I'm dealing with such scenario by:
1. setting up custom channel - `const customChannel = channel()`
2. in a callback using `customChannel.put(action)`
3. in your regular saga generator, kinda watcher on `customChannel`:
```
while (true) {
	const action = yield take(customChannel)
	yield put(action)
}
```

**Comment by mheiber** [comment]
I don't know enough about the implementation of react-native-sqlite-storage to know if this creates a memory leak or something, but you can use a promise to pull out the transaction from the callback and await it using `yield`:

```js
const getTxn = () => new Promise((resolve, reject) => {
    db.transaction(txn => resolve(txn))
})

// in a saga
const txn = yield getTxn()
```

**Comment by adrispo** [comment]
Hi! I have one solution, maybe is not the best, but it works:

`let sql = 'YOUR SQL`

In your saga function

```javascript
let sql = 'YOUR_SQL'
 const sqlResults = yield call(() => executeSQL(sql));
```
In your saga, you can create a function like:
```javascript
function executeSQL(sql) {
    return new Promise((resolve) => {
        SqliteHelper._db.transaction((tx) => {
            tx.executeSql(sql, [], (results) => {
                    resolve({
                        results
                    })
                },
                (error) => {
                    resolve({
                        error
                    })
                });
        });
    });
}
```

**Comment by Andarist** [comment]
@adrispo it's actually a good way of integrating with Promise/callback based APIs

**Comment by elshen321** [comment]
> My solution might not be the best, but I dont know how to do it better for now. If anyone knows, please share! :)
> 
> So far I'm dealing with such scenario by:
> 
> 1. setting up custom channel - `const customChannel = channel()`
> 2. in a callback using `customChannel.put(action)`
> 3. in your regular saga generator, kinda watcher on `customChannel`:
> 
> ```
> while (true) {
>     const action = yield take(customChannel)
>     yield put(action)
> }
> ```

Hi hope  you  well
Event  channel  create  loop  automatically  until emitt END , and  in get  data  from sqlite is not sutable  becauae stop loop is not easy
