### ISSUE TITLE
How to unit test / assert a debounced saga?

### ISSUE THREAD

**Issue by hzhu** [yelouafi/redux-saga#482]
I've made a [debounced saga](http://yelouafi.github.io/redux-saga/docs/recipes/index.html) to fetch data for a typeahead component. I'd like to write a unit test for it. What are to steps to assert that a Saga has been debounced? Are there any examples out there? I'm completely lost at how to write a unit test for this 😞 .

My debounced saga:

    export function* getCompanies() {
      const delay = (ms) => new Promise(resolve => setTimeout(resolve, ms));
      yield call(delay, 250); // debounce getCompanies saga by 250 ms
    
      const searchTerm = yield select(selectSearchTerm());
      if (searchTerm === '') return; // cancel api fetch if term is empty

      // fetch companies
      const requestURL = `https://autocomplete-api.com/suggest?query=${searchTerm}`;
      const companies = yield call(request, requestURL);

      if (!companies.err) {
        yield put(loadCompanies(companies.data)); // dispatch action: load companies
      }

     return;
    }

    export function* getCompaniesWatcher() {
      while (yield take(FETCH_RESULTS)) {
        yield call(getCompanies);
      }
    }

**Comment by Andarist** [comment]
In fact there is a way I think, please take a look here - https://github.com/yelouafi/redux-saga/blob/master/test/sagaHelpers/takeLatest.js

It is a really similar example. If you really want to check this debouncing thing.

However you dont even need to check:
1. use `delay` helper from `redux-saga` (`import { delay } from 'redux-saga'`)
2. use it exactly the same - `yield call(delay, 250)`
3. just test if `call` effect is created with correct arguments. Effects are description to saga what should be done by it. You actually do not need to check if it happened, just if saga was ordered to do something

Also in my opinion you do not need to use `yield call(getCompanies)`. I guess you are exporting `getCompanies`, so it can be tested. For me its exporting just for testing purposes which is not ideal (in my opinion). You can `yield* getCompanies()` so in your test (after `const it = getCompaniesWatcher()`) calls to `it.next` will be delegated in to your underlaying iterator which is the one created by `getCompanies`, so it can stay hidden from the outside world and still works exactly the same. However that is my personal preference.

**Comment by hzhu** [comment]
Apologies, I'm completely new to generator functions and redux-saga...

I was trying the three steps you listed, but isn't that just testing the `delay` function from redux-saga library?

In my code, delay is defined by me, similar to the [recipe](http://yelouafi.github.io/redux-saga/docs/recipes/index.html#debouncing) I followed, with 
```
const delay = (ms) => new Promise(resolve => setTimeout(resolve, ms));
```

What I really need to be asserting is the Effect objects that the generator function yields, right? But I'm not sure how to go about that.
