### ISSUE TITLE
Cannot remove "babel-plugin-transform-es2015-modules-commonjs" from the plugin list

### ISSUE THREAD

**Issue by elitan** [yelouafi/redux-saga#489]
On my debian with node v6.2.2 and npm v2.14.8 I get erorr while doing `npm install`

Reproduce:

```sh
$ git clone https://github.com/yelouafi/redux-saga.git
$ cd redux-saga
$ npm install
```

I get the following error:

```sh
Error: Cannot remove "babel-plugin-transform-es2015-modules-commonjs" from the plugin list.
    at Object.<anonymous> (/home/eli/repos/redux-saga/node_modules/babel-preset-es2015-webpack/index.js:35:11)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at /home/eli/repos/redux-saga/node_modules/babel-core/lib/transformation/file/options/option-manager.js:324:15
    at Array.map (native)
```
More error:

```sh
67246 error Linux 3.16.0-4-amd64
67247 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
67248 error node v6.2.2
67249 error npm  v3.9.5
67250 error code ELIFECYCLE
67251 error redux-saga@0.11.0 prepublish: `npm run check && npm run compile && npm run build`
67251 error Exit status 1
67252 error Failed at the redux-saga@0.11.0 prepublish script 'npm run check && npm run compile && npm run build'.
67252 error Make sure you have the latest version of node.js and npm installed.
67252 error If you do, this is most likely a problem with the redux-saga package,
67252 error not with npm itself.
67252 error Tell the author that this fails on your system:
67252 error     npm run check && npm run compile && npm run build
67252 error You can get information on how to open an issue for this project with:
67252 error     npm bugs redux-saga
67252 error Or if that isn't available, you can get their info via:
67252 error     npm owner ls redux-saga
67252 error There is likely additional logging output above.
67253 verbose exit [ 1, true ]
```

Am I doing something obviously wrong or is there a problem with this repo?

**Comment by Andarist** [comment]
Had same problem while developing a branch. So you are not alone. Looked into the issue for a brief moment and I've seen that:

```
    // npm ^3
    commonJsPlugin = require('babel-plugin-transform-es2015-modules-commonjs');
```

was sucessful and later in 
```
es2015WebpackPluginList = es2015PluginList.filter(function (es2015Plugin) {
    return es2015Plugin !== commonJsPlugin;
});
```

Nothing was filtered out of the list and it was supposed to. It may be some issue with incorrect package versions? I see that `babel-preset-es20150-webpack` is requiring via npm3 `commonJsPlugin = require('babel-plugin-transform-es2015-modules-commonjs');` from a flat structure and in `es2015PluginList` is included `require("babel-plugin-transform-es2015-modules-commonjs"), { loose: loose }]` which probably has some other identity cause of a flag passed in.

**Comment by elitan** [comment]
So, right now there is no working version of redux saga?

**Comment by Andarist** [comment]
Probably there isnt, cause it is a problem with a package its depending on (`babel-preset-es2015`). I've found why this had happened. Culprit is here - https://github.com/babel/babel/commit/c6354a2132c18caca18792a544105cc1e932987a#diff-a854a9360f2dd5153da7e0f8ed87c965 . `[].concat` flattens arrays, so concatening an array to an array is like adding elements from the second one to the first one. And they have changed it so the second flat wasnt flattened at all and the list became `[a,b,c, [d]]` instead of `[a,b,c,d]`. Therefore filtering in another package `babel-preset-es2015-webpack` just broke. Im gonna make a pull request to fix it in few minutes.

**Comment by Andarist** [comment]
Oh, I see there was already pull request with the fix there - (https://github.com/gajus/babel-preset-es2015-webpack/pull/13) but  its pending on approval.

**Comment by Andarist** [comment]
@elitan it seems that `babel-preset-es2015-webpack` got deprecated and a simple change with updated `babel-preset-es2015` seems to work perfectly. Just made PR here within `redux-saga`.

**Comment by elitan** [comment]
@Andarist sounds very good. Finally I can start learning and using redux saga. Thank you so much.
