### ISSUE TITLE
es6 generators, promises, abort xhr?

### ISSUE THREAD

**Issue by aft-luke** [yelouafi/redux-saga#49]
Sorry for the plethora of questions lately @yelouafi; I find this idea very intriguing and want to start using it in a real world app, but there are quite a few unknowns I would like cleared up first.

I'm curious if it's possible to abort an outstanding xhr request that was fired via a promise, as a result of a generator invocation? I have poured over a ton of different blogs / specs talking about generators and their relation to promises, but I haven't found any instances of this behavior. Bluebird 3.0 offers a pipeline for cancellation, but I'm not sure if it's possible to both yield a promise (and use its value on success) and cancel that generator (and then cancel the promise)?

```javascript
    function* doFetch(id) {
        let req
        try {
            // I want to be able to do something like this....
            yield req = xhr({
                method: 'GET'
                , url: `${api.fetchEndpoint}/${id}`
            })
        } catch (e) {
            // on cancel abort the xhr
            if (e instanceof io.SagaCancellationException) {
                req.cancel()
            }
        }
    }

    function* fetchThing(id) {
        try {
            const { body } = yield io.call(doFetch, id)
            // do stuff with the response body
        } catch (e) {
            // capture SagaCancellationException, and any js errors
            // resulting from an early exit of the yield call (such as body is not defined)
        }
    }

    // the root saga generator
    function* root() {
        let fetch
        while (true) {
            const { thing } = yield io.take(actions.SELECT_THING)

            // if user selects a different thing, cancel current fetch
            if (fetch && fetch.isRunning()) {
                yield io.cancel(fetch)
            }

            fetch = yield io.fork(fetchThing, thing.id)
        }
    }
```

What's the right way to go about this, assuming it's possible at all?

A `yield req = xhr()` continues immediately (as shown by a console.log(req) -> { the promise object }), so I get an error in the fetchThing catch of "cannot read property 'body' of undefined", but if cancelled the `req` object *is* defined in the error block. On the other hand, a `req = yield xhr()` waits for the result before continuing, and properly returns the xhr request body, but if cancelled `req` is not defined in the error block.

**Comment by wmertens** [comment]
Promise cancellation is still under discussion. Whatwg fetch (the next-gen xhr) is discussion cancellable fetching separate from promises here: https://github.com/whatwg/fetch/issues/27 (interesting but very long)

**Comment by yelouafi** [comment]
@aft-luke I think the `undefined` issue is that you dont return a value from `doFetch` (`return (yield req = ...)`)

Regarding cancellation, redux-saga cancels only the effects it creates itself (called sagas, take effects). raw promise cancellation is a no-op since this is not yet supported by the standard.

**Comment by aft-luke** [comment]
I realize cancellation is not standard yet, but my favorite promise library [bluebird](https://github.com/petkaantonov/bluebird/blob/master/API.md) does support cancellation, and I have a decorated/promisified xhr library that will xhr.abort() when told.

Thanks again @yelouafi, you are right. I'm not sure I totally understand the syntax here, but `return (yield someVar = ... ))` makes `someVar` declared inside a catch block.

**Comment by aikoven** [comment]
@aft-luke `redux-saga/lib/proc` module exports `CANCEL` symbol. You can use it to add cancellation to any promise:
```js
import {CANCEL} from 'redux-saga/lib/proc';

promise[CANCEL] = () => { /* cancellation logic */ }
```
