### ISSUE TITLE
Sagas catching errors unrelated to direct execution

### ISSUE THREAD

**Issue by ronaldheft** [yelouafi/redux-saga#491]
I have a crazy scenario which is happening, and I'm hoping someone can help me figure out if I'm fundamentally doing something wrong with my sagas or this is expected behavior.

Given a saga and React component that look like the following:

```
saga.js:

[...]

try {
   yield put({type: 'UPDATE_VAR', payload: 1});
} catch (e) {
   console.log(e);
}

[...]
```
```
component.js:

[...]

componentWillReceiveProps(props) {
   if ( props.var === 1) {
      throw new Error('ERROR!');
   }
}

[...]
```

So, in this scenario, the saga is dispatching a state update that eventually propagates to the connected component. The connected component throws an error as a result of the state update, which is propagated all the way back to the saga.

I'm a little confused as to why this is happening. Is the React component deeply connected to the call stack of the saga through redux? I would not expect an error throw as a state change to be on the same call stack, but maybe that's how it works.

I don't think this is necessarily a problem, but it's certainly made me more aware of the complexities of error handling! 😄

**Comment by jrvidal** [comment]
I think the flow is something similar to:

`put` -> `dispatch` -> your `reducer` -> listener function created by `connect` -> `setState` on the connected component -> (Rendering happens to occur synchronously [not always the case]) -> `componentWillReceiveProps`

**Comment by ronaldheft** [comment]
Thanks for confirming I'm not crazy, @jrvidal! The more I think about it, this makes complete sense. I was operating under an assumption that React's render would be async, but from what I've seen, yeah, that's not always the case.
