### ISSUE TITLE
Middleware vs sagas ?

### ISSUE THREAD

**Issue by julienR2** [yelouafi/redux-saga#492]
Getting familiar with redux, and sagas, I bumped into a choice between middleware and sagas.
Which are the differences between this:
```
export function * routerSagas() {
  while (true) {
    const { payload: { method, args } } = yield take(CALL_HISTORY_METHOD);
    if (method === 'push' ) {
       // change route
    }
  }
}
```

and this:
```
export default function routerMiddleware() {
  return () => next => action => {      
    if (action.type !== CALL_HISTORY_METHOD) {
      return next(action);
    }

    const { payload: { method, args } } = action;
    if (method === 'push' && typeof Actions[args[0]] === 'function') {
       // change route
    }
  };
}
```

Is it somehow related and sagas are an other way of writing middlewares ? Is there any one better than the other ?

Thanks for your help !

**Comment by Andarist** [comment]
Saga is another way of dealing with async and side effects than thunk-like middleware. So it is not exactly `an other way of writing middlewares` but another way of dealing with things you could do within middleware.

Saga is more robust and can give you way better structured code than the middleware approach for those scenarios.

**Comment by slorber** [comment]
A saga (as it is in redux-saga, also called process manager) is just a piece of software that receive events and emit new events.

You can achieve this pattern in a lot of different ways, including using a custom middleware.

It's just the redux-saga impementation based on generators is really interesting as it gives a good testability, and a good expressivity to handle complex currency patterns.

Here is a concrete example I gave: http://stackoverflow.com/questions/35411423/how-to-dispatch-a-redux-action-with-a-timeout/38574266#38574266
Good luck implementing this thing with redux-thunk, or a custom middleware

**Comment by julienR2** [comment]
Thanks a lot for these information !
It is still quite new for me so I was surprise to discover these two ways of achieving this pattern.

No doubt in the power of sagas in handling more complex behaviors. But performances speaking I would have think the sagas would be greedier than a middleware.. Or not ? 

Thanks again for theses details !
