### ISSUE TITLE
Communication between different saga engines via channels

### ISSUE THREAD

**Issue by sergej-s** [yelouafi/redux-saga#493]
Hello!

I'd like to have several redux stores in the same application and organize communication between them using saga channels. I tested this and it seems to work, but I want to be assured: is this approach allowable?

**Comment by Andarist** [comment]
I would say its normal usage. Shouldnt cause you any problems I think, but ofc I cant be sure as im not @yelouafi ;) 

However Im doing similar things with my channels. 

Also I dont see how communicating between stores would be different than communicating between sagas 'owned' by one store and the later is mentioned in the docs as one of main purposes of channels.

**Comment by sergej-s** [comment]
@Andarist Yes, I am thinking the same way, but hope @yelouafi confirm that saga engine supports this.

**Comment by yelouafi** [comment]
sorry for the delay. channels are official API (and meant to stay). using them for inter saga communication is all normal and even recommended
