### ISSUE TITLE
Need clarification: Is double cancellation possible

### ISSUE THREAD

**Issue by pke** [yelouafi/redux-saga#498]
I had this (obviously) faulty code:

```es6
function* authorizedFlow() {
  let payload
  while (({ payload } = yield take([actions.LOGIN_SUCCESS, actions.START_SIGNUP_SUCCESS]))) {
    const { access_token } = payload
    yield race({
      watchers: [
        call(logoutFlow, access_token),
        call(refreshUser, access_token),
        call(refreshInvoices, access_token),
        call(refreshPendingTransactions, access_token),
      ],
      logout: take(actions.LOGOUT_SUCCESS),
    })
    console.info("authorizedFlow: Logged out")
  }
}

function* logoutFlow(access_token) {
  while (yield take(actions.LOGOUT)) {
    try {
      yield call(api.logoutAsync, access_token)
      yield put(actions.logoutSuccess())
    } catch (error) {
      yield put(actions.logoutError(error))
    }
  }
}
```

What happened that when the `LOGOUT` was dispatched the `logoutFlow` started to wake up and end dispatching `LOGOUT_SUCCESS` as well as `LOGOUT_ERROR`. It did not always happen.
But the result was that `refreshUser`, `refreshInvoices` and `refreshPendingTransactions` were not cancelled and kept running.

I opened this issue because I want to verify that I understood and fixed the problem correctly.
When the `logoutFlow` emits the `LOGOUT_SUCCESS` action the `race` started in `authorizedFlow` ends with `logout` as the result. This means that all the `watchers` will be cancelled by redux-saga. `logoutFlow` is the first one in the `race` array and is cancelled first. This triggers the `catch(error)` and the `logoutFlow` dispatches the `LOGOUT_ERROR` action, but none of the other `race`'ed sagas were cancelled. My question is why?

And is this a proper fix:

```es6
function* authorizedFlow() {
  let payload
  while (({ payload } = yield take([actions.LOGIN_SUCCESS, actions.START_SIGNUP_SUCCESS]))) {
    const { access_token } = payload
    yield fork(logoutFlow, access_token)
    yield race({
      watchers: [
        call(refreshUser, access_token),
        call(refreshInvoices, access_token),
        call(refreshPendingTransactions, access_token),
      ],
      logout: take(actions.LOGOUT_SUCCESS),
    })
    console.info("authorizedFlow: Logged out")
  }
}
```

I now fork the `logoutFlow` and its not part of the `race` anymore.
This seems to work now. I don't see any errors anymore and the sagas are all cancelled properly (as per console output).

Thanks for clarifying.

**Comment by Andarist** [comment]
That is probably cause `race` accepts only simple dictionaries and arrayed values are not treated properly there. In fact it might even be an accident that all 4 `watchers` were run.

Its kinda weird scenario that you have tried to race array of effects. How would you like it to behave in various situations? I mean like:
- what should happen if 1 effect from the array finishes? shouldnt one key finish when all effects in array completes?
- what should happen to the arrayed effects when effect under other key finishes?

**Comment by pke** [comment]
thanks @Andarist 
I found another problem with my code of `logoutFlow`. It runs in a loop, which is actually not necessary, because once you have logged out, you need to login again and get a new `access_token` anyway. So the `logoutFlow` would have to be forked again. Your cancellation of all watchers prevents it from actually running in a loop but the code is still wrong.
