### ISSUE TITLE
Saga being called multiple times

### ISSUE THREAD

**Issue by tengis** [yelouafi/redux-saga#502]
**version: 0.11.0**

i have exactly same issue explained here #471 but his solution didn't work on my case.

**My code**

```javascript
function* submit(action) {
  console.log('saga submit');
}

export function* watchSubmit() {
  yield* takeEvery(SUBMIT_FORM, submit);
}
```

**My scenario:**

1. First time full refresh browser - click the submit button which dispatches action once & saga once.
2. Change the location using react router then go back to previous route click the submit button again - which dispatches action once & saga twice. So every time do this saga will executed increasingly. 

So console log look like:
![screen shot 2016-08-22 at 4 52 34 pm](https://cloud.githubusercontent.com/assets/358442/17845932/e2cabdde-6888-11e6-90be-bd006192e3d9.png)

Any help or suggestion most appreciated 

Thanks

**Comment by Andarist** [comment]
Crucial here is how and when do you run `watchSubmit`? Most likely you run it on every route change, so with each change you fire up this`takeEvery`.

**Comment by tengis** [comment]
@Andarist Thanks. That's exactly what was happened. 

So i made some research found this solution https://github.com/mxstbr/react-boilerplate/pull/390
