### ISSUE TITLE
Immutable values inside sagas 

### ISSUE THREAD

**Issue by tobyl** [yelouafi/redux-saga#503]
Hi there - totally NOT a bug, just a newbie question as I try to learn redux-saga..

I'm using immutablejs, and in my actions I have `payload: data` as an immutable map.

Once passed to my saga though, whenever I try to console log it I can only ever get `0` as the result. For example I'd like to be able to use:

`auth: call(authorize, { data, isRegistering: false }),`

But inside the saga `data` only ever seems to be `0`, not the immutable map sent by the action.

Any help greatly appreciated!

**Comment by Andarist** [comment]
Could you please post more code? How do you get your actions in saga, where is this call and what is authorize?

**Comment by tobyl** [comment]
My form values come from redux-form (v6.0.0-rc.5 with immutable support) and my submit function is:

```
showResults(values) {
    this.props.loginRequest(values);
  }
```
This is referenced is `mapDispatchToProps` like so:

```
function mapDispatchToProps(dispatch) {
  return {
    loginRequest: (values) => dispatch(loginRequest(values)),
    logoutUser: () => dispatch(logout()),
    dispatch,
  };
}
```
The action this is passed to is:

```
export function loginRequest(data) {
  return {
    type: LOGIN_REQUEST,
    payload: data,
  };
}
```
And finally, `authorize` is the saga that communicates with auth function:

```
export function* authorize({ data, isRegistering }) {

  yield put({ type: SENDING_REQUEST, sending: true });

  try {

    let response;

    if (isRegistering) {
      response = yield call(auth.register);
    } else {
      response = yield call(auth.login, data);
    }

    return response;

  } catch (error) {

    yield put({ type: REQUEST_ERROR, error: error.message });
    return false;

  } finally {
    yield put({ type: SENDING_REQUEST, sending: false });
  }
} 
```

Basically, I'm following [saga-login-flow](https://github.com/sotojuan/saga-login-flow), except in their [example](https://github.com/sotojuan/saga-login-flow/blob/master/app/sagas/index.js#L30-L61) they are simply passing the plain strings, whereas I'm trying to work with an immutable object.

Many thanks for the response.

**Comment by tobyl** [comment]
Sorry - just saw your example, trying that now - thanks again!

**Comment by tobyl** [comment]
Your example totally makes sense - but the console log in `authorize` now shows `undefined`.

To clarify, my action is:

```
export function loginRequest(data) {
  console.log(data);
  return {
    type: LOGIN_REQUEST,
    payload: data,
  };
}
```

and that console log **DOES** show the immutable map as expected. Could it because I'm using `yield race` ?

```
while (true) {
    const { data } = yield take(LOGIN_REQUEST);

    const winner = yield race({
      // auth: call(authorize, {data, isRegistering: false}),
      auth: call(authorize, { payload: data, isRegistering: false }),
      logout: take(LOGOUT),
    });

    if (winner.auth) {
      yield put({ type: SET_AUTH, newAuthState: true });
      forwardTo('/account');
    } else if (winner.logout) {
      yield put({ type: SET_AUTH, newAuthState: false });
      yield call(logout);
      forwardTo('/');
    }
  }
```

And:

```
export function* authorize({ payload, isRegistering }) {

  console.log('payload: ', payload);
  ...
```

**Comment by tobyl** [comment]
Well, I'm not sure why - but for some reason, using the es6 practice of switching:

`payload: data,`

to:

`data,`

In my action just completely fixed this. I might have been referencing something wrong, or the simplicification might have solved another problem I wasn't aware of - either way, this works.

Thank you so much for your help @Andarist !

**Comment by Andarist** [comment]
https://github.com/yelouafi/redux-saga/issues/503#issuecomment-241844258

in that comment you have a such line - `const { data } = yield take(LOGIN_REQUEST);`

and that was the wrong reference from what I see, you `LOGIN_REQUEST` action has shape of `{ type, payload }`, so you have extracted `undefined` from it.
