### ISSUE TITLE
redux-saga is a lot like an IO monad

### ISSUE THREAD

**Issue by paldepind** [yelouafi/redux-saga#505]
Hello @yelouafi.

I've been thinking about how redux-saga has a lot in common with the IO monad from purely functional languages. But you've likely realized that as well. I've been using redux-saga for a project at work and I'm thoroughly enjoying it. But even though I can understand that it was inspired by the saga pattern I always think of it as an IO monad :smile:

It occurred to me that the use of generators is reminiscent of Haskell's do-notation. In fact [Fantasy Do](https://github.com/russellmcc/fantasydo) uses generator functions to implement do-notation for fantasy land monads.

I've played a little with the idea of implementing an IO-monad in JavaScript and using it with Fantasy Do like do-notation. Do you think such a thing is viable? One restriction would be that the do-notation would only allow one to `yield` IO-monad's whereas redux-saga gives the user a lot of flexibility about what to `yield`.

I can see that there has previously (#16) been talk about decoupling redux-saga from redux. What is your thoughts about that now? I think a general purpose declarative effects library for JS could be interesting albeit probably not to an audience as wide as the Redux userbase.

**Comment by slorber** [comment]
Hi,

I've often compared redux-saga to an hybrid between imperative programming and free monad.

The flow of redux-saga, often using while looks and sequential operations look like imperative programming, but the effects you can yield that are run against an interpreter look like the free monad. The difference between IO and Free is that with Free being that Free can be interpreted while IO can only be run.
See also: http://stackoverflow.com/a/34623840/82609

After that I'm not a FP guru.

Don't know if this thing has been done in other FP languages for now.
I tried to ask John de Goes which seems expert in Free and didn't found much: https://twitter.com/sebastienlorber/status/763664957846216704

For example in Scala, people use Free monad, but they have to chain sequential calls in a monadic way, and can't use imperative logic. In Scala, async/await is implemented as a language extension and uses macros, and it's the closest we have to this imperative style programming afaik. Not sure to have seen the equivalent of JS generators in any languages so far but would be interested to know if there are some :)

**Comment by yelouafi** [comment]
>I've been thinking about how redux-saga has a lot in common with the IO monad from purely functional languages

Yeah, I think it's due to the way JS Generators work: yield looks a lot like do notation in Haskell. But I'm not sure the IO monad models the *effect as data* concept (can be unit tested?). IO Seems like an opaque data type (although I don't know how IO is tested in Haskell).

as @slorber commented, redux-saga looks like a hybrid approach: individual Effects have some similarities with Free (model this thing as a Data structure which can be interpreted). OTOH control flow inside Generators looks like the imperative sequencing on IO monads.

>One restriction would be that the do-notation would only allow one to yield IO-monad's whereas redux-saga gives the user a lot of flexibility about what to yield.

Another thing is related to concurrency, In redux-saga you can fork tasks *in parallel*, join and cancel them. Monads by nature are sequential. I think Haskell has a `forkIO` function but not sure how much control it gives over concurrency. 

>I've played a little with the idea of implementing an IO-monad in JavaScript and using it with Fantasy Do like do-notation. Do you think such a thing is viable? 

Generators have one limitation though: they can't be started from an arbitrary point, this can cause weird problems when the monad calls the chain function multiple times (eg: Array monad), especially when chained blocks have visible side effects. Do Fantasy has a [special multi mode](https://github.com/russellmcc/fantasydo#multi-mode) to handle this.

>I can see that there has previously (#16) been talk about decoupling redux-saga from redux. What is your thoughts about that now? I think a general purpose declarative effects library for JS could be interesting albeit probably not to an audience as wide as the Redux userbase.

yeah. and another concern is about maintaining 2 repos (one for the core lib and another for just the middleware). Likely most of redux-saga issues will be related to the core Generator driver so either We'll have to ask redux-saga users to post issues on the core lib repo; or we'll have to duplicate them in the core repo. Each solution can be very confusing for either part (user or maintainer).

**Comment by mxstbr** [comment]
> and another concern is about maintaining 2 repos

You could go with a monorepo with the two packages in the same repo! That'd solve the issue problem

**Comment by paldepind** [comment]
Thanks for the great replies :smile:

@slorber 

> I've often compared redux-saga to an hybrid between imperative programming and free monad.

> The flow of redux-saga, often using while looks and sequential operations look like imperative programming, but the effects you can yield that are run against an interpreter look like the free monad. The difference between IO and Free is that with Free being that Free uses data structures and can be tested / transformed / interpreted while IO is more like a thunk that can only be run.
See also: http://stackoverflow.com/a/34623840/82609

I have seen that you've mentioned the Free monad in other threads. It's very interesting. I have been reading a bit about the Free monad. I don't really understand it yet but I partly understand the similarity with redux-saga. In Haskell a function with the type `Integer -> IO (String)` conceptually returns a description of an action that produces a `String` when executed. In this sense it is very similar to redux-saga. But as you mention, the difference is that `IO` is completely opaque unlike saga actions that can be inspected and tested. If I understand correctly then `Free` accounts for this since it can be used to build up transparent AST structures that can be interpreted in several ways. But in the special case where the AST is simply executed it is similar to the IO monad. That is my current understanding. Please correct me if I'm wrong.

@yelouafi 

> But I'm not sure the IO monad models the effect as data concept (can be unit tested?). IO Seems like an opaque data type (although I don't know how IO is tested in Haskell).

You are indeed right that `IO` is opaque, but conceptually it's just data. I guess the reason for the opaqueness is so that it allows for `IO`-code to be compiled into efficient machine code where the `IO` construct doesn't exist at run-time.

Testing `IO` code in Haskell is much like testing imperative JavaScript code: hard and messy :sob: It certainly doesn't have the advantages that redux-saga has.

> Another thing is related to concurrency, In redux-saga you can fork tasks in parallel, join and cancel them. Monads by nature are sequential. I think Haskell has a `forkIO` function but not sure how much control it gives over concurrency.

Monads are indeed sequential. But each line in a saga is also executed sequentially isn't it? Line number 2 in a saga is never run before line number 1? It seems to me like it matches monads. I actually think the asynchronous features in redux-saga are covered by concurrency in the `IO` monad. `fork` in saga is like [`forkIO`](https://hackage.haskell.org/package/base-4.9.0.0/docs/Control-Concurrent.html#v:forkIO), `call` in saga is like a blocking `IO` action, `cancel` in saga is like [`killThread`](https://hackage.haskell.org/package/base-4.9.0.0/docs/Control-Concurrent.html#v:killThread).

> Generators have one limitation though: they can't be started from an arbitrary point, this can cause weird problems when the monad calls the chain function multiple times (eg: Array monad), especially when chained blocks have visible side effects. Do Fantasy has a special multi mode to handle this.

Yes. That is a quite sad restriction. Especially because it breaks the abstraction in Fantasy Do. You can't use the same do-notation with all monads. To solve this and other issues I'm working on a fantasy land replacement, [jabz](https://github.com/paldepind/jabz). I'm planning to specify it so that each monad must declare if it is multi or not. Then do-notation can be implemented so that it works for all monads and without the awkwardness in Fantasy Do.

**Comment by yelouafi** [comment]
@mxstbr looks interesting! I'll have to look at this

**Comment by danny-andrews-snap** [comment]
I've always gotten around the difficulty in testing `IO` code by using the `Reader` Monad. It's essentially the `IO` Monad that lets you pass config through your application. I use this as a lightweight dependency injection framework which allows me to pass a spy in my tests in place of the actual method (e.g. `console.log`) and make assertions on how it is called (e.g. it was called twice).

Examples can be found here: https://github.com/danny-andrews/circleci-weigh-in/tree/master/src/effects/__tests__.

p.s. I believe QuickCheck is the goto way to test IO-using Haskell programs, although I have absolutely no idea how it works. 😜
