### ISSUE TITLE
[BUG] take defined with matcher will allways take from the buffer

### ISSUE THREAD

**Issue by Andarist** [yelouafi/redux-saga#507]
Snippet to reproduce
```
	const chan = channel()
	yield put(chan, { type: 'OTHER_ACTION' })
	yield fork(function* () {
		while (true) {
			const action = yield take(chan, 'TEST')
			console.info('action', action)
		}
	})

	yield put(chan, { type: 'TEST' })
	yield put(chan, { type: 'JUST_ANOTHER_ACTION' })
```

If `buffer` is not-empty during a `take` effect channel will always `take` from it, completely ignoring the `matcher` argument. 

Possible solution? implementing `matcher` arugment in `buffer.take`?

**Comment by yelouafi** [comment]
I'm not sure this should be considered a bug. 

the `matcher` argument is not exposed as a public API. but used internally for the special case of resolving store actions `yield take(ACTION)`. Store actions are handled internally using an eventChannel with no buffering. So when matcher is provided to the channel we'll always have an empty buffer
