### ISSUE TITLE
How to use yield call() from an external API callback?

### ISSUE THREAD

**Issue by davidwparker** [yelouafi/redux-saga#508]
Hello! 

I'm using an external API (Firebase), which uses callbacks. I'm not 100% sure what's the best approach to converting the callbacks to something usable by redux-saga because of its use of generators.

Code:
```javascript
    const database = firebase.database();
    const connectionRef = database.ref('.info/connected');
    connectionRef.on('value', (snapshot) => {
      if (snapshot.val() === true) {
        yield call(actions.connected);
      }
    });
```
Action:
```javascript
    export const connected = () => {
      return {
        type: types.FIREBASE_CONNECT,
      };
    };
```
Reducer:
```javascript
    const connectionStatus = (state: boolean = initialState, action: Object) => {
      switch (action.type) {
      case types.FIREBASE_CONNECT:
        return true;
      default:
        return state;
      }
    };
```
I can't use `yield` because the callback isn't a `*` generator function. 

What's the correct approach to converting it in a manner that's good for redux-saga to handle?

BTW, I've really been enjoying redux-saga- it's been fantastic to use, thanks!

**Comment by aikoven** [comment]
You can wrap your code to a function that returns promise, something like

```js
function connect() {
  return new Promise(resolve => {
    const database = firebase.database();
    const connectionRef = database.ref('.info/connected');
    connectionRef.on('value', resolve);
  });
}
```

Then use it in saga:

```js
const snapshot = yield call(connect);
if (snapshot.val() === true)
  yield put(actions.connected());
```

**Comment by Andarist** [comment]
@aikoven this Promise will resolve just once, if he wants to get multiple values over time from the firebase callback it is not a suitable solution unfortunately

what i came up to in my project is that - https://github.com/yelouafi/redux-saga/issues/475#issuecomment-239129811

**Comment by aikoven** [comment]
@Andarist You're right, in this case using channels is a way to go.

**Comment by davidwparker** [comment]
@aikoven - Yeah, I tried the promise route already, I should have mentioned that it needs to fire more than once.

@Andarist - thanks, I'll try what you came up with and see if that works for me as well.

**Comment by davidwparker** [comment]
@Andarist - works perfectly, thanks!

@yelouafi - do you recommend @Andarist's suggestion as the preferred way? If so, is it worth it if (I or someone else) adds some documentation around handling callbacks like this? 

Cheers!

**Comment by thieu75** [comment]
Hi !
I would appreciate to see part of your code on this topic in order to help me to ease the learning curve :)

**Comment by davidwparker** [comment]
@thieu75 

sagas:
```javascript
function *rootSaga() {
  yield [
    appSagas.watchConnectionStatus(),
  ];
}
```

sagas/applications
```javascript
import { channel } from 'redux-saga';
import { call, put, take } from 'redux-saga/effects';

import firebase from 'firebase';
import { firebaseCallbacks } from 'modules';

export function *connectionStatusChange(): Generator<void, void, void> {
  const connectionStatusChannel = channel();
  const connectionStatus = firebaseCallbacks.connectionStatusWrapper(connectionStatusChannel);
  const connectionRef = firebase.database().ref('.info/connected');
  connectionRef.on('value', connectionStatus);

  while (true) {
    const action = yield take(connectionStatusChannel);
    yield put(action);
  }
}

// @no-test-needed
export function *watchConnectionStatus(): Generator<void, void, void> {
  yield call(connectionStatusChange);
}
```

firebase
```javascript
import actions from 'modules/actions';

function connectionStatusWrapper(channel) {
  function connectionStatus(snapshot) {
    if (snapshot.val() === true) {
      channel.put(actions.connected());
    }
    else {
      channel.put(actions.disconnected());
    }
  }

  return connectionStatus;
}

export default connectionStatusWrapper;
```

actions
```javascript
// firebase actions
export const connected = () => {
  return {
    type: types.FIREBASE_CONNECTED,
  };
};

export const disconnected = () => {
  return {
    type: types.FIREBASE_DISCONNECTED,
  };
};
```

reducer connectionStatus:
```javascript
// @flow
import { ActionTypes as types } from 'modules/constants';

const initialState = false;

const connectionStatus = (state: boolean = initialState, action: Object) => {
  switch (action.type) {
  case types.FIREBASE_CONNECTED:
    return true;
  case types.FIREBASE_DISCONNECTED:
    return false;
  default:
    return state;
  }
};

export default connectionStatus;
```

**Comment by marsonmao** [comment]
@davidwparker I kinda not understand why Andarist said that `this Promise will resolve just once`, and what 's the difference between your final solution and aikoven's?

It looks that `connectionStatusChange` is executed 1 time, so that `connectionRef.on('value', connectionStatus);` is executed 1 time, then there would be either `channel.put(actions.connected());` or `channel.put(actions.disconnected());` executed 1 time, so finally `yield put(action);` in the while loop dispatches one of em?

I think I am wrong, but I dont understand why. Hope that you could explain it!

**Comment by Andarist** [comment]
It really is about how do u want to structure your code. Problem with `Promise`s as I've mentioned is that they provide a SINGLE value and that's all.

You can ofc wrap this one in a Promise and just listen to that promise with an infinite while loop fashion, but you would have to remember to clear up the subscription in the callback, like this:
```js
function connect() {
  return new Promise(resolve => {
    const database = firebase.database();
    const connectionRef = database.ref('.info/connected');
    connectionRef.on('value', val => {
      connectionRef.off('value', resolve)
      resolve(val)
    });
  });
}
```

By wrapping the thing not in a Promise but in a channel you allow the underlying source (firebase here) to emit MULTIPLE values over time to the channel and you will be able to take from that channel and act appropriately on the received items.

**Comment by weishijun14** [comment]
Hi, I got some question about yield ..
```
*queryAppid({ payload },{ put, call }){
     wx.ready(function(){
        wx.getLocation({
          type: 'wgs84', 
          success: function (res) {
            let latitude = res.latitude; 
            let longitude = res.longitude; 
            let speed = res.speed; 
            let accuracy = res.accuracy; 
           
           //when get latitude and  longitude  then getLocation.
            var map = new BMap.Map("l-map");
            map.centerAndZoom(new BMap.Point(longitude, latitude));
            var myGeo = new BMap.Geocoder();
            myGeo.getLocation(new BMap.Point(longitude, latitude), function(result){
              if (result){
                //when I get result ,I want to dispatch an Action 
                yield put({ type: 'someAction' , payload: { location: result.address} })
              }
            });
          }
        });
}
```
When wx is ready then getLocation if success then callback ,I want use yield put in it, but I dont know how to do with it, can someone help me ~ appreciate !!

**Comment by Andarist** [comment]
Its basically the same situation. You need to wrap your data source in the eventChannel, emit items from it and just `take` those items from the saga. Something like this:
```js
function queryAppid({ payload },{ put, call }){
     return new eventChannel(emit => {
      wx.ready(function(){
        wx.getLocation({
          type: 'wgs84', 
          success: function (res) {
            let latitude = res.latitude; 
            let longitude = res.longitude; 
            let speed = res.speed; 
            let accuracy = res.accuracy; 
           
           //when get latitude and  longitude  then getLocation.

            var myGeo = new BMap.Geocoder();
            myGeo.getLocation(new BMap.Point(longitude, latitude), function(result){
              if (result){
                emit(result)
              }
            });
          }
        });

        return () => {
          // return some unscubscribe function here
        }
     })
}

function* someSaga() {
  const payload = ...
  const chan = queryAppid({ payload })
  while (true) {
    const result = yield take(chan)
    yield put({ type: 'someAction' , payload: { location: result.address} })
  }
}
```
