### ISSUE TITLE
[Question] Is triggering effects before reducers possible?

### ISSUE THREAD

**Issue by darkalor** [yelouafi/redux-saga#509]
As the docs state, all actions in a saga after a `yield take ACTION_NAME` happen *after* the reducers have fired. What if I want a sequence that needs some actions to happen *before*? I.e. something like `onBefore()` -> `reducer()` -> `onAfter()`. 

Currently I'm using an additional middleware, that intercepts actions similar to sagas, however that's not a good solution, as it means that I have to duplicate the logic of handling different action types.
Alternatively, some sort of handling like that could be done in the action creators (before returning the action), but that makes them have multiple responsibilities, which does not seem right either.

I'd prefer to have sagas as my single point of handling any additional effects. Does anyone have any solutions for something like that?

**Comment by Andarist** [comment]
well, sagas are not for intercepting actions, just to handle side effects of them, if you want to act on action before it hits reducer you need to dispatch action which will not be handled by reducers (unknown to them), handle it in the saga and dispatch other action upon completion so it can be handled by reducers

```
function* saga() {
	while (true) {
		const action = yield take('BEFORE_REDUCERS')
		// handle action 
		// ...
		yield put({
			...action,
			type: 'HIT_REDUCERS'
		})
	}
}
```

**Comment by darkalor** [comment]
> well, sagas are not for intercepting actions, just to handle side effects of them
Right, however the state could influence the way that the side effect is processed (e.g condition based on `select`), and we're always going to hit the store after the reducer was executed.

I've thought about doing multiple actions, as in your example, but this is not really viable if there's a lot of actions and only some of them can have additional "before" logic. I.e. this would kind of make your reducers aware of the additional processing in sagas, since some actions would have to be handled by original names, and some - by the new names.

**Comment by Andarist** [comment]
Well, if `state could influence the way that the side effect is processed (e.g condition based on select)` then you dont really have a problem, cause your `take` effect will execute after store's update. 

Follow 'splitting actions into 2' pattern only if you need that before logic.

**Comment by ms88privat** [comment]
@darkalor I wrote a related article about this https://medium.com/@marcelschulze/using-react-native-with-redux-and-redux-saga-a-new-proposal-ba71f151546f#.mp66tk62d
