### ISSUE TITLE
Subscribing to websocket events 

### ISSUE THREAD

**Issue by emirotin** [yelouafi/redux-saga#51]
Hi. I would really appreciate some clarification om how to handle my case.
Sorry for a bit lengthy explanation, but I'd like to describe every bit involved.

I have several sagas:
1. XHR API middleware that takes the API request action, calls the API, waits for the promise to resolve, etc. Pretty standard and I have no issues with it. It uses an isolated "service" module to make the actual XHR calls.
2. Websocket middleware that has 3 different sagas: connect, subscribe, emit. It uses an isolated service (which essentially wraps the socket.io-client lib). The `connect` method returns a promise (and works OK). The `emit` method is synchronous, works fine as well. The `subscribe` method is the one that baffles me. The issue here is that events from the socket can happen _multiple times_, so I cannot promisify this method. See below for how I use it.
3. The actual "meat" saga that has to do the following: `take` the XHR success event for a specific resource (chat rooms list), subscribe to the websocket events for the new messages, and emit the subscription websocket event (that will actually put the current client into the listeners list for the given char rooms on the server).

Now here's how the latter saga looks:

```
export default function* myRooms(getState) {
  while (true) {
    yield take(MY_ROOMS_SUCCESS) // works OK

    yield put(subscribeSocket({ // it's sent and taken just fine in the other saga
      event: 'newMessage', // the name of the socket.io event to subscribe to
      actionType: MY_ROOMS_NEW_MESSAGE // the name of the action to dispatch
    }))

    const state = getState()
    const roomIds = ... // get the IDs of the chat rooms
    yield put(emitSocket({
      event: 'subscribe', // the name of the socket.io event to emit
      payload: roomIds
    }))
  }
}
```

Now for the socket subscription saga:

```
function* subscribeSocket(getState) {
  while (true) {
    const nextAction = yield take(SUBSCRIBE_SOCKET)
    const subscribeConfig = nextAction.payload
    const { event, actionType } = subscribeConfig
    const callback = (payload) => put({ type: actionType, payload }) // <-- here
    const unsibscribe = socket.subscribe(event, callback)
  }
}
```

So the subscription saga gets the socket event name to listen to, and the action type name to dispatch together with the event payload.
I can tell from the debugging that the `callback` is actually executed. As far as I understand the problem here is the improper `put` usage.

The question is: what is the proper usages of sagas in this case? I want to dispatch the `actionType` every time the `callback` is called.

Thanks in advance!

**Comment by jedwards1211** [comment]
Here's an idea.  Fork a subtask that:
* subscribes to the websocket events
* enters a while loop that:
  * yields a Promise that gets fulfilled with the next websocket message when it comes in
  * yields a `put` for that message.
* catches cancelation exceptions and unsubscribes when that happens

**Comment by jedwards1211** [comment]
I have to say though, I wonder if redux-saga really provides a clear advantage for subscribing to things over a simple custom middleware that just dispatches the events/messages from a websocket/whatever as they arrive.  It seems like testing might be easier with redux-saga.  Does anyone else have an opinion on this?

**Comment by emirotin** [comment]
Thanks for the idea.
redux-saga works well for the XHR middleware and for the general orchestration, that's why I tend to keep the socket stuff there as well

So now I have this:

```
function* listenToSocket(event, actionType) {
  let promise
  let resolveFn
  const callback = (payload) => {
    resolveFn(payload)
  }
  const unsibscribe = socket.subscribe(event, callback)

  while (true) {
    promise = new Promise(resolve => {
      resolveFn = resolve
    })
    const payload = yield promise
    yield put({ type: actionType, payload })
  }
}

function* subscribeSocket(getState) {
  while (true) {
    const nextAction = yield take(SUBSCRIBE_SOCKET)
    const subscribeConfig = nextAction.payload
    const { event, actionType } = subscribeConfig
    yield fork(listenToSocket, event, actionType)
  }
}
```

Which suprisingly works (insult towards my understanding of sagas, not your idea :)). But indeed looks less readable than a middleware that can call `store.dispatch` directly at any given time. I'd like to hear @yelouafi's opinion on this.

**Comment by yelouafi** [comment]
@emirotin I think this maybe related to [this SO question](http://stackoverflow.com/questions/34859932/can-i-use-redux-sagas-es6-generators-as-onmessage-listener-for-websockets-or-ev). The main point is

>To integrate external push sources, we'll need to transpose the Event Source from the push model into the pull model; i.e. we'll have to build an event iterator from which we can pull the future events from the event source

It joins somewhat your solution, but factor out the concept into a separate function. So the saga can be easily tested. You can find a jsbin live demo here https://jsbin.com/wumuri/edit?js,console

```javascript
// Event iterator for socket events
function socketEventIterator(event) {
  let deferred
  socket.subscribe(event, payload => {
    if(deferred) {
      deferred.resolve(payload)
      deferred = null 
    }
  }

  return {
    nextEvent() {
      if(!deferred) {
        deferred = {}
        deferred.promise = 
          new Promise(resolve => deferred.resolve = resolve)
      }
      return deferred.promise
    }
  }
}

function* listenToSocket(event, actionType) {
  const { nextEvent } = yield call(socketEventIterator, event)
  while (true) {
    const payload = yield call(nextEvent)
    yield put({ type: actionType, payload })
  }
}

function* subscribeSocket(getState) {
  while (true) {
    const nextAction = yield take(SUBSCRIBE_SOCKET)
    const subscribeConfig = nextAction.payload
    const { event, actionType } = subscribeConfig
    yield fork(listenToSocket, event, actionType)
  }
}
```

**Comment by emirotin** [comment]
Thanks for your response. Indeed a very similar question, though I tried searching before asking and it didn't come. I like the concepts separation, will update my code.

**Comment by aft-luke** [comment]
Perhaps I'm missing something here, but I'm dropping events across the websocket connection using this deferred method. 

It seems like this is a result of the event loop and next-tick mechanics, because if I change the code to this:
```javascript
  socket.subscribe(event, payload => {
    if(deferred) {
      deferred.resolve(payload)
      deferred = null 
    } else {
      console.log('dropped event', payload)
    }
  }
```

I get a whole lot of `dropped event` logs.

**Comment by yelouafi** [comment]
@aft-luke Yes the above method doesn't queue in-between events. The method on the SO does queue the events

**Comment by mjrussell** [comment]
I ran into the same issues, but ended up with a different solution. This is essentially using a link-list approach to queue up the messages:

```js
// Creates a chain of message promises, each promise (when resolved) has a payload and nextPromise 
// to wait for the next message
function socketMessageChain(socket) {
  let resolveNext;
  const headPromise = new Promise(resolve => resolveNext = resolve);

  socket.onmessage = event => {
    const resolveThis = resolveNext;
    const nextPromise = new Promise(resolve => resolveNext = resolve);
    resolveThis({ payload: JSON.parse(event.data), nextPromise });
  };

  return headPromise;
}
```

**Comment by gajus** [comment]
@yelouafi I am probably overlooking something, but the solution that you have proposed looks to me over-engineered.

Wouldn't this achieve the same result?

```js
function socketEventIterator (eventName) {
    let resolveNextValue,
        resolved;

    resolved = true;

    bridge.on(eventName, (event) => {
        resolveNextValue(event);

        resolved = true;
    });

    return () => {
        if (!resolved) {
            throw new Error('Iterator can be used by only one agent.');
        }

        resolved = false;

        return new Promise((resolve) => {
            resolveNextValue = resolve;
        });
    };
}
```

or even

```js
function socketEventIterator (eventName) {
    return new Promise((resolve) => {
        bridge.once(eventName, (event) => {
            resolve(event);
        });
    });
}
```

**Comment by sslotsky** [comment]
Maybe this is a dumb question, but would it also be possible to do this using an event channel? Here's some totally untested code to serve as an example, am I way off base here? 

```javascript
function socketEmitter(subject) {
  return eventChannel(emitter => {
    const channel = channel(subject)
    channel.on('message', payload => {
      emitter(payload)
    })

    return () => {
      channel.removeAllListeners('message')
    }
  })
}

function* listen(subject, actionType) {
  const chan = yield call(socketEmitter, subject)
  try {
    while (true) {
      let payload = yield take(chan)
      yield put({ type: actionType, payload })
    }
  } finally {
    if (yield cancelled())
      chan.close()
  }
}

function* subscribe(subject, getState) {
  while (true) {
    const nextAction = yield take(SUBSCRIBE_SOCKET)
    const { subject, actionType } = nextAction.payload
    const listenTask = yield fork(listen, subject, actionType)
    const unsubscribed = yield take(UNSUBSCRIBE_SOCKET)
    const { cancelledSubject } = unsubscribed.payload
    if (cancelledSubject == subject)
      yield cancel(listenTask) 
  }
}
```

**Comment by emirotin** [comment]
@gajus this seems to only fire _once_ for the given event?
But the purpose is to translate every occurrence of the event into an action.

**Comment by gajus** [comment]
> @gajus this seems to only fire once for the given event?
> But the purpose is to translate every occurrence of the event into an action.

Both implementations that I have proposed fire for every event.

We have been using this in staging env for over a week now.

**Comment by emirotin** [comment]
Interesting, I was confused by .once.

**Comment by gajus** [comment]
> Interesting, I was confused by .once.

`socketEventIterator` will be called every time the previous promise is resolved. Therefore, `once` binding will be created/ discarded upon each event.

For the record, we are using the first variation. I haven't extensively tested the `once` approach beyond ensuring that it is passing all the test cases.

**Comment by sslotsky** [comment]
For what it's worth, I got around to testing my code and it was almost correct. Here's a working version with `eventChannel`

```javascript
import { eventChannel, takeEvery } from 'redux-saga'
import { take, call, put, fork, cancel, cancelled } from 'redux-saga/effects'
import socket, { channel } from './socket'
import * as actionTypes from './constants'

function socketEmitter(subject) {
  return eventChannel(emitter => {
    socket.emit('track', subject)
    const newChannel = channel(subject)

    newChannel.on('tweets', tweets => {
      emitter(tweets)
    })

    return () => {
      newChannel.removeAllListeners('tweets')
      socket.emit('untrack', subject)
    }
  })
}

function* listen(subject) {
  const chan = yield call(socketEmitter, subject)
  try {
    while (true) {
      let tweets = yield take(chan)
      yield put({
        type: actionTypes.TWEETS_RECEIVED,
        subject,
        tweets,
        read: false
      })
    }
  } finally {
    if (yield cancelled())
      chan.close()
  }
}

function* subscribe(action) {
  while (true) {
    const listenTask = yield fork(listen, action.subject)
    const unsubscribed = yield take(actionTypes.STOP_TRACKING)
    if (action.subject == unsubscribed.subject)
      yield cancel(listenTask) 
  }
}

function* track() {
  yield* takeEvery(actionTypes.TRACK_SUBJECT, subscribe)
}

export default track
```

**Comment by m-2k** [comment]
```javascript
  yield* takeEvery(actionTypes.TRACK_SUBJECT, subscribe)
       ^
```
