### ISSUE TITLE
Buffer limit in `actionChannel`

### ISSUE THREAD

**Issue by akoenig** [yelouafi/redux-saga#511]
We use `redux-saga` for our internal tracking pipeline and we love it a lot. It made the code structure a beauty :) Therefore, thanks for your effort!

Unfortunately, we identified a breaking change in the current release `v0.11.1`. #438 introduced a change of the internal buffer implementation, which is in fact a really solid implementation. We use the `actionChannel` for queuing tracking actions. The internal buffer implementation switched from `Infinity` to a buffer limit of `10`, which broke our tracking on mobile devices. Is it possible to define the buffer limit in the `actionChannel` call without defining an own `buffer` implementation?

Are you open for a PR which introduces the limit definition in the `actionChannel` call?

**Comment by Andarist** [comment]
What's wrong with passing custom buffer? you can use the one implemented in `redux-saga` and customize your buffer limit as you wish just by passing a second argument to the `actionChannel`, like so:

```
import { buffers } from 'redux-saga'
import { actionChannel } from 'redux-saga/effects'

//...
yield actionChannel(EXAMPLE_ACTION, buffers.fixed())
```

**Comment by yelouafi** [comment]
the new version v0.12.0 includes now a new type `buffer.expanding()` (https://github.com/yelouafi/redux-saga/releases/tag/v0.12.0) which behaves like the old `fixed`.
