### ISSUE TITLE
Select is returning a stale value

### ISSUE THREAD

**Issue by tomrj** [yelouafi/redux-saga#513]
Not sure if this is a misuse of generators or is this a real bug in sagas, but we have encountered some weird behaviour in code like this:

```
function* startSomething()  {
    yield call(updateDataForAdditional);
    const features = yield select(selectFeatures);
    const needMore = yield select(selectAdditional);

    if (needMore || features.length > 0) {
      if (needMore) {
        features.push('MORE'); // (*)
      }
      yield put(enableFeatures(features));
    } 
    yield put(somethingStarted())
  }
}

function* watchStartSomething() {
  while (true) {
    yield take("START_SOMETHING_TRIGGERED");
    yield call(startSomething);
  }
}
```

Here selectFeatures selector cannot return 'MORE'. What we observe however is that the select does do that on the second execution of startSomething, after the first execution has executed line '*'.

Are we misusing generators somehow here?

**Comment by Andarist** [comment]
I guess you are mutating the `features` with `push`. With `const features = yield select(selectFeatures);` you are grabbing the reference to some nested object in your `state` and then you are mutating its content so it gets updated in `state` too, so when you grab it again on the second run of `startSomething` you are geting mutated result and you will probably just `push` to it again so those `MORE` will just pile up in your state.

I would suggest to `const [...features] = yield select(selectFeatures)`

**Comment by tomrj** [comment]
I'm not sure this is the case. The value returned by `selectFeatures` is returning a copy of ImmutableJS Seq converted to a native array with toJS. Also, `selectFeatures` cannot return 'MORE' in any circumstance. The behaviour is somewhat surprising, unless you consider the generated code (Babel's take below), where the reference of `features` is declared outside the generator body.

I haven't yet dug into how sagas step the generators here, but if there is a programming error on my part here, I cannot still determine what it is.


```
function startSomething() {
  var features, needMore;
  return regeneratorRuntime.wrap(function startSomething$(_context) {
    while (1) {
      switch (_context.prev = _context.next) {
        case 0:
          _context.next = 2;
          return select(selectFeatures);

        case 2:
          features = _context.sent;
          _context.next = 5;
          return select(selectAdditional);

        case 5:
          needMore = _context.sent;

          if (!(needMore || features.length > 0)) {
            _context.next = 10;
            break;
          }

          if (needMore) {
            features.push('MORE');
          }
          _context.next = 10;
          return put(enableFeatures(features));

        case 10:
        case 'end':
          return _context.stop();
      }
    }
  }, _marked[0], this);
}

```

**Comment by Andarist** [comment]
Could you maybe try to post more code? Especially this selector - `selectFeatures`? Have you tried this `const [...features] = yield select(selectFeatures)`? (I know you are using Immutable so its probably not a case, but still ;))

It shouldnt matter that this `features` reference is outside in the closure in transpiled code, cause every `call` effect will call `startSomething` and thus create new references in 2 separate instances of this generator.
