### ISSUE TITLE
Silently swallowing errors. What patterns should we use to handle errors more specifically?

### ISSUE THREAD

**Issue by sebinsua** [yelouafi/redux-saga#521]
In the docs you recommend [this error-handling pattern](https://yelouafi.github.io/redux-saga/docs/basics/ErrorHandling.html):

```js
function* fetchProducts() {
  try {
    const products = yield call(Api.fetch, '/products')
    yield put({ type: 'PRODUCTS_RECEIVED', products })
  }
  catch(error) {
    yield put({ type: 'PRODUCTS_REQUEST_FAILED', error })
  }
}
```

However, I noticed that since `put` causes a `dispatch` this can error, and therefore `catch` can receive both `Api.fetch` errors and any error thrown when rendering a component.

Additionally, if a component errors during a `put`, and we then attempt to render again due to another `put` action within the catch-block it will (1) give you a `__reactInternalInstance` error, and (2) likely have swallowed the original error (there is no logger being used here).

I believe [*this tweet* by Dan Abramov actually refers to the same thing, but with promises instead of generators](https://twitter.com/dan_abramov/status/770914221638942720). As he points out further down [these errors thrown within a `dispatch` corrupt React's internal state, too](https://twitter.com/dan_abramov/status/770918163965997056).

Silently losing errors surely can't be the recommendation.

**What's a better pattern for handling errors with `redux-saga`?**

**Comment by yelouafi** [comment]
The issue with try/catch in JavaScript is there is no way to have error specific catch like in Java or C#

```js
try {
 ...
} catch (MySpecificError err) {
  will catch only MySpecificError erroros
  other errors (like React or runtime JS errors) should bubble up
}
```

because of this, I believe that in Javascript (and not just in Redux-saga) *expected errors* (business errors like in ajax fetches) shouldn't be communicated using try/catch but using explicit return values

```js
function* fetchProducts() {
    const {response, error}= yield call(Api.fetch, '/products')
    if(response)
       yield put({ type: 'PRODUCTS_RECEIVED', products: response })
    else
      yield put({ type: 'PRODUCTS_REQUEST_FAILED', error })
}
```

This will let all other *unexpected errors* (bugs) bubble up to the root and can be caught for crash reports

**Comment by sebinsua** [comment]
Thanks for your response!

I wrote a set of utilities to handle these types of issues and to ease writing basic sagas: [**`redux-saga-helpers`**](https://github.com/sebinsua/redux-saga-helpers)

Hopefully others find the functions useful. :)
