### ISSUE TITLE
try catch bug?

### ISSUE THREAD

**Issue by swamikevala** [yelouafi/redux-saga#522]
yield in try block is getting executed even when I get a 400 HTTP error back from the api.
then the yield in the catch block is also getting executed

```
export function* searchContacts(query) {
  try {
    const contacts = yield call(apiSearchContacts, query)
    yield put({ type: "CONTACTS_RECEIVED", data: contacts })
  }
  catch(error) {
    yield put({ type: "CONTACTS_REQUEST_FAILED", error })
  }
}
```

```
export function apiSearchContacts(query) {
	return fetch("https://qa-api.isha.in/v1/in/contact/api/contact/search", {
		method: 'post',
		headers,
	  body: JSON.stringify({ 
	  	matchValues: query
	  })
	}).then(response => response.json())
}
```

**Comment by Andarist** [comment]
I have just tried your exact code and everything is like expected - got `400` error from the API response and only `CONTACTS_REQUEST_FAILED` got dispatched.

**Comment by swamikevala** [comment]
see my output of redux devtools

[redux-devtools-output.zip](https://github.com/yelouafi/redux-saga/files/452261/redux-devtools-output.zip)

If I handle the error in my Api code then it works: 

```
}).then(response => {
		if (response.status >= 400) {
			throw new Error("Bad response from server");
		}
 		return response.json();
	})
}
```
But it still shouldn't be executing the yields in both the try and catch blocks

**Comment by Andarist** [comment]
Could you maybe make a jsfiddle with minimal test case?

**Comment by swamikevala** [comment]
[](https://jsfiddle.net/o0ge38L3/21/)

I have taken the relevant parts of my app and put in jsfiddle... However, I'm not able to get it working due to some error with the generator functions

Hope this is of some help

**Comment by Andarist** [comment]
Could you share this, even not working, fiddle here?

**Comment by swamikevala** [comment]
[https://jsfiddle.net/o0ge38L3/21/](https://jsfiddle.net/o0ge38L3/21/)

**Comment by Andarist** [comment]
I've made just few minor changes (just to make it work) here - http://www.webpackbin.com/Vygh0vIo-

And everything works as expected, I got in the console just those 2 messages
```
searchContacts(query)
catched error from apiSearchContacts
```

**Comment by swamikevala** [comment]
This is not a bug. I thought that receiving 400 HTTP error from fetch should trigger the catch block only. (I didn't realise that fetch still considers this a "success" response). 

Maybe worthwhile putting a note in the docs about this - since may be a common misconception

Am closing this

**Comment by neurosnap** [comment]
the fetch documentation makes it clear, only network errors are thrown, any response that contains a status response is not thrown
