### ISSUE TITLE
docs: 1.2 Saga background—replace with first part of README

### ISSUE THREAD

**Issue by mheiber** [yelouafi/redux-saga#524]
Section 1.2 of the current docs, "Saga background" consists of "WIP" and links to papers and a video.

My suggestion is to replace this with the (excellent) introduction at the start of the README.

Reason: Sagas, as described in the original papers and the presentation:

> ... LLT [long-lived transaction, lasting hours or days] that can be broken up into a series of sub-transactions that can be interleaved in any way with other transactions ... each saga transaction ... should be provided with a compensating transaction ... such that [either all of the transactions in the saga run or all of the transactions + all of the compensating transactions run]

have almost nothing to do with redux-saga sagas.

The "A Saga on Sagas" paper, in spite of the title, is explicitly not about sagas in the sense of the original Sagas paper, but about process  managers, which also have little to do with redux-saga sagas.

I think it's confusing to refer in the docs to historical ideas that happen to share the same name, "sagas," but aren't that similar.. 

A brief intro to what redux-saga does and why it exists certainly belongs in the docs, in my opinion, and there's a good one in the README.

Happy to PR this if you're amenable.

**Comment by yelouafi** [comment]
>I think it's confusing to refer in the docs to historical ideas that happen to share the same name, "sagas," but aren't that similar..

I agree, but I think also that having an historical background (+ the mention that redux-saga's Sagas have a different meaning) could help avoiding confusion.

>Happy to PR this if you're amenable.

Sure, you're welcome.

**Comment by yelouafi** [comment]
Will delete the actial Saga section since it adds nothing but confusion and more fatigue. If anyone have an article on using Sagas in the context of react/redux apps, It'd be better.
