### ISSUE TITLE
Testing a 'yield put'

### ISSUE THREAD

**Issue by rpmonteiro** [yelouafi/redux-saga#525]
![image](https://cloud.githubusercontent.com/assets/7824615/18224790/176a1fb8-71d9-11e6-8563-d1bd80850184.png)

![image](https://cloud.githubusercontent.com/assets/7824615/18224795/68affcbc-71d9-11e6-9703-01b3487fcbac.png)

It doesn't seem right to just assert that a `PUT` exists... I want to test exactly what that `PUT` was.

How would you test this? I'm finding testing sagas to be a difficult task... all the examples I find are to test the trivial things, but there are no examples for testing 'real-life', complex sagas... 

Thank you for any help you might provide to this poor soul 👍

**Comment by Andarist** [comment]
you just create an effect in your test and check its deep equality against yielded one

```
next = gen.next()
expect(next.value).toEqual(put(itemDeleteSuccess()))
```

**Comment by rpmonteiro** [comment]
Haha looks so simple once you know it!

Thanks @Andarist !!

**Comment by rpmonteiro** [comment]
@Andarist what if the `yield put` is called with a TON of arguments? How do you test without passing all those args?

```
next = gen.next()
expect(next.value).toEqual(put(itemDeleteSuccess({
  superComplexObject: {
    thatNeverEnds: {...}
  }
})))
```

**Comment by Andarist** [comment]
Well, it probably depends on what do you want to test rly. You could play with this https://github.com/yelouafi/redux-saga/blob/b29b4315e729e45f71feb06f69c5afd7eee0e73e/src/utils.js#L2 to grab effect's payload and test what you want about it. Cause effects are just plain object, similarly to actions.
