### ISSUE TITLE
Action is being dispatched twice

### ISSUE THREAD

**Issue by surajsavita** [yelouafi/redux-saga#527]
Hey Guys,

First of all thanks for this great side-effects library \m/.

Secondly I got one small issue with the implementation described in the doc.
I have used async example to implement one todo app and the issue is actions are being dispatched twice once directly without going through sagaMiddleware and another one through sagaMiddleware.

So each and every Action which I am listening for using take side-effect is being dispatched to reducer directly as well as via saga.

Tried to go through stack trace as well but it just give me all this info. I can't figure out what's the issue in here.

Let me know if this is due to some configuration switch or what could cause this issue.

Cheers,
Suraj

**Comment by Andarist** [comment]
Could you post here code of your saga?

**Comment by surajsavita** [comment]
Here is the code: 

//configurStore.js:
export default function configureStore(preloadedState) {
  const sagaMiddleware = createSagaMiddleware()
  sagaMiddleware.run(rootSaga)
  return {
    ...createStore(rootReducer, applyMiddleware(sagaMiddleware)),
    runSaga: sagaMiddleware.run
  }
}

//saga/Index.js
export function FetchAPIActor(url = config.api_root, method = 'GET', payload = {}) {
  let request_map = {
    method: method,
    mode: 'cors',
    redirect: 'follow',
    credentials: 'same-origin',
    headers: new Headers({
      'Content-Type': 'application/json',
    }),
  }
  if (payload && ['PUT', 'POST'].indexOf(method) >= 0) {
    request_map.body = JSON.stringify(payload)
  }
  var request = new Request(url, request_map);
  console.log("REQUEST : ", request)
  return fetch(request)
    .then(response => response.json())
    .then(json => {
      console.log(json.data)
      return json.data
    })
    .catch(error => console.log("Fetch Error ", url, method, payload, error))
}

function* patchTodo() {
  while (true) {
    const {id, text} = yield take(actionTypes.EDIT_TODO)
    try {
      //yield call(patchFetchApi, config.api_root + `/mytodos/` + id, {todo: text})
      yield call(FetchAPIActor, config.api_root + `/mytodos/` + id, 'PATCH', {todo: text})
      yield put(Actions.editTodo(id, text))
    }
    catch (error) {
      console.log("PATCH TODO ERROR", error)
    }
  }
}

export default function* root() {
  yield [
//    startup(),
    patchTodo(),
  ]
}
//actionTypes.js
export function editTodo(id, text) {
  console.log("PATCH_TODO")
  return {
    type: types.EDIT_TODO,
    id,
    text
  }
}

//reducers/index.js
const initialState = []
export default function todos(state = initialState, action) {
  switch (action.type) {
    case EDIT_TODO:
      return state.map(todo =>
        todo.id === action.id ?
          Object.assign({}, todo, {text: action.text}) :
          todo
      )
    default:
      return state
  }
}

// So here I can see in console log "PATCH_TODO" is getting printed 2 times.

**Comment by Andarist** [comment]
That's cause sagas are not for intercepting actions, but for acting whenever 1 happens. So you are both listening for `EDIT_TODO` and dispatching `EDIT_TODO` in response for that. For it to work properly, you need to distinguish those 2.

For better understanding look into the source code here - https://github.com/yelouafi/redux-saga/blob/7b30115cc75ed121e3308fa8d5b274b5346120b0/src/internal/middleware.js#L50

As you can see the action is hitting reducers first and then emitted to the `redux-saga`

**Comment by surajsavita** [comment]
![image](https://cloud.githubusercontent.com/assets/5236276/18232085/0de978cc-72e6-11e6-83e2-f4f542c68558.png)

To me middleware seems more of a decorators wrapping the actual code like an onion layers so that you can run code before and after actual action being performed by reducers.
I have seen few examples too in redux-saga like async example which uses SELECT_REDDIT action in reducer as well as in sagas but runs only once on dropdown selection change.
It looks like I am missing some major point in here. 
Ref: https://www.codementor.io/reactjs/tutorial/intro-to-react-redux-pros

**Comment by Andarist** [comment]
You can dispatch action from the saga and run code in reducers at the same
action. Just do not listen for action A in the saga (with take) and then
dispatch action A, cause it will end up running ur reducers twice

**Comment by surajsavita** [comment]
Looks like I have to follow Database transaction like actions here: BEGIN --- Saga --- [COMMIT/ROLLBACK]

Thanks, It would do the job.
