### ISSUE TITLE
Async actions chaining best practices

### ISSUE THREAD

**Issue by gkaran** [yelouafi/redux-saga#531]
Hi there I started recently using redux-saga and must say that I really love it. I do face a situation though that I am not sure which is the best way to approach.

I have a route that creates a new resource in the server and if the creation is successful, then  a redirection should happen to another page. Now the problem is that those two actions not always come together meaning that I want to be able to create the resource without redirecting to another page. So I cannot strictly yield one action from inside the other like in the following;

````javascript
export function createResource(data) {
  return {
    type: CREATE_REQUEST,
    payload: data
  };
}

function *watch() {
  yield * takeEvery(CREATE_REQUEST, createTheResource);
}

function *createTheResource (action) {
  try {
    const data = yield call(Api.createTheResource, action.payload);
    yield put({ type: CREATE_SUCCESS, payload: { data } });
    yield call(routerAction.push, ....); // This should not be here always but happen on demand
  } catch (error) {
    yield put({ type: CREATE_FAILURE, payload: { error } });
  }
}
````

Now my question is, how do people handle those scenarios? How do you chain actions that are not always used together. A (perhaps naive ??) approach would be to wrap the actions the actions in another one like follows:

````javascript
function *createResourceAndRedirect (action) {
  yield * call(createTheResource, action);
  yield * call(redirectToPage);
}
````

Is this a proper approach though?

**Comment by Andarist** [comment]
Well, there must be some condition I guess and if its true then just `yield call(routerAction.push, ...)` and if not wait for some action to happen (with `yield take(...`) and *then* `yield call(routerAction.push, ...)`. You can branch it ofc in some separate generator like you have shown on the bottom of your post to avoid too much indentation.

**Comment by gkaran** [comment]
So in general this is the acceptable way to go. Thank you very much.
