### ISSUE TITLE
How to handle anonymous functions in a saga generator?

### ISSUE THREAD

**Issue by DTwigs** [yelouafi/redux-saga#532]
```
function* mySaga(todos) {
  yield call(delay, 1000);
  todos.forEach((todo) => {
    yield put(completeTodo(todo));
  });
}
```

The above is a contrived example but the yield inside of the forEach does not work because it is in an anonymous function that is not a generator.  Now I know I can use a standard `for` loop that doesn't utilize an anonymous function but I'm really curious as to how I can get the example above to work.  I use lodash which uses a lot of anonymous functions to loop through arrays/collections/etc. and it'd be helpful if someone could provide a pattern to get the above to work.

**Comment by Andarist** [comment]
Well, its not rly possible inside callbacks, cause `redux-saga` is pulling values out of your generatators by calling theirs `next` method. Just like you would create manually iterator by calling `const it = mySaga()` and then pull values out of it by `it.next()`.

And there is not way to delegate this inside the callback (as far as i know) so `next` could understand it.

I came up with this for dealing with callbacks - https://github.com/yelouafi/redux-saga/issues/475#issuecomment-239129811 . But it was for some other use case - forwarding things from other sources, like this db transaction callback described in the linked question. In your case I think that's really not worth to wrap it like that.

However you could maybe try this:

```
const putEffects = todos.map((todo) => put(completeTodo(todo))
yield putEffects
```

That should work.

**Comment by DTwigs** [comment]
Thank you for the response!  
I'll try what you are suggesting.  I also like that custom channel suggestion in your linked answer.  I need to do some reading up on channels.

**Comment by mheiber** [comment]
@DTwigs just as `Array#forEach` and `Array#map` work for arrays, you can define similar helpers for working with iterators.

```js
// define helper
function* iterMap(items, func) {
  for (let item of items) {
    yield func(item)
  }
}

// use it like this
yield* iterMap(todos, todo => put(complete(todo)))

```

A `for` loop would be more idiomatic here, though.
