### ISSUE TITLE
[Question] Is it possible to select the previous state?

### ISSUE THREAD

**Issue by axelson** [yelouafi/redux-saga#538]
I'm pretty sure that the answer to this is no, but I'm trying to figure out a good way to solve this problem.

I have an action, let's call it `EXTERNAL_UPDATE` that updates the state of objects in the redux store within a reducer. On some `EXTERNAL_UPDATE`'s I want to fire an additional action to show a popup to the user depending on the state that was changed. However, the `EXTERNAL_UPDATE` action only contains the new state and when I run a `select` after the `EXTERNAL_UPDATE` I only get the new state as well.

The only solution I could see from redux is making `take` return the previous state (before the action) as well as the action.

Alternatively since the `EXTERNAL_UPDATE` is being dispatched from within a ~~reducer~~ **saga**, I may use a `channel` to send out the `EXTERNAL_UPDATES` before the actual action is sent out, but this seems like a hacky solution.

One other possibility is for the reducers to not act on `EXTERNAL_UDPATE` directly but have a saga that listens for it and then emits another action like `DO_EXTERNAL_UPDATE` (or actions specific to the type of update being performed)

Has anyone else dealt with this problem?

Edit: fixed typo, I'm dispatching within a saga, not a reducer

**Comment by mheiber** [comment]
@axelson if I understand correctly, what you want to do is absolutely possible.

In the code below ([adapted from `/examples/async`](https://github.com/yelouafi/redux-saga/blob/master/examples/async/src/sagas/index.js#L31)), the `SHOW_POPUP` action is dispatched depending on a condition based on both the current and previous state:

```js

export function* nextRedditChange() {
  while(true) {
    const oldReddit = yield select(selectedRedditSelector)
    yield take(actions.EXTERNAL_UPDATE)
    const newReddit = yield select(selectedRedditSelector)
    const shouldShowPopup = oldReddit !== newReddit
    if (shouldShowPopup) {
      yield put(actions.SHOW_POPUP)
    }
}
```

**Comment by Andarist** [comment]
@mheiber 

It is not rly a good solution as between `yield select(selectedRedditSelector)` and `yield take(actions.EXTERNAL_UPDATE)` may happen multiple other actions which will change the state.

**Comment by axelson** [comment]
@Andarist You are correct that you cannot dispatch within a reducer, that was a typo, I am dispatching within a saga.

Your suggested solution works but the data in question is a list of entities that's potentially 500+ long and the `EXTERNAL_UPDATE` only affects one of them so I'd rather not cache all of them.

I ended up going with creating a new event channel but I still think it would be nice to have something built into redux-saga to help with this case. Maybe a custom/new effect. It could operate like a hybrid of `take` and `select`

   function takeWithPreviousState(pattern, previousStateSelector)

It would return when `pattern` is matched but in addition to returning `action` it would return the result of the `previousStateSelector` run against the state immediately before the action matching `pattern` was processed by the reducers.

**Comment by Andarist** [comment]
Well, you will just keep reference to this huge list of entities, so i
wouldnt rly be too much concern about it
