### ISSUE TITLE
[Question] Serial async 

### ISSUE THREAD

**Issue by km-tr** [yelouafi/redux-saga#540]
```js
function* serial() {
  yield ['hoge', 'huga', ...].map( (item) => call(xxxfunc
, item) );
}
```
↑this parallel.

I want to do serial(series？) from array.
What should i do?

**Comment by Andarist** [comment]
I would recommend similar thing like I've proposed in other question thread - https://github.com/yelouafi/redux-saga/issues/532#issuecomment-245337343

```
function* serial() {
	// map your data to effects (which are just plain objects)
	const effects = ['hoge', 'huga', ...].map( (item) => call(xxxfunc, item) );
	// yield those created effect-objects to the saga, so it can run them all in parallel
	yield effects
}
```

**Comment by km-tr** [comment]
Thank you!

The point is, does this mean I can not to be serial?

**Comment by Andarist** [comment]
Oh sorry. Ive misunderstood your intention. I guess then just regular loop
will do fine. Just iterate through your array
