### ISSUE TITLE
Can I make yield take(chan, ‘SOME_ACTION’) working?

### ISSUE THREAD

**Issue by sergej-s** [yelouafi/redux-saga#545]
Hello everyone! 

We use redux-saga extensively and love this great and superb library :)
We utilize a lot of channels to communicate between many sagas and write code like this:

```yield take(chan, ‘SOME_ACTION’)```.

At first we thought that take effect is able to handle invocation with two arguments channel and pattern because:

```function runTakeEffect({channel, pattern, maybe}, cb)```

But this is partly true. It’s works if channel was empty when we yielded take effect. In this case taker was pushed into takers array and it will be called **with accordance to matching pattern** when action is put into channel. But if the buffer is not empty then taker is invoked immediately with first element from buffer ignoring pattern at all.
How can we workaround this problem and get only certain actions from the channel using ```yield take(chan, ‘SOME_ACTION’)```?
@yelouafi How do you think about including such behavior into the lib? Maybe iterate over buffer to return action that is matched to pattern?

**Comment by Andarist** [comment]
I've recently have noticed the same thing and thought about it as a bug too, look here - https://github.com/yelouafi/redux-saga/issues/507

And later have implemented this - https://github.com/yelouafi/redux-saga/pull/539 , so `take(chan, pattern)` may not be used at all as it produces various unexpected effects.

Implementing support for taking from `channel`s with `pattern` would be a little bit strange, cause it would have to be implemented at `buffer` level and it stays agnostic of the `pattern` so far. They are just FIFO queues.

**Comment by sergej-s** [comment]
@Andarist Thank you very much for the response. It's hard to not use take(chan, pattern) because we extensively use eventChannels with sockets, simple channles to communicate between sagas and I wrote sequential code like this:
``` const action1 = yield take(channel, 'SOME_ACTION1');
    do something with action1
    const action2 = yield take(channel, 'SOME_ACTION2');
    do something with action2
    etc
```
So only solution is to put everything from channel to std broadcast channel and then yield take(pattern)?

**Comment by Andarist** [comment]
Well, you could implement your own channel and buffer with the API of those provided in the lib and just tweak yours to your custom needs, but it depends if my PR will get merged in. If it get merged in you would also have to implement your `take(chan, pattern)` effect.

I realise though it is hacking around the lib pretty much.

You could maybe split actions between various channels, so you could have more control about what you are taking without need of a `pattern`.

**Comment by Andarist** [comment]
As `take(chan, pattern)` API was hidden completely in `0.12` to avoid such confusions, I'll close the issue right now.

In general I think that your proposal makes sense, but present `buffer` FIFO-like implementation is not suitable for the purpose.

**Comment by hbarcelos** [comment]
Almost 4 years later, hehe...
I couldn't find anything in that regard in the docs.

Any suggestion on how to achieve this?
Thank you.

**Comment by Andarist** [comment]
@hbarcelos how exactly would you expect this to work? remember that buffers (and channels based on them) are FIFOs and also that you can have multiple takers on a single channel where a single item is always given to just a single consumer. There is also `multicastChannel` API which doesn't come with buffering but notifies or pending consumers with an item.

**Comment by hbarcelos** [comment]
Maybe I'm doing this wrong, or channels are not meant to be used like this, but here's what I'm trying to achieve:

I have a transaction which could either ERROR right the way if it's invalid or it could be submitted. If it's submitted, it will produce several different events, one of them indicating the transaction was ACCEPTED. However, the transaction could also ERROR after it was submitted as well.

I wanted tap into the channel and wait for what would happen first, either an ERROR or and ACCEPTED event:

```js
yield race({
   ok: take(chan, action => action.type === 'ACCEPTED'),
   failure: take(chan, action => action.type === 'ERROR'),
});
```
However this wouldn't work because `take` consumes the event in the channel, right?
What I'd really need would be something like `peek` that would allow me to take the event from the channel and put it back in LIFO-style.

**Comment by Andarist** [comment]
If you don't care about buffering then and you just want to listen of events as they happen then you could do this:
```js
const chan = multicastChannel()

// ...

yield race({
   ok: take(chan, action => action.type === 'ACCEPTED'),
   failure: take(chan, action => action.type === 'ERROR'),
});
```

**Comment by hbarcelos** [comment]
Hey @Andarist, sorry for the delay... Busy week at work.j

I couldn't find much about `multicastChannel` around.
What is the difference between `stdChannel` and `multicastChannel`?

**Comment by Andarist** [comment]
> What is the difference between stdChannel and multicastChannel?

It's almost the same, `stdChannel` has slightly different scheduling - it is only supposed to be used as 'top-level' channel with `runSaga` API.
