### ISSUE TITLE
Saga runs twice for a single action

### ISSUE THREAD

**Issue by jshumakerpruitt** [yelouafi/redux-saga#549]
I have a saga to handle like requests.  The user clicks a button to toggle the liked status of a photo.  

The saga listens for an action of type `SUBMIT_LIKE`.  My problem is that the `submitLikeSaga` is running twice for each `SUBMIT_LIKE` action.
e.g. In the api-error case one `SUBMIT_LIKE` action triggers two api calls and four `RECEIVE_LIKE` actions.

(using [react-boilerplate](https://github.com/mxstbr/react-boilerplate) if that helps.)

    export function* submitLikeSaga(action) {
    
      // optimistically update the UI
      // action shape: {
      //    type: RECEIVE_LIKE,
      //    like: {id: 1, liked: true}
      //  }
      yield put(receiveLike(action.like));
    
      // POST like data to api
      const response = yield call(
        request,
        `${API_ENDPOINT}/user_likes.json`,
        {
          method: 'POST',
          headers: {
            Authorization: `Bearer ${action.token}`,
            Accept: 'application/json',
            'Content-Type': 'application/json',
          },
          body: JSON.stringify(action.like),
        }
      );
    
      // if api call failed, reverse change made to UI
      if (response.err) {
        yield put(receiveLike({
          id: action.like.id,
          liked: !action.like.liked,
        }));
      }
    }
    
    export function* watchSubmitLike() {
      yield* takeEvery(SUBMIT_LIKE, submitLikeSaga);
    }
    
    // All sagas to be loaded
    export default [
      watchFetchUsers,
      watchSubmitLike,
    ];

#ProfileGrid.js

    const ProfileGrid = ({
      users,
      submitLike,
      token,
    }) =>
      <div className={styles.profileGrid}>
        {users.map((user, i) => (
          <div key={i} className={styles.gridTile}>
            <GridTile
              title={user.username}
              actionIcon={<ActionIcon
                onIconClick={() => { submitLike(user.id, !user.liked, token); }}
    
                isActive={user.liked}
                activeColor="yellow"
                defaultColor="white"
              />}
            >
              <img style={{ width: '100%', height: 'auto' }} src={user.avatar} alt="profile" />
            </GridTile>
          </div>
        ))}
      </div>;

# ActionIcon.js
    const ActionIcon = ({

      onIconClick,
      isActive,
      activeColor,
      defaultColor,
    }) =>
      <IconButton onClick={onIconClick} >
        <StarBorder
          color={isActive ? activeColor : defaultColor}
        />
      </IconButton>;

**Comment by Andarist** [comment]
That's probably cause you are running somehow `watchSubmitLike` twice. Could you post a snippet with the moment you are starting your root saga and this one?

**Comment by jshumakerpruitt** [comment]
@Andarist 
# store.js
    /**
     * Create the store with asynchronously loaded reducers
     */
    
    import { createStore, applyMiddleware, compose } from 'redux';
    import { fromJS } from 'immutable';
    import { routerMiddleware } from 'react-router-redux';
    import createSagaMiddleware from 'redux-saga';
    import createReducer from './reducers';
    
    const sagaMiddleware = createSagaMiddleware();
    const devtools = window.devToolsExtension || (() => (noop) => noop);
    
    export default function configureStore(initialState = {}, history) {
      // Create the store with two middlewares
      // 1. sagaMiddleware: Makes redux-sagas work
      // 2. routerMiddleware: Syncs the location/URL path to the state
      const middlewares = [
        sagaMiddleware,
        routerMiddleware(history),
      ];
    
      const enhancers = [
        applyMiddleware(...middlewares),
        devtools(),
      ];
    
      const store = createStore(
        createReducer(),
        fromJS(initialState),
        compose(...enhancers)
      );
    
      // Extensions
      store.runSaga = sagaMiddleware.run;
      store.asyncReducers = {}; // Async reducer registry
    
      // Make reducers hot reloadable, see http://mxs.is/googmo
      /* istanbul ignore next */
      if (module.hot) {
        module.hot.accept('./reducers', () => {
          System.import('./reducers').then((reducerModule) => {
            const createReducers = reducerModule.default;
            const nextReducers = createReducers(store.asyncReducers);
    
            store.replaceReducer(nextReducers);
          });
        });
      }
    
      return store;
    }

# asyncInjectors.js

    import { conformsTo, isEmpty, isFunction, isObject, isString } from 'lodash';
    import invariant from 'invariant';
    import warning from 'warning';
    import createReducer from '../reducers';
    
    /**
     * Validate the shape of redux store
     */
    export function checkStore(store) {
      const shape = {
        dispatch: isFunction,
        subscribe: isFunction,
        getState: isFunction,
        replaceReducer: isFunction,
        runSaga: isFunction,
        asyncReducers: isObject,
      };
      invariant(
        conformsTo(store, shape),
        '(app/utils...) asyncInjectors: Expected a valid redux store'
      );
    }
    
    /**
     * Inject an asynchronously loaded reducer
     */
    export function injectAsyncReducer(store, isValid) {
      return function injectReducer(name, asyncReducer) {
        if (!isValid) checkStore(store);
    
        invariant(
          isString(name) && !isEmpty(name) && isFunction(asyncReducer),
          '(app/utils...) injectAsyncReducer: Expected `asyncReducer` to be a reducer function'
        );
    
        store.asyncReducers[name] = asyncReducer; // eslint-disable-line no-param-reassign
        store.replaceReducer(createReducer(store.asyncReducers));
      };
    }
    
    /**
     * Inject an asynchronously loaded saga
     */
    export function injectAsyncSagas(store, isValid) {
      return function injectSagas(sagas) {
        if (!isValid) checkStore(store);
    
        invariant(
          Array.isArray(sagas),
          '(app/utils...) injectAsyncSagas: Expected `sagas` to be an array of generator functions'
        );
    
        warning(
          !isEmpty(sagas),
          '(app/utils...) injectAsyncSagas: Received an empty `sagas` array'
        );
    
        sagas.map(store.runSaga);
      };
    }
    
    /**
     * Helper for creating injectors
     */
    export function getAsyncInjectors(store) {
      checkStore(store);
    
      return {
        injectReducer: injectAsyncReducer(store, true),
        injectSagas: injectAsyncSagas(store, true),
      };
    }

**Comment by Andarist** [comment]
Still dont know how are you running this - `getAsyncInjectors`. Break yourself on this line - `sagas.map(store.runSaga);` and it will be reached probably at least 2 times with the mentioned `watchSubmitLike` saga. Check why is that and you will probbaly know how to fix this.

**Comment by neurosnap** [comment]
You don't have a `rootSaga` you are calling `Sagamiddleware.run` on every single saga you created.

```js
/**
 * Inject an asynchronously loaded saga
 */
export function injectAsyncSagas(store, isValid) {
  return function injectSagas(sagas) {
    if (!isValid) checkStore(store);

    invariant(
      Array.isArray(sagas),
      '(app/utils...) injectAsyncSagas: Expected `sagas` to be an array of generator functions'
    );

    warning(
      !isEmpty(sagas),
      '(app/utils...) injectAsyncSagas: Received an empty `sagas` array'
    );

    sagas.map(store.runSaga);
  };
}
```

Instead of:
```js
sagas.map(store.runSaga);
```

Try this:
```js
store.runSaga(function* () {
  yield sagas;
});
```

**Comment by jshumakerpruitt** [comment]
@neurosnap Thanks for the tip.  I got it to work by changing it to match the style of other sagas in react-boilerplate. Closing this since it was never an issue with redux-saga.

```javascript
export function* watchSubmitLike() {
  /* eslint-disable no-constant-condition */
  while (true) {
    const action = yield take(SUBMIT_LIKE);
    yield call(submitLikeSaga, action);
  }
  /* eslint-enable no-constant-condition */
}

export function* likeData() {
  // Fork watcher so we can continue execution
  const watcher = yield fork(watchSubmitLike);

  // Suspend execution until location changes
  yield take(LOCATION_CHANGE);
  yield cancel(watcher);
}


// All sagas to be loaded
export default [
  watchFetchUsers,
  likeData,
];
```

**Comment by cusxio** [comment]
Just faced this issue, however I realised that my sagas were being instantiated twice instead of being called twice by `LOCATION_CHANGE`.

Turns out, it's a bug from [react-router-redux](https://github.com/reactjs/react-router-redux/issues/481), leaving it here so that someone finds it.

**Comment by yummyelin** [comment]
I solved the issue by cancel takelatest watcher.

Before:
export function* likeData() {
  yield takelatest(watchSubmitLike);
}

After:
export function* likeData() {
  const watcher = yield takelatest(watchSubmitLike);
  yield take(LOCATION_CHANGE);
  yield cancel(watcher);
}

**Comment by Andarist** [comment]
@yummyelin thats the way to go
