### ISSUE TITLE
How to chain multiple data source loads that  depends on each other?

### ISSUE THREAD

**Issue by elitan** [yelouafi/redux-saga#551]
Hi,

Lets say I want to to make sure data source A, B and C are loaded to the redux store. Data source B is dependent on A and must be loaded after that A is loaded and data source C is dependent on data source B and must be loaded after B is loaded.

I also want to do this in a single function so I can do it in the same function scope.

How do I do this in a nice way in redux saga?

My take on this is the following:

1.
```
...
export function* loadMultipleDataSources() {
    // load data source A
    yield put(document_actions.myDocumentsLoad());
    yield take(
	[
	    document_actions.MY_DOCUMENTS_LOAD_CACHED,
	    document_actions.MY_DOCUMENTS_LOAD_SUCCEEDED,
	]
    );
    
    // load data source B, this must happend after 'MY_DOCUMENTS' are in the redux store
    // load data source C...

```

2.
```
export function* myDocumentsLoad() {
    const my_documents = yield select(state => state.documents.get('all'));
    if (my_documents.size > 0) {
        yield put({
            type: document_actions.MY_DOCUMENTS_LOAD_CACHED,
        });
        return;
    }
    ...
```

However, this does not work because of how javascript works. The MY_DCOCUMENTS_LOAD_CACHED will trigger before the code in (1) has come to its `take`.

However, if i tweak (2) a bit, by adding a `delay` it works.
```
yield call(delay, 0); // needs to be here for take() to finish setup
yield put({
    type: document_actions.MY_DOCUMENTS_LOAD_CACHED,
});
```

Now, the `take` in (1) will finish up before the `put` in (2).

Is this a good way to solve the problem? 
Is there some better solution to this problem?

**Comment by Andarist** [comment]
How are 1 and 2 connected? Where and how 2nd generator (`myDocumentsLoad`) is ran?

**Comment by elitan** [comment]
(1) is ran on a specific react component constructor.

(2) is runs every time `document_actions.myDocumentsLoad()` is run. `document_actions.myDocumentsLoad()` dispatches an action, which (2) has a takeEvery-watcher on.

Does this clear things up?

**Comment by Andarist** [comment]
Ok. This might be in fact a little bit confusing - the ordering of things here. I would say the easiest and the most 'clean' way of handling this is using `channel`. You can do smth like that:

```
export function* loadMultipleDataSources() {
    const chan = yield actionChannel([
        document_actions.MY_DOCUMENTS_LOAD_CACHED,
        document_actions.MY_DOCUMENTS_LOAD_SUCCEEDED,
    ]);
    // load data source A
    yield put(document_actions.myDocumentsLoad());
    yield take(chan);

    // load data source B, this must happend after 'MY_DOCUMENTS' are in the redux store
    // load data source C...
```

It will buffer those actions internally in the created channel, so you wont miss them.

**Comment by elitan** [comment]
This works and looks alright.

Does `actionChannel` comes with any side effects after `yield take(chan);`? 
Like, do I need to delete the `actionChannel` (the chan variable) or something?

**Comment by Andarist** [comment]
It acts like a listener for the action types you have passed in while creating it and also it has a buffer iternally, so if you really want to dispose it I would suggest just closing it - `chan.close()`

**Comment by elitan** [comment]
Ok, perfect. Thanks @Andarist! This answered my questions regarding this issue.

**Comment by neurosnap** [comment]
instead of dispatching an action for data source A, why not simply yield to the generator for it? composing sagas should be able to solve chaining data sources.

**Comment by elitan** [comment]
@neurosnap I am not sure what you mean. Could you maybe explain with an example?

**Comment by neurosnap** [comment]
```js
function* dataSourceA() {
  const req = yield call(fetch, 'http://...');
  const data = yield req.json();

  // ...

  yield put({ type: 'ADD_MY_DOCUMENTS', payload: documents });
  return data;
}

function* dataSourceSaga() {
  while (true) {
    const action = yield take('LOAD_DOCUMENTS');
    const sourceAData = yield* dataSourceA(action);
    // this wont trigger until all of the async calls from dataSourceA have finished
    yield put({ type: 'LOAD_DATA_SOURCE_B' });
  }
}
```

**Comment by elitan** [comment]
I want to have the whole 'LOAD_DOCUMENTS' in a single function scope. I dont want to break out the fetches in different functions.

**Comment by neurosnap** [comment]
Do the actions you dispatch run sagas?  If so then they aren't all inside one function.  It's up to you how you want to organize your application, but one of the big benefits to sagas are their composability.
