### ISSUE TITLE
[Question] Watch a list of calendar entries

### ISSUE THREAD

**Issue by janhartmann** [yelouafi/redux-saga#555]
I am currently trying to watch my state calendar entries for the next happening. But I am unsure if I am on the right path for doing this most effectively and correct.

I am a bit stuck right now with this piece of code:

``` js
import {select } from 'redux-saga/effects'
import moment from 'moment-timezone';

export default function * watchCalendar() {
    while (true) {
        const entry = yield select((state) => state.calendar.entries[0]);
        if (entry) {
            const now = moment();
            var start = moment(entry.start);
            if (start.isSame(now)) {
                console.log(entry);
            }
        }
    }
}
```

While this runs, I am never hitting the `if (now.isSame(start)) { ... }` - I have a feeling the `while` is terminating. Can anyone point me in the right direction for watching a array in state?

**Comment by neurosnap** [comment]
You want to watch for actions being dispatched, not your state.  The only way your state `calendar` can be changed is by dispatching an action, something like `UPDATE_CALENDAR` which then goes through your reducer to return the next state.

```js
while (true) {
  const action = yield take('UPDATE_CALENDAR');
  const entry = action.payload; // or whatever your action data looks like to update your calendar
  // ...
```

**Comment by janhartmann** [comment]
Okay. I can possible dispatch an action - but I need to do something every time a calendar entry is about to begin. Should I then dispatch an action e.g. every minute? Or is there any better approach? Thank you. :-)

**Comment by janhartmann** [comment]
Ah, maybe I can do something like

```js
export function * watchCalendar(action) {
	while (true) {
		 const { stopped } = yield race({
			wait: call(delay, 60000),
			stopped: take("STOP_LOOKING_FOR_CALENDAR_ENTRIES")
		});

		if (!stopped) {
			 yield put(actions.lookForUpdates());
		}
	}
}

export default function * calendar() {
    yield * takeLatest("START_LOOKING_FOR_CALENDAR_ENTRIES", watchCalendar);
}
```

And then having a separate saga for the "lookForUpdates()" action. Any other suggestions is appreciated.

**Comment by Andarist** [comment]
Some possible approach was posted here - https://github.com/yelouafi/redux-saga/issues/660#issuecomment-263612752

However your use case could be a different one, the only way to change your state which you have wanted to check in your `select` effect is dispatching an action, so the simplest way of detecting changes is just this
```javascript
while () {
  yield take(ACTION_TRIGGERING_CALENDAR_ENTRIES_CHANGE)
  const entry = yield select((state) => state.calendar.entries[0]);
  //... do smth
}
```

Please remember that even `time1` and `time2` shouldnt be equal, so your change detection was kinda broken in the first place
```javascript
const time1 = moment()
const time2 = moment()
time1.isSame(time2) // false
```

If you still have further questions, please reopen the issue, Ill try to help to my best
