### ISSUE TITLE
Testing race()

### ISSUE THREAD

**Issue by SpencerCDixon** [yelouafi/redux-saga#562]
Sorry if this is explained somewhere but I've search on SO, the Gitbook, and past issues and can't find.  How am I suppose to test `race`?

My saga:
```
export function* deleteUserSaga() {
  const { success, fail } = yield race({
    success: take(at.DELETE_SUCCESS),
    fail: take(at.DELETE_FAIL),
  });

  if (success) {
    yield put(push('/users'));
    yield put(addToast('Successfully deleted user'));
  }

  if (fail) {
    yield put(addToast(
      'Deleting failed. Make sure all access keys are deleted, groups are detached, and policies have been removed'
    ));
  }
}
```

Trying to test:
```
  describe('deleteUserSaga()', function() {
    it('successfully', function() {
      const gen = deleteUserSaga();

      expect(gen.next().value).to.eql(race({
        success: take(at.DELETE_SUCCESS),
        fail: take(at.DELETE_FAIL),
      }));

      const next = gen.next()
      console.log('NEXT IS', next);
      expect(next.value).to.eql(put(push('/users')));

      // expect(gen.next()).to.eql({
        // done: true, value: undefined
      // });
    });
  });
```

It just keeps failing with:
`undefined is not an object (evaluating '_ref2.success')`

Am I missing something super obvious haha?

**Comment by SpencerCDixon** [comment]
Do I have to pass in an object to the call to `gen.next({success: true}).value` or something like that?

**Comment by oanylund** [comment]
I am having the exact same issue! Can't get race to return anything.

**Comment by oanylund** [comment]
Inject the value in the second  call of next, in your case the one one the line before the `console.log('NEXT IS', next);`. Spent half an hour trying to inject it in the first one before i figured it out..

**Comment by SpencerCDixon** [comment]
@oanylund issue fixed my issue... closing this.
