### ISSUE TITLE
Dispatch runs before saga has started listening for actions

### ISSUE THREAD

**Issue by iverberk** [yelouafi/redux-saga#563]
I've created a Saga that listens and sends action on a websocket channel. Code can be found here: https://github.com/iverberk/nomad-ui/blob/master/frontend/src/sagas/event.js

It takes some time to connect to the backend. Meanwhile a component like this (https://github.com/iverberk/nomad-ui/blob/master/frontend/src/containers/job.js#L43) will fire its ComponentWillMount lifecycle hook and dispatches an action that gets lost somewhere.

I'm looking for guidance on how to best 'wait' for the Saga to have connected to the backend before firing the dispatch or some way for the action to not get lost and processed by the Saga when it starts listening. Maybe I need to restructure my saga? I'm not sure what to do here. Thanks!

**Comment by iverberk** [comment]
It's fixed by wrapping the connection code in a Promise and yielding the generator function on resolve: https://github.com/iverberk/nomad-ui/blob/master/frontend/src/sagas/event.js#L129-L135

**Comment by WuTheFWasThat** [comment]
reposting here so it's not lost forever.  

you can buffer the component's actions in a channel to access later

untested:
```
const componentAction = 'ACTION_NAME'

function* mainSaga() {
  const chan = channel()
  const task = fork(takeEvery, componentAction, (action) => chan.put(action))

  function* otherSaga() {
    // somewhere in this
    const action = yield take(chan)
    yield call(doThingWithAction, action)
    // when the socket is done, if you want to stop buffering, you can cancel the other saga
    yield cancel(task)
    // and now you can just listen to the actions directly
    yield takeEvery(componentAction, doThingWithAction)
  }

  yield fork(otherSaga)
}
```

**Comment by rjdestigter** [comment]
Just another thought. You could also create a simple middleware to inject into redux before redux saga is is injected that queue's incoming actions until a flag on state changes to true. For example, within a large application where each route boots up it's own set of sagas, on location change you could set that state flag to false, start up your sagas, then set the the state flag to true.

The middleware would check if the flag is false and queue incoming incoming actions and flush them back to redux if the flag changes to true
