### ISSUE TITLE
Running sagas on react-router's onEnter hook

### ISSUE THREAD

**Issue by luandro** [yelouafi/redux-saga#568]
I've been trying to get sagas to run on react-router's `onEnter` hook: 

```
const loadData = (nextState, replace, cb) => {
    const path = nextState.location.pathname;
    const loader = new Promise((resolve) => {
      switch (path) {
        case '/news':
          resolve(store.dispatch(loadNews()));
        default:
      }
    });
    loader.then(() => cb());
  };
```

```
     {
          onEnter: (_, nextState, replace, cb) => loadData(_, nextState, replace, cb),
          path: 'news',
          getComponent(location, cb) {
            System.import('containers/New')
              .then(loadModule(cb))
              .catch(errorLoading);
          },
        },
```

The `loadNews` action get's dispatched, but the saga which is watching it doesn't get called

```
export function* getNewsWatcher() {
  while (yield take(GET_NEWS)) {
    console.log('GET_NEWS saga got called');
    yield call(postGetNews);
  }
}
```

It works if I navigate from one route such as `/` to `/new`. But if I start running the app from the `/new` route, where the action is called, it doesn't.

Any thoughts?

**Comment by pke** [comment]
you just dispatch a `GET_NEWS` action with the param of which news to load in the `onEnter` hook?

**Comment by luandro** [comment]
Yea,  basically.

Em 6 de out de 2016 4:24 AM, "Philipp Kursawe" <notifications@github.com>
escreveu:

**Comment by pke** [comment]
so maybe the hook is not called on app start cause its the first route?

**Comment by luandro** [comment]
Could be? What to do?

**Comment by yelouafi** [comment]
closing this as it seems more related to react-router
