### ISSUE TITLE
introduction link in the readme is a 404

### ISSUE THREAD

**Issue by toranb** [yelouafi/redux-saga#573]
When you click the intro link you redirect to the url below and as a result a 404

http://yelouafi.github.io/redux-saga/docs/introduction/index.html

**Comment by toranb** [comment]
disregard :) must have had a stale html readme (all good now)

**Comment by srails** [comment]
404 Again... 

Thanks

**Comment by Andarist** [comment]
`redux-saga` has recently migrated to the organization account and therefore some public urls have changed, the correct one should be `https://redux-saga.github.io/redux-saga/docs/introduction/index.html` from now on

is there somewhere in the docs linked old version of the URL? or have just tried to enter it manually?

**Comment by srails** [comment]
https://github.com/redux-saga/redux-saga-beginner-tutorial

"Companion Repo for **Redux/Redux-saga beginner tutorial**"
This link is throwing a 404 also might want to update.

Thanks

**Comment by Andarist** [comment]
Fixed, thanks for noticing!
