### ISSUE TITLE
[Docs] Misleading note for takeEvery / takeLatest

### ISSUE THREAD

**Issue by iTob191** [yelouafi/redux-saga#574]
Hey,

in the docs for `takeEvery` and `takeLatest` there is a note showing how those helpers are implemented but actually they work a little different: They don't return immediately.

With the implementation of the docs, this works as intended (logging `1` and then `2` and calling `console.log` for every `ACTION`):
``` javascript
function* saga() {
	console.log(1);
	yield* takeEvery("ACTION", console.log);
	console.log(2);
}
```
But using the real helper, it doesn't get past the `takeEvery` call so the `2` will never appear in the console.

**Comment by Andarist** [comment]
What version of the lib r u using? With `v0.12.0` such snippet should work:
```
function* saga() {
    console.log(1);
    yield takeEvery("ACTION", console.log);
    console.log(2);
}
```

**Comment by iTob191** [comment]
Damn, I should really read the release notes more carefully :x Yep, was on `v0.11.x`. Thanks for pointing that out to me.
