### ISSUE TITLE
Question about `put` behavior

### ISSUE THREAD

**Issue by bstro** [yelouafi/redux-saga#575]
If I'm in a Saga and I `put` an action back into the store, does that action get processed immediately or is it queued up for the next tick? That is to say, does `put`-ing into the store pause the current generator execution, and resume until after the action described by the `put` has finished processing? Or does the current generator complete, followed by the next action?

**Comment by Andarist** [comment]
`put` is synchronous, so generally it should return to generator execution immediately after geting processed by the store, you can look here how it is handled - https://github.com/yelouafi/redux-saga/blob/93f54110ecea401a7a3637fe3d71dba9d23b0751/src/internal/proc.js#L431

**Comment by bstro** [comment]
thanks!!!
