### ISSUE TITLE
[Question] Forward/Backward opportunity

### ISSUE THREAD

**Issue by DiMoNTD** [yelouafi/redux-saga#576]
I apologize for the fact that I leave the question here, but I need to understand some opportunities of redux-saga to build application.

I've developing kiosk application (user interface), and need to describe different scenarios of payment.

To describe UI-elements, was choosen a React. I liked the Redux for the one direction of data flow. But in this architecture I didn't knew where put the business logic to describe different workflows. In research, I found the wonderful module - redux-saga. I understood, that this module can be like process manager, and I found that many people thought like this.

But with redux-saga not all so clear, as I wanted, so I write my questions here.

Main thought that I have one big workflow, separated with steps. For example, process - payment cellular by phone number. It's look like this:

Process payment cellular:

- Enter phone number

- Online check number

 - Bad response: Error

     - Backward: Enter phone number

- Confirm information

- Put the cash

- Make payment

 - Bad response: Error

     - Backward: Exit from process payment cellular

- Information about transaction

In my vision every stage is a saga, that will call from previous stage. It's all cool, until I need to give to the user an opportunity go to the previous stage, for example, from Confirmation backward to Enter phone number.

So question, how to manage stages in my main workflow, if I can forward from one stage to another, and go back?

Thanks for answers!

**Comment by Andarist** [comment]
It might not be ideal, just from the top of my head right now, you could model it in such manner (and probably do it more cleanly)
```
function* handleFirstStep(action) {
	// some logic
}

function* handleSecondStep(action) {
	// some logic
}

function* saga {
	let step = 1

	yield takeEvery('CHANGE_STEP', function* (action) {
		step = action.step
	})

	while (true) {
		const action = yield take(pattern)

		switch (step) {
		case 1:
			yield* handleFirstStep(action)
			break
		case 2:
			yield* handleSecondStep(action)
			break
		default:
			break
		}
	}
}
```

generators are really similar to regular functions, so you can do pretty neat things with scopes and closures

**Comment by DiMoNTD** [comment]
@Andarist thank you for the answer! It's cool example.

In addictional, there is one more example, that I've found useful
https://github.com/kuy/redux-saga-examples/tree/master/wizard
