### ISSUE TITLE
Race effect when used with concurrent effects does not cancel alternate tasks

### ISSUE THREAD

**Issue by Alxandr** [yelouafi/redux-saga#578]
I'm seeing tasks not cancelled when using `race` with tasks that (sometimes) returns immediately. In my case I have the following:

```js
yield race({
  route: take(myChannel),
  move: take(MOVE_ACTION)
});
```

If `myChannel` has items in it's buffer, then the listener for `MOVE_ACTION` is never cancelled, which breaks things further down the line when I call the race again (I have to trigger `MOVE_ACTION` twice, first one to clear away the old listener).

**Comment by Andarist** [comment]
Could you possibly make a fiddle with the reproduced issue? Would be really helpful for fixing this sooner than later :)

**Comment by Alxandr** [comment]
https://jsbin.com/curoxayojo/edit?js,console

Basically, what happens is that in race, the callback of effect 1 is called before effect 2 is "subscribed" to (thus, the `cancel` method is not set). It can be solved by either adding a delaying mechanism (preventing synchronous execution), or by adding `if (!completed)` to the loop at https://github.com/yelouafi/redux-saga/blob/master/src/internal/proc.js#L602. There are probably other ways too. I would suggest the second one, forcing async execution, but that's just my 2 cents.

**Comment by Andarist** [comment]
Fixed the issue, probably will merge soon, although I would like to have @yelouafi look at the PR beforehand

**Comment by Alxandr** [comment]
Hehe. I was just about to fix it myself, but ran in to a bug in CPS when testing my fix (hence the PR) :P
