### ISSUE TITLE
Isn't Saga just solving the same problem that custom middleware solves?

### ISSUE THREAD

**Issue by AriaFallah** [yelouafi/redux-saga#58]
Currently my actions look like this

```javascript
export function getFormula(id) {
  return {
    type: GET_FORMULA,
    [PARSE]: {
      parseClass: new FORMULA_CLASS(),
      method: 'GET',
    },
    [PROMISE]: {
      resolvedAction: {
        id
      },
      rejectedAction: {
        id
      }
    }
  }
}
```

The actions themselves have no functions in thunks or anything. Just instructions.

Likewise with Saga you'd just dispatch an action, but more plainly

```javascript
export function getFormula(id) {
  return {
    type: GET_FORMULA,
    id,
  }
}
```

But inside the saga defined for it you'd still have to write out basically the same things that I wrote in both my action and in all my middleware for that action.

Also middleware can be decoupled and tested just like how sagas can be individually tested.

So aren't sagas just a different way of exposing the middleware API that redux has?

I ask this not to deprecate sagas (I think they're great) , but because I'm looking for a reason to switch haha.

**Comment by AriaFallah** [comment]
Just kidding.

**Comment by AriaFallah** [comment]
Sagas are amazing

**Comment by yelouafi** [comment]
Sagas can express control flow that's hard to implement by simple middleware (complex login process, game rules). Where the logic spans accross multiple actions (Like login then refresh authorization each min until logout)

It's all normal to ask :)
