### ISSUE TITLE
throttle test is randomly failing

### ISSUE THREAD

**Issue by Alxandr** [yelouafi/redux-saga#582]
![image](https://cloud.githubusercontent.com/assets/112334/19345596/4a151226-913f-11e6-8879-41f4d4594e69.png)

This happens randomly it seems, and I'm guessing it's timing dependent.

**Comment by Andarist** [comment]
I've just noticed that myself, do you maybe use some `console.log`s for debugging purposes? I've somehow found that with them in my code it was failing but the moment I've deleted them it started to work again.

**Comment by Alxandr** [comment]
Nope. This test seems really brittle to me, as it's using timing to "work things out", which should probably be improved upon.

**Comment by Andarist** [comment]
Do you have any ideas how this could be improved? Depending on the timing is indeed not ideal, but as `throttle` is about the time I had no idea how to test it in other manner.

**Comment by Alxandr** [comment]
Probably using something like this: http://sinonjs.org/docs/#clock

**Comment by Alxandr** [comment]
More googleing lead me to https://github.com/sinonjs/lolex which is extracted from sinon (in case you feel an entire mocking library is too much of a dependency).

**Comment by Andarist** [comment]
Personally I dont think even dozen dependencies for development purposes is too much, as long as they make your life easier :) Gonna look into both links soon, thanks for sharing.

**Comment by Alxandr** [comment]
Reading more from the lolex one, it seems it's extracted from sinonjs (and also under the sinon umbrella), so unless you need the rest of sinon that's probably the one to go with.

**Comment by yelouafi** [comment]
cf #586. if implemented, could possibly make testing this possible without mocks

**Comment by Alxandr** [comment]
Don't really think so. Cause this is testing that without doing anything custom like that, `throttle` works as expected.

**Comment by yelouafi** [comment]
I meant that we could get control over precise resolution order of the delay calls (by using promises we resolve in a specific order) and forks (to inspect that the helper throttle forked tasks). I had perviously this kind of randomness (see #109) due to repeated accumulation of timeouts
