### ISSUE TITLE
eventChannel not fired after route change

### ISSUE THREAD

**Issue by billyshena** [yelouafi/redux-saga#587]
Hello guys ! I'm currently trying to implement eventChannel for my websockets events.
Here is how my sagas look like:

```javascript
export function* messageCreatedWatcher(channel) {
  const pushChan = yield call(onMessageCreated, channel);
  while(true) {
    console.log('Should pass here');
    const message = yield take(pushChan);
  }
}


function onMessageCreated(channel) {
  return eventChannel(emit => {
    channel.on('message:created', (message) => {
      console.log(message);
      emit(message);
    });
    return () => {};
  });
}

```

Problem: Whenever a new message is created, it prints `console.log(message)` and then `console.log('Should pass here')`. However if I change route and come back again, it only prints `console.log(message)` and does not enter in the `while(true)` anymore (but console.log(message) is fired)

Looks like my watcher with `while(true)` is destroyed somehow whenever I switch route.

Any ideas?

Best

**Comment by Andarist** [comment]
That really depends how do you start this saga, what do you on route changes?

**Comment by billyshena** [comment]
Thanks for your quick answer @Andarist . Just figured out that I had a `yield cancel` when my route changes (using react-router) so that's why it stopped my messageCreatedWatcher.
I just removed the `yield cancel` to make it work 👍

**Comment by Andarist** [comment]
No problem, I'm glad you have figured it out :)
