### ISSUE TITLE
Is there a better way to do takeFirst?

### ISSUE THREAD

**Issue by ekeric13** [yelouafi/redux-saga#589]
So the takeEvery and takeLatest helper functions are quite useful.
But in a situation where you want to take the first take, but ignore the rest, such as a user clicking the delete button multiple times, what is the best way to write your saga watcher function so that it only takes the first delete action dispatch?

By modifying takeLatest I got a function that looks like this:
```
function* takeFirst(pattern, saga, ...args) {
  const task = yield fork(function* () {
    let firstTask = true;
    while(true) {
      const action = yield take(pattern);
      if (firstTask) {
        firstTask = false;
        yield call(saga, ...args.concat(action));
        firstTask = true;
      }
    }
  });
  return task;
}
```

Now in a watcher you might be able to do this:
```
export function* watchDeleteWidgetsSaga() {
  yield takeFirst(DELETE_WIDGETS_SAGA, deleteAndUpdateWidgets);
}
```

Is this a good way to "takeFirst"? Or are there already saga helpers and effect creators in the existing saga api that would help me do this? Or is "takeFirst" just an anti-pattern completely - if so why?

**Comment by Andarist** [comment]
call is a blocking effect so you can just skip this whole firstTask flag.
In ur fork just put take and call in a while (true) loop. Effect will be
the same and what u r looking for

**Comment by thebucknerlife** [comment]
@Andarist any advice on how to test a custom helper like takeFirst? We've followed the same pattern as above. I've been trying to pattern our test off of https://github.com/yelouafi/redux-saga/blob/master/test/sagaHelpers/takeEvery.js.

**Comment by Andarist** [comment]
I would rather base this one on https://github.com/yelouafi/redux-saga/blob/master/test/sagaHelpers/takeLatest.js , rather than on `takeEvery`. You can dispatch your action, multiple times (so only first will get handled), then resolve promise in the `call`ed worker so it gets unblocked. Push to the `actual` some time on the way and just check in the end that it contains only one action

**Comment by nibblesnbits** [comment]
@ekeric13, do you have a final version of this function?  I imagine it wouldn't be too bad to do myself, but if you've got a tested version, I'd love to see it.

**Comment by ekeric13** [comment]
@nibblesnbits 
The code @Andarist has above is what you are looking for
```
function* takeFirst(pattern, saga, ...args) {
  const task = yield fork(function* () {
    while(true) {
      const action = yield take(pattern);
      yield call(saga, ...args.concat(action));
    }
  });
  return task;
}
```

"Call" blocks while "fork" does not block. So you can just take the takeEvery code:

```
function* takeEvery(pattern, saga, ...args) {
  const task = yield fork(function* () {
    while (true) {
      const action = yield take(pattern)
      yield fork(saga, ...args.concat(action))
    }
  })
  return task
}
```

and replace fork with call.

Personally I don't use a helper for takeFirst but simply a vanilla saga pattern.

```
function* watcher() {
  while (true) {
    const action = yield take(pattern);
    yield call(saga, action);
  }
}
```

**Comment by tgevaert** [comment]
For anyone finding this pattern from a google search, be aware that the above `takeFirst` implementation matches the older style `takeEvery` helper functions from pre `v0.14.0`.  (See the [changelog](https://github.com/redux-saga/redux-saga/releases/tag/v0.14.0)

If you're using the newer style
```
import {takeEvery} from 'redux-saga/effects';
...
yield takeEvery(...)
...
```

Implementing `takeFirst` as above does not get invoked the same way.  You need
```
yield* takeFirst(..)
```
(note the `*`) otherwise `takeFirst` will block.

**Comment by Andarist** [comment]
actually `takeFirst` should be defined as:
```js
export const takeFirst = fork(function* (pattern, saga, ...args) {
  while(true) {
    const action = yield take(pattern);
    yield call(saga, ...args.concat(action));
  }
})
```
that way it could be yielded like this (without the `*`):
```js
yield takeFirst(...)
```
and it would mirror how `takeEvery` etc are implemented in the core.

**Comment by Andarist** [comment]
There is other issue about this - https://github.com/redux-saga/redux-saga/issues/1315 and outside contributor has offered his help in providing this.

**Comment by Amareis** [comment]
@Andarist your code in latest message doesn't run, seem to fork return not a function, but just effect in current redux-saga version.
```js
import { fork, call, take } from 'redux-saga/effects'

export default fork(function* (pattern, saga, ...args) {
    while(true) {
        const action = yield take(pattern)
        yield call(saga, ...args.concat(action))
    }
})
```

```js
import takeFirst from 'utils/takeFirst'

export default function* locationRootSaga() {
    yield all([
        takeFirst(LOCATION_CHANGE, onLocationChange),
    ])
}
```

```
uncaught at rootSaga 
 TypeError: (0 , _takeFirst.default) is not a function
```

**Comment by Andarist** [comment]
please correct it to:
```js
import { fork, call, take } from 'redux-saga/effects'

export default (pattern, saga, ...args) => fork(function* () {
    while(true) {
        const action = yield take(pattern)
        yield call(saga, ...args.concat(action))
    }
})
```
although Ive looked on this only for a brief moment, so I hope it will work for you

**Comment by Amareis** [comment]
Yeah, I already did it in my code and this works perfect, TY. But is this helper will included into library?

**Comment by Andarist** [comment]
Maybe - it needs internal implementation. I'd also appreciate better name for it though as `takeFirst` is imho not the best one.

**Comment by tkvw** [comment]
👍, what about `takeEarliest`?

**Comment by jacobbuck** [comment]
`takeLeading`?

**Comment by Andarist** [comment]
I like `takeLeading` 👍 @tomoyukim r u still working on this?

**Comment by tomoyukim** [comment]
@Andarist Yes. I've almost finished on my local and greatly appreciated a little more wait. I'll rename the helper with `takeLeading`. Thank you.

**Comment by SmirnovW** [comment]
@tomoyukim hurry dude, we can't live without it! :)

**Comment by Andarist** [comment]
Please don't be demanding about OSS (even with added smile) - it can truly discourage people from helping. Pressure is never good and we all are just volunteers here.

**Comment by SmirnovW** [comment]
@Andarist ok, I don't want to demand anything from anybody. I just wanted to say that this is very cool and really needed feature.
@tomoyukim sorry if that was rude :(

**Comment by tomoyukim** [comment]
@SmirnovW No problem! Thank you.

**Comment by tomoyukim** [comment]
I've finally been able to create PR for `takeLeading`. Thank you very much for waiting long time.

**Comment by justgeek** [comment]
@SmirnovW You did not sound demanding. Some people just don't understand simple stuff properly :) (Even with a smiley)

**Comment by thorlukasz** [comment]
Is the build with `takeLeading` released on the npm?

**Comment by restrry** [comment]
@thorlukasz https://github.com/redux-saga/redux-saga/releases/tag/v1.0.0-beta.1

**Comment by thorlukasz** [comment]
Thanks so much. Is there any scheduled release date for this release :) ?

**Comment by Andarist** [comment]
@thorlukasz it's released, just under beta tag and not the latest, you have to install it with `npm install --save redux-saga@beta`

**Comment by rendomnet** [comment]
@Andarist will it get in release build?

**Comment by Andarist** [comment]
>  it's released, just under beta tag and not the latest, you have to install it with npm install --save redux-saga@beta

**Comment by rendomnet** [comment]
@Andarist yeah I'm using it this way. And wonder will it move to release?

**Comment by Andarist** [comment]
It will, we hope to release final v1 this month (or next one).

**Comment by crobinson42** [comment]
Hi there, I'm in the camp of "still wrapping my head around sagas :-)"

Both of these solutions seem to solve this need of "take first/leading", what's the difference in yielding `fork` and _not_ here?

```
function* takeFirst(pattern, saga, ...args) {
  yield fork(function*() {
    while (true) {
      const action = yield take(pattern);
      yield call(saga, ...args.concat(action));
    }
  });
}

function* takeLeader(pattern, saga, ...args) {
  while (true) {
    const action = yield take(pattern);
    yield call(saga, ...args.concat(action));
  }
}

export default function* rootSaga() {
  yield all([
    takeFirst("INCREMENT_ASYNC", incrementAsync), 
    takeLeader("INCREMENT_ASYNC", incrementAsync),
  ]);
}
```

Thanks!

**Comment by Andarist** [comment]
Your snippets are roughly equivalent - `fork` is only adding an extra layer of a task internally.

I think what you might have meant is the difference between those:
```js
function* takeFirstA(pattern, saga, ...args) {
  yield fork(function*() {
    while (true) {
      const action = yield take(pattern);
      yield call(saga, ...args.concat(action));
    }
  });
}

function takeFirstB(pattern, saga, ...args) {
  return fork(function*() {
    while (true) {
      const action = yield take(pattern);
      yield call(saga, ...args.concat(action));
    }
  });
}
```

`takeFirstB` is a factory for an effect (so idiomatic way of running new tasks in saga), whereas `takeFirstA` is a generator, so to run it in idiomatic way (through effects) you should actually do `yield fork(takeFirstA, "INCREMENT_ASYNC", incrementAsync)`.

**Comment by JoshMcCullough** [comment]
> I'd also appreciate better name for it though as `takeFirst` is imho not the best one.

I'm confused by this `takeFirst` vs. `takeLeading` talk. I'm also confused by the examples. Furthermore, I realize this post is very old!

My primary concern here / what I'm looking for is "take exactly one action of this pattern and never, ever take any more". Reading the docs for the "new" `takeLeading`, it sounds like it will continue to take actions and process them. Even the docs are confusing:

> Spawns a `saga` on each action dispatched to the Store that matches `pattern`.

This first line from the README makes it sound like it will fire the saga for every action matching pattern. (The word "each" here implies every -- e.g. `takeEvery`, at least to me.)

> After spawning a task once, it blocks until spawned saga completes and then starts to listen for a `pattern` again.

The following line makes it sound like it fires the saga for every action matching the pattern, but essentially blocks / fires one action/saga at a time.

Given the above, I don't understand still how `takeLeading` is a proper name. Seems like `takeSequentially` is more appropriate. 

I am now under the assumption that `takeLeading` is **not** intended to literally take the first and only the first _ever_ action matching the pattern, but it rather continues to take them and runs the actions through the saga in sequence.

---

So, for my requirement of "take exactly one action of this pattern and never, ever take any more", I would suggest that I only need to do:

```js
function* takeOnlyOne(pattern, saga, ...args) {
  const action = yield take(pattern);
  
  yield call(saga, ...args.concat(action));
}
```

That is, remove the `while `loop. Is this correct?

**Comment by neurosnap** [comment]
I understand your confusion, the docs are something we want to spend some time updating soon.  Another option is to read the source code to figure out what these helper functions do:

https://github.com/redux-saga/redux-saga/blob/master/packages/core/src/internal/sagaHelpers/takeLeading.js

We don't use generators in our own source code, so it's a little hard to read.  It pretty much translates to this code:

```js
function* takeLeading(patternOrChannel, worker, ...args) {
  while (true) {
    const action = yield take(patternOrChannel)
    yield call(worker, ...args);
  }
}
```

> So, for my requirement of "take exactly one action of this pattern and never, ever take any more"
> That is, remove the while loop. Is this correct?

That's correct!

**Comment by JoshMcCullough** [comment]
@neurosnap thanks. To your knowledge has a "take only one" option been suggested before? I wouldn't want to suggest one if it's already been suggested / declined. I'm surprised this wouldn't be needed more often e.g. to fetch configuration information only once per app load.

**Comment by dongseok0** [comment]
It's quite old one but I just faced an issue that it terminates other sagas blocked on the effect. 

> The middleware provides a special action END. If you dispatch the END action, then all Sagas blocked on a take Effect will be terminated regardless of the specified pattern. If the terminated Saga has still some forked tasks which are still running, it will wait for all the child tasks to terminate before terminating the Task.

ref. https://redux-saga.js.org/docs/api#takepattern
 
So my version is
```
export const takeOnlyOnce = (patternOrChannel, saga, ...args) =>
  fork(function* () {
    const action = yield take(patternOrChannel);
    yield call(saga, ...args.concat(action));
  });
```
