### ISSUE TITLE
Create a test-utils library with raceResult()

### ISSUE THREAD

**Issue by mjrussell** [yelouafi/redux-saga#59]
I've recently been writing some tests for a race condition and Im really impressed with how easy it is to test. There's one thing that bothers me a little bit which is how the tester needs to know a bit about the implementation of race.

Lets say we have the following (inside some loop with an interval variable):
```js
 const { stop, update } = yield race({
    delay: call(delay, interval),
    update: take('UPDATE'),
    stop: take('STOP'),
  })

  if (stop) {
    break;
  } else if (update) {
    interval = update.payload.interval;
  }
      
```

I can do a test like:
```js
   let next = generator.next()
    expect(next.value).to.deep.equal(race({
      delay: call(delay, 100),
      update: take('UPDATE'),
      stop: take('STOP'),
    }))

    // Assume update wins
    next = generator.next({ update: { payload: { interval: 50 } }, start: null, delay: null })
    // Test something on the update
```

This is actually pretty good, but it seems like I have to know something about the internals of race. I wonder if it might make more sense to include a `raceResult` testUtility that allows you to abstract this knowledge away and if in the future the internals of race change, it would be transparent.

Id imagine something like:
````js
generate.next(raceResult({
   update: { payload: { interval: 100 }
})
```
or even `generate.next(raceResult('update', { payload: { interval: 100 }))` and have it handle the unpacking to null.

Do you think this would be something useful? If so I could swing a PR together. I could envision several testing utilities for the spec mode, maybe there is one for handling the tasks which have been popping up in other issues.

**Comment by yelouafi** [comment]
Unless I miss something. You dont have to put the loser keys with null. It should just work with just the winner key 'update' key alone.

**Comment by mjrussell** [comment]
It seemed like the unpacking due to `const { stop, update } = yield race({`ended up causing a null point. I can double check though

**Comment by yelouafi** [comment]
Actually the result of race is an object that only includes the winner key. That's why i said nulled keys are unnecessary

**Comment by mjrussell** [comment]
Ah yeah my bad, closing this
