### ISSUE TITLE
try and catch not working correctly inside the generator

### ISSUE THREAD

**Issue by aindong** [yelouafi/redux-saga#592]
Hi guys, I'm trying to implement a session saga, 

The page will be in SESSION_GET state using this handleAppEnter

```javascript
handleAppEnter = (nextState, replace, callback) => {
        new Promise((resolve, reject) => {
            this.props.getSession(resolve, reject);
        }).then(() => {
            if(nextState.location.pathname === '/'){
                replace('/dashboard');
            }
            callback();
        },() => {
            callback();
        });
    };
```

```javascript
render() {
        const routes = (
            <Route path="/" onEnter={this.handleAppEnter} component={App}>
                <IndexRoute component={UserIsAuthenticated(Home)} />
                <Route path="/login" component={UserIsUnAuthenticated(Login)} />
                {/*<Route path="/dashboard" component={UserIsAuthenticated(Home)} />*/}
            </Route>
        );

        return (
            <Router history={this.props.history}>
                {routes}
            </Router>
        )
    }
```

then here is the actions@getSession

```javascript
export const getSession = (resolve, reject) => ({
    type: SESSION_GET,
    meta: {
        resolve,
        reject
    }
});
```

and here is my watchSessionGet function

```javascript
export function* watchSessionGet() {
    yield takeLatest(SESSION_GET, getSession);
}
```

then here is my getSession generator

```javascript
export function* getSession(action) {
    let resolve = null;
    let reject = null;
    const hasMeta = action && action.hasOwnProperty("meta");
    if(hasMeta){
        resolve = action.meta.resolve;
        reject = action.meta.reject;
    }

    try {
        const payload = yield call(getSessionApi);
        yield put({ type: SESSION_GET_SUCCESS, payload });

        if(resolve){
            yield call(resolve);
        }
    } catch (err) {
        yield put({ type: SESSION_GET_FAILED });
        if(resolve){
            yield call(reject);
        }
    }
}
```

the generator will call for the action `getSessionApi` - a fetch function that returns a promise

here it is
```javascript
export const getSessionApi = () => {
    fetch(`${API_HOST}/admin/auth`, fetchOpts('GET')).then(
        (res) => {
            // eslint-disable-next-line
            if(res.status == 200){
                // sessionStorage.setItem('session', JSON.stringify(res.json()));

                return res.json();
            }
            throw res;
        }
    )
};
```
even though I have a try and catch on the getSession generator and throwing the exception from the fetch or called function. The catch block doesn't seem to catch it.

<img width="1178" alt="screen shot 2016-10-18 at 12 53 27 pm" src="https://cloud.githubusercontent.com/assets/1896053/19464842/0aea3198-9532-11e6-9cdc-96c06733cc68.png">

the supposed `reject` function for the Promise doesn't seem being triggered at all. Please help me. Thank you so much. I might have overlooked into something. Thank you in advance.

**Comment by Andarist** [comment]
First of all your `getSessionApi` doesnt return a `Promise`. You should add explicit `return` or omit surrounding curly brackets to leverage the implicit one. Please check again after you fix this.

**Comment by aindong** [comment]
@Andarist `getSessionAPI` should return the data I got from the server so I return the `response.json()`. I'm sending the `promise` to `getSession` using `handleAppEnter` with the `onEnter` event of `react-router`.  and this one is working


```javascript
export const postSessionApi = (credentials) => (
    fetch(`${API_HOST}/admin/auth`, fetchOpts('POST',credentials)).then(
        (res) => {
            // eslint-disable-next-line
            if(res.status == 200){
                // sessionStorage.setItem('session', JSON.stringify(res.json()));

                return res.json();
            }
            throw res;
        }
    )
);
```

**Comment by aindong** [comment]
oops I got it. Sorry for not understanding your first statement @Andarist

**Comment by Andarist** [comment]
No problem, happy you got it working :)

**Comment by aindong** [comment]
@Andarist I accidentally put curly brackets instead of parenthesis >_< that's why it is not returning anything. LOL

**Comment by Aarbel** [comment]
Had same issue with generators and try / catch. 

Was coming from the fact i was catching error in the fetch function, so the error wasn't 'catched' in the try catch and was 'stopped' before.
