### ISSUE TITLE
Unit Testing with Channels

### ISSUE THREAD

**Issue by mjrussell** [yelouafi/redux-saga#597]
I started using channels in my app, really liking the interface so far. I'm running into some issues writing tests for them however.

lets say I have the following (trivialized)

``` js
function* mySaga() {
  const chanA = yield actionChannel('TYPE_A');
  const actionA = yield take(chanA);
  yield put({ type: 'GOT_A' });
  // Some other blocking stuff cause channels are awesome
}
```

Now I want to write a unit test, it seems like it should be:

``` js
// test setup above
const generator = mySaga();
const testChanA = actionChannel('TYPE_A');
expect(generator.next()).to.deep.equal(chanA); // This fails because the functions inside the channel objects don't compare for equality
expect(generator.next(testChanA)).to.deep.equal(take(testChanA)); // Also fails, see error below
expect(generator.next({ type: 'A' }).to.deep.equal(put({ type: 'GOT_A' }));
```

I understand why the channels have issues comparing for deep equality here, maybe there could be a helper which can check if the arguments to the channel are identical? If this was the only issue I could skip the first expect, and just do a `generator.next()` to keep the test moving.

The real problem is in the `take`. I can't even get to that line of testing because of the following error:
`Error: take(patternOrChannel): argument [object Object] is not valid channel or a valid pattern`.

I assume that this is because there is something special happening when you yield the actionChannel to redux-saga which I cant do in the test, but I'm not sure exactly whats going on under the hood here.

Any advice testing these (and eventChannels) would be greatly appreciated!

**Comment by Andarist** [comment]
This
```
const generator = mySaga();
const testChanA = actionChannel('TYPE_A');
expect(generator.next()).to.deep.equal(chanA);
```
should be
```
const generator = mySaga();
const testChanA = actionChannel('TYPE_A');
expect(generator.next()).to.deep.equal(testChanA);
```

Effects are just plain object and `actionChannel` effect does not hold any function references so it should be fine to check deep equality against it. Effects become executed only after real redux-saga interprets them.

Personally I think this way of testing the saga (iterating through the generator) is far away from perfect anyway, there is a begining of the effort to make testing more robust, so it can be tested more in store-like environment and so you wouldnt have to worry about inserting a new non-behaviour-changing yield in between to break your tests. Just look on some other threads about testing in the issues. There are even 2 community written libraries which aim at easing that.

About `take(channel)` - you probably could mock `channel` in your test. You can even `import  { channel } from 'redux-saga'` and have the interface implemented already. So this
```
expect(generator.next(testChanA)).to.deep.equal(take(testChanA)); // Also fails, see error below
```
would become smth like
```
const mockedChannel = channel()
expect(generator.next(mockedChannel)).to.deep.equal(take(mockedChannel));
```

**Comment by yelouafi** [comment]
also `generator.next().value` instead of `generator.next()`

**Comment by jawb** [comment]
I'm wondering what's the best way to test sagas.
I agree with @Andarist, iterating through the generator doesn't seem like a good testing  mechanism. For example I wrote this [saga](https://github.com/jawb/JSVMReact/blob/master/JSVM/app/data/sagas/executer.js) and I'm still not sure how to test it.

**Comment by mjrussell** [comment]
Sorry for not responding sooner, I was focused on #598. Thank you for the responses, I tried to over simplify my example and then ended up having bugs/typos in the example 😞 

I got confused about the difference between the effect descriptor and the actual channel in my testing at first. I was trying to pass back into the generator the result of `actionChannel` but I needed a mocked channel instead as @Andarist pointed out. Im going to post a quick example below in case other people run into this.

```js
function* channelSaga() {
  const chanA = yield actionChannel('TYPE_A');
  const chanB = yield actionChannel('TYPE_B');

  while (true) {
    const { a, b } = yield race({
      a: chanA,
      b: chanB,
    });

    if (a) {
      yield put(a);
    } else if (b) {
      yield put(b);
    }
  }
}

describe('Testing channelSaga', () => {
  it('Can unit test', () => {
    const generator = channelSaga();

    let next;
    next = generator.next();

    const mockChanA = channel();
    const mockChanB = channel();

    expect(next.value).to.deep.equal(actionChannel('TYPE_A'));
    next = generator.next(mockChanA);

    expect(next.value).to.deep.equal(actionChannel('TYPE_B'));
    next = generator.next(mockChanB);

    expect(next.value).to.deep.equal(race({
      a: mockChanA,
      b: mockChanB,
    }));

    next = generator.next({ a: { type: 'TYPE_A' } });
    expect(next.value).to.deep.equal(put({ type: 'TYPE_A' }));

    next = generator.next();
    expect(next.value).to.deep.equal(race({
      a: mockChanA,
      b: mockChanB,
    }));

    next = generator.next({ b: { type: 'TYPE_B' } });
    expect(next.value).to.deep.equal(put({ type: 'TYPE_B' }));
  });
});
```

**Comment by mjrussell** [comment]
Also looking forward to alternative ways of testing, agree that using a mock store or some other approach is probably better long term so your tests aren't so tightly coupled to the implementation details of the saga

**Comment by simonbuchan** [comment]
`channel()` has implementation, so even if `take(channel())` only returns a description of the effect I feel a bit weird using it as a mock. Worse, you can't distinguish instances in failures, so I prefer meeting the minimal (read-only) API of channels:

```js
function createMockChannel(name = 'channel') {
  return { name, take: jest.fn(), close: jest.fn() };
}
```
