### ISSUE TITLE
Missed actions with take when using put

### ISSUE THREAD

**Issue by mjrussell** [yelouafi/redux-saga#598]
So I've been struggling with trying to create an example for this and I haven't been able to do so, but I think the result of the saga monitor should be compelling enough to hopefully explain a bit about what I'm seeing.

I've been very careful in my app to avoid using blocking actions (like `call`) in the same saga as those that use `take`. And use helpers where I can. My understanding is that `put` is safe because it is non-blocking. However, I'm seeing an issue where a `put` appears to be taking so long to complete that it misses a subsequent `take` completely. To be fair, I could refactor my code to use `actionChannels` (this works quite well in this case). **However** it forces me to question my understanding of `put` and other places in my code where I use `put` and `take` together.

Here is the sagaMonitor which shows how I am missing a `take` because of the length of time it takes for the `put` to complete. Both sagas should get a `SOCKET_PUSH`, followed by a `SOCKET_SEND_PARSE_RESPONSE`, and then a final `SOCKET_PUSH`, but you can see the second one missed the `SOCKET_SEND_PARSE_RESPONSE` because the `put` took too long (185ms).

![image](https://cloud.githubusercontent.com/assets/1641895/19570013/e79764b4-96ac-11e6-822e-706866d252a6.png)

A little background info on my saga. The `appSocketForwardParser` has two types of messages it cares about `SOCKET_PUSH` and `SOCKET_SEND_PARSE_RESPONSE`. The `SOCKET_PUSH` come from another saga listening to a websocket `onMessage` and the `SOCKET_SEND_PARSE_RESPONSE` are dispatched via redux actions. Internally in the saga, we are building a map from to parse socket responses to redux actions, that can be added to dynamically with `SOCKET_SEND_PARSE_RESPONSE` messages which are then dispatched with `put`.

The only difference between `appSocketForwardParser` and `appSocketForwardParserCopy` is the following line which is the source of the `put` in the sagaMonitor:

``` js
yield put({ ...parsedAction, type: 'FOO' }); // original yield put({ ...parsedAction });
```

Essentially Im just clobbering the type of the parsedAction, so this redux action gets dispatched and nothing is "looking for it".

My guess right now is that `put` takes longer to return because this sets up a lot of initial data in my store and forces rendering of many components. There isn't another saga listening for this type, and I don't have any middleware that perform an action for this type either.

Thanks for the great, library and any help you can provide on this

**Comment by Andarist** [comment]
Could you probably post code both of `appSocketForwardParser` and `appSocketForwardParserCopy`. I see there are some races involved and to better understand the flow it would be really helpful.

**Comment by mjrussell** [comment]
Sure...its a bit long but here goes:
```js
export function* appSocketForwardParser(app, parser, forwardForApp = isForwardForApp(app),
  parseResponseForApp = isParseResponseForApp(app), parseFrame = parseAppFrame) {
  // Map from sequenceId to the parser responsible for it
  let parsersBySequence = {};
  while (true) {
    const { parseResponse, forward } = yield race({
      parseResponse: take(parseResponseForApp),
      forward: take(forwardForApp),
    });
    if (forward) {
      const payload = parseFrame(forward);
      let parsedAction;
      try {
        // If its a forward, check if there is a sequence and a parser for that sequence
        if (_.isNumber(payload.sequence)) {
          const parserForSequence = parsersBySequence[payload.sequence];
          if (parserForSequence) {
            parsedAction = parserForSequence(payload);
            parsersBySequence = _.omit(parsersBySequence, payload.sequence);
          } else {
            /* eslint-disable no-console */
            console.log('Received socket payload with sequence without parser, using default parser', payload);
            /* eslint-enable */
            parsedAction = parser(payload);
          }
        } else {
          parsedAction = parser(payload);
        }
      } catch (error) {
        yield put({ type: APP_SOCKET_PARSE_ERROR, error: true, payload: { error, payload } });
        continue; // eslint-disable-line no-continue
      }
      if (parsedAction) {
        yield put(parsedAction);
      } else {
        yield put({ type: APP_SOCKET_UNKNOWN_FRAME, error: true, payload: { payload } });
      }
    } else if (parseResponse) {
      const { payload: { sequence, parser: parserForSequence } } = parseResponse;
      if (_.isNumber(sequence) && _.isFunction(parserForSequence)) {
        parsersBySequence = {
          ...parsersBySequence,
          [sequence]: parserForSequence,
        };
      } else {
        console.error('Parse response request was invalid', parseResponse); // eslint-disable-line no-console
      }
    }
  }
}
```

```js
export function* appSocketForwardParserCopy(app, parser, forwardForApp = isForwardForApp(app),
  parseResponseForApp = isParseResponseForApp(app), parseFrame = parseAppFrame) {
  // Map from sequenceId to the parser responsible for it
  let parsersBySequence = {};
  while (true) {
    const { parseResponse, forward } = yield race({
      parseResponse: take(parseResponseForApp),
      forward: take(forwardForApp),
    });
    if (forward) {
      const payload = parseFrame(forward);
      let parsedAction;
      try {
        // If its a forward, check if there is a sequence and a parser for that sequence
        if (_.isNumber(payload.sequence)) {
          const parserForSequence = parsersBySequence[payload.sequence];
          if (parserForSequence) {
            parsedAction = parserForSequence(payload);
            parsersBySequence = _.omit(parsersBySequence, payload.sequence);
          } else {
            /* eslint-disable no-console */
            console.log('Received socket payload with sequence without parser, using default parser', payload);
            /* eslint-enable */
            parsedAction = parser(payload);
          }
        } else {
          parsedAction = parser(payload);
        }
      } catch (error) {
        yield put({ type: APP_SOCKET_PARSE_ERROR, error: true, payload: { error, payload } });
        continue; // eslint-disable-line no-continue
      }
      if (parsedAction) {
         yield put({ ...parsedAction, type: 'FOO' }); // original yield put({ ...parsedAction });
      } else {
        yield put({ type: APP_SOCKET_UNKNOWN_FRAME, error: true, payload: { payload } });
      }
    } else if (parseResponse) {
      const { payload: { sequence, parser: parserForSequence } } = parseResponse;
      if (_.isNumber(sequence) && _.isFunction(parserForSequence)) {
        parsersBySequence = {
          ...parsersBySequence,
          [sequence]: parserForSequence,
        };
      } else {
        console.error('Parse response request was invalid', parseResponse); // eslint-disable-line no-console
      }
    }
  }
}
```

Thanks for looking into this!

**Comment by Andarist** [comment]
Are you able to debug a little bit the saga internals? Crucial would be to check if and possibly why during your - `yield put(parsedAction)` there is a lock preventing from the effect being executed immediately. From what I see in the source code, the only reasoning I might come to is that - its locked for some reason and lock is lifted too late, so in the meantime websocket's onmessage callback is emiting the action you would expected `race` is already waiting for.

https://github.com/yelouafi/redux-saga/blob/dfefd046d70615c662971b10438c0881fe84503f/src/internal/asap.js#L5 - it would be the starting point for debugging. I would propose checking these:
1. if it is locked indeed
2. when the lock is taken down (what line is doing a `flush` and why)
3. when the lock was set up in the first place, before coming to the point of `yield put(parsedAction)`

**Comment by mjrussell** [comment]
I threw a few console logs in each function inside `asap.js`. Im not exactly sure 100% what Im looking for through. Could you explain a bit about when `suspend` and `flush` should be called? It does appear that during the `put` call `isSuspended` is true and there isn't a flush until much later.

![image](https://cloud.githubusercontent.com/assets/1641895/19630725/5feae7f2-9945-11e6-88e5-8e037fd41114.png)

**Comment by mjrussell** [comment]
One thing that is possibly interesting, is that in another saga there is a `race` of a couple different `take` calls. Its listening for the `HARDHAT_OPEN_DATA` redux action, and subsequently does the `put` of the `APP_SOCKET_CONNECTED`. It seems like the call to flush is occurring only after this finishes.

**Comment by Andarist** [comment]
Hm, there is quite some things going on here and debugging it through this issue thread might be a rl long process ;) Could we maybe schedule some teamviewer session or smth to handle it?

**Comment by mjrussell** [comment]
Yeah definitely! I'll message you on gitter and we can set something up

**Comment by Andarist** [comment]
Got fixed in https://github.com/yelouafi/redux-saga/issues/622

**Comment by mjrussell** [comment]
👍 looking forward to the next release
