### ISSUE TITLE
Undo recipe code formatting off

### ISSUE THREAD

**Issue by baldwmic** [yelouafi/redux-saga#600]
<img width="1161" alt="screen shot 2016-10-21 at 00 15 43" src="https://cloud.githubusercontent.com/assets/10538297/19586546/00218c04-9724-11e6-93e0-803f1ec6fd88.png">

**Comment by Andarist** [comment]
Thanks for noticing.

@yelouafi 
I guess gitbook needs to be published, cause its fixed already on the master.

**Comment by yelouafi** [comment]
done
