### ISSUE TITLE
 Is there anything like 'non-blocking take'?

### ISSUE THREAD

**Issue by ImJoeHs** [yelouafi/redux-saga#601]
Sorry guys I am a rookie and the question below might seem kind of stupid , apologize.

I am trying to make two actions, 'loginflow' and 'jumptologin'. As their name , first is for login, and the second one will jump to the login page and goback when login success (replace the origin success callback), so im thinking about these code:

```
function* _loginFlow() {
    while (true) {
        const isJumpFromOthenPlace = yield take("JUMPTO_LOGIN");
        const { payload } = yield take("LOGIN");
        try {
            const { jsonResult } = yield call(api.login, payload.params);
            if (isJumpFromOthenPlace) {
                // jump back 
            } else {
                // the origin success staff
            }
        } catch (err) {
        }
   }
}
```
so is there anything like 'non-blocking take' can make this work? Or is there better solution to achieve that goal? I know I could store it as a state and just check but I am still wondering about the stuff above.

**Comment by Andarist** [comment]
Non-blocking - `take(pattern)` doesnt rly make sense, as `take` is acting as a listener for a `pattern` so it needs to be set up first and can listen only for actions AFTER being set up. Non-blocking kinda means that action would be available for a taking in the exact moment of `take` (listener) being set up. And those 2 cant happen in the same moment.

Non-blocking - `take(channel)` does make a little bit more sense, as `channel` can buffer things inside it, so it is possible that there is something already in the channel and in that case it will be returned to the saga synchronously so such scenario is made in non-blocking fashion. There is also a scenario where in the moment of `take` there is nothing in the buffer it will block until something pop ups in the buffer to be taken. To sum it up - non-blocking `maybeTake` (not the best name ;) ) would make sense only for `channel` usage, cause there are different scenarios right now when you `take(channel)`.

For a non-blocking `take(channel)` someone could maybe try to utilize smth like:
```
const actions = yield flush(channel)
if (actions) {
    // ...
}
```

But lets go back to your case I aint sure whats the exact flow you are trying to achieve, but probably you should check out the `race` effect.
```
function* callApi(login, params) {
    const { jsonResult } = yield call(login, params)
    yield put({ type: 'LOGIN_SUCCESS', data: jsonResult })
}
function* _loginFlow() {
    while (true) {
        const { payload } = yield take("LOGIN")
        yield fork(callApi, api.login, payload.params)
        const { jumpTo, loginSuccess } = yield race({
            jumpTo: take("JUMPTO_LOGIN"),
            loginSuccess: take("LOGIN_SUCCESS")
        });
        if (jumpTo) {
            // jump back
            continue
        }
        const { data: jsonResult } = loginSuccess.data
        // the origin success staff
   }
}
```

**Comment by arashd** [comment]
Also a total rookie here, but if you're trying to listen for two types of action, you can do: 
`const action = yield take(['ACTION_TYPE_1', 'ACTION_TYPE_2'])`
then check the action type:
`if (action.type === 'ACTION_TYPE_1')`
See the second to last example in [this section of the docs](https://yelouafi.github.io/redux-saga/docs/advanced/NonBlockingCalls.html)

**Comment by ImJoeHs** [comment]
Thank you! I should read the docs carefully.

**Comment by Andarist** [comment]
Yeah, didnt even think about it. Its probably in this case even a better
solution than racing 2 takes
