### ISSUE TITLE
Issue with Devtools & fork'd puts

### ISSUE THREAD

**Issue by lukebarton** [yelouafi/redux-saga#615]
When forking sagas and triggering puts, Devtools isn't able to reflect state changes properly. If I `call` rather than `fork`, the changes are reflected as expected.

Clicking pause in the Devtools seems to reconnect Devtools with the correct state.

I think it's related to `fork` because Devtools seems to erroneously report that a `fork`d action has changed the state back to the state at the time of the fork, if the state was since updated by other actions.

Please see the video for the oddness.

https://dl.dropboxusercontent.com/u/8812332/redux-devtools-bug2.mov

**Comment by Andarist** [comment]
Truth to be told I dont quite grasp whats the exact problem, it would be much better if you paste some code with explanatory whats wrong on each of the step and what did you expect to happen.

**Comment by zalmoxisus** [comment]
I tried a rough example as [written here](https://github.com/zalmoxisus/redux-devtools-extension/issues/249#issuecomment-258515651), but don't seem to reproduce the issue.

**Comment by zalmoxisus** [comment]
Should be fixed. @lukebarton please confirm.
