### ISSUE TITLE
Question: ignoring actions?

### ISSUE THREAD

**Issue by nibblesnbits** [yelouafi/redux-saga#616]
Quick question:  Is it possible to ignore actions?

I have a saga for a request in my application that can take about 10 seconds, and it is possible to fire the action for this saga more than once.  I need to only respond to the first request and ignore the rest.  How do I create a saga (or watcher, really) that will only execute when that action is not currently being run?

**Comment by Andarist** [comment]
I think you have the same question as in
https://github.com/yelouafi/redux-saga/issues/589

**Comment by nibblesnbits** [comment]
Yes, that's exactly what I needed.  Thanks!
