### ISSUE TITLE
Request to join cdnjs

### ISSUE THREAD

**Issue by ian4hu** [yelouafi/redux-saga#617]
redux-saga is a great middleware for redux, and I'm using it with public cdn service, and I can not found it in the cdnjs, would you mind to send redux-saga to cdnjs?

here is the [cdnjs/cdnjs](https://github.com/cdnjs/cdnjs)

**Comment by Andarist** [comment]
You've already filed an issue in their repository - https://github.com/cdnjs/cdnjs/issues/9501 . It got High Priority and an assignee already, so hopefully it will be added there soon. I think it should be handled there from now on, so gonna close the issue here.

**Comment by ian4hu** [comment]
Yes, after start this issue, I explore the cdnjs, and start a Add Request issue, it's ok to close this now.
