### ISSUE TITLE
Calling saga from within

### ISSUE THREAD

**Issue by nicoms91** [yelouafi/redux-saga#618]
Hi! I am trying to call a Saga from within (see example below) but when I send use `put `, this is not being taken. Example:
```

function * example () {
  while (true)
    yield take('initialAction')
    const someAction = yield call(apiClient.someClientAction, parameter)
    yield put({ type: initialAction' })
}
```

I wonder if this is the correct pattern or maybe am I missing something in the documentation.

Thanks in advance!

**Comment by Andarist** [comment]
That is not a correct pattern, that is because `put` causes `dispatch` but the generator is resolved only once the dispatch is finished, so it doesnt meet `take` again yet. Only subsequent `initialAction` could be taken by this `take`. 

Think of `take` as one-time subscriber to the action type. Once its resolved it's no longer listening to the action till the time generator meets it again so the subscriber can be set up once again.

**Comment by nicoms91** [comment]
@Andarist Thanks for the answer, I was suspecting something like this.

The way I managed to get it working now is to create a second function called wacther that will permit this loop. Here is what I got so far:

```
function * example () {
  while (true) {
    yield take('start')
    const someAction = yield call(apiClient.someClientAction, parameter)
    yield put({ type: initialAction' })
  }
}

function * watcher () {
    while(true){
    const actions = yield take('initialAction')
    yield put({type: 'start'})
  }
}
```

This is working, but I do not know if it is the most elegant way to solve the issue.

**Comment by Andarist** [comment]
Well i dont know whats the scenario u would like to handle. If you describe
what u can do i might look on it and possibly help a little

**Comment by nicoms91** [comment]
Sure, I will try to maintain things simple:

My main generator is a function that will process some actions that the server sends, things like play videos, show messages, etc. The payload for this will be in an array with object similar to: {actionType: PLAY_VIDEO, videoUrl: 'http....'}

The problem is that one of this actions will request a new call to the server endpoint requesting new actions. Something like this: {actionType: REQUEST_ACTIONS}.

So, ones I get these new actions, I should call the generator again and procces them.

The code would look something like this:

```
function * processServerActions () {
	
	while(true) {
		const nextActions = yield take('start')
		for (let action of nextActions.payload) {

			switch(action.actionType) {

				case REQUEST_ACTIONS:
					const nextAcitons = yield call(apiClient.requestActions)
					yiel put({actioType: 'start', payload: nextActions})
					break;

				case PLAY_ACTION:
					yield put({ type: PLAY_AUDIO, payload: action.url })
					break;

				case MESSAGE_ACTION:
					yield put({ type: ADD_MESSAGE, payload: action.payload })
					break;

				case CLEAR_MESSAGES_ACTION:
					yield put({ type: CLEAR_MESSAGES })
					break;
			}
		}
	}	
}
```

So, my problem lays in the REQUEST_ACTIONS case, where I would to call the generator again, but I cannot make to take this 'start' action, unless I use a second function like I show in my previous comment.

Let me know if it is clear or if I should add further details.

Thanks in advance!

**Comment by Andarist** [comment]
You could use `actionChannel(pattern)` + `take(channel)` instead of simple `take` to make it work. It has a built-in buffering in it. So it would look smth like this:

```
function * processServerActions () {
    const chan = yield actionChannel('start')
    while(true) {
        const nextActions = yield take(chan)
        for (let action of nextActions.payload) {
            switch(action.actionType) {
                case REQUEST_ACTIONS:
                    const nextAcitons = yield call(apiClient.requestActions)
                    yiel put({actionType: 'start', payload: nextActions})
                    break;

                case PLAY_ACTION:
                    yield put({ type: PLAY_AUDIO, payload: action.url })
                    break;

                case MESSAGE_ACTION:
                    yield put({ type: ADD_MESSAGE, payload: action.payload })
                    break;

                case CLEAR_MESSAGES_ACTION:
                    yield put({ type: CLEAR_MESSAGES })
                    break;
            }
        }
    }   
}
```

With that method, you wont miss any `start` action.

**Comment by nicoms91** [comment]
Great, it's working, thanks a lot for your help!
