### ISSUE TITLE
reusable components, distinguishing events?

### ISSUE THREAD

**Issue by aft-luke** [yelouafi/redux-saga#62]
I'm curious how one might utilize reusable components or dynamic components that involve a saga.

Consider if you had a date-picker on the page, perhaps a start date and end date for some configuration settings. That component might be pretty well isolated, perhaps even reusable across different applications. 

```javascript
parentAReducer(state, action) {
    ...
    case picker.PICK_DATE:
        state.startDate = action.pickedDate 

    ...
}

parentBReducer(state, action) {
    ...
    case picker.PICK_DATE:
        state.endDate = action.pickedDate 

    ...
}
```

Assuming you have already figured out a way to direct distinct/unique messages to the appropriate implementing reducer of the reusable component (perhaps attaching an id to the action, or some sort of sophisticated messaging bus) how can that distinction be made inside the saga?

```javascript
function* watchForEndDate() {
    while (true) {
        const {pickedDate} = yield io.take(picker.PICK_DATE)

        // ... ut oh, is this start date or end date? 
    }
}
```

The problem shifts slightly when dealing with not just reusable components, but dynamic reusable components, because suddenly you don't know until runtime how many identical actions you have to sift through to find the right one.

```javascript
function* watchForEndDate() {
    while (true) {
        const {pickedDate} = yield io.take(picker.PICK_DATE)

        // ... ut oh, is this start date or end date for our "widget A" or "widget B" or "widget A1" or "widget B1"? 
    }
}
```

It's very plausible this is a user-land concern, and not a library concern, but I would still be interested in hearing some thoughts others might have.

**Comment by yelouafi** [comment]
maybe related to #30

**Comment by aft-luke** [comment]
Thanks for the reference @yelouafi. I never considered runSaga for this approach, but it looks like it's more or less suitable. I have been struggling to find a way to have truly reusable components (where a component is a packaged set of actions, a reducer, and a view) inside the redux architecture. I *think* I managed to get what I'm looking for by exposing a `.create()` function on all reusable components that generates a uuid, wraps all their action creators with that unique id, and embeds the uuid in the state slice. When reducers are invoked, I first check if that id matches up with the instance id and only proceed if this is the case.

The issue I'm having, and perhaps this is related to https://github.com/yelouafi/redux-saga/issues/48 (but I don't really think so), is that when I spawn a `runSaga` during `.create()`, those reusable component's sagas never catch their first `take`.

```javascript
function* watchComponentMount(id) {
    while (true) {
        // ...this never triggers
        const event = yield io.take(acitons.COMPONENT_MOUNTED)
        if (event.id !== id) continue
        ...
    }
}

...
create(reusableComponent) {
    const uuid = cuid()
    if (reusableComponent.hasSagas()) {
        const dynamicSagas = reusableComponent.getSagas().map((saga) => {
            return runSaga(
                saga(uuid)
                , storeIO(store)
            )
        })
    }

    ...
}
...
```

If I utilize the normal middlewares, though, the same saga will capture that event.

```javascript
initSagas() {
    return function* rootSaga() {
        yield io.fork(watchComponentMount)
    }
}
```

I have dug around a bit making sure that my app code isn't doing something funny, but I just can't see what the source of the problem might be.

**Comment by yelouafi** [comment]
when do you call your create function ? not after the component has been mounted ?

**Comment by aft-luke** [comment]
To give you a bigger picture, here's a bit more detail.

In short, `create` is invoked prior to mounting. I can prove this by introducing breakpoints, but also by the fact that a `io.fork(watchComponentMount)` saga that runs through the "normal" middleware captures this event without issue.

```javascript

function parentReducer(state, action) {
    switch (action.type) {
        case ACTION_THAT_REQUIRES_CREATING_CHILD:
            state = {
                ...state
                , childState: reusableChildReducer.create()
            }
            return state
        ...
    }

function reusableChildReducer(state, action) {
    switch (action.type) {
        case '$create':
            // special key invoked on .create()
            // ...do some initializing stuff
            return { ...state, someInitValue: 'foo' }
        ...
    }
}

// any component that wants to be "reusable" is decorated by this wrapper
reusableDecorator.create = (initialState = {}, action = {}) => {
    const id = cuid()

    // wrap the action creators of this reusable component so each call
    // to a creator enchances the { type: some_type, ...args } action
    // object with the unique id associated with this created instance
    const wrappedActionCreators = wrapActionCreatorsWithId(id, initialState)

    // run the reducer once with a special key to initialize any default
    // properties.
    //
    // <<Important>> provide the wrapped action creators as functions on
    // the initial state... this allows components to reuse our implementation
    // by simply handing down all properties (including the action creators)
    // to the view via <ReusableComponent { ...this.props.reusableStateSlice } />
    const reusableInitialState = reducerToDecorate(wrappedActionCreators, { type: '$create', ...args })

    if (reducerToDecorate.hasSagas()) {
        // same runSaga code as above
    }

    return reusableInitialState
}

```

I hope the above ^ makes sense.

As for the actual implementation, it's something like:

```javascript
componentDidMount() {
    this.props.mounted()
}

actionCreators() {
    mounted() {
        return {
            type: actions.COMPONENT_MOUNTED
        }
    }
}

reducer(state, action) {
    switch (action.type) {
        case '$create':
            ...
            return state
        ...
    }
}

// parent
render() {
    return (
        <div>
            // this is where the wrapped action creator is provided
            // to the reusable component (without each parent having
            // to "know" or implement its own versions of these creators)
            <ReusableComponent {...this.props.childState} />
        </div>
    )
}
```

**Comment by aft-luke** [comment]
Just for completeness' sake, here is the basics of the function that generates wrapped creators:

```javascript
function wrapActionCreatorsWithId(id, initialState) {
    // redux makes dispatch hard to get a handle onto - you only have the decoupled
    // handle during a mapDispatchToProps invocation on a Connect() component. instead
    // we are going to sideskirt the issue by taking a handle directly after the
    // store has been generated by the bootstrap, and use that handle to invoke
    // dispatch from within reusable components
    const dispatch = store.dispatch

    // store this on the state if needed for later use
    initialState._reusable = {
        id
    }

    let wrappedCreators = {}
    for (let p in actionCreators) {
        // each call to an action creator is really a call to the wrapper
        wrappedCreators[p] = (args) => {
            // get the original action object
            let created = actionCreators[p].call(null, args)

            // can only use this strategy without thunk-able action creators
            if (typeof created !== 'object') {
                throw new Error('reusable action creators must return plain objects')
            }

            // wrap each action creator with the id before dispatching
            created = { ...created, target: initialState._reusable }
            return dispatch(created)
        }
    }

    // return any initial state enhanced with the wrapped creator functions
    // present right on the state object-- this allows implementers using a
    // reusable component to remain ambivalent about the inner details of
    // the component
    return { ...initialState, ...wrappedCreators }
}
```

I noticed the monkey-patching used in `runSaga` to rewire `store.dispatch`, but my handle onto `dispatch` is taken after this patching completes, so that is also not the source of the issue.

**Comment by yelouafi** [comment]
can you try with the new version 0.6 ?

**Comment by aft-luke** [comment]
I'm slammed with work currently, I'll get back and let you know.

**Comment by aft-luke** [comment]
Hey @yelouafi I looked into this further after updating to `0.6.1` and the problem still remains. I'm pretty sure it's related to #48. The simple reason seems to be that `runSaga` has its own instance of eventEmitter when it should really be subscribing to the existing instance of middleware's eventEmitter. 

I have patched this in my own fork and things seem to be working as intended there, but the api is admittedly gross/difficult to use.

**Comment by yelouafi** [comment]
FYI https://github.com/yelouafi/redux-saga/releases/tag/v0.7.0

**Comment by aft-luke** [comment]
Just from perusing [the implementation](https://github.com/yelouafi/redux-saga/commit/eceefcfe585650df914b2b36e52f5035c48856e1) I can tell this will fix the problem, thanks!  

Is the API abandoning the ability to provide a different `IO` implementation?

**Comment by yelouafi** [comment]
>Is the API abandoning the ability to provide a different IO implementation?

No. runSaga is still here. Only storeIO was deprecated because of its issues
