### ISSUE TITLE
throttle and eventChannel

### ISSUE THREAD

**Issue by rosendi** [yelouafi/redux-saga#620]
Is it possible to throttle `eventChannel`?

Something like:

```
export const onEvent = (source, eventName) => eventChannel(emitter => {
  source.addEventListener(eventName, emitter);

  return () => {
    source.removeEventListener(eventName, emitter);
  };
});

function* saga() {
  const userEvent = yield call(onEvent, document, 'click');  

  yield throttle(1000, userEvent, function* () {
    ...
  })   
}
```

**Comment by Andarist** [comment]
For now it is not possible as `throttle` is implemented internally with `actionChannel(pattern, buffers.sliding(1))`. That was however something I was thinking about - ability to accept custom channels. 

Unfortunately implementation for now would be a little bit clunky, I'll might re-implement ir some time in the near future, but for now I would recommend you to use a custom `throttle` helper, here we go:

```javascript
export function throttle(delayLength, subscribe, worker, ...args) {
	const chan = eventChannel(subscribe, buffers.sliding(1))

	for (;;) {
		const item = yield take(chan)
		yield fork(worker, ...args, item)
		yield call(delay, delayLength)
	}
}
```

with that your code could look like:
```javascript
export const onEvent = (source, eventName) => emitter => {
  source.addEventListener(eventName, emitter);

  return () => {
    source.removeEventListener(eventName, emitter);
  };
};

function* saga() {
  const userEventSubscribe = yield call(onEvent, document, 'click');  

  yield throttle(1000, userEventSubscribe, function* () {
    ...
  })   
}
```

**Comment by Andarist** [comment]
And ofc there is always much simpler solution in your case - just throtte
the emitter and use throttled one in your addEventListener. Then just take
from the channel without any saga throttling. You can grab throttle from
lodash, some other utility lib or write ur own ofc

**Comment by rosendi** [comment]
@Andarist yep, I checked the throttle's source code, but it's a little bit tricky at first glance. Thank you for you answer!

I don't like throttling the emitter, because this way it becomes less generic, i.e I have to create a two different `eventChannel` for throttling and debouncing; or check the `eventChannel`'s options to conditionally apply throttle or debounce inside it. 

You added the enhancement label so I leave the issue open.

**Comment by Andarist** [comment]
Hm, I dont rly see the problem with it being 'less' generic as built-in `throttle` is not generic either. You wont be able to achieve debouncing with it, you wont also be able to achieve `trailingThrottle` nor `leadingThrottle` as all those things needs other logic than `throttle` itself.

So throttling the `emitter` is nothing different from it rly in my opinion.

**Comment by Andarist** [comment]
It is not possible for `throttle` helper to know if passed in function is a `subscriber` or just a `predicate` testing actions. Gonna close the issue in favor of implementing it in userland.
