### ISSUE TITLE
throttle is missing in definition file 'index.d.ts'

### ISSUE THREAD

**Issue by yenshih** [yelouafi/redux-saga#624]
Hi, I would like to using redux-saga with Typescript, but I got an error "Module has no exported member 'throttle'" when `import { throttle } from 'redux-saga`.
I've checked 'index.d.ts' and I couldn't find any definition about throttle.

**Comment by Andarist** [comment]
`redux-saga` is not written in TS nor using flow. Typings are added by community and included in the lib as courtesy for ppl liking to use such tools.

Would you be willing to add `throttle` typing? Its documented in the docs + function signature in the original source code is pretty straightforward.

**Comment by yenshih** [comment]
Sure, I just created a PR for this issue :)
