### ISSUE TITLE
Contradiction in docs whether `put` is blocking

### ISSUE THREAD

**Issue by datenreisender** [yelouafi/redux-saga#626]
In https://github.com/yelouafi/redux-saga/blame/c6af0703ba5e8829494583e33c1537e137569ff1/docs/Glossary.md#L41 it says that `put` is blocking, but in https://github.com/yelouafi/redux-saga/blame/c6af0703ba5e8829494583e33c1537e137569ff1/docs/api/README.md#L316 it says that it is non-blocking (and below that only `put.sync` is non-blocking). 

Which of those two is true? The other one should be corrected.

**Comment by banderror** [comment]
@datenreisender `put` is definitely non-blocking, and `put.sync` is blocking :)

**Comment by yelouafi** [comment]
Glossary example is outdated; should be updated.
