### ISSUE TITLE
Persist state

### ISSUE THREAD

**Issue by xcarpentier** [yelouafi/redux-saga#627]
Hello 😊
Is there a way or good practice to persist state with redux-saga ?

**Comment by Andarist** [comment]
There is no official 'good practice' for this use case, but it is really easy to implement such a thing. Persisting could be made as follows (the easiest scenario)

```javascript
const identity = a => a

const save = state => window.localStorage.setItem('persisted-state', JSON.stringify(state))
 
function* persistState() {
  const state = yield select(identity)
  yield call(save, state)
}

// ...

yield takeEvery('*', persistState)
```

But all of that rly depends on your use case, just play around with the snippet, accomodate it to your needs and think of rehydrating strategy.

**Comment by xcarpentier** [comment]
Why it's not possible to use redux-persist with redux-saga ?

**Comment by Andarist** [comment]
It is possible, in fact this is what Im doing in my project.

I just thought you want for whatever reason (i.e. not liking to include next library) to use sagas to achieve the same result

**Comment by xcarpentier** [comment]
Thank you.

I see it's possible to persist state using saga, but how do you rehydrate state when you reload the app ?

redux-persist must adapt is code I think to persist also with redux-sagas. But why it's not a problem with redux-thunk and it is with saga ? 

Is there a solution to provide a compatibility between both (ie. redux-persist & redux-saga, both are pretty much standard for  now) ?

**Comment by xcarpentier** [comment]
@Andarist is it possible know how you configure your store with redux-saga and redux-persist ?
Because of this issue : https://github.com/mxstbr/react-boilerplate/issues/396

**Comment by xcarpentier** [comment]
Ok so, I code a solution. I share it with you. (source cf. https://egghead.io/lessons/javascript-redux-persisting-the-state-to-the-local-storage#/tab-transcript)

It's for **react-native** (ie. _AsyncStorage_).

- `store.js`
```javascript
/**
 * @providesModule Store
 * @flow
 */

import { createStore, applyMiddleware } from 'redux';
import createSagaMiddleware from 'redux-saga';

import middleware from 'Middlewares';
import reducers from 'Reducers';
import sagas from 'Sagas';
import { loadState, persistStore } from 'PersistState';

const sagaMiddleware = createSagaMiddleware();
const createStoreWithMiddleware = applyMiddleware(...middleware, sagaMiddleware)(createStore);

const configureStore = async () => {
  const store = createStoreWithMiddleware(reducers, await loadState());
  persistStore(store);
  sagaMiddleware.run(sagas);
  return store;
};

export default configureStore;
```

- `persist.js`
```javascript
/**
 * @providesModule PersistState
 * @flow
 */

import AsyncStorage from 'AsyncStorage';
import throttle from 'lodash/throttle';

export const loadState = async () => {
  try {
    const serializedState = await AsyncStorage.getItem('state');
    if (serializedState === null) {
      return undefined;
    }
    return JSON.parse(serializedState);
  } catch (err) {
    return undefined;
  }
};

const saveState = (state) => {
  try {
    const serializedState = JSON.stringify(state);
    AsyncStorage.setItem('state', serializedState);
  } catch (err) {
    // Ignore write errors.
  }
};

export const persistStore = store =>
  store.subscribe(throttle(() => saveState(store.getState()), 777));
```

**Comment by Andarist** [comment]
Oh, sorry, I totally forgot posting here

Anyway - my usage of both `redux-saga` and `redux-persist` is pretty much the same as yours, had no trouble integrating them.
```javascript
// index.js
import { persistStore } from 'redux-persist'

const store = configureStore() // in which I apply middlewares and expose sagaMiddleware.run on store object
store.runSaga(rootSaga)
persistStore(store)

// and later in my reducer I have
import { REHYDRATE } from 'redux-persist/constants'

export default (state, action) => {
        switch (action.type) {
        case REHYDRATE:
            // update the state with rehydrated data from the storage
            return state
        }
}
```

gonna close it for now, if you have questions, just reopen and ask
