### ISSUE TITLE
Recommendations for working with WebRTC streams

### ISSUE THREAD

**Issue by tauren** [yelouafi/redux-saga#635]
I'm building an app that streams remote video using WebRTC into `<video>` tags in the DOM. This app is built upon libraries such as react, redux, reselect, immutable.js, and redux-saga. How do I get the video streams to my stateless react `<video>` component the "redux-saga" way? 

tldr;

Currently, my app state is comprised of simple primitives, objects and arrays, wrapped in Immutable.js constructs. My understanding is that the state should not contain classes, instances, promises, steams, and other complex or mutable structures. Considering this, it is not clear to me the best way to pass video streams back into my stateless components.

I have ideas on how to solve this. For instance, I could add video streams to some sort of a video stream registry singleton. A stream lookup key would be added to the state, and the video component would know how to find the stream for that key from the stream registry. But this doesn't seem right since now my video component is tightly coupled with this "global" registry.

My sagas trigger functions that utilize the WebRTC apis to create connections and establish data channels. Once a channel has been established, the channel's `onmessage` handler is triggered repeatedly with streamed video data. I somehow need to expose this data to my video component.

I'd love to get some feedback on how to pass a stream reference the "redux-saga" way, or even just the "redux" way. This [StackOverflow question](http://stackoverflow.com/questions/34137783/where-to-store-webrtc-streams-when-building-react-app-with-redux) is very similar to my question, and one of the answers suggests that using `redux-saga` might help. Hoping someone here can add some clarity.

**Comment by Andarist** [comment]
Well, you probably are familiar with the concept of smart and dumb components. Even if you create a singleton for your app so both - saga and components could access it, you wont couple dumb component, you will pass the necessary data/stream to it through the smart component, which is already coupled with redux, so I wouldnt consider it a big hassle.

I think what you have proposed with global registry is fine, probably could be put in react's `context`.
