### ISSUE TITLE
Using Sagas like middleware to reduce boilerplate, and putting actions to only other Sagas

### ISSUE THREAD

**Issue by AriaFallah** [yelouafi/redux-saga#64]
Hey so I was following along with your real world example, but there was a whole bunch of repeated logic:

For example in your actions file:

```javascript
export const USER = createRequestTypes('USER')
export const REPO = createRequestTypes('REPO')
export const STARRED = createRequestTypes('STARRED')
export const STARGAZERS = createRequestTypes('STARGAZERS')

// ....other stuff

export const user = {
  request: login => action(USER.REQUEST, {login}),
  success: (login, response) => action(USER.SUCCESS, {login, response}),
  failure: (login, error) => action(USER.FAILURE, {login, error}),
}

export const repo = {
  request: fullName => action(REPO.REQUEST, {fullName}),
  success: (fullName, response) => action(REPO.SUCCESS, {fullName, response}),
  failure: (fullName, error) => action(REPO.FAILURE, {fullName, error}),
}

export const starred = {
  request: login => action(STARRED.REQUEST, {login}),
  success: (login, response) => action(STARRED.SUCCESS, {login, response}),
  failure: (login, error) => action(STARRED.FAILURE, {login, error}),
}

export const stargazers = {
  request: fullName => action(STARGAZERS.REQUEST, {fullName}),
  success: (fullName, response) => action(STARGAZERS.SUCCESS, {fullName, response}),
  failure: (fullName, error) => action(STARGAZERS.FAILURE, {fullName, error}),
}
```

and then in your actual sagas file

```javascript
const fetchUser       = fetchEntity.bind(null, user, api.fetchUser)
const fetchRepo       = fetchEntity.bind(null, repo, api.fetchRepo)
const fetchStarred    = fetchEntity.bind(null, starred, api.fetchStarred)
const fetchStargazers = fetchEntity.bind(null, stargazers, api.fetchStargazers)
```

There's a lot more too, but I think it would be redundant to post it.

I used that as a guide for my own personal project since I had something really similar, but I realized that I could cut down on a lot of that by writing an apiCall saga and a promise Saga much like how one would have written middleware:

```javascript
// Create lifecycle of a promise
const createPromiseLifecycle = (base) => ({
  PENDING:  `${base}_PENDING`,
  RESOLVED: `${base}_RESOLVED`,
  REJECTED: `${base}_REJECTED`
})

function* apiCall() {
  while(true) {
    // Grab all actions with the API intention
    const { type, payload: { method, options } } = yield take((action) => action[actions.API])

    // Pass on the pending API call to the promise saga
    yield put({
      [actions.PROMISE]: true,
      type,
      payload: {
        promise: call(api[method], options)
      }
    })
  }
}

function* promise() {
  while(true) {
    // Grab all actions with the PROMISE intention
    const action = yield take((action) => action[actions.PROMISE])
    const lifecycle = createPromiseLifecycle(action.type)

    // Put out the fact the promise is pending
    yield put({ type: lifecycle.PENDING })

    // Try to resolve the promise
    try {
      const result = yield action.payload.promise
      yield put ({
        type: lifecycle.RESOLVED,
        payload: {
          result
        }
      })
    } catch(err) {
      yield put ({
        type: lifecycle.REJECTED,
        payload: {
          err
        }
      })
    }
  }
}
```

I have two questions about this:

1. Is this against what sagas are about? I've just interpreted them as middleware with much more advanced capabilities.

2. Is there any equivalent to `next` from middleware in sagas? If you noticed I do a `put` in my apiCall, but it has an undesired behavior as it also sends that action to the reducers. I want to be able to do a `put` that only my sagas can receive basically.

**Comment by yelouafi** [comment]
>Is this against what sagas are about? I've just interpreted them as middleware with much more advanced capabilities. 


Against no I dont think. But sagas can do more than that. See 

http://stackoverflow.com/questions/34930735/pros-cons-of-using-redux-saga-with-es6-generators-vs-redux-thunk-with-es7-async

>Is there any equivalent to next from middleware in sagas? If you noticed I do a put in my apiCall, but it has an undesired behavior as it also sends that action to the reducers. I want to be able to do a put that only my sagas can receive basically.

As long as the action types arent of any meaning to the reducer. It will ignore them. But you can if you want create a filter middleware that intercept all saga actions and put it after the redux-saga middleware in the middleware chain

**Comment by braco** [comment]
@yelouafi: what do you think of what @AriaFallah wrote, as a pattern? I too am put off by the repetitive boilerplate.

**Comment by AriaFallah** [comment]
@braco not really sorry. I haven't worked on that project where I was using redux-saga in a while.

**Comment by ryankask** [comment]
I found this issue after looking for solutions to reduce the amount boilerplate. For example, to an API call like login you have three `LOGIN_*` actions, a `login` action creator, a `login` saga, and a `login` API utility function.

I haven't spent much time abstracting this although I did write an API request saga factory that looks something like the code posted above.

I'm eager to see what other users are doing.

**Comment by jiayihu** [comment]
I had the same issue, so I just created a small gist with my own implementation of an action creator factory: https://gist.github.com/jiayihu/811f2dc704d6ce6308d679a987348b20

Can be used as following:

```javascript
export const addInvoice = createAction('ADD_INVOICE', {
  request: (invoice) => ({ invoice }),
  success: (invoice, result) => ({ invoice, result }),
});
```
