### ISSUE TITLE
What's the return value of select called after put?

### ISSUE THREAD

**Issue by AJIh** [yelouafi/redux-saga#641]
I read from the doc that `put` is non-blocking call. I am confused about the return value of select called after put.

```javascript
const selectAIsPositive = state => state.a > 0;

function *example() {
  // state = { a: -1 } now
  yield put(actionThatChangesA({ a: 1 }));  // action will reduce state to { a: 1 }
  const isPositive = yield select(selectAIsPositive);
}
```

Is `isPositive` true or false?

**Comment by Andarist** [comment]
Saga will resume this generator after `put` executs the `dispatch` under the hood. If there is no async in your middleware chain preventing action to hit the reducers you are good to go. `select` will return updated value

**Comment by AJIh** [comment]
@Andarist Thanks! So what's the difference of `put.sync` and `put`?

**Comment by Andarist** [comment]
`put.sync` has different logic for:
1. error handling, when `catch`ed it will `throw` on your saga
2. result handling - if `dispatch` returns a `Promise` it will block until this `Promise` is resolved

**Comment by AJIh** [comment]
Thank you for your help!
