### ISSUE TITLE
Dynamically load sagas

### ISSUE THREAD

**Issue by zoff** [yelouafi/redux-saga#645]
Hi all,

I have a large Angular2-redux project in which modules are loaded dynamically.
Every module defines its actions and reducers and register himself on a redux registry on load.

Something like this:
1. Application defines a shared ReduxRegistry
2. ReduxRegistry initialize Redux store with all middlewares using a "base reducer"
3. Every module on load:
    * calls reduxRegistryInstance.register(moduleReducer)
    * registers a service that offers redux action generators
3. ReduxRegistry detects reducer changes and updates its store

Is there any way to update sagas at runtime in a similar way?

**Comment by HansDP** [comment]
I'm working on something similar, but in React.

Some of my container components are loaded dynamically (as in: the main app does not know they exist). And these container components need to run a saga.

Currently, I'm exposing the `run` method from the saga middleware to those dynamic container components. So, I have some module similar to:

```javascript
import createSagaMiddleware from 'redux-saga'

const sagaMiddleware = createSagaMiddleware()

export const runSaga = sagaMiddleware.run
export default sagaMiddleware
```

This `runSaga` method is then passed to the container components, which can use it whenever they need it. This is a typical implementation of its usage:

```javascript
import React from 'react'
import myContainerSaga from './saga'

export default class MyContainer extends React.Component {
  componentWillMount() {
    const { runSaga } = this.props
    this.saga = runSaga(myContainerSaga())
  }
  componentWillUnmount() {
    if (this.saga) {
      this.saga.cancel()
    }
  }
}
```

**Comment by yelouafi** [comment]
as @HansDP commented, you can export the `sagaMiddleware.run` function. There is also the [runSaga](http://yelouafi.github.io/redux-saga/docs/api/index.html#runsagaiterator-options) which offers more control on running and connecting sagas dynamically.
