### ISSUE TITLE
yield takeLatest docs inconsistency

### ISSUE THREAD

**Issue by sepo-one** [yelouafi/redux-saga#648]
takeLatest docs:
- [api](https://yelouafi.github.io/redux-saga/docs/api/index.html#takelatestpattern-saga-args):
`function* watchLastFetchUser() {
  yield takeLatest('USER_REQUESTED', fetchUser)
}`

- [main page](https://github.com/yelouafi/redux-saga):
`function* mySaga() {
  yield* takeLatest("USER_FETCH_REQUESTED", fetchUser);
}`

so yield* takeLatest() should be with star, right ?
(because takeLatest() is actually a generator afaiu)

however it works both ways.
why would that be ?

**Comment by Andarist** [comment]
Those saga helpers are indeed iterators, so `yield*` will work and in fact it was the only way to use them some time ago, but they got decorated with internal flag, so when used as such `yield takeLatest` their iterators are wrapped under the hood with `fork` and in effect return `task` descriptor.

So the difference is that:
```
function* watchLastFetchUser() {
  // this is non blocking call
  const task = yield takeLatest('USER_REQUESTED', fetchUser)
  // this may be done afterwads
  yield call(someFunc)
  // ...
  // and you can even cancel it later!
  yield cancel(task)
}
```

and 
```
function* mySaga() { 
  // this is a blocking call
  yield* takeLatest("USER_FETCH_REQUESTED", fetchUser);
  // this will never be reached
  yield call(someFunc)
}
```

Additionally using them with `yield*` will get deprecated in the future and after some time completely removed as it is really confusing to newcomers - https://github.com/yelouafi/redux-saga/pull/596

**Comment by Andarist** [comment]
Also, I've corrected the docs to use `yield takeLatest` form

**Comment by sepo-one** [comment]
thanks
