### ISSUE TITLE
How do I cancel fetch when using takeLatest?

### ISSUE THREAD

**Issue by funkjunky** [yelouafi/redux-saga#651]
takeLatest cancels the previous generator when called a second time, but what happens to the promise currently yielded?

So I have:

    try {
        const result = yield call(fetch, 'getresult');
    } finally {
        if(cancelled())
            //how do I cancel fetch?
    }

When used with takeLatest, i can get to the cancelled branch, but then I don't know how to send a cancel to my fetch call. I don't want all those ajax requests to return and be handled by fetch, unnecessarily, and I want them to show as cancelled on the dev tools.

A more general question is, how do I access the promise I yielded?

**Comment by Andarist** [comment]
> A more general question is, how do I access the promise I yielded?

If you yield a promise, you are passing concern of creating it and its resolution to the `redux-saga`. Whats your use case? Why do you want to access it?

As of `fetch` cancellation - it is not possible and not because of the `redux-saga`. `fetch` API is based on promised and those are not cancellable by design (at least not yet, there are ongoing discussions about making cancellation spec)

**Comment by funkjunky** [comment]
Couldn't you reject a promise?

The use case is cancelling fetch calls when the generator caller has been cancelled.

Basically if I spam a button that makes an ajax call, I want to cancel all but the last ajax call.

**Comment by Andarist** [comment]
And how would you reject a promise? It has only `then` and `catch` methods. 

No promise can be rejected from the outside. If you want this ability `fetch` API is not suitable for your use case. I've heard lately that this lib https://github.com/mzabriskie/axios is geting much praise from the community and it supports cancelation.

Keep in mind that even if you cannot cancel a request it doesnt mean that you will get some duplicate data back into your app. `takeLatest` in your scenario will use automatically only the newest response and all previous ones will be disarded for you.

**Comment by funkjunky** [comment]
Ok I see, the cancel token I'd give to call() could be used to cancel in the finally if(cancelled()) branch.

Cool beans. Thanks!

**Comment by Andarist** [comment]
or even better - you could write your custom `fetchAPI`, which would look something like this

```javascript
import axios, { CancelToken } from 'axios'
import { CANCEL } from 'redux-saga'

export default function fetchAPI(url) {
  const source = CancelToken.source()
  const request = axios.get(url, { cancelToken: source.token })
  request[CANCEL] = () => source.cancel()
  return request
}
```

...and have process of cancelation builtin into your helper, instead of handling this manually in your sagas.

**Comment by funkjunky** [comment]
woah, clever idea... have you tested this out yet? I'll try it out and let you know how it goes.

**Comment by Andarist** [comment]
Didnt test it, I knew there is a possibility to attach `CANCEL` callback to the promise so saga can handle it, so I just looked into `axios` docs and wrote this snippet based on them. 

There might be some issues with it, I never have used `axios` and you probably would need to make this `fetchAPI` more configurable as its capable now only for making `GET` requests as a demonstration but overall I think this should work without need of changing it too much.

**Comment by L-Jovi** [comment]
@Andarist  thanks for your sample, it's useful to me :)

regards.

**Comment by rclai** [comment]
I can confirm that using [the code shared above](https://github.com/redux-saga/redux-saga/issues/651#issuecomment-262375964) does cancel mid-flight requests when `race`ing or `cancel`ing, which is nice.

**Comment by vivekdwivedi** [comment]
Can anyone please explain how this part works as I am not able to get this to work:

`request[CANCEL] = () => source.cancel()`

From what I can understand with axios, calling source.cancel() will cancel the request. And from my saga understanding, cancelling a saga will call this method:

```
function cancel(task) {
  (0, _utils.check)(task, _utils.is.notUndef, 'cancel(task): argument task is undefined');
  if (!isForkedTask(task)) {
    throw new Error('cancel(task): argument ' + task + ' is not a valid Task object \n(HINT: if you are getting this errors in tests, consider using createMockTask from redux-saga/utils)');
  }

  return effect(CANCEL, task);
}
```
And this returns that CANCEL effect that we are referring in our helper. But I can't understand how this all is connected. How does a `request` know that CANCEL is returned from sagas and it should now call `source.cancel()`

**Comment by Andarist** [comment]
@vivekdwivedi 
You have confused 2 things. `cancel` effect returns an object description for the `redux-saga` which is later interpreted by the saga and it cancels the task contained in that created effect object.

What you attach to the request is not an effect, its just a special symbol which can be recognized by `redux-saga` later on to perform cancellation.

When you yield cancel effect to the `redux-saga` it calls `task.cancel()` and the cancellation process begins - it propagates this signal downwards through each child task, their childs etc. When a task gets cancelled it simply checks on what effect it is currently paused and tries to call its cancellation function. By attaching previously a `CANCEL` symbol to your promise you had attached a cancellation function to it, so the `redux-saga` gets to know what to call when its needed - otherwise there is no automatic way for it to know HOW it should be cancelled.

For some other effects like i.e. `fork` `redux-saga` knows exactly how it should be cancelled so it attaches the cancel method to it automatically.

**Comment by vivekdwivedi** [comment]
That makes sense now. Thanks a lot :)

**Comment by Andarist** [comment]
Well, promises are unfortunately not cancellable, can't do much about it. You can always wrap your promise chain in a function that would have custom `[CANCEL]` raising internal flag for your wrapper that could "cancel" the chain or something.

**Comment by gilbsgilbs** [comment]
I'm embarrassed by the monkey-patching in @spaceemotion and @Andarist solution. I don't see why the helper couldn't/shouldn't make the request and cancel it by itself:

```js
export function request(config = {}) {
  return call(function*() {
    const source = CancelToken.source();
    try {
      return yield call(axios.request, {...config, cancelToken: source.token});
    } finally {
      if (yield cancelled()) {
        source.cancel();
      }
    }
  });
}

// and then defining verbs

export function get(url, config = {}) {
  return request({method: 'get', url, ...config});
}

export function post(url, data, config = {}) {
  return request({method: 'post', url, data, ...config});
}

// … and so on
```

It can be used like so:

```js
takeLatest(SOME_ACTION, function*() {
  yield get('https://httpstat.us/200');
});
```

I can still be forked or raced, just like any other effect.

**Comment by khalidAzam** [comment]
I am using axios for ajax / xhr request cancellation.

```
const CancelToken = axios.CancelToken;

export function* getAsynResult(action) {
  const source = CancelToken.source();
  const reqData = Object.assign({}, action.data, { cancelToken: source.token });
  try {
    yield call(apiCall, reqData);
  } finally {
    if (yield cancelled()) {
      source.cancel('cancelled');
    }
  }
}

```
