### ISSUE TITLE
How to handle conditional request sequences?

### ISSUE THREAD

**Issue by Kitanotori** [yelouafi/redux-saga#654]
I search from [the documentation](http://yelouafi.github.io/redux-saga/docs/advanced/ComposingSagas.html) but couldn't find information on how to handle following type of scenario:

```
yield put({ type: DATA_POST_SUCCEEDED }); // handled by the reducer
yield put({ type: SOME_REQUEST }); // handled by a Saga worker
// if above resulted in SOME_SUCCEEDED, put below
// if above resulted in SOME_FAILED, do nothing
yield put({ type: ANOTHER_REQUEST }); // handled by a Saga worker
```

All of my `{action_name}_REQUEST`s `put` either `{action_name}_SUCCEEDED` or `{action_name}_FAILED`, depending on whether the request was executed as intended. My question is, how do I perform a conditional request depending on the outcome of a previous request? I want `ANOTHER_REQUEST` to be `put` only if `SOME_REQUEST` resulted in the corresponding worker `put`ting `SOME_SUCCEEDED`.

```
// example of my watchers
export const watchers = [
	function* someWatcher() {
		yield* takeLatest(SOME_REQUEST, someWorker);
	},
	function* anotherWatcher() {
		yield* takeLatest(ANOTHER_REQUEST, anotherWorker);
	}
];
```

I figured out that one possible way is to provide the next requests of the sequence as parameters:

`yield put({ type: SOME_REQUEST, next: [{ type: ANOTHER_REQUEST }] });`

Then in `someWorker`, I would check the existence of `next`, and if it exist, I would `put` the next actions sequentially. Is this approach ok, or am I doing something wrong, or is the documentation missing information?

**Comment by Andarist** [comment]
```javascript
yield put({ type: DATA_POST_SUCCEEDED }); // handled by the reducer
yield put({ type: SOME_REQUEST }); // handled by a Saga worker
const { error } = yield race({
  success: take(SOME_SUCCEEDED),
  error: take(SOME_FAILED),
})

if (error) {
  return
}

yield put({ type: ANOTHER_REQUEST }); // handled by a Saga worker
```

**Comment by Kitanotori** [comment]
Awesome. Really starting to like Saga the more I get to know it. Keep up the good work!
