### ISSUE TITLE
try - catch in runPutEffect drops thrown errors

### ISSUE THREAD

**Issue by esseb** [yelouafi/redux-saga#655]
https://github.com/yelouafi/redux-saga/blob/master/src/internal/proc.js#L437 does a dispatch within a try - catch and drops any thrown errors, which means thrown errors within any rendered component, or connected redux containers, rendered as a result of the dispatch simply get lost.

The dispatch that made me notice this issue triggered a connected redux container component to render where I attempted to do `return: {foo: bar.baz}` by mistake inside a redux `mapStateToProps`, where `bar` was undefined. Normally I'd just get a `Cannot read property 'baz' of null` letting me fix my error immediately, but because of the try - catch all I see in Chrome's devtools is:
```
uncaught at root 
 at root 
 Invariant Violation: Attempted to update component `Example` that has already been unmounted (or failed to mount).
```

I'll attempt a reduced testcase if this issue report isn't enough.

**Comment by esseb** [comment]
Note: I haven't investigated this very thoroughly yet, so I just realised redux saga rethrows the error further up and my issue is elsewhere...

**Comment by Andarist** [comment]
We'll do smth about this, we just need to figure out what

see https://github.com/yelouafi/redux-saga/issues/632

**Comment by esseb** [comment]
Thanks, I'm subscribing to that issue now.
