### ISSUE TITLE
Watching differences in selectors

### ISSUE THREAD

**Issue by eirslett** [yelouafi/redux-saga#660]
Often, there are many different actions that can touch the same part of a Redux subtree. For example, a shopping cart app:

ITEM_ADDED updates the total sum
ITEM_REMOVED updates the total sum
COUPON_USED updates the total sum
CURRENCY_CHANGE updates the total sum (given you were to build the state tree with sum as a number, and currency as a separate property in the tree)

One can imagine there will be more actions as well. What we would have to do in today's saga, is to

```javascript
fork(takeLatest, [ITEM_ADDED, ITEM_REMOVED, COUPON_USED, etc etc] doStuff);
```

The problem is that if more actions are added to the applications later on, that can change the total sum in some way, then the saga will not be triggered if somebody forgets to add that action in takeLatest.

Another way to approach this problem, would be to watch diffs in the state tree, based on a selector:

```javascript
function totalSumSelector(state) {
  return state.shoppingCart.total;
}

...

// in the saga:
fork(takeEveryDiff, totalSumSelector, doStuff);
```

That way, the saga code would scale with the application. Is this something that is in line with the design decisions in redux-saga? If so, could it be added maybe? (I could try to assemble a PR)

**Comment by eirslett** [comment]
I guess this issue is somewhat related to #555 as well? @janhartmann

**Comment by Andarist** [comment]
Relaying on state is something rather discouraged in sagas and `select` is rather an escape hatch, easing a life of a developer, so it is not needed to maintain the saga state in the same way reducers already do it. 

If you make a properly memoized selector it shouldnt be much of a cost in making a higher order saga

```javascript
function* takeEveryDiff(selector, worker) {
  return fork(function* () {
    let prevVal
    while (true) {
      yield take('*')
      const val = yield select(selector)
      if (prevVal === val) {
        continue
      }
      prevVal = val
      yield fork(worker, val)
    }
  })
}
```
