### ISSUE TITLE
TypeScript. Run array of sagas in parallel.

### ISSUE THREAD

**Issue by lysoff** [yelouafi/redux-saga#664]
Actually, we are not using most of typescript features on the project, it's es6 all the way. Nevertheless, typescript compiler is still running and causes the following issue while trying to run sagas in parallel:

```
Error:(32, 24) TS2345:Argument of type '() => IterableIterator<IterableIterator<TakeEffect<{}>>[]>' is not assignable to parameter of type 'SagaRest'.
  Type 'IterableIterator<IterableIterator<TakeEffect<{}>>[]>' is not assignable to type 'IterableIterator<TakeEffect<any> | PutEffect<any> | RaceEffect | CallEffect | CpsEffect | ForkEff...'.
    Type 'IterableIterator<TakeEffect<{}>>[]' is not assignable to type 'TakeEffect<any> | PutEffect<any> | RaceEffect | CallEffect | CpsEffect | ForkEffect | JoinEffect ...'.
      Type 'IterableIterator<TakeEffect<{}>>[]' is not assignable to type 'Effect[]'.
        Type 'IterableIterator<TakeEffect<{}>>' is not assignable to type 'Effect'.
          Type 'IterableIterator<TakeEffect<{}>>' is not assignable to type 'CancelledEffect'.
            Property 'CANCELLED' is missing in type 'IterableIterator<TakeEffect<{}>>'.
```

There is a saga:
```javascript
import { take } from 'redux-saga/effects';
import { SHOW_CONFIRM, HIDE_CONFIRM } from '../actions/constants';

export default function* confirmSaga() {
    while (true) {
        const { resolve, reject } = yield take(SHOW_CONFIRM);
        const { isConfirmed } = yield take(HIDE_CONFIRM);
        isConfirmed ? resolve() : reject();
    }
}
```
There is a root saga (probably there will be more sagas in project, so, i guess we need this aggregation):
```javascript
import confirmSaga from './confirmSaga'

export default function* rootSaga() {
    yield [
        confirmSaga()
    ];
};
```
Configuring the store:
```javascript
import rootSaga from 'sagas/';
//...
const sagaMiddleware = createSagaMiddleware();
//...
const middlewares = [
//...
  sagaMiddleware
];
//...
sagaMiddleware.run(rootSaga); // <-- this line causes the error
```
As i mentioned in the code, the ```run``` makes typescript compiler fail.

So, for now i run confirmSaga directly and it goes ok:
```javascript
sagaMiddleware.run(confirmSaga); // <-- ok
```
but for sure we will add more sagas in future, so the issue is still there

**Comment by Andarist** [comment]
TS typings (same goes for flow) are completely community-driven and not directly implemented by `redux-saga` author. The library is written in plain javascript.

Would you be willing to correct them and send a PR? Help would be much appreciated.

cc @aikoven

**Comment by lysoff** [comment]
@Andarist thank you for your reply
Sure, i'll give it a try, but unfortunately i have too few experience in TS typings

**Comment by aikoven** [comment]
Typings enforce you to always `yield` effects, not regular values or promises or generators. To get the most out of them, annotate return type of every saga with `SagaIterator`:
```ts
import {SagaIterator} from "redux-saga";

function* someSaga(): SagaIterator {
  // ...
}
```

In your particular case you should replace this:
```ts
    yield [
        confirmSaga()
    ];
```
with this:
```ts
    yield [
        call(confirmSaga)
    ];
```

**Comment by lysoff** [comment]
Awesome, thanks!)
