### ISSUE TITLE
Add a cheatsheet to the docs for what effects are blocking/non-blocking

### ISSUE THREAD

**Issue by granmoe** [yelouafi/redux-saga#665]
I see a lot of confusion from newcomers regarding what effects are blocking/non-blocking. I think there should be a "cheatsheet" for this in the docs. The definitive, concise source of truth on this topic.

**Comment by granmoe** [comment]
Currently, there is a section in the glossary that addresses this, but it isn't complete and it's kind of hidden away.

**Comment by Andarist** [comment]
Would you be willing to create an API section with this cheatsheet?

**Comment by granmoe** [comment]
I'd be happy to :-) I'll open a PR for it probably some time this week

**Comment by granmoe** [comment]
Closing per PR #693
