### ISSUE TITLE
implementing undo/redo with a stack

### ISSUE THREAD

**Issue by anthonychung14** [yelouafi/redux-saga#668]
I've checked out the undo recipe in the docs and wanted to get your opinion on this post:

TLDR:

If undo/redo needed to be implemented with a stack of actions and we needed to persist state on the server, how would you best leverage sagas to do the following

1. Retry failed updates to server
2. Undo more than 1 action without having multiple copies of a state tree

http://stackoverflow.com/questions/40954685/undo-redo-with-sagas-redux-pt-2

**Comment by Andarist** [comment]
Hey, did u solve your issue?
