### ISSUE TITLE
All-or-nothing cancellation - is spawning the correct approach?

### ISSUE THREAD

**Issue by tomenden** [yelouafi/redux-saga#669]
In my App I have a toggle which sends some data to the server when its value changes.
To ensure that the data is not sent too many times, I `debounce` the requests by 300 ms. Here is an example:
```javascript
function* watchChangeAction() {
    let task;
    while (true) {
        const action = yield take(actionTypes.CHANGE);
        if (task) {
            yield cancel(task);
        }
        task = yield fork(updateDataInServer, action);
    }

}

function* updateDataInServer(action) {
    try {
        // debounce 300 ms
        yield call(delay, 300);

       //retrieve key from the store
        const key = yield select(selectors.getKey);
        const newSettings = yield select(selectors.getSettingsItems);

        const response = yield call(serverSettings.update, newSettings, key);
        const responseKey = serverSelectors.getKey(response);
       // dispatch action with responseKey, which is stored for later user
        yield put(actions.saved(responseKey));

    } 
//...
 }
```

The issue is that my server returns a distinct key in every response that it makes. In order to be able to call the server, I must provide it the latest key in my request, which I maintain inside myStore (see above `const key = yield select(selectors.getKey)`).

The problem occurs when the cancellation is done before the response from the server is received. 
What happens is that the request had already gone out (thus a new key has been provided), but by the time the response arrives the task is already cancelled, and thus the response key is never stored, and it is not possible to send any more requests.

After investigating the issue, I decided to go with `spawn` in order to insure an all-or-nothing- approach. If the task is cancelled before the request has gone out then it will be ignored, however if the request had occurred, the entire process will happen. So `updateDataInServer` now looks like this:

```javascript
 try {
      // debounce 300 ms
        yield call(delay, 300);

        const key = yield select(selectors.getKey);
        const newSettings = yield select(selectors.getSettingsItems);

         yield spawn(function*() {
               const response = yield call(serverSettings.update, newSettings, key);
               const responseKey = serverSelectors.getKey(response);
               yield put(actions.saved(responseKey));
        });

    } 
//...
```

I was wondering whether this is the correct approach. @yelouafi - I would appreciate your feedback.
I upgraded from version 0.95 in order to get `spawn` because I could not find a different way to solve this issue. Can the behavior I want be achieved with that version?

Thanks

**Comment by tomenden** [comment]
This approach actually does not work either.. If the second call is made after 300 ms and before the response came back, I am facing the same situation of sending the server the wrong key.. What is the right way to make sure that the second request will happen only **after** the first response has returned and the key has been updated in the store?

**Comment by Andarist** [comment]
I've created a simple debounce helper for you (might introduce it to redux-saga natively at some point). 
```javascript
function* debounce(ms, pattern, worker, ...args) {
	const task = yield fork(function* () {
		while (true) {
			let ac = yield take(pattern)

			while (true) {
				const { action, debounced } = yield race({
					action: take(pattern),
					debounced: call(delay, ms),
				})

				if (debounced) {
					yield fork(worker, ...args, ac)
					break
				}

				ac = action
			}		
		}
	})
	return task
}

function* watchChangeAction() {
	yield debounce(300, actionTypes.CHANGE, updateDataInServer)
}

function* updateDataInServer(action) {
	try {
		// debounce 300 ms
		yield call(delay, 300);

	   //retrieve key from the store
		const key = yield select(selectors.getKey);
		const newSettings = yield select(selectors.getSettingsItems);

		const response = yield call(serverSettings.update, newSettings, key);
		const responseKey = serverSelectors.getKey(response);
	   // dispatch action with responseKey, which is stored for later user
		yield put(actions.saved(responseKey));

	} 
//...
 }
```

Didnt test it yet, as I dont have much time now, but it should work or be quite simple to fix. 

Please remember though that if you send 2 requests they dont necesserily come back to you in the same order, so that should be handled also.

**Comment by tomenden** [comment]
@Andarist 
Thanks for your help, but unfortunately this approach does not seem to work either.
Perhaps I did not clarify my use-case well enough. If I attempt to make two requests at the same time **one of them will necessarily fail**. I must wait for the response to come back before dispatching the second request, in order for the key that I send to be correct.

Here is the scenario in which this fails:
User changes data - `debounced` wins the race, and thus the task is forked. All is well and nice.
After some time (>300ms) the user changes the data again. `debounced` wins the race, yet again, and the second request is sent. However, the server did not yet respond to the first request, the key is not updated in the store, and thus the second request fails.

Hope this makes sense now. Currently my thought is perhaps to change the logic a bit to also rely on the response action to have occurred (i.e - in case a request is made while another request is in progress, the second request will wait for the `saved` action before sending itself.

I am also checking a way of making the solution more generic, but without much luck in the meanwhile.

What do you think?

Thanks in advance!

**Comment by Andarist** [comment]
As for w8ing with making new requests maybe changing fork to call would
suffice? If not i would probably make request channel which would buffer
debounced requests and take + call within the loop from thus channel

**Comment by Andarist** [comment]
It would look smth like this
```javascript
function* debounce(ms, pattern, worker, ...args) {
	const task = yield fork(function* () {
		while (true) {
			let ac = yield take(pattern)

			while (true) {
				const { action, debounced } = yield race({
					action: take(pattern),
					debounced: call(delay, ms),
				})

				if (debounced) {
					yield fork(worker, ...args, ac)
					break
				}

				ac = action
			}		
		}
	})
	return task
}

function* watchChangeAction() {
	const requestChannel = channel()
	yield debounce(300, actionTypes.CHANGE, queueRequest, requestChannel)

	while (true) {
		const action = yield take(requestChannel)
		yield call(updateDataInServer, action)
	}
}

function* queueRequest(chan, action) {
	yield put(chan, action)
}

function* updateDataInServer(action) {
	try {
	   //retrieve key from the store
		const key = yield select(selectors.getKey);
		const newSettings = yield select(selectors.getSettingsItems);

		const response = yield call(serverSettings.update, newSettings, key);
		const responseKey = serverSelectors.getKey(response);
	   // dispatch action with responseKey, which is stored for later user
		yield put(actions.saved(responseKey));

	} 
//...
 }
```

**Comment by tomenden** [comment]
@Andarist 
First of all, I'd like to thank you a lot for your assistance, and for recommending channels. It got me to read about this pattern which is extremely powerful, and very suitable for the issue I am facing.
I created a generic solution to create a 'debounce channel', I will be very happy to get your feedback on it. You can see the gist [here](https://gist.github.com/tomenden/a600115fe0549836e85b5503fe3cca84).

I want to ask specifically regarding [this](https://gist.github.com/tomenden/a600115fe0549836e85b5503fe3cca84#file-debounced-channel-js-L12) line. The reason I am spawning here is because the `debouncedChannel` is being consumed by using [call](https://gist.github.com/tomenden/a600115fe0549836e85b5503fe3cca84#file-debounced-channel-js-L4) (in order to `take` from the channel inside the main saga). I was surprised to see that when using `fork` in `debouncedChannel`, the original saga (`watchChangeAction`) does not immediately resolve. Is this the expected behavior? I understand that `call`ing a `saga` will block until the saga has completed, but was unaware that this is also true for the sagas' non-blocking effects. Is this the expected?

Once again, huge thanks!

**Comment by Andarist** [comment]
As for forking within call - it is expected, althought quite confusing even to me. Maybe @yelouafi could elaborate on reasoning behind this?

Your snippet is probably good although quite convoluted at first grasp. This is what I would have used:
```javascript
function* debounce(ms, pattern, worker, ...args) {
    const task = yield fork(function* () {
        while (true) {
            let ac = yield take(pattern)

            while (true) {
                const { action, debounced } = yield race({
                    action: take(pattern),
                    debounced: call(delay, ms),
                })

                if (debounced) {
                    yield fork(worker, ...args, ac)
                    break
                }

                ac = action
            }       
        }
    })
    return task
}

//usage example:
function* watchChangeAction() {
    const requestChannel = channel()
    yield debounce(300, actionTypes.CHANGE, function* (action) {
        yield put(requestChannel, action)
    })  
    while (true) {
        const action = yield take(requestChannel)
        yield call(handleRequest, action)
    }
}
```
Way of debouncing - mine or yours is only a personal preference. I just think hacing 2 separate channels is obsolate in your scenario, as it seems that the only place where buffering is needed is a `requestChannel`
