### ISSUE TITLE
Testing problem

### ISSUE THREAD

**Issue by antoinerey** [yelouafi/redux-saga#67]
Hello !

Considering this code :

```javascript
function* checkout(getState) {

  while( yield take(types.CHECKOUT_REQUEST) ) {
      const cart = getState().cart
      const { response, error } = yield call(api.buyProducts, cart)

     if (response)
      yield put(actions.checkoutSuccess(cart))
    } else {
      yield put(actions.checkoutFailure(error))
    }
  }
}
```

How would one test this code ?

At the moment, I'm looping over this code twice. Simulating an API success, then an API failure, to get both paths covered. But I get my first assertions twice too.

**Comment by yelouafi** [comment]
>But I get my first assertions twice too

There is no way to return a generator back in time;  but you can factor out the part that test the 2 first assertions; then simply make the assertion noop on subsequent iterations

```javascript
const cart = {}
const getState = () ={ cart }

function testTakeAndCall(gen, deepEqual) {
   deepEqual(gen.next().value, 
   take(types.CHECKOUT_REQUEST),
  )

  deepEqual(
    gen.next().value, 
    call(api.buyProducts, cart)
  )
}

test('checkout Saga test', function (t) {
  
  const noop = () => {}
  const gen = checkout(getState)

  // 1st iteration: perform the assertions
  testTakeAndCall(gen, assert.deepEqual)

  const response = {}
  t.deepEqual(
    gen.next({response}).value, 
   put( actions.checkoutSuccess(cart) )
  )

  // 2nd iteration: do not perform the assertions
  testTakeAndCall(gen, noop)

   const error = {}
   t.deepEqual(
    gen.next({error}).value, 
   put( actions.checkoutFailure(error) )
  )

  t.end()
})
```

**Comment by antoinerey** [comment]
Thanks for this answer !

The solution you exposed worked fine, but looping over the full saga (even while hiding the assertions) is a concern for me. 

So, I extracted this ...

```javascript
if (response)
  yield put(actions.checkoutSuccess(cart))
} else {
  yield put(actions.checkoutFailure(error))
}
```
... to a function, which is fully testable in its own, without loops.

**Comment by yelouafi** [comment]
I dont think it's a big deal unless it has a noticeable impact on testing time. In my own experience this is negligible compared to the latency of other tests (ui, integration)

But your separate function could be useful as it can be made reusable
