### ISSUE TITLE
Add ability to provide custom emitter

### ISSUE THREAD

**Issue by pbadenski** [yelouafi/redux-saga#670]
This feature is something I found useful when integrating with [redux-batched-actions](https://github.com/tshelburne/redux-batched-actions). Redux-batched-actions allows to publish and reduce all actions in a batch (which is a separate action), rather than going one by one - useful when you send hundreds or thousands of them. At the same time when used with redux-saga it introduces a bit of a leaky abstraction - as TAKE is concerned what gets published is a completely new action. Actual actions are inside of it's payload, and that's what redux-saga needs to be informed with.

I implemented it in my forked repo (https://github.com/pbadenski/redux-saga/commit/80ffb8450b164bb50eabb84b37846a78b2470e79), so if this issue sounds reasonable I can submit a pull request immediately.

See example below:

```javascript
const emitter_ = emitter();
  const sagaMiddleware = createSagaMiddleware({emitter: {
    subscribe: emitter_.subscribe,
    emit: (action: any) => {
      if (action.type === "BATCHING_REDUCER.BATCH") {
        action.payload.map(emitter_.emit);
      } else {
        emitter_.emit(action);
      }
    }
  }});
```

**Comment by Andarist** [comment]
It sounds reasonable, please create a PR and we'll continue from there.

**Comment by Andarist** [comment]
Gonna close already in favor of PR discussions.
