### ISSUE TITLE
Cancel current task in actionChannel

### ISSUE THREAD

**Issue by sospedra** [yelouafi/redux-saga#671]
We're building a [snackbar component](https://material.google.com/components/snackbars-toasts.html).
The requirements are the following:

1. Buffer all the triggered actions (we use an actionChannel for this)
2. Allow cancelation of the current task

I've been able to have both of the requirements as stand-alone but not together. See this webpackbin for details: http://www.webpackbin.com/4kL3OORGz
(I tried to keep it as simplier as possible)

**Configuration A** (Right from the webpackbin)
The **bad**: If you click a lot of times on the `Display` button you'll notice that it's only triggering once.  Therefore, is working as a `takeLatest` not as an actionChannel with a Buffer.
The **good**: If you click quickly first `Display` and then `Close` multiple times you'll notice that cancellation is actually working.

**Configuration B** (On the webpackbin `sagas.js` comment L29-31 and uncomment L34-40)
The **bad**: Tasks cannot be cancelled. If you do as with the previous "good" test you'll notice that it hides the `close` button but not cancelling the task. Therefore, after the 2 seconds delay triggers again the next `show` action.
The **good**: It buffers the `show` actions. Click multiple times on `display` and `close` button will be popping in and out every 2 seconds.

Question is: **How can I get the two good parts in a single set up?**

Many thanks and sorry for the long post and webpackbin.

**Comment by Andarist** [comment]
Im not sure if I understand completely what you are trying to achieve. 

From what I understand you you want to buffer `DISPLAY` actions, display 1 snackbar and when user clicks HIDE cancel the forked task, then proceed with next `DISPLAY`, right?

If that's the case I would recommend trying it this way:
```javascript
while (TRUE) {
	const action = yield take(channel)
	const task = yield fork(displayWithCancellation, action)

	yield race({
		forceHide: take({ type, force } => type === HIDE && force),
		taskEnd: join(task)
	})

	yield cancel(task)
}
```

Your loop was totally non blocking after taking from the channel, so basically each item put in the channel was consumed immediately. You had to make some blocking call after taking so it prevents from taking again.

Also do not use `takeEvery` within a loop, as with each run it will create a new subscriber for the action. `takeEvery` is just a helper easing creation of such construct
```javascript
function* takeEvery(pattern, worker, ...args) {
	const task = yield fork(function* () {
		while (true) {
			const ac = yield take(pattern)
			yield fork(worker, ...args, ac)
		}
	})
	return task
}
```
And looking at that you should see the problem with using `takeEvery` in the loop.

**Comment by sospedra** [comment]
Yish! This was exactly what I was looking for. Many many thanks ;) I've never thought in use `race` like that.
