### ISSUE TITLE
Blocking Touchable events in react native

### ISSUE THREAD

**Issue by jck2** [yelouafi/redux-saga#672]
I'm working on a react-native app that uses sagas to do some async actions in the background (including some expensive API calls). I have been running into some issues with the responsiveness of my UI to touch events (the onPress calls of TouchableOpacity in particular, they tend to execute in batches after some background tasks have completed). I found that if I commented out the code where I make the most expensive API call, then the UI is responsive immediately, but that confused me because the task should be running asynchronously.

My root saga follows the following pattern:

`yield [
  spawn(saga1),
  spawn(saga2),
  ...
]`

I'm wondering if there's any known reason why this type of performance problem might occur.

**Comment by Andarist** [comment]
Could u post what you have commented out?

**Comment by jck2** [comment]
I did some more debugging last night, it appears that the problem is that constant rerendering of the UI is the problem and not sagas. You can close this issue

**Comment by Rajat421** [comment]
I am facing the same issue . In my case i have stop constant redenring of ui still face  this issue ..

**Comment by MAhtishamShahzad** [comment]
I am facing the same issue .can any one guide how to solve
