### ISSUE TITLE
Saga doesn't dispatch new events

### ISSUE THREAD

**Issue by steven10172** [yelouafi/redux-saga#674]
I wrote a test application using saga's and it seems that I cannot figure out how to dispatch new actions. All the examples show using the `put` command with the action data to dispatch a new action, but I cannot get it to work.

I've tried
```
yield put(actions.receiveTodos(todos));
```

```
yield put({
  type: 'RECEIVE_TODOS',
  todos
});
```

The only way I was able to get it to work was with the following (which required exporting the store to the window):
```
yield put(window.store.dispatch(actions.receiveTodos(todos)));
```
Source: https://github.com/steven10172/todo-list/blob/master/src/sagas/index.js#L8

If someone could point me in the right direction I'd greatly appreciate it.

**Comment by Andarist** [comment]
You had configured store in some wrong way, I've tweaked your configuration and its working now
```javascript
import { createStore, applyMiddleware, compose } from 'redux'
import createSagaMiddleware, { END } from 'redux-saga'
import rootReducer from '../reducers'

export default function configureStore(preloadedState) {
  const sagaMiddleware = createSagaMiddleware();
  const composeCreateStore = () => compose(
    applyMiddleware(sagaMiddleware),
    window.__REDUX_DEVTOOLS_EXTENSION__ ? window.__REDUX_DEVTOOLS_EXTENSION__() : fn => fn,
  )(createStore)
  const finalCreateStore = composeCreateStore()
  const store = finalCreateStore(rootReducer, preloadedState)

  store.runSaga = sagaMiddleware.run;
  store.close = () => store.dispatch(END);

  return store;
}
```

additionally you are desctructuring wrongly your takers with this configuration
`yield take(({action}) => action && action.type === ADD_TODO);`
should become
`yield take((action) => action && action.type === ADD_TODO);`
or even more concise for this simple use case
`yield take(ADD_TODO);`

I hope it helps

**Comment by steven10172** [comment]
Thanks. I will try it out later today. I only had the yield statements like that due to how the data was being passed to them, but that was probably due to the store constructing issue.

**Comment by Andarist** [comment]
Did it help for you? I would like to close the issue, but aint sure if your problem got resolved.

**Comment by steven10172** [comment]
Thanks. I was able to play around after your suggestion and it seems that there was an issue with the `window.__REDUX_DEVTOOLS_EXTENSION_` initialization.

After using your line to initialize redux dev tools everything was working as expected: https://github.com/steven10172/todo-list/commit/c949601bb239f3674bff94af05bad7554f777647
