### ISSUE TITLE
How to dispatch put action inside XHR's onload event

### ISSUE THREAD

**Issue by schuchowsky** [yelouafi/redux-saga#675]
Hello everyone, I'm trying to store in redux state the progress of file uploads.

```javascript
xhr.upload.onprogress = (e) => {
    let percentLoaded
    if (e.lengthComputable) {
      percentLoaded = Math.round((e.loaded / e.total) * 100)
      yield put(actions.uploadProgress([progressFactory(percentLoaded, percentLoaded === 100 ? 'Finalizing' : 'Uploading', file)]))
    }
  }
```

The problem is I can't use `yield` inside of the `onload` callback, because it's not a generator function. Also, calling `put` without `yield` does nothing.

Does anyone knows a workaround for this?

Thanks in advance.

**Comment by restrry** [comment]
There are some questions on SO. for example, http://stackoverflow.com/questions/40685288/redux-saga-upload-file-progress-event/40718234. 
@Andarist should we add it to examples?

**Comment by Andarist** [comment]
Just like @restrry said, wrapping your callbacks with `eventChannel` is a way to go. Gonna close the issue for now, if you have more questions, please reopen and ask.

**Comment by schuchowsky** [comment]
Thanks guys @restrry and @Andarist! That worked like a charm. 

Here's a gif of the result (it's an application/octet-stream, you may open with browser if you like):
http://hnordt.d.pr/RYlP+
