### ISSUE TITLE
Using take effect inside of while condition

### ISSUE THREAD

**Issue by henrikra** [yelouafi/redux-saga#679]
There is lot of examples where yielding take effect inside of while condition. Like this: 
```javascript
function* watchFetch() {
  while (yield take(FETCH_POSTS)) {
    yield call(fetchPosts)
  }
}
```
But I noticed that this can't be tested normally like this:
```javascript
it('waits for FETCH_POSTS', () => {
  const expectedYield = take(actionTypes.FETCH_POSTS);
  expect(generator.next().value).to.deep.equal(expectedYield);
});
```

Or this test will pass but the **next one does not** because generator.next().done is true. But if I change the generator to this format:
```javascript
function* watchFetch() {
  while (true) {
    yield take(FETCH_POSTS)
    yield call(fetchPosts)
  }
}
```
Then it will work. The code work the same in the app with the tests it doesn't. Is this intended or what? I have seen both formats in the docs :)

**Comment by Andarist** [comment]
I think you might have some error in your code as `generator.next().done` shouldnt be true as you are running endless loops in both of your snippets. Could you post a working example of undesired behaviour?

**Comment by henrikra** [comment]
The other logic does not matter. Endless loop is normal in generators. Just try any of your own sagas to move the `yield take` inside of while loop's condition and the tests won't work after that :D That is how you can reproduce it

**Comment by yelouafi** [comment]
@henrikra for the test to pass you have to pass back some mock action to the generator on the next iteration (the result of the first yield). Otherwise the generator resumes with undefined i.e. gives `while(undefined)` which breaks the loop and terminates the generator

**Comment by henrikra** [comment]
@yelouafi This is the right answer and it makes perfect sense! So basically people should always put the take effect inside of while loop and NOT to it's condition. Because this will make testing easier. Do you guys agree? :D

**Comment by Andarist** [comment]
No, I wouldnt say this will make testing easier, it may **accidently** be less error-prone, but I think it is a good thing to understand what those line of codes do and how generators work if you are using them, so making such a rule of "put `take` always into the loop's body" would deprive many people of that basic understanding.

**Comment by henrikra** [comment]
Okay so what is your suggestion? :)

**Comment by Andarist** [comment]
```javascript
it('waits for FETCH_POSTS', () => {
  const expectedTake = take(actionTypes.FETCH_POSTS);
  const expectedCall = call(fetchPosts);
  expect(generator.next().value).to.deep.equal(expectedTake);
  expect(generator.next({ type: actionTypes.FETCH_POSTS }).value).to.deep.equal(expectedCall);
});
```
