### ISSUE TITLE
takeEvery/takeLatest could look into the action object

### ISSUE THREAD

**Issue by luisherranz** [yelouafi/redux-saga#680]
We use takeEvery and takeLatest a lot, but a lot of times we need more control.

We can make our own enhanced take helpers but maybe it makes sense to include this in redux-saga.

This is our proposal:
```javascript
// 1st param: String
// Normal behaviour, backwards compatible.
takeEvery(SAVE_SETTINGS_REQUESTED, saveSettingsSaga);

// 1st param: Object
// Match not only type, but any other action param.
takeEvery({
  type: SAVE_SETTINGS_REQUESTED,
  name: 'publication-settings',
}, saveSettingsSaga);

// 1st param: Function
// Pass action to the function. Match if the function returns true.
takeEvery(
  action => action.type === SAVE_SETTINGS_REQUESTED && action.name.startsWith('publication'),
  saveSettingsSaga
);
```

Let me know what you think.

**Comment by Andarist** [comment]
Passing predicate is already possible and your first proposal with passing
object can be easily achieved with it, so I think there is no point in
extending the API with that

**Comment by luisherranz** [comment]
My bad for not checking that first. Sorry! I'm glad it's already implemented and we missed anyway, makes a lot of sense :)
