### ISSUE TITLE
`onError` or `onerror` for options of `createSagaMiddleware`

### ISSUE THREAD

**Issue by kuy** [yelouafi/redux-saga#682]
Hi, I'm writing flow-typed's definition for redux-saga 0.13.x. While working on it, I found miss-spelling issues in options of `createSagaMiddleware` function.

[Code #1](https://github.com/yelouafi/redux-saga/blob/master/src/internal/middleware.js#L43): `onerror`
[Code #2](https://github.com/yelouafi/redux-saga/blob/master/src/internal/proc.js#L152): `onError`
[Release Note](https://github.com/yelouafi/redux-saga/releases/tag/v0.12.0): `onError`
[API docs](http://yelouafi.github.io/redux-saga/docs/api/index.html#createsagamiddlewareoptions): `onError`

The author wrote `onerror` in [original PR](https://github.com/yelouafi/redux-saga/pull/533). But it  doesn't follow JavaScript manner. May I send a PR to change from `onerror` to `onError`? Please let me hear your thought on this.

**Comment by Andarist** [comment]
I would say that onerror is more in javascript manner than onError.
Obviously we need to set 1 naming convention and follow it strictly through
the source code and docs.

If we decide to do a change in the source code we should keep both naming
conventions available to use for this particular case, but the old one
should give a deprecation warning.

@yelaoufi should decide here which one should prevail

**Comment by kuy** [comment]
@Andarist Ah, you're right. I wanted to say that `onerror` doesn't follow camelcase but I forgot that JavaScript uses `onerror` in many places as a specification.

**Comment by yelouafi** [comment]
I'd opt for onError but that's just my personal bias (perhaps bc of my java background)

**Comment by kuy** [comment]
@yelouafi Thanks. The most of code and docs contains `onError` not `onerror`. In case of we adopt `onError`, it doesn't cause a huge impact to the users because API docs and the actual code use `onError`. The code that is not working is just three lines that verify the given options.

```js
  if(options.onerror && !is.func(options.onerror)) {
    throw new Error('`options.onerror` passed to the Saga middleware is not a function!')
  }
```

https://github.com/yelouafi/redux-saga/blob/b5e42c983a20715ecd4c627124a9f1ffb49168a1/src/internal/middleware.js#L43-L45

I also choose `onError` but wait for replying @Andarist .

**Comment by kuy** [comment]
Even if API docs say `onError`, it's better to add a warning message for the users who spell `onerror` not `onError`.

**Comment by Andarist** [comment]
`onError` is fine with me 2, using camelCase in most of the situations too

Would you like to provide PR introducing `onError` into the source code and deprecating `onerror`? If not I can do it some time later

**Comment by kuy** [comment]
@Andarist Thank you! I send PR for this. I'm happy if you help me on the review phase.

**Comment by abrkn** [comment]
I've tried both and neither seem to be working. I'm on latest from npm. Ideas?

**Comment by Andarist** [comment]
Could u post a code snippet?

**Comment by eiriklv** [comment]
The only way I seem to be able to get this to bubble the error up entirely is

```js
const sagaMiddleware = createSagaMiddleware({
  onError(error) {
    setImmediate(() => {
      throw error;
    });
  }
});
```

**Comment by Andarist** [comment]
well, `redux-saga` and rly most of the code runs big chunks of code synchronously, so for it to keep working it needs to swallow the error on one level or another - or pass it to the user ofc like here so he can report it somehow

We cannot let it to throw just like that as everything would go south.

**Comment by eiriklv** [comment]
@Andarist I understand that. It's a tough thing to solve ✌️ It's the same thing with `then().catch()` vs. `then(onSuccess, onError)` as well.

The biggest issue is the whole `put` thing where redux-saga "catches" errors that are triggered as a result of a reducer throwing (as an example). When redux-saga logs the error the source mapping for some reason doesn't work, but if you re-throw it you at least get the correct references.

**Comment by Andarist** [comment]
Well, stack issue is something entirely different - this one can probably be fixed on our side. I dont have time to tackle this though now, would you like to dive into the code a little bit and check why that's happening?

Also the whole swallow put errors by default is a little bit questionable and I'd like to revisit it and rethink if its actually a good idea.

**Comment by eiriklv** [comment]
Will give it a try 👍
