### ISSUE TITLE
Does module run with redux-thunk?

### ISSUE THREAD

**Issue by khankuan** [yelouafi/redux-saga#69]
I tried dispatching functions (for thunk) but nothing happened:
```
yield put(myAction())
```

If `myAction` returns a function (for thunk to consume), nothing is called. However, if `myAction` is an action object, `myAction` is called.

**Comment by youknowriad** [comment]
I think one of the main ideas behind redux-saga is avoid using action creators (thunk or whatever). I don't know exactly what is `myAction` doing, but may be you should consider rewrite myAction, to return a promise and do something like.

```javascript
const promiseResult = yield call(myAction)
yield put({ type: 'myActionTriggered', payload: promiseResult })
```

But If you really want to dispatch thunks using 'put' you might have to change the order of the middlewares in the `applyMiddleware` call.

**Comment by khankuan** [comment]
I did tried swapping the middleware but it seems to be the same hmm

**Comment by khankuan** [comment]
Ah nvm, found the issue :/ mixed up compose and applyMiddleware..
