### ISSUE TITLE
tracking unique redux-saga tasks

### ISSUE THREAD

**Issue by anthonychung14** [yelouafi/redux-saga#694]
I am using sagas to track multiple async tasks, but there is one problem I haven't been able to completely solve:

```
function* performTask1() {
    // Some logic here to takeLatest for the relevant component

    // check if component id matches?

    // Only perform API call with the latest
    const { result } = yield takeLatest('doAsync2')
}

function* performTask2() {
    const { result } = yield call(api, args)
    // do something with results (not relevant)
}

function* watchAsyncTasks() {
    yield takeEvery('doAsync2', performTask2)
    yield takeEvery('doAsync1', performTask1)
}

```
1. componentA dispatches doAsync1
2. componentB dispatches doAsync1

3. component C dispatches doAsync2 (for good measure)

4. componentA dispatches doAsync1
5. componentB dispatches doAsync1

How can I use sagas to ensure that only sagas 3, 4, and 5 complete their API call?

**Comment by Andarist** [comment]
hm, im not 100% sure if I understand your requirements, but from what I do it seems that
1. `performTask2` should be performed for each `doAsync2`
2. `performTask1` should be performed for latest `doAsync1` but scoped per some component id which is included in the `doAsync1` action

So for those requirements I've written a simple general use-case helper and rewritten your snippet using that
```javascript
function* takeLatestPerProps(propsOrSelector, pattern, worker, ...args) {
	const channelsMap = {}

	while (true) {
		const action = take(pattern)
		const propsValue = typeof propsOrSelector === 'function' ? propsOrSelector(action) : action[propsOrSelector]
		if (!channelsMap[propsValue]) {
			channelsMap[propsValue] = channel()
			yield takeLatest(channelsMap[propsValue], worker, ...args)
		}
		yield put(channelsMap[propsValue], action)
	}
}

function* performTask1() {
	// already scoped per 'id'
    const { result } = yield call(api, args)
    // do something with results (not relevant)
}

function* performTask2() {
    const { result } = yield call(api, args)
    // do something with results (not relevant)
}

function* watchAsyncTasks() {
    yield takeEvery('doAsync2', performTask2)
    yield takeLatestPerProps('id', 'doAsync1', performTask1)
}
```

NOTE: also the form you have used in your snippet - `const { result } = yield takeLatest('doAsync2')` wont work as `takeLatest` returns a task descriptor (so it could be canceled at a later time)

**Comment by anthonychung14** [comment]
you are correct in detailing the requirements. I did not think of using a helper to select by id, but this definitely works better than my solution. 

I thought of using an action channel to process requests serially, but definitely prefer being able to use takeLatest, since I'd like to cancel an unfinished request if another for the same component fires.

Thank you! This was very instructive. From my understanding: this helper will create a buffer channel per id given, the yield passes the action to the proper channel, and thus concurrent doAsync1 actions can be dispatched/processed for unique components.

I will close this once I implement and finish. I have a question about how propsVal works, but I think I have enough to go on and answer my own question in the process.

**Comment by Andarist** [comment]
Your understanding is correct - just creating new channels for not yet created ones per props (+ spawning `takeLatest` with the created channel passed in) and `takeLatestPerProps` serves as proxy for passing actions to appropriate channel and then takeLatest can do its thing.

`propsValue` is the unique identifier to be used for creating and storing channels in the map. Ive included obtaining it simply by accessing property of the action or by running a selector on the action with that line
```
const propsValue = typeof propsOrSelector === 'function' ? propsOrSelector(action) : action[propsOrSelector]
```
which can come handy in some situations. Its pretty similar to the concept of `take(pattern)` which you can use by simply passing a string in like so `take(ACTION_TYPE)` or `take(ac => ac.type === ACTION_TYPE)`

**Comment by anthonychung14** [comment]
Mid-implementation, I have one question about channelsMap:

Upon completion of task at channelsMap['a'], does channelsMap['a'] clear or will I have to take care of that garbage collection?

Since this was a custom-helper function you created, I am going to assume yes (for now)

Does this mean I just have to add this line after the yielding put?

` 
yield put(channelsMap[propsValue], action) 
delete channelsMap[propsValue]

`

**Comment by Andarist** [comment]
No. You dont need to do it. `takeLatest` will take any items in those channels and handle only the latest one with a `worker` generator. So those channels should have at most (for a brief moment) 1 item buffered in them, which are gonna be immediately `take`n from them, so there is no need for clearing them - they will clear themselves automatically (thanks to `takeLatest`)

**Comment by anthonychung14** [comment]
Closed. I believe this works, but I am opening a separate issue for how your takeLatest unit test works. I am using it as a template for generating my own unit tests for takeLatestByProps

**Comment by andraaspar** [comment]
Arrived here some time later via Google. Had to fix a couple of things to make `takeLatestPerProps` work:
```JS
function takeLatestPerProps(propsOrSelector, pattern, worker, ...args) { // Not a generator
  return fork(function* () { // Fork a generator here to make it work like takeLatest
    const channelsMap = {}

    while (true) {
      const action = yield take(pattern) // yield necessary here
      const propsValue = (typeof propsOrSelector === 'function' ? propsOrSelector(action) : action[propsOrSelector]) + ''
      if (!channelsMap[propsValue]) {
        channelsMap[propsValue] = channel()
        yield takeLatest(channelsMap[propsValue], worker, ...args)
        console.log(`channelsMap: ${Object.keys(channelsMap).join(`, `)}`) // List buildup of channels
      }
      yield put(channelsMap[propsValue], action)
    }
  })
}
```

I have one major issue with this though. When used with a large number of different `propsValue`s, it builds up an equal number of channels and forked tasks, and those are never removed. I added a log call to list them.

My use case is, I am loading items by ID and would like to cancel earlier requests to the same ID. Any suggestions?

**Comment by therealparmesh** [comment]
I have an open PR (https://github.com/redux-saga/redux-saga/issues/1744) addressing this issue.

I am not using channels in my implementation, just a map (by key) of tasks. I also see a buildup over time of processes if there are many unique keys, but I do not believe this affects performance much even when the object has a lot of entries. I think there is room for a performance improvement (manual garbage collection) in the future. It should not be too difficult.

**Comment by ihinsdale** [comment]
What I've ended up with looks like this:

```
import { Action } from 'redux'
import { channel, Channel } from 'redux-saga'
import { fork, put, takeEvery, takeLatest } from 'redux-saga/effects'

interface IChannels<A extends Action> {
  [scope: string]: Channel<A>
}

/**
 * Implements `takeLatest` handling per unique value returned by `scopeSelector`.
 */
export function takeLatestPerScope<A extends Action>(
  scopeSelector: (action: A) => string, pattern: A['type'], worker: (action: A) => void,
) {
  return fork(function*() {
    const channels: IChannels<A> = {}

    yield takeEvery(pattern, function*(action: A) {
      const scope = scopeSelector(action)
      if (!channels[scope]) {
        channels[scope] = channel()
        yield takeLatest(channels[scope], worker)
      }
      yield put(channels[scope], action)
    })
  })
}
```

What is notably different from @andraaspar and @Andarist's examples is my use of `takeEvery`.

The `while` block + `const action = yield take(pattern)` approach in their examples misses the dispatching of an action matching `pattern` that occurs during the execution of the rest of the `while` block; the action is missed because we haven't gotten back to blocking on `yield take(pattern)`.

In my case, I was using `yield all([ put({ type: FOO, scope: 1 }), put({ type: FOO, scope: 2 }) ])` to dispatch two of the same action for parallel execution. The action with scope 2 was never being captured by `take`.

Using `takeEvery` solves this problem.

**Comment by polomoshnov** [comment]
Regarding one major issue mentioned by @andraaspar [here are my comments](https://github.com/redux-saga/redux-saga/pull/1744#issuecomment-556932147).

**Comment by therealparmesh** [comment]
Please see https://github.com/redux-saga/redux-saga/issues/1751#issuecomment-4985948888
