### ISSUE TITLE
TypeError: (0 , _effects.takeLatest) is not a function??

### ISSUE THREAD

**Issue by mrdulin** [yelouafi/redux-saga#698]
`saga/Beginning.js`
```js
import {call, put, takeEvery, takeLatest} from 'redux-saga/effects';

//api service
const api = 'http://it-ebooks-api.info/v1';

const service = {};

service.fetchBook = function (query) {
    const url = `${api}/search/${query}`;
    return fetch(url).then(res => res.json());
}

function* fetchBook(action) {
    try {
        const books = yield call(service.fetchBook, action.payload.query);
        yield put({type: 'BOOK_FETCH_SUCCEEDED', books});
    } catch(e) {
        yield put({type: 'BOOK_FETCH_FAILED', message: e.message});
    }
}

function* watchFetchBook() {
    yield takeEvery('BOOK_FETCH_REQUESTED', fetchBook);
}

function* watchFetchBook() {
    yield takeLatest('BOOK_FETCH_REQUESTED', fetchBook);
}

export default watchFetchBook;
```

`saga/index.js`
```js
import {fork} from 'redux-saga/effects';

import Beginning from './Beginning';

export default function* root() {
    yield [
        fork(Beginning)
    ]
}
```

**Comment by neurosnap** [comment]
`takeEvery` and `takeLatest` are not effects, you want to import them from the primary module  `redux-saga`

```js
import { takeEvery, takeLatest } from 'redux-saga';
```

**Comment by mrdulin** [comment]
@neurosnap I enter the breakpoint find this. Thanks! The example of `README.md` is wrong?

**Comment by aaroncraig10e** [comment]
Over a month after the last comment here, the docs are still out of date.  Any idea when the docs and code will be aligned?  For newcomers to this library it's already a steep learning curve, and frustrating when you follow the docs and things don't work.

I'm happy to update the docs and open a PR if it looks like this will not get updated soon.

**Comment by Andarist** [comment]
Docs are up to date already as new version got already released. Do you experience any errors? What version of `redux-saga` are you on?

**Comment by aaroncraig10e** [comment]
So, upon further toying around, I have it working like this: 

```js
import { call, put, takeLatest } from 'redux-saga';
import { take } from 'redux-saga/effects';
```

**Comment by Andarist** [comment]
both `import { takeLatest } from 'redux-saga/effects';` and `import { takeLatest } from 'redux-saga';` are working since `v0.14` but the latter (the one you are using at the moment) is deprecated

**Comment by aaroncraig10e** [comment]
Confirmed -- I was on an older version.
