### ISSUE TITLE
TypeError: Cannot read property 'call' of undefined 

### ISSUE THREAD

**Issue by adel-tahir** [yelouafi/redux-saga#699]
Hi,

I have following `saga`, but I get `TypeError: Cannot read property 'call' of undefined ` error.

saga.js
```
import { call, put } from 'redux-saga/effects'
import LoginActions from '../Redux/LoginRedux'
import AuthAPI from '../Services/Auth'

// attempts to login
export function * login ({ email, password, save }) {
	try {
		const user = yield call(AuthAPI.login, {user: {email, password }})
		// dispatch successful logins
	  yield put(LoginActions.loginSuccess(user.data))
	} catch(e) {
		yield put(LoginActions.loginFailure(e))
	}
}
```
Services/Auth.js
```
import request from 'superagent'

export default class AuthAPI {
  static login (data) {
  	return request.post('/sessions.json').send(data)
  }
}

```

**Comment by Andarist** [comment]
Should work, check if you have `redux-saga` installed and your overall configuration. That's standard way of importing and using this, never had a problem.

**Comment by adel-tahir** [comment]
@Andarist debug console snippet added
https://i.imgur.com/hWAMF4D.png

**Comment by Andarist** [comment]
Could you post a webpack bin with your problem? And also what version of the `redux-saga` are you using? 

From what I seen on the screen the `call` effect was `yield`ed to the saga as `runCallEffect` is visible in the stack. Is your `login` generator run by a `call` effect?

**Comment by adel-tahir** [comment]
@Andarist it turned out that there was an error in the api side.
