### ISSUE TITLE
[TypeScript] Update Monitor Interface for 0.13 changes

### ISSUE THREAD

**Issue by CarsonF** [yelouafi/redux-saga#700]
[Monitor Interface](https://github.com/yelouafi/redux-saga/blob/master/index.d.ts#L18) is missing `actionDispatched` from #609

**Comment by Andarist** [comment]
Would you be willing to provide a PR for it?

**Comment by CarsonF** [comment]
Yes I can. But I'm not sure the definition for it. Are there parameters given to the method? returns void, right?
