### ISSUE TITLE
how to appropriately cancel es6 fetch with saga cancel operator

### ISSUE THREAD

**Issue by L-Jovi** [yelouafi/redux-saga#701]
I notice that with this smart saga's operator that I could cancel some actions by `race` or `cancel`, thanks for your lib :)

and I find that it seems not possible to cancel fetch indeed even if I use `cancel` inside saga, maybe it's still [continuing issue](https://github.com/whatwg/fetch/issues/27), I follow some smart temporary solution below which may cancel fetch

```
const makeCancelable = (promise) => {
  let hasCanceled_ = false;
  const wrappedPromise = new Promise((resolve, reject) => {
    promise.then((val) =>
      hasCanceled_ ? reject({isCanceled: true}) : resolve(val)
    );
    promise.catch((error) =>
      hasCanceled_ ? reject({isCanceled: true}) : reject(error)
    );
  });
  return {
    promise: wrappedPromise,
    cancel() {
      hasCanceled_ = true;
    },
  };
};  
```

and I also hold question and confused now, may I use `cancel` or `race` to cancel fetch, or how could I use above method within saga,

thanks for your time,

regards.

**Comment by AJIh** [comment]
fetch API doesn't expose a method to abort. To abort request when cancelling promise in saga, use some alternative libraries(like axios which supports [cancellation](https://github.com/mzabriskie/axios#cancellation)) instead.

```javascript
function getURL(url) {
  let cancel;

  let promise = axios.get(url, {
    cancelToken: new axios.CancelToken(function executor(c) {
      // An executor function receives a cancel function as a parameter
      cancel = c;
    })
  });

  // cancel the request
  promise[CANCEL] = cancel;
}
```

Unfortunately, [cancelable promises proposal](https://github.com/tc39/proposal-cancelable-promises) has been withdrawn. :-( Not sure how long will axios support this feature.

**Comment by Andarist** [comment]
You can also read a little bit more here - https://github.com/yelouafi/redux-saga/issues/651#issuecomment-262375964

Also remember that even if your `race` wont be able to 'cancel' your regular `fetch`, so the response will return to your browser, it doesnt mean that `redux-saga` will handle it - its response will be ignored.

**Comment by L-Jovi** [comment]
@AJIh  thanks for your example :)

@Andarist  thanks for your reply.

**Comment by rclai** [comment]
I can confirm that using [the code shared above](https://github.com/redux-saga/redux-saga/issues/701#issuecomment-267512606) does cancel mid-flight requests when `race`ing or `cancel`ing, which is nice.
