### ISSUE TITLE
Is there something like redux-saga on the server side?

### ISSUE THREAD

**Issue by juanbernabo** [yelouafi/redux-saga#712]
Hi,

We are developing an app with redux-sagas, btw great work!

We wanted to use the same metaphor of redux but at the system level with a common reactive state that pushes changes to all the clients, we are using Firebase for this.

What we did was started to send, thru a middleware, some of the actions on the client to the server side by using a message queue, and started to create micro services that reacted with the actions, some updating the database (the global state), some generating new actions and some integrating our system with other systems.

It's nice to have the same metaphor for the whole thing, I think we are onto something interesting.
The problem is that, on the server side, we are missing some things that we got used on the client side, like redux-saga.

Does anyone is working on something similar or want to have a talk on how to implement something like this?

Thanks in advance,
Juan.

**Comment by Andarist** [comment]
Checkout this [comment](https://github.com/yelouafi/redux-saga/issues/705#issuecomment-267756960)

**Comment by orourkedd** [comment]
Take a look at this: https://github.com/orourkedd/effects-as-data

We're using this at Pluralsight and have built key parts of the learning experience with it (front and back end).  `effects-as-data` solves the side effect problem but is designed to be used anywhere javascript runs.

**Comment by akinnee** [comment]
Here's a newer non-redux specific library which is quite similar to redux-saga. It uses the same `call()` wrapper to yield instructions instead of yielding promises.
https://github.com/neurosnap/cofx
