### ISSUE TITLE
Calling sagas from within components

### ISSUE THREAD

**Issue by prashaantt** [yelouafi/redux-saga#73]
Saga noob here. I was able to get quickly up and running using a bootstrapping/startup saga that pulls in async data the first time the app loads. I now want to be able to call sagas at will from within my React components just like I'd `dispatch` redux actions, after let's say a button press, or after moving to a new route (I'm using react-router). I can do that easily using redux because I have access to the `dispatch` through the `connect()`. What's the equivalent facility that redux-saga provides? My searches didn't get me anything, although I admit there's some new terminology here so I may be looking in the wrong places.

**Comment by mjrussell** [comment]
@prashaantt you can listen to any actions inside your sagas using `take` so why not just dispatch an action from `componentWillMount` or `componentDidMount` to kick off your saga? For listening to route changes, I'd look at #37

**Comment by mjrussell** [comment]
Also check out how the examples work. [Counter](https://github.com/yelouafi/redux-saga/tree/master/examples/counter) is pretty simple and shows button clicking leading to work being done inside a saga

**Comment by cherta** [comment]
Hello @prashaantt, as @mjrussell says you can listen to any action on a saga using `take`, I was facing the same problem (I guess) and it was discussed on #37. Basically redux-router eats the actions before they can be handled by sagas middleware, simple-redux-router doesn't so I came up with an example on #37 on how I solved it.

Let me know if you need some more guidance.

**Comment by yelouafi** [comment]
@prashaantt Normally Sagas aren't fired from within UI components; but are started with your application; If an UI component need to communicate something to a Saga you can do it by dispatching the action from the component and taking it in the Saga

For example

```javascript
// component file
class MyComponent extends React.Component {

  componentDidMount() {
     dispatch( myAction() )
  }
}

// In your Saga
function *mySaga() {
   while(true) {
      const action = yield take(MY_ACTION)
      // do something with action
   }
}
```

**Comment by prashaantt** [comment]
Thanks for the pointers guys, things are certainly clearer to me now. I have now begun to understand sagas as intercepts to regular redux actions, which can then carry on async background jobs, and call other redux actions in turn when done.

What I'm still figuring out to do properly is to decide on how to structure multiple sagas in a complex app and wondering how many of these async actions can I keep checking for in an infinite-ish while loop. For example, I may have tons of API requests to make at various points in my app — will I have to boot my app with all those `fork`ed while loops waiting for those future actions without needing to worry about any performance issues?

**Comment by yelouafi** [comment]
> will I have to boot my app with all those forked while loops waiting for those future actions without needing to worry about any performance issues?

The while loop doesn't run synchronously; for example when you do something like

```javascript
function* watchApiRequest() {
   while(true) {
      const action = yield take(API_REQUEST)
      yield fork(doSomeWork, action)
   }
}

function* doSomeWork(action) {
  const response = yield call(someApi, action.payload)
  yield put(actions.response(response)
}
```

In `watchApiRequest`, the while(true) will *block* on `yield take(API_REQUEST)` until it receives an action of type `API_REQUEST`. When a matching action occurs, it'll fork `doSomeWork` then will block again until another action happens.

As for `doSomeWork` it terminates as soon as it performs the `yield put(...)`. So there are no memory issues, because the infinite-ish while loop progresses only as matching actions are taken; and the forked *worker tasks* terminates as soon as they finish their business

>What I'm still figuring out to do properly is to decide on how to structure multiple sagas in a complex app 

A simple pattern is to divide the flow between *watcher sagas* and a *worker sagas*. In the above example, the watcher Saga `watchApiRequest` watch for specific actions then forks worker tasks `doSomeWork`. Also see https://github.com/yelouafi/redux-saga/issues/68#issuecomment-178086859

**Comment by slorber** [comment]
If the saga middleware did return a storeIO to use against runSaga, wouldn't it solve the problem?
