### ISSUE TITLE
Cancellation warning incorrect?

### ISSUE THREAD

**Issue by aft-luke** [yelouafi/redux-saga#81]
I'm wondering if there's a dangling `.cancel()` call somewhere when using `runSaga`?

Given this setup, I'm getting a console.warn about an uncaught `SagaCancellationException`.
```javascript
    try {
        let task
        runSaga(function* someSaga() {
            yield cancelIfRunning(task)
            task = runSaga(...)
        }())
    } catch (e) {
        /* handle error */
    }
```

But if I tweak it to use this more-verbose form, I get no such error.
```javascript
    let task
    function* someSaga(runSaga) {
        yield cancelIfRunning(task)
        task = runSaga(...)
    }

    try {
        runSaga(someSaga(runSaga))
    } catch (e) {
        /* handle error */
    }
```

What's the difference? I'm starting to wonder if maybe the [README](https://github.com/yelouafi/redux-saga#task-cancellation) for nested cancellation just hasn't been updated since the `0.6` changes?

**Comment by aft-luke** [comment]
In a similar vein, it looks like the auto-cancellation caused by `race` is thrown as a warning as well. I suppose this is intentional, though it feels pretty heavy to have to do this:

```
function* someTaker() {
  try {
    yield take(ACTION)
  } catch (e) {
     ...
  }
}
yield race({
  a: call(someTaker)
 , b: call(someGenerator)
})
```

versus this:

```
yield race({
  a: take(ACTION)
 , b: call(someGenerator)
})
```

Maybe the cancellation wouldn't be thrown when caused by a `race` for those actions racing a simple `take`?

**Comment by yelouafi** [comment]
You dont have to catch cancel errors in someTaker. Errors wont bubble uo. 

The main point of warnings is to remind the developer. And they are logged only in dev mode

**Comment by musbaig** [comment]
Is there some way to turn off the log warnings dev mode?
