### ISSUE TITLE
spec testing custom take functions?

### ISSUE THREAD

**Issue by mjrussell** [yelouafi/redux-saga#82]
I often find myself writing something like the following:

```js
const checkFn = ({ type, payload }) => 
  type === MY_CONST && payload && payload.data === someData;
```

and then passing it to take with
```js
yield take(checkFn)
```

In my spec tests, unfortunately (as far as I can tell) theres no way to test the take. I was wondering if a similar solution to the `call` parameters might be possible?

Something like:
```js

const checkFn = (dataToCheck) => ({ type, payload }) => 
  type === MY_CONST && payload && payload.data === dataToCheck;

function* mySaga() {
  yield take(checkFn, 5);
}

...

expect(mySaga.next()).to.deep.equal(take(checkFn, 5));
```

**Comment by yelouafi** [comment]
First, sorry for the late response.

I assume the `someData` param is missed in your first snippet

The issue is that calling `checkFn(5)` multiple times will lead to different results because `checkFn` will return a different function object on each invocation.

What for example if we *memoize* the result of `checkFn` so it'd return the same function object for the same argument. 

```javascript
// for example using lodash memoize 
const checkFn = _.memoize(
  (dataToCheck) => ({ type, payload }) => 
    type === MY_CONST && payload && payload.data === dataToCheck
)

assert.equal( checkFn(5), checkFn(5) )
```

**Comment by mjrussell** [comment]
@yelouafi thanks, and no worries on the late response, I know you've been quite busy with the Docs (which are coming along great).

Yeah missed the first curried param, your example is what I was thinking. Seems like using memoize will definitely work, not sure why I didn't think of that :smile: 

I was thinking back to how sagas with `call` works where you test the fact that you will yield `call` with certain args rather than the equality of `call` after evaluating it.

I can definitely use the memoize for now though
