### ISSUE TITLE
typeScript

### ISSUE THREAD

**Issue by zivni** [yelouafi/redux-saga#84]
It would help if there was a typeScript definition file. Or there is one and I just didn't find it?

**Comment by aikoven** [comment]
It was approved yesterday.
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/redux-saga%2Fredux-saga.d.ts

**Comment by yelouafi** [comment]
@aikoven It seems the `apply` function is missed

**Comment by aikoven** [comment]
Typings are incomplete, I only wrote ones for stuff I'm using in my
project. But I plan to fill the missing parts when I have time.

Вт, 9 февр. 2016 г. в 16:44, Yassine Elouafi
notifications@github.com>:

**Comment by yelouafi** [comment]
Thanks @aikoven.
