### ISSUE TITLE
Monitor: Cannot read property 'effect' of undefined

### ISSUE THREAD

**Issue by romseguy** [yelouafi/redux-saga#85]
I set up the monitor pretty early in the development of my app, and ended up not using it too much because it's quite verbose when mapping over an array and yielding effects.

Now that I try using it again, an error shows up right after dispatching `LOG_EFFECT`:

![screenshot from 2016-02-07 21 02 29](https://cloud.githubusercontent.com/assets/109238/12874895/2854d664-cdde-11e5-8748-6de3ac320981.png)

Adding the following in [`case LOG_EFFECT:`](https://github.com/yelouafi/redux-saga/blob/master/examples/sagaMonitor/index.js#L41) :

```javascript
      effectsById[action.effectId] = {...action,
        status: PENDING,
        start: time()
      }
```

makes the error go away but then I just (obviously) get:

![screenshot from 2016-02-07 21 08 50](https://cloud.githubusercontent.com/assets/109238/12874934/09185cca-cddf-11e5-8801-babab0bc71b2.png)

**Comment by yelouafi** [comment]
Starting from 0.6 monitor actions fires only on dev mode. Do you have process.env. NODE_ENV set to 'development' ?

**Comment by romseguy** [comment]
Adding

```javascript
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: '"development"'
      },
```

worked like a charm, thank you. Might be useful to get a warning from the monitor when `process.env.NODE_ENV !== 'development'` then. I can open a PR if you like.

**Comment by yelouafi** [comment]
>I can open a PR if you like.

Of course. Thanks!
