### ISSUE TITLE
TIP: :: as bind if you use babel

### ISSUE THREAD

**Issue by bradennapier** [yelouafi/redux-saga#86]
Instaed of using the [context, apply]...args you can use

yield call(::this.myFunction, arg1, arg2, arg3) 

I find this to be a much simpler syntax and it works great.

**Comment by yelouafi** [comment]
Does the :: operator return the same reference on multiple invocations?

```javascript
::obj.func === ::obj.func
```

Otherwise w'd have some issue when testing sagas

**Comment by gaearon** [comment]
I advise you not to rely on experimental feature proposals anywhere except personal projects. Certainly not in the documentation or the source, as it confuses users who are not familiar with those proposals, or worse, leads them to believe those are safe to use when in reality they may well be withdrawn later.

**Comment by yelouafi** [comment]
@gaearon Agree. 

@bradennapier  It seems `::obj.func` is just a syntactic sugar for `obj.func.bind(obj)` (from babel REPL). So it can't be tested by simple equality. You can't simply test you Saga using

```javascript
function *mySaga() {
  yield call(::obj.func)
}

const gen = mySaga()

// this will fail, because ::obj.func will return a different `func` object from the
// one produced inside the Saga
assert.deepEqual(gen.next().value, call(::obj.func))
```

**Comment by bradynapier** [comment]
Yep, just noticed that after some initial confusion!

**Comment by bradynapier** [comment]
Oops just removed the label you had added.  Can close this.
