### ISSUE TITLE
How to contribute to the documentation website ?

### ISSUE THREAD

**Issue by DjebbZ** [yelouafi/redux-saga#93]
I spotted a few typos here and there as I'm reading the website, but when I browse the `docs` directory in the `master` branch, the corresponding `.md` file has only the content 

> **WIP**

**Comment by yelouafi** [comment]
The content in docs should mirror the website content. Unless is missed to push something

Did you see a difference between docs and website ?

**Comment by DjebbZ** [comment]
My bad, I can't find any difference. I must have mistaken a .md file with the wrong page. Expect some easy "typos" PR(s) soon !

**Comment by gaearon** [comment]
@DjebbZ Thank you for contributing!

**Comment by yelouafi** [comment]
No worry :) thanks

**Comment by DjebbZ** [comment]
I finished my round of typos fixes. Hope this helps !

**Comment by yelouafi** [comment]
Sure it helps. Thanks for all the efforts.
